import type { LanguageCourse } from "./genericLessons";

export const AR_COURSE: LanguageCourse = {
  code: "ar",
  name: "Arabe",
  native: "العربية",
  heroTitle1: { fr: "Apprenez", en: "Learn" },
  heroTitle2: { fr: "l'arabe", en: "Arabic" },
  heroSubtitle: {
    fr: "Un parcours débutant en douze leçons : salutations, quotidien, travail et entretien d'embauche.",
    en: "A beginner path in twelve lessons: greetings, daily life, work and a job interview.",
  },
  lessons: [
    {
      number: 1,
      slug: "ar-01",
      title: "Se présenter et saluer",
      titleEn: "Introducing yourself and greeting",
      summary: "Saluez, dites votre nom et votre ville d'origine avec des phrases simples.",
      summaryEn: "Greet people, say your name and where you are from with simple sentences.",
      grammar: ["Les salutations formelles et informelles", "Le pronom personnel أنا (moi)", "La phrase nominale اسمي (mon nom)"],
      explanation:
        "Pour se présenter en arabe, on utilise la phrase nominale sans verbe être au présent. « اسمي » (ismī) signifie « mon nom est », « أنا » (anā) signifie « moi, je ». Pour dire d'où l'on vient, on emploie « أنا من » (anā min) suivi de la ville ou du pays. Les salutations : « مرحباً » (marhaban) « bonjour », « السلام عليكم » formel, « صباح الخير » « bonjour (le matin) ».",
      explanationEn:
        "To introduce yourself in Arabic, use the nominal sentence without a present-tense verb 'to be'. 'اسمي' (ismī) means 'my name is', 'أنا' (anā) means 'I'. To say where you are from, use 'أنا من' (anā min) followed by the city or country. Greetings: 'مرحباً' (marhaban) 'hello', 'السلام عليكم' (formal), 'صباح الخير' 'good morning'.",
      examples: [
        { target: "مرحباً، أنا سارة.", roman: "marhaban, anā sāra.", fr: "Bonjour, je suis Sarah.", en: "Hello, I am Sarah." },
        { target: "اسمي أحمد.", roman: "ismī aḥmad.", fr: "Mon nom est Ahmed.", en: "My name is Ahmed." },
        { target: "أنا من فرنسا.", roman: "anā min faransā.", fr: "Je viens de France.", en: "I am from France." },
        { target: "أنا سعيد بلقائك.", roman: "anā saʿīd biliqāʾik.", fr: "Je suis heureux de te rencontrer.", en: "I am glad to meet you." },
      ],
      vocab: [
        { target: "مرحباً", roman: "marhaban", fr: "bonjour", en: "hello" },
        { target: "اسمي", roman: "ismī", fr: "mon nom est", en: "my name is" },
        { target: "أنا", roman: "anā", fr: "je, moi", en: "I, me" },
        { target: "من", roman: "min", fr: "de, depuis", en: "from" },
        { target: "أهلاً وسهلاً", roman: "ahlan wa sahlan", fr: "bienvenue", en: "welcome" },
        { target: "على الرحب والسعة", roman: "ʿalā ar-raḥb wa as-saʿa", fr: "de rien", en: "you are welcome" },
        { target: "من فضلك", roman: "min faḍlik", fr: "s'il vous plaît", en: "please" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « mon nom est » en arabe ?",
          promptEn: "How do you say 'my name is' in Arabic?",
          options: ["اسمي", "مرحباً", "شكراً", "نعم"],
          accept: ["اسمي"],
          explain: "« اسمي » (ismī) signifie « mon nom est ».",
          explainEn: "'اسمي' (ismī) means 'my name is'.",
        },
        {
          prompt: "Complétez : « أنا من ... »",
          promptEn: "Complete: 'أنا من ...'",
          options: ["فرنسا", "أهلاً", "نعم", "لا"],
          accept: ["فرنسا"],
          explain: "« أنا من فرنسا » signifie « je viens de France ».",
          explainEn: "'أنا من فرنسا' means 'I am from France'.",
        },
        {
          prompt: "Quelle salutation utilise-t-on le matin ?",
          promptEn: "Which greeting is used in the morning?",
          options: ["صباح الخير", "تصبح على خير", "مع السلامة", "لا بأس"],
          accept: ["صباح الخير"],
          explain: "« صباح الخير » signifie « bonjour » le matin.",
          explainEn: "'صباح الخير' means 'good morning'.",
        },
      ],
      interview: [
        {
          question: "عَرِّف بنفسك من فضلك.",
          roman: "ʿarraf binafsika min faḍlik.",
          fr: "Présentez-vous, s'il vous plaît.",
          en: "Please introduce yourself.",
          modelFr: "Je m'appelle Ahmed, j'ai vingt-cinq ans et je viens de France.",
          modelEn: "My name is Ahmed, I am twenty-five years old and I come from France.",
          accept: ["اسمي أحمد", "أنا أحمد", "أنا من فرنسا", "أنا اسمي أحمد"],
        },
      ],
    },
    {
      number: 2,
      slug: "ar-02",
      title: "Origine, nationalité et profession",
      titleEn: "Origin, nationality and profession",
      summary: "Exprimez votre nationalité, votre langue et votre métier.",
      summaryEn: "Express your nationality, your language and your job.",
      grammar: ["Les adjectifs de nationalité", "Le genre masculin/féminin", "La question ما مهنتك (quel est ton métier)"],
      explanation:
        "En arabe, la nationalité est un adjectif qui suit le genre : « فرنسي » (faransī) au masculin, « فرنسية » (faransiyya) au féminin. La profession se construit avec « أنا » suivi du métier : « أنا مهندس » (anā muhandis). Pour demander le métier, on dit « ما مهنتك؟ » (mā mihnatuka ?). La langue se dit « اللغة » (al-lugha), ex. « أتكلم العربية » (atakallam al-ʿarabiyya) « je parle arabe ».",
      explanationEn:
        "In Arabic, nationality is an adjective that agrees in gender: 'فرنسي' (faransī) masculine, 'فرنسية' (faransiyya) feminine. Profession uses 'أنا' followed by the job: 'أنا مهندس' (anā muhandis). To ask someone's job, say 'ما مهنتك؟' (mā mihnatuka?). Language is 'اللغة' (al-lugha), e.g. 'أتكلم العربية' (atakallam al-ʿarabiyya) 'I speak Arabic'.",
      examples: [
        { target: "أنا فرنسي.", roman: "anā faransī.", fr: "Je suis Français.", en: "I am French." },
        { target: "هي فرنسية.", roman: "hiya faransiyya.", fr: "Elle est Française.", en: "She is French." },
        { target: "أنا مهندس.", roman: "anā muhandis.", fr: "Je suis ingénieur.", en: "I am an engineer." },
        { target: "أتكلم العربية والإنجليزية.", roman: "atakallam al-ʿarabiyya wa al-inglīziyya.", fr: "Je parle arabe et anglais.", en: "I speak Arabic and English." },
      ],
      vocab: [
        { target: "فرنسي", roman: "faransī", fr: "français", en: "French" },
        { target: "مهندس", roman: "muhandis", fr: "ingénieur", en: "engineer" },
        { target: "طبيب", roman: "ṭabīb", fr: "médecin", en: "doctor" },
        { target: "معلم", roman: "muʿallim", fr: "enseignant", en: "teacher" },
        { target: "مهنتك", roman: "mihnatuk", fr: "ta profession", en: "your profession" },
        { target: "أتكلم", roman: "atakallam", fr: "je parle", en: "I speak" },
        { target: "لغة", roman: "lugha", fr: "langue", en: "language" },
        { target: "العربية", roman: "al-ʿarabiyya", fr: "l'arabe", en: "Arabic" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « je suis ingénieur » ?",
          promptEn: "How do you say 'I am an engineer'?",
          options: ["أنا مهندس", "أنا طالب", "أنا طبيب", "أنا فلاح"],
          accept: ["أنا مهندس"],
          explain: "« أنا مهندس » (anā muhandis) signifie « je suis ingénieur ».",
          explainEn: "'أنا مهندس' (anā muhandis) means 'I am an engineer'.",
        },
        {
          prompt: "Complétez : « أنا ... » (je suis Français, au masculin)",
          promptEn: "Complete: 'أنا ...' (I am French, masculine)",
          accept: ["فرنسي"],
          explain: "« أنا فرنسي » (anā faransī) signifie « je suis Français ».",
          explainEn: "'أنا فرنسي' (anā faransī) means 'I am French'.",
        },
        {
          prompt: "Comment demande-t-on le métier de quelqu'un ?",
          promptEn: "How do you ask someone's job?",
          options: ["ما مهنتك؟", "أين أنت؟", "كم عمرك؟", "أهلاً بك"],
          accept: ["ما مهنتك؟"],
          explain: "« ما مهنتك؟ » signifie « quel est ton métier ? ».",
          explainEn: "'ما مهنتك؟' means 'what is your profession?'.",
        },
      ],
    },
    {
      number: 3,
      slug: "ar-03",
      title: "Le verbe être et avoir",
      titleEn: "The verbs to be and to have",
      summary: "Exprimez l'existence et la possession avec كان et عندي.",
      summaryEn: "Express existence and possession with كان and عندي.",
      grammar: ["كان (être) au passé", "عندي (j'ai) pour la possession", "La négation ليس/ما عندي"],
      explanation:
        "Au présent, l'arabe ne met pas le verbe « être » (la phrase est nominale). Au passé, on utilise « كان » (kāna) : « كنت طالباً » (kuntu ṭāliban) « j'étais étudiant ». La possession s'exprime avec « عندي » (ʿindī) « j'ai » : « عندي سيارة » (ʿindī sayyāra) « j'ai une voiture ». La négation : « ما عندي » (mā ʿindī) « je n'ai pas ». Ces deux structures sont essentielles pour se décrire en entretien.",
      explanationEn:
        "In the present tense Arabic omits the verb 'to be' (the sentence is nominal). In the past, use 'كان' (kāna): 'كنت طالباً' (kuntu ṭāliban) 'I was a student'. Possession uses 'عندي' (ʿindī) 'I have': 'عندي سيارة' (ʿindī sayyāra) 'I have a car'. Negation: 'ما عندي' (mā ʿindī) 'I do not have'. These two structures are essential to describe yourself in an interview.",
      examples: [
        { target: "كنت طالباً.", roman: "kuntu ṭāliban.", fr: "J'étais étudiant.", en: "I was a student." },
        { target: "عندي سيارة جديدة.", roman: "ʿindī sayyāra jadīda.", fr: "J'ai une voiture neuve.", en: "I have a new car." },
        { target: "ما عندي وقت.", roman: "mā ʿindī waqt.", fr: "Je n'ai pas de temps.", en: "I do not have time." },
        { target: "عندي خبرة في العمل.", roman: "ʿindī khibratun fī al-ʿamal.", fr: "J'ai de l'expérience de travail.", en: "I have work experience." },
      ],
      vocab: [
        { target: "كان", roman: "kāna", fr: "être (passé)", en: "to be (past)" },
        { target: "عندي", roman: "ʿindī", fr: "j'ai (possession)", en: "I have" },
        { target: "سيارة", roman: "sayyāra", fr: "voiture", en: "car" },
        { target: "خبرة", roman: "khibrat", fr: "expérience", en: "experience" },
        { target: "وقت", roman: "waqt", fr: "temps", en: "time" },
        { target: "ما عندي", roman: "mā ʿindī", fr: "je n'ai pas", en: "I do not have" },
        { target: "مشروع", roman: "mashrūʿ", fr: "projet", en: "project" },
        { target: "مال", roman: "māl", fr: "argent", en: "money" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « j'ai une voiture » ?",
          promptEn: "How do you say 'I have a car'?",
          options: ["عندي سيارة", "عندي وقت", "عندي بيت", "لا شيء"],
          accept: ["عندي سيارة"],
          explain: "« عندي سيارة » (ʿindī sayyāra) signifie « j'ai une voiture ».",
          explainEn: "'عندي سيارة' (ʿindī sayyāra) means 'I have a car'.",
        },
        {
          prompt: "Complétez : « كنت ... » (j'étais étudiant)",
          promptEn: "Complete: 'كنت ...' (I was a student)",
          accept: ["طالباً", "طالب"],
          explain: "« كنت طالباً » (kuntu ṭāliban) signifie « j'étais étudiant ».",
          explainEn: "'كنت طالباً' (kuntu ṭāliban) means 'I was a student'.",
        },
        {
          prompt: "Comment dit-on « je n'ai pas de temps » ?",
          promptEn: "How do you say 'I do not have time'?",
          options: ["ما عندي وقت", "عندي وقت", "أنا مشغول", "لا أعرف"],
          accept: ["ما عندي وقت"],
          explain: "« ما عندي وقت » (mā ʿindī waqt) signifie « je n'ai pas de temps ».",
          explainEn: "'ما عندي وقت' (mā ʿindī waqt) means 'I do not have time'.",
        },
      ],
    },
    {
      number: 4,
      slug: "ar-04",
      title: "La routine quotidienne",
      titleEn: "The daily routine",
      summary: "Décrivez votre journée : se réveiller, travailler, se reposer.",
      summaryEn: "Describe your day: waking up, working, resting.",
      grammar: ["Le présent de l'indicatif", "Les verbes se réveiller, travailler, manger", "Les adverbes de fréquence"],
      explanation:
        "La routine se décrit au présent avec le préfixe du sujet : « أستيقظ » (astaqīẓ) « je me réveille », « أعمل » (aʿmal) « je travaille », « آكل » (ākul) « je mange ». On utilise les adverbes de fréquence : « كل يوم » (kull yawm) « chaque jour », « أحياناً » (aḥyānan) « parfois », « دائماً » (dāʾiman) « toujours ». Exemple : « أستيقظ الساعة السابعة » « je me réveille à sept heures ».",
      explanationEn:
        "The routine is described in the present tense with a subject prefix: 'أستيقظ' (astaqīẓ) 'I wake up', 'أعمل' (aʿmal) 'I work', 'آكل' (ākul) 'I eat'. Use frequency adverbs: 'كل يوم' (kull yawm) 'every day', 'أحياناً' (aḥyānan) 'sometimes', 'دائماً' (dāʾiman) 'always'. Example: 'أستيقظ الساعة السابعة' 'I wake up at seven o'clock'.",
      examples: [
        { target: "أستيقظ كل يوم في السابعة.", roman: "astaqīẓ kull yawm fī as-sābiʿa.", fr: "Je me réveille chaque jour à sept heures.", en: "I wake up every day at seven." },
        { target: "أعمل في مكتب.", roman: "aʿmal fī maktab.", fr: "Je travaille dans un bureau.", en: "I work in an office." },
        { target: "آكل الغداء في الظهيرة.", roman: "ākul al-ghadāʾ fī aẓ-ẓahīra.", fr: "Je mange le déjeuner à midi.", en: "I eat lunch at noon." },
        { target: "أنام مبكراً دائماً.", roman: "anāmu mubakkiran dāʾiman.", fr: "Je me couche toujours tôt.", en: "I always sleep early." },
      ],
      vocab: [
        { target: "أستيقظ", roman: "astaqīẓ", fr: "je me réveille", en: "I wake up" },
        { target: "أعمل", roman: "aʿmal", fr: "je travaille", en: "I work" },
        { target: "آكل", roman: "ākul", fr: "je mange", en: "I eat" },
        { target: "أنام", roman: "anāmu", fr: "je dors", en: "I sleep" },
        { target: "كل يوم", roman: "kull yawm", fr: "chaque jour", en: "every day" },
        { target: "دائماً", roman: "dāʾiman", fr: "toujours", en: "always" },
        { target: "مبكراً", roman: "mubakkiran", fr: "tôt", en: "early" },
        { target: "الغداء", roman: "al-ghadāʾ", fr: "le déjeuner", en: "lunch" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « je travaille » ?",
          promptEn: "How do you say 'I work'?",
          options: ["أعمل", "آكل", "أنام", "أسكن"],
          accept: ["أعمل"],
          explain: "« أعمل » (aʿmal) signifie « je travaille ».",
          explainEn: "'أعمل' (aʿmal) means 'I work'.",
        },
        {
          prompt: "Complétez : « أستيقظ ... » (je me réveille chaque jour)",
          promptEn: "Complete: 'أستيقظ ...' (I wake up every day)",
          accept: ["كل يوم"],
          explain: "« أستيقظ كل يوم » signifie « je me réveille chaque jour ».",
          explainEn: "'أستيقظ كل يوم' means 'I wake up every day'.",
        },
        {
          prompt: "Comment dit-on « je dors tôt » ?",
          promptEn: "How do you say 'I sleep early'?",
          options: ["أنام مبكراً", "أنام متأخراً", "أعمل مبكراً", "آكل مبكراً"],
          accept: ["أنام مبكراً"],
          explain: "« أنام مبكراً » (anāmu mubakkiran) signifie « je dors tôt ».",
          explainEn: "'أنام مبكراً' (anāmu mubakkiran) means 'I sleep early'.",
        },
      ],
    },
    {
      number: 5,
      slug: "ar-05",
      title: "Les goûts et loisirs",
      titleEn: "Tastes and hobbies",
      summary: "Parlez de ce que vous aimez avec le verbe أحب.",
      summaryEn: "Talk about what you like with the verb أحب.",
      grammar: ["Le verbe أحب (aimer)", "Aimer + nom ou + verbe", "Exprimer les loisirs"],
      explanation:
        "Le verbe « أحب » (uḥibb) « j'aime » se construit directement avec un nom ou un verbe : « أحب القراءة » (uḥibb al-qirāʾa) « j'aime la lecture », « أحب أن أسافر » (uḥibb an usāfir) « j'aime voyager ». Pour dire son goût : « أحب كثيراً » « j'aime beaucoup ». On exprime les hobbies de routine comme « أمارس الرياضة » (umāris ar-riyāḍa) « je fais du sport ».",
      explanationEn:
        "The verb 'أحب' (uḥibb) 'I like' is built directly with a noun or verb: 'أحب القراءة' (uḥibb al-qirāʾa) 'I like reading', 'أحب أن أسافر' (uḥibb an usāfir) 'I like to travel'. To express strong liking: 'أحب كثيراً' 'I like very much'. Express routine hobbies like 'أمارس الرياضة' (umāris ar-riyāḍa) 'I do sports'.",
      examples: [
        { target: "أحب القراءة.", roman: "uḥibb al-qirāʾa.", fr: "J'aime la lecture.", en: "I like reading." },
        { target: "أحب أن أسافر.", roman: "uḥibb an usāfir.", fr: "J'aime voyager.", en: "I like to travel." },
        { target: "أمارس الرياضة كل أسبوع.", roman: "umāris ar-riyāḍa kull usbūʿ.", fr: "Je fais du sport chaque semaine.", en: "I do sports every week." },
        { target: "لا أحب الانتظار.", roman: "lā uḥibb al-intiẓār.", fr: "Je n'aime pas attendre.", en: "I do not like waiting." },
      ],
      vocab: [
        { target: "أحب", roman: "uḥibb", fr: "j'aime", en: "I like" },
        { target: "القراءة", roman: "al-qirāʾa", fr: "la lecture", en: "reading" },
        { target: "الرياضة", roman: "ar-riyāḍa", fr: "le sport", en: "sport" },
        { target: "أسافر", roman: "usāfir", fr: "je voyage", en: "I travel" },
        { target: "الموسيقى", roman: "al-mūsīqā", fr: "la musique", en: "music" },
        { target: "لا أحب", roman: "lā uḥibb", fr: "je n'aime pas", en: "I do not like" },
        { target: "كثيراً", roman: "kathīran", fr: "beaucoup", en: "very much" },
        { target: "هواية", roman: "hiwāya", fr: "passe-temps, hobby", en: "hobby" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « j'aime la lecture » ?",
          promptEn: "How do you say 'I like reading'?",
          options: ["أحب القراءة", "أحب الرياضة", "لا أحب ذلك", "أنا متعب"],
          accept: ["أحب القراءة"],
          explain: "« أحب القراءة » (uḥibb al-qirāʾa) signifie « j'aime la lecture ».",
          explainEn: "'أحب القراءة' (uḥibb al-qirāʾa) means 'I like reading'.",
        },
        {
          prompt: "Complétez : « لا أحب ... » (je n'aime pas le sport)",
          promptEn: "Complete: 'لا أحب ...' (I do not like sport)",
          accept: ["الرياضة"],
          explain: "« لا أحب الرياضة » signifie « je n'aime pas le sport ».",
          explainEn: "'لا أحب الرياضة' means 'I do not like sport'.",
        },
        {
          prompt: "Comment dit-on « j'aime voyager » ?",
          promptEn: "How do you say 'I like to travel'?",
          options: ["أحب أن أسافر", "أحب القراءة", "أحب الطبخ", "أحب النوم"],
          accept: ["أحب أن أسافر"],
          explain: "« أحب أن أسافر » (uḥibb an usāfir) signifie « j'aime voyager ».",
          explainEn: "'أحب أن أسافر' (uḥibb an usāfir) means 'I like to travel'.",
        },
      ],
    },
    {
      number: 6,
      slug: "ar-06",
      title: "La famille et les personnes",
      titleEn: "Family and people",
      summary: "Nommez les membres de la famille et posez des questions.",
      summaryEn: "Name family members and ask questions.",
      grammar: ["Les membres de la famille", "Les possessifs (père de, fils de)", "La question المعرّف بأل"],
      explanation:
        "Les membres de la famille : « الأب » (al-ab) « le père », « الأم » (al-umm) « la mère », « الأخ » (al-akh) « le frère », « الأخت » (al-ukht) « la sœur ». La possession s'exprime avec « أبو » (abū) « père de » : « أبو أحمد » « le père d'Ahmed ». Pour décrire sa famille : « عائلتي صغيرة » (ʿāʾilatī ṣaghīra) « ma famille est petite ». On demande « كم عدد عائلتك ؟ » « combien de personnes compte ta famille ? ».",
      explanationEn:
        "Family members: 'الأب' (al-ab) 'father', 'الأم' (al-umm) 'mother', 'الأخ' (al-akh) 'brother', 'الأخت' (al-ukht) 'sister'. Possession uses 'أبو' (abū) 'father of': 'أبو أحمد' 'Ahmed's father'. To describe your family: 'عائلتي صغيرة' (ʿāʾilatī ṣaghīra) 'my family is small'. Ask 'كم عدد عائلتك ؟' 'how many people are in your family?'",
      examples: [
        { target: "هذه أمي.", roman: "hādhihi ummī.", fr: "C'est ma mère.", en: "This is my mother." },
        { target: "أخي مهندس.", roman: "akhī muhandis.", fr: "Mon frère est ingénieur.", en: "My brother is an engineer." },
        { target: "عائلتي صغيرة.", roman: "ʿāʾilatī ṣaghīra.", fr: "Ma famille est petite.", en: "My family is small." },
        { target: "عندي أختان.", roman: "ʿindī ukhtān.", fr: "J'ai deux sœurs.", en: "I have two sisters." },
      ],
      vocab: [
        { target: "العائلة", roman: "al-ʿāʾila", fr: "la famille", en: "family" },
        { target: "الأب", roman: "al-ab", fr: "le père", en: "father" },
        { target: "الأم", roman: "al-umm", fr: "la mère", en: "mother" },
        { target: "الأخ", roman: "al-akh", fr: "le frère", en: "brother" },
        { target: "الأخت", roman: "al-ukht", fr: "la sœur", en: "sister" },
        { target: "صغيرة", roman: "ṣaghīra", fr: "petite", en: "small" },
        { target: "أم", roman: "umm", fr: "mère", en: "mother" },
        { target: "عائلتي", roman: "ʿāʾilatī", fr: "ma famille", en: "my family" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « le père » ?",
          promptEn: "How do you say 'the father'?",
          options: ["الأب", "الأم", "الأخت", "البيت"],
          accept: ["الأب"],
          explain: "« الأب » (al-ab) signifie « le père ».",
          explainEn: "'الأب' (al-ab) means 'the father'.",
        },
        {
          prompt: "Complétez : « هذه ... » (c'est ma mère)",
          promptEn: "Complete: 'هذه ...' (this is my mother)",
          accept: ["أمي", "الأم"],
          explain: "« هذه أمي » (hādhihi ummī) signifie « c'est ma mère ».",
          explainEn: "'هذه أمي' (hādhihi ummī) means 'this is my mother'.",
        },
        {
          prompt: "Comment dit-on « ma famille est petite » ?",
          promptEn: "How do you say 'my family is small'?",
          options: ["عائلتي صغيرة", "عائلتي كبيرة", "أمي صغيرة", "أخي كبير"],
          accept: ["عائلتي صغيرة"],
          explain: "« عائلتي صغيرة » (ʿāʾilatī ṣaghīra) signifie « ma famille est petite ».",
          explainEn: "'عائلتي صغيرة' (ʿāʾilatī ṣaghīra) means 'my family is small'.",
        },
      ],
    },
    {
      number: 7,
      slug: "ar-07",
      title: "Le travail et le bureau",
      titleEn: "Work and the office",
      summary: "Le vocabulaire du travail, de l'entreprise et des réunions.",
      summaryEn: "Work, company and meeting vocabulary.",
      grammar: ["Le vocabulaire du bureau", "Les prépositions de lieu (في، إلى)", "Parler de son entreprise"],
      explanation:
        "Au travail, on retrouve des mots courants : « شركة » (sharika) « société », « مكتب » (maktab) « bureau », « اجتماع » (ijtimāʿ) « réunion », « فريق » (farīq) « équipe ». La préposition « في » (fī) signifie « dans/en », « إلى » (ilā) « vers/à ». Exemple : « أعمل في شركة كبيرة » (aʿmal fī sharika kabīra) « je travaille dans une grande entreprise ». « الفريق » (al-farīq) désigne l'équipe avec laquelle on collabore.",
      explanationEn:
        "At work you find common words: 'شركة' (sharika) 'company', 'مكتب' (maktab) 'office', 'اجتماع' (ijtimāʿ) 'meeting', 'فريق' (farīq) 'team'. The preposition 'في' (fī) means 'in', 'إلى' (ilā) 'to/towards'. Example: 'أعمل في شركة كبيرة' (aʿmal fī sharika kabīra) 'I work in a big company'. 'الفريق' (al-farīq) is the team you collaborate with.",
      examples: [
        { target: "أعمل في شركة كبيرة.", roman: "aʿmal fī sharika kabīra.", fr: "Je travaille dans une grande entreprise.", en: "I work in a big company." },
        { target: "عندنا اجتماع اليوم.", roman: "ʿindanā ijtimāʿ al-yawm.", fr: "Nous avons une réunion aujourd'hui.", en: "We have a meeting today." },
        { target: "الفرق يتعاون جيداً.", roman: "al-farīq yataʿāwanu jayyidan.", fr: "L'équipe collabore bien.", en: "The team collaborates well." },
        { target: "أذهب إلى المكتب كل صباح.", roman: "adhabu ilā al-maktab kull ṣabāḥ.", fr: "Je vais au bureau chaque matin.", en: "I go to the office every morning." },
      ],
      vocab: [
        { target: "شركة", roman: "sharika", fr: "société, entreprise", en: "company" },
        { target: "مكتب", roman: "maktab", fr: "bureau", en: "office" },
        { target: "اجتماع", roman: "ijtimāʿ", fr: "réunion", en: "meeting" },
        { target: "فريق", roman: "farīq", fr: "équipe", en: "team" },
        { target: "مشروع", roman: "mashrūʿ", fr: "projet", en: "project" },
        { target: "العمل", roman: "al-ʿamal", fr: "le travail", en: "work" },
        { target: "رئيس", roman: "raʾīs", fr: "directeur, chef", en: "manager, boss" },
        { target: "النجاح", roman: "an-najāḥ", fr: "le succès", en: "success" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « l'équipe » ?",
          promptEn: "How do you say 'the team'?",
          options: ["الفريق", "الاجتماع", "الشركة", "المالك"],
          accept: ["الفريق"],
          explain: "« الفريق » (al-farīq) signifie « l'équipe ».",
          explainEn: "'الفريق' (al-farīq) means 'the team'.",
        },
        {
          prompt: "Complétez : « أعمل في شركة ... » (je travaille dans une grande entreprise)",
          promptEn: "Complete: 'أعمل في شركة ...' (I work in a big company)",
          accept: ["كبيرة"],
          explain: "« أعمل في شركة كبيرة » signifie « je travaille dans une grande entreprise ».",
          explainEn: "'أعمل في شركة كبيرة' means 'I work in a big company'.",
        },
        {
          prompt: "Comment dit-on « réunion » ?",
          promptEn: "How do you say 'meeting'?",
          options: ["اجتماع", "مكتب", "شركة", "وقت"],
          accept: ["اجتماع"],
          explain: "« اجتماع » (ijtimāʿ) signifie « réunion ».",
          explainEn: "'اجتماع' (ijtimāʿ) means 'meeting'.",
        },
      ],
    },
    {
      number: 8,
      slug: "ar-08",
      title: "Faire des achats et commander",
      titleEn: "Shopping and ordering",
      summary: "Demandez un prix, commandez au restaurant et au marché.",
      summaryEn: "Ask for a price, order at the restaurant and the market.",
      grammar: ["Le verbe acheter et commander", "Demander le prix (بكم؟)", "Les formules de politesse"],
      explanation:
        "Au marché ou au restaurant : « أريد » (urīd) « je veux », « أشتري » (ashtarī) « j'achète », « بكم؟ » (bikam ?) « c'est combien ? ». Exemple : « أريد قهوة من فضلك » « je voudrais un café s'il vous plaît ». Pour commander : « اطلب طبقاً » « commande un plat ». La politesse est essentielle : « من فضلك » (min faḍlik) « s'il vous plaît », « شكراً » (shukran) « merci ».",
      explanationEn:
        "At the market or restaurant: 'أريد' (urīd) 'I want', 'أشتري' (ashtarī) 'I buy', 'بكم؟' (bikam?) 'how much is it?'. Example: 'أريد قهوة من فضلك' 'I would like a coffee please'. To order: 'اطلب طبقاً' 'order a dish'. Politeness is essential: 'من فضلك' (min faḍlik) 'please', 'شكراً' (shukran) 'thank you'.",
      examples: [
        { target: "بكم هذا؟", roman: "bikam hādhā?", fr: "C'est combien ?", en: "How much is this?" },
        { target: "أريد قهوة من فضلك.", roman: "urīd qahwa min faḍlik.", fr: "Je voudrais un café, s'il vous plaît.", en: "I would like a coffee, please." },
        { target: "أشتري خبزاً من السوق.", roman: "ashtarī khubzan min as-sūq.", fr: "J'achète du pain au marché.", en: "I buy bread at the market." },
        { target: "شكراً جزيلاً.", roman: "shukran jazīlan.", fr: "Merci beaucoup.", en: "Thank you very much." },
      ],
      vocab: [
        { target: "أريد", roman: "urīd", fr: "je veux", en: "I want" },
        { target: "بكم؟", roman: "bikam?", fr: "c'est combien ?", en: "how much?" },
        { target: "قهوة", roman: "qahwa", fr: "café", en: "coffee" },
        { target: "سوق", roman: "sūq", fr: "marché", en: "market" },
        { target: "خبز", roman: "khubz", fr: "pain", en: "bread" },
        { target: "شكراً", roman: "shukran", fr: "merci", en: "thank you" },
        { target: "مطعم", roman: "maṭʿam", fr: "restaurant", en: "restaurant" },
        { target: "ثمن", roman: "thaman", fr: "prix", en: "price" },
      ],
      exercises: [
        {
          prompt: "Comment demande-t-on le prix ?",
          promptEn: "How do you ask for the price?",
          options: ["بكم هذا؟", "أين هو؟", "من أنت؟", "كم عمرك؟"],
          accept: ["بكم هذا؟"],
          explain: "« بكم هذا؟ » (bikam hādhā?) signifie « c'est combien ? ».",
          explainEn: "'بكم هذا؟' (bikam hādhā?) means 'how much is this?'.",
        },
        {
          prompt: "Complétez : « أريد ... من فضلك » (je voudrais un café, s'il vous plaît)",
          promptEn: "Complete: 'أريد ... من فضلك' (I would like a coffee, please)",
          accept: ["قهوة"],
          explain: "« أريد قهوة » signifie « je voudrais un café ».",
          explainEn: "'أريد قهوة' means 'I would like a coffee'.",
        },
        {
          prompt: "Comment dit-on « je veux » ?",
          promptEn: "How do you say 'I want'?",
          options: ["أريد", "أكره", "أنا", "نعم"],
          accept: ["أريد"],
          explain: "« أريد » (urīd) signifie « je veux ».",
          explainEn: "'أريد' (urīd) means 'I want'.",
        },
      ],
    },
    {
      number: 9,
      slug: "ar-09",
      title: "Le temps, les saisons et l'heure",
      titleEn: "Weather, seasons and time",
      summary: "Parlez de la météo, des saisons et donnez l'heure.",
      summaryEn: "Talk about the weather, seasons and tell the time.",
      grammar: ["Les saisons de l'année", "L'expression de l'heure (الساعة)", "La météo (الطقس)"],
      explanation:
        "L'heure se dit « كم الساعة ؟ » (kam as-sāʿa ?) « quelle heure est-il ? ». La réponse : « الساعة السابعة » « il est sept heures ». Les saisons : « الربيع » ar-rabīʿ « le printemps », « الصيف » aṣ-ṣayf « l'été », « الخريف » al-kharīf « l'automne », « الشتاء » ash-shatāʾ « l'hiver ». La météo : « الجو جميل » « le temps est beau », « الجو بارد » « il fait froid ».",
      explanationEn:
        "Time is asked with 'كم الساعة ؟' (kam as-sāʿa?) 'what time is it?'. The answer: 'الساعة السابعة' 'it is seven o'clock'. The seasons: 'الربيع' ar-rabīʿ 'spring', 'الصيف' aṣ-ṣayf 'summer', 'الخريف' al-kharīf 'autumn', 'الشتاء' ash-shatāʾ 'winter'. The weather: 'الجو جميل' 'the weather is nice', 'الجو بارد' 'it is cold'.",
      examples: [
        { target: "كم الساعة الآن؟", roman: "kam as-sāʿa al-ān?", fr: "Quelle heure est-il maintenant ?", en: "What time is it now?" },
        { target: "الساعة السابعة.", roman: "as-sāʿa as-sābiʿa.", fr: "Il est sept heures.", en: "It is seven o'clock." },
        { target: "الجو جميل اليوم.", roman: "al-jaww jamīl al-yawm.", fr: "Le temps est beau aujourd'hui.", en: "The weather is nice today." },
        { target: "أحب الصيف كثيراً.", roman: "uḥibb aṣ-ṣayf kathīran.", fr: "J'aime beaucoup l'été.", en: "I like summer very much." },
      ],
      vocab: [
        { target: "ساعة", roman: "sāʿa", fr: "heure", en: "hour, clock" },
        { target: "ربيع", roman: "rabīʿ", fr: "printemps", en: "spring" },
        { target: "صيف", roman: "ṣayf", fr: "été", en: "summer" },
        { target: "خريف", roman: "kharīf", fr: "automne", en: "autumn" },
        { target: "شتاء", roman: "shatāʾ", fr: "hiver", en: "winter" },
        { target: "جو", roman: "jaww", fr: "temps, climat", en: "weather" },
        { target: "بارد", roman: "bārid", fr: "froid", en: "cold" },
        { target: "جميل", roman: "jamīl", fr: "beau", en: "beautiful" },
      ],
      exercises: [
        {
          prompt: "Comment demande-t-on l'heure ?",
          promptEn: "How do you ask the time?",
          options: ["كم الساعة؟", "كم عمرك؟", "أين أنت؟", "ما اسمك؟"],
          accept: ["كم الساعة؟"],
          explain: "« كم الساعة ؟ » (kam as-sāʿa?) signifie « quelle heure est-il ? ».",
          explainEn: "'كم الساعة ؟' (kam as-sāʿa?) means 'what time is it?'.",
        },
        {
          prompt: "Complétez : « ... السابعة » (il est sept heures)",
          promptEn: "Complete: '... السابعة' (it is seven o'clock)",
          accept: ["الساعة"],
          explain: "« الساعة السابعة » signifie « il est sept heures ».",
          explainEn: "'الساعة السابعة' means 'it is seven o'clock'.",
        },
        {
          prompt: "Quel mot désigne « le printemps » ?",
          promptEn: "Which word means 'spring'?",
          options: ["الربيع", "الشتاء", "الصيف", "الخريف"],
          accept: ["الربيع"],
          explain: "« الربيع » (ar-rabīʿ) signifie « le printemps ».",
          explainEn: "'الربيع' (ar-rabīʿ) means 'spring'.",
        },
      ],
    },
    {
      number: 10,
      slug: "ar-10",
      title: "Entretien : présente-toi et ton parcours",
      titleEn: "Interview: introduce yourself and your background",
      summary: "Préparez-vous à parler de votre parcours lors d'un entretien.",
      summaryEn: "Prepare to talk about your background in an interview.",
      grammar: ["Raconter son parcours", "Utiliser كان au passé pour l'expérience", "Vocabulaire de l'entretien"],
      explanation:
        "Pour un entretien, racontez votre parcours en enchaînant les étapes : « درست في الجامعة » (darastu fī al-jāmiʿa) « j'ai étudié à l'université », « عملت في شركة » (ʿamiltu fī sharika) « j'ai travaillé dans une entreprise ». Le passé se forme avec « كنت » (kuntu) « j'étais » et les verbes au passé. Présentez clairement : « أنا خريج هندسة » « je suis diplômé en ingénierie », en insistant sur vos compétences.",
      explanationEn:
        "For an interview narrate your background by chaining steps: 'درست في الجامعة' (darastu fī al-jāmiʿa) 'I studied at university', 'عملت في شركة' (ʿamiltu fī sharika) 'I worked in a company'. The past uses 'كنت' (kuntu) 'I was' and past verbs. Introduce clearly: 'أنا خريج هندسة' 'I am a graduate in engineering', highlighting your skills.",
      examples: [
        { target: "أنا خريج هندسة.", roman: "anā kharīj handasa.", fr: "Je suis diplômé en ingénierie.", en: "I am an engineering graduate." },
        { target: "درست في الجامعة خمس سنوات.", roman: "darastu fī al-jāmiʿa khams sanawāt.", fr: "J'ai étudié à l'université pendant cinq ans.", en: "I studied at university for five years." },
        { target: "عملت في شركة لمدة ثلاث سنوات.", roman: "ʿamiltu fī sharika limuddat thalāth sanawāt.", fr: "J'ai travaillé dans une entreprise pendant trois ans.", en: "I worked in a company for three years." },
        { target: "أتمنى الانضمام إلى فريقكم.", roman: "atamannā al-inḍimām ilā farīqikum.", fr: "J'espère rejoindre votre équipe.", en: "I hope to join your team." },
      ],
      vocab: [
        { target: "مسار مهني", roman: "masār mihanī", fr: "parcours professionnel", en: "career path" },
        { target: "جامعة", roman: "jāmiʿa", fr: "université", en: "university" },
        { target: "درست", roman: "darastu", fr: "j'ai étudié", en: "I studied" },
        { target: "عملت", roman: "ʿamiltu", fr: "j'ai travaillé", en: "I worked" },
        { target: "خريج", roman: "kharīj", fr: "diplômé", en: "graduate" },
        { target: "خبرة عملية", roman: "khibrat ʿamaliyya", fr: "expérience pratique", en: "practical experience" },
        { target: "مهارات", roman: "mahārāt", fr: "compétences", en: "skills" },
        { target: "هدف", roman: "hadaf", fr: "objectif", en: "goal" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « j'ai étudié à l'université » ?",
          promptEn: "How do you say 'I studied at university'?",
          options: ["درست في الجامعة", "عملت في شركة", "أنا متعب", "لا أعرف"],
          accept: ["درست في الجامعة"],
          explain: "« درست في الجامعة » signifie « j'ai étudié à l'université ».",
          explainEn: "'درست في الجامعة' means 'I studied at university'.",
        },
        {
          prompt: "Complétez : « عملت في ... » (j'ai travaillé dans une entreprise)",
          promptEn: "Complete: 'عملت في ...' (I worked in a company)",
          accept: ["شركة"],
          explain: "« عملت في شركة » signifie « j'ai travaillé dans une entreprise ».",
          explainEn: "'عملت في شركة' means 'I worked in a company'.",
        },
        {
          prompt: "Comment dit-on « je suis diplômé en ingénierie » ?",
          promptEn: "How do you say 'I am an engineering graduate'?",
          options: ["أنا خريج هندسة", "أنا طالب", "أنا معلم", "أنا سائق"],
          accept: ["أنا خريج هندسة"],
          explain: "« أنا خريج هندسة » signifie « je suis diplômé en ingénierie ».",
          explainEn: "'أنا خريج هندسة' means 'I am an engineering graduate'.",
        },
      ],
      interview: [
        {
          question: "حَدِّثني عن مَسِيرَتِك المهنية.",
          roman: "ḥaddithnī ʿan masīratika al-mihaniyya.",
          fr: "Parlez-moi de votre parcours professionnel.",
          en: "Tell me about your career path.",
          modelFr: "J'ai étudié l'ingénierie puis j'ai travaillé trois ans dans une entreprise, ce qui m'a donné une solide expérience.",
          modelEn: "I studied engineering, then worked three years in a company, which gave me solid experience.",
          accept: ["عملت في شركة لمدة ثلاث سنوات", "درست في الجامعة", "أنا خريج هندسة", "عملت في شركة"],
        },
      ],
    },
    {
      number: 11,
      slug: "ar-11",
      title: "Entretien : atouts, faiblesses, motivation",
      titleEn: "Interview: strengths, weaknesses, motivation",
      summary: "Exprimez vos points forts et votre motivation à rejoindre l'entreprise.",
      summaryEn: "Express your strengths and motivation to join the company.",
      grammar: ["Exprimer ses points forts (نقطة قوة)", "Exprimer ses faiblesses (نقطة ضعف)", "Expliquer sa motivation"],
      explanation:
        "Pour les atouts : « نقطة قوتي هي ... » (nuqṭat quwwatī hiya ...) « ma force est ... », « أنا مجتهد ومنظم » « je suis travailleur et organisé ». Pour les faiblesses : « نقطة ضعفي هي ... » « ma faiblesse est ... ». Pour la motivation : « لماذا تقدمت إلى هذه الشركة ؟ » « pourquoi avez-vous postulé dans cette entreprise ? », réponse type : « لأنني أريد أن أتعلم وأتطور » « parce que je veux apprendre et progresser ».",
      explanationEn:
        "For strengths: 'نقطة قوتي هي ...' (nuqṭat quwwatī hiya ...) 'my strength is ...', 'أنا مجتهد ومنظم' 'I am hardworking and organized'. For weaknesses: 'نقطة ضعفي هي ...' 'my weakness is ...'. For motivation: 'لماذا تقدمت إلى هذه الشركة ؟' 'why did you apply to this company?', typical answer: 'لأنني أريد أن أتعلم وأتطور' 'because I want to learn and progress'.",
      examples: [
        { target: "نقطة قوتي هي العمل في الفريق.", roman: "nuqṭat quwwatī hiya al-ʿamal fī al-farīq.", fr: "Ma force est le travail en équipe.", en: "My strength is teamwork." },
        { target: "أنا مجتهد ومنظم.", roman: "anā mujtahid wa munaẓẓam.", fr: "Je suis travailleur et organisé.", en: "I am hardworking and organized." },
        { target: "أريد أن أتعلم وأتطور.", roman: "urīdu an ataʿallam wa atatawwar.", fr: "Je veux apprendre et progresser.", en: "I want to learn and progress." },
        { target: "لأنني أحب التحديات.", roman: "liʾannanī uḥibb at-taḥaddiyāt.", fr: "Parce que j'aime les défis.", en: "Because I love challenges." },
      ],
      vocab: [
        { target: "نقطة قوة", roman: "nuqṭat quwwa", fr: "point fort", en: "strength" },
        { target: "نقطة ضعف", roman: "nuqṭat ḍuʿf", fr: "point faible", en: "weakness" },
        { target: "مجتهد", roman: "mujtahid", fr: "travailleur", en: "hardworking" },
        { target: "منظم", roman: "munaẓẓam", fr: "organisé", en: "organized" },
        { target: "أتطور", roman: "atatawwar", fr: "je progresse", en: "I progress" },
        { target: "تحدي", roman: "taḥaddin", fr: "défi", en: "challenge" },
        { target: "الدافع", roman: "ad-dāfiʿ", fr: "la motivation", en: "motivation" },
        { target: "الانضباط", roman: "al-inḍibāṭ", fr: "la discipline", en: "discipline" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « point fort » ?",
          promptEn: "How do you say 'strength'?",
          options: ["نقطة قوة", "نقطة ضعف", "هدف", "مهارة"],
          accept: ["نقطة قوة"],
          explain: "« نقطة قوة » (nuqṭat quwwa) signifie « point fort ».",
          explainEn: "'نقطة قوة' (nuqṭat quwwa) means 'strength'.",
        },
        {
          prompt: "Complétez : « أريد أن أتعلم وأن ... » (je veux apprendre et progresser)",
          promptEn: "Complete: 'أريد أن أتعلم وأن ...' (I want to learn and progress)",
          accept: ["أتطور"],
          explain: "« أريد أن أتعلم وأتطور » signifie « je veux apprendre et progresser ».",
          explainEn: "'أريد أن أتعلم وأتطور' means 'I want to learn and progress'.",
        },
        {
          prompt: "Comment dit-on « je suis travailleur et organisé » ?",
          promptEn: "How do you say 'I am hardworking and organized'?",
          options: ["أنا مجتهد ومنظم", "أنا كسول", "أنا متعب", "أنا غاضب"],
          accept: ["أنا مجتهد ومنظم"],
          explain: "« أنا مجتهد ومنظم » signifie « je suis travailleur et organisé ».",
          explainEn: "'أنا مجتهد ومنظم' means 'I am hardworking and organized'.",
        },
      ],
      interview: [
        {
          question: "ما هي نقاط قوتك وضعفك؟",
          roman: "mā hiya nuqaṭ quwwatika wa ḍuʿfika?",
          fr: "Quelles sont vos forces et vos faiblesses ?",
          en: "What are your strengths and weaknesses?",
          modelFr: "Ma force est le travail en équipe et ma faiblesse, je travaille dur pour l'améliorer.",
          modelEn: "My strength is teamwork and my weakness, I work hard to improve it.",
          accept: ["نقطة قوتي هي العمل في الفريق", "أنا مجتهد ومنظم", "نقطة قوتي", "أنا منظم"],
        },
        {
          question: "لماذا تقدمتَ إلى هذه الشركة؟",
          roman: "limādhā taqaddamta ilā hādhihi ash-sharika?",
          fr: "Pourquoi avez-vous postulé dans cette entreprise ?",
          en: "Why did you apply to this company?",
          modelFr: "Parce que je veux apprendre, me développer et contribuer avec mon expérience.",
          modelEn: "Because I want to learn, grow and contribute with my experience.",
          accept: ["أريد أن أتعلم وأتطور", "لأنني أحب التحديات", "أريد أن أتطور", "أريد أن أتعلم"],
        },
      ],
    },
    {
      number: 12,
      slug: "ar-12",
      title: "Entretien : projets, travail d'équipe, gestion du stress",
      titleEn: "Interview: projects, teamwork, stress management",
      summary: "Exprimez vos objectifs futurs et votre capacité à gérer le stress.",
      summaryEn: "Express your future goals and ability to manage stress.",
      grammar: ["Parler de ses projets futurs", "Le travail en équipe", "La gestion du stress"],
      explanation:
        "Pour les projets futurs : « آمل أن ... » (āmal an ...) « j'espère que je ... », « أرى نفسي بعد خمس سنوات ... » (arā nafsī baʿd khams sanawāt ...) « je me vois dans cinq ans ... ». Le travail d'équipe : « أحب العمل مع الآخرين » « j'aime travailler avec les autres ». La gestion du stress : « أتحكم في التوتر » « je gère le stress », « أخذ قسطاً من الراحة » « je prends un moment de repos ». Ces réponses montrent maturité et sérénité.",
      explanationEn:
        "For future projects: 'آمل أن ...' (āmal an ...) 'I hope to ...', 'أرى نفسي بعد خمس سنوات ...' (arā nafsī baʿd khams sanawāt ...) 'I see myself in five years ...'. Teamwork: 'أحب العمل مع الآخرين' 'I like to work with others'. Stress management: 'أتحكم في التوتر' 'I control stress', 'أخذ قسطاً من الراحة' 'I take some rest'. These answers show maturity and calm.",
      examples: [
        { target: "أرى نفسي بعد خمس سنوات في منصب قيادي.", roman: "arā nafsī baʿd khams sanawāt fī manṣib qiyādī.", fr: "Je me vois dans cinq ans dans un poste à responsabilités.", en: "I see myself in five years in a leadership position." },
        { target: "أحب العمل مع الآخرين.", roman: "uḥibb al-ʿamal maʿa al-ākharīn.", fr: "J'aime travailler avec les autres.", en: "I like to work with others." },
        { target: "أتحكم في التوتر.", roman: "ataḥakkam fī at-tawattur.", fr: "Je gère le stress.", en: "I manage stress." },
        { target: "أأخذ قسطاً من الراحة عند الحاجة.", roman: "ākhudhu qiṣṭan min ar-rāḥa ʿind al-ḥāja.", fr: "Je prends un moment de repos quand il le faut.", en: "I take a rest when needed." },
      ],
      vocab: [
        { target: "هدف مستقبلي", roman: "hadaf mustaqbalī", fr: "objectif futur", en: "future goal" },
        { target: "بعد خمس سنوات", roman: "baʿd khams sanawāt", fr: "dans cinq ans", en: "in five years" },
        { target: "منصب قيادي", roman: "manṣib qiyādī", fr: "poste à responsabilités", en: "leadership position" },
        { target: "العمل الجماعي", roman: "al-ʿamal al-jamāʿī", fr: "le travail collectif", en: "teamwork" },
        { target: "التوتر", roman: "at-tawattur", fr: "le stress", en: "stress" },
        { target: "أتحكم", roman: "ataḥakkam", fr: "je contrôle, je gère", en: "I manage, I control" },
        { target: "راحة", roman: "rāḥa", fr: "repos", en: "rest" },
        { target: "آمل", roman: "āmal", fr: "j'espère", en: "I hope" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « je me vois dans cinq ans » ?",
          promptEn: "How do you say 'I see myself in five years'?",
          options: ["أرى نفسي بعد خمس سنوات", "أنا متعب", "أنا أذهب", "لا أعرف"],
          accept: ["أرى نفسي بعد خمس سنوات"],
          explain: "« أرى نفسي بعد خمس سنوات » signifie « je me vois dans cinq ans ».",
          explainEn: "'أرى نفسي بعد خمس سنوات' means 'I see myself in five years'.",
        },
        {
          prompt: "Complétez : « أحب العمل ... » (j'aime travailler avec les autres)",
          promptEn: "Complete: 'أحب العمل ...' (I like to work with others)",
          accept: ["مع الآخرين", "مع الناس"],
          explain: "« أحب العمل مع الآخرين » signifie « j'aime travailler avec les autres ».",
          explainEn: "'أحب العمل مع الآخرين' means 'I like to work with others'.",
        },
        {
          prompt: "Comment dit-on « je gère le stress » ?",
          promptEn: "How do you say 'I manage stress'?",
          options: ["أتحكم في التوتر", "أخاف", "أنا غاضب", "أعمل كثيراً"],
          accept: ["أتحكم في التوتر"],
          explain: "« أتحكم في التوتر » (ataḥakkam fī at-tawattur) signifie « je gère le stress ».",
          explainEn: "'أتحكم في التوتر' (ataḥakkam fī at-tawattur) means 'I manage stress'.",
        },
      ],
      interview: [
        {
          question: "أين ترى نفسك بعد خمس سنوات؟",
          roman: "ayna tarā nafsaka baʿd khams sanawāt?",
          fr: "Où vous voyez-vous dans cinq ans ?",
          en: "Where do you see yourself in five years?",
          modelFr: "Je me vois dans un poste à responsabilités, en train de contribuer à la réussite de l'entreprise.",
          modelEn: "I see myself in a leadership position, contributing to the company's success.",
          accept: ["أرى نفسي بعد خمس سنوات في منصب قيادي", "في منصب قيادي", "أرى نفسي في منصب قيادي"],
        },
        {
          question: "كيف تدير التوتر في العمل؟",
          roman: "kayfa tudīr at-tawattur fī al-ʿamal?",
          fr: "Comment gérez-vous le stress au travail ?",
          en: "How do you manage stress at work?",
          modelFr: "Je m'organise, je priorise et je prends un moment de repos quand il le faut.",
          modelEn: "I organize myself, set priorities and take a rest when needed.",
          accept: ["أتحكم في التوتر", "أأخذ قسطاً من الراحة", "أنظم وقتي", "أتحكم في التوتر بالراحة"],
        },
      ],
    },
  ],
};
