import type { LanguageCourse } from "./genericLessons";

export const CN_COURSE: LanguageCourse = {
  code: "cn",
  name: "Chinois",
  native: "中文",
  heroTitle1: { fr: "Apprenez", en: "Learn" },
  heroTitle2: { fr: "le chinois", en: "Chinese" },
  heroSubtitle: {
    fr: "Un parcours débutant en douze leçons : salutations, vie quotidienne, travail et entretien d'embauche en mandarin.",
    en: "A beginner path in twelve lessons: greetings, daily life, work and the job interview in Mandarin.",
  },
  lessons: [
    {
      number: 1,
      slug: "cn-01",
      title: "Se présenter et saluer",
      titleEn: "Introducing yourself and greeting",
      summary:
        "Les salutations de base et les présentations : dire bonjour, donner son nom et dire d'où l'on vient.",
      summaryEn:
        "Basic greetings and introductions: saying hello, giving your name and saying where you come from.",
      grammar: ["动词 是 (être)", "人称代词 (pronoms personnels)", "你好 / 我叫 / 我来自"],
      explanation:
        "En chinois, les salutations les plus courantes sont 你好 (nǐ hǎo, bonjour), 早上好 (zǎoshang hǎo, bonjour le matin) et 再见 (zàijiàn, au revoir). Pour se présenter, on dit 我叫... (wǒ jiào..., je m'appelle...) ou 我是... (wǒ shì..., je suis...). On exprime son origine avec 我来自 (wǒ láizì, je viens de). Le verbe 是 (shì, être) relie le sujet à ce qu'il est : 我是老师 (wǒ shì lǎoshī, je suis professeur). Le pronom sujet 我 (wǒ, je) s'écrit toujours devant le verbe, contrairement au français.",
      explanationEn:
        "In Chinese the most common greetings are 你好 (nǐ hǎo, hello), 早上好 (zǎoshang hǎo, good morning) and 再见 (zàijiàn, goodbye). To introduce yourself you say 我叫... (wǒ jiào..., my name is...) or 我是... (wǒ shì..., I am...). You express your origin with 我来自 (wǒ láizì, I come from). The verb 是 (shì, to be) links the subject to what it is: 我是老师 (wǒ shì lǎoshī, I am a teacher). The subject pronoun 我 (wǒ, I) is always written before the verb, unlike in French or English.",
      examples: [
        { target: "你好，我叫丹尼尔。", roman: "Nǐ hǎo, wǒ jiào Dānní'ěr.", fr: "Bonjour, je m'appelle Daniel.", en: "Hello, my name is Daniel." },
        { target: "很高兴认识你。", roman: "Hěn gāoxìng rènshi nǐ.", fr: "Enchanté de faire votre connaissance.", en: "Nice to meet you." },
        { target: "我来自法国。", roman: "Wǒ láizì Fǎguó.", fr: "Je viens de France.", en: "I come from France." },
        { target: "我是学生。", roman: "Wǒ shì xuésheng.", fr: "Je suis étudiant.", en: "I am a student." },
      ],
      vocab: [
        { target: "你好", roman: "nǐ hǎo", fr: "bonjour, salut", en: "hello, hi" },
        { target: "我叫", roman: "wǒ jiào", fr: "je m'appelle", en: "my name is" },
        { target: "我来自", roman: "wǒ láizì", fr: "je viens de", en: "I come from" },
        { target: "我是", roman: "wǒ shì", fr: "je suis", en: "I am" },
        { target: "很高兴认识你", roman: "hěn gāoxìng rènshi nǐ", fr: "enchanté de vous rencontrer", en: "nice to meet you" },
        { target: "谢谢", roman: "xièxie", fr: "merci", en: "thank you" },
        { target: "再见", roman: "zàijiàn", fr: "au revoir", en: "goodbye" },
        { target: "老师", roman: "lǎoshī", fr: "professeur", en: "teacher" },
      ],
      exercises: [
        {
          prompt: "Complète pour dire « je m'appelle Ana » : « 我___ 安娜。 »",
          promptEn: "Complete to say \"my name is Ana\": \"我___ 安娜。\"",
          accept: ["叫"],
          explain: "On utilise 叫 (jiào) pour donner son nom : 我叫安娜 (wǒ jiào Ānnà). Le verbe 叫 signifie « s'appeler ».",
          explainEn: "We use 叫 (jiào) to give a name: 我叫安娜 (wǒ jiào Ānnà). The verb 叫 means \"to be called\".",
        },
        {
          prompt: "Quelle salutation utilise-t-on le matin ?",
          promptEn: "Which greeting do you use in the morning?",
          options: ["早上好", "再见", "谢谢"],
          accept: ["早上好"],
          explain: "早上好 (zǎoshang hǎo) se dit le matin ; 再见 (zàijiàn) pour dire au revoir et 谢谢 (xièxie) pour remercier.",
          explainEn: "早上好 (zǎoshang hǎo) is said in the morning; 再见 (zàijiàn) to say goodbye and 谢谢 (xièxie) to say thank you.",
        },
        {
          prompt: "Comment dis-tu « je viens de France » ?",
          promptEn: "How do you say \"I come from France\"?",
          options: ["我来自法国", "我叫法国", "我老师法国"],
          accept: ["我来自法国"],
          explain: "On exprime l'origine avec 我来自 (wǒ láizì) : 我来自法国.",
          explainEn: "You express origin with 我来自 (wǒ láizì): 我来自法国.",
        },
      ],
      interview: [
        {
          question: "请介绍一下你自己。",
          roman: "Qǐng jièshào yīxià nǐ zìjǐ.",
          fr: "Présentez-vous.",
          en: "Tell me about yourself.",
          modelFr: "Je m'appelle Daniel, je viens de France et je suis ingénieur logiciel avec cinq ans d'expérience.",
          modelEn: "My name is Daniel, I come from France and I am a software engineer with five years of experience.",
          accept: ["你好，我叫", "我来自法国", "我是工程师"],
        },
        {
          question: "你今天怎么样？",
          roman: "Nǐ jīntiān zěnme yàng?",
          fr: "Comment allez-vous aujourd'hui ?",
          en: "How are you today?",
          modelFr: "Je vais très bien, merci. Je suis très heureux de participer à cet entretien.",
          modelEn: "I am very well, thank you. I am very happy to take part in this interview.",
          accept: ["我很好", "非常高兴", "谢谢"],
        },
      ],
    },
    {
      number: 2,
      slug: "cn-02",
      title: "Origine, nationalité et profession",
      titleEn: "Origin, nationality and profession",
      summary:
        "Dire d'où l'on vient, sa nationalité et sa profession avec les verbes 是 et 住.",
      summaryEn:
        "Saying where you come from, your nationality and your job with the verbs 是 and 住.",
      grammar: ["国家 + 人 (nationalités)", "动词 住 (habiter)", "工作/职业 (professions)"],
      explanation:
        "La nationalité s'exprime avec le nom du pays + 人 (rén, personne) : 法国人 (Fǎguó rén, Français), 中国人 (Zhōngguó rén, Chinois). Pour dire sa profession on utilise 是 (shì, être) : 我是工程师 (wǒ shì gōngchéngshī, je suis ingénieur). Pour dire où l'on vit, on emploie le verbe 住 (zhù, habiter) avec 在 (zài, à) : 我住在巴黎 (wǒ zhù zài Bālí, j'habite à Paris). Construction de la phrase : sujet + 是 + profession, sujet + 住 + 在 + lieu.",
      explanationEn:
        "Nationality is expressed with the name of the country + 人 (rén, person): 法国人 (Fǎguó rén, French person), 中国人 (Zhōngguó rén, Chinese person). To say your job you use 是 (shì, to be): 我是工程师 (wǒ shì gōngchéngshī, I am an engineer). To say where you live, use the verb 住 (zhù, to live) with 在 (zài, in/at): 我住在巴黎 (wǒ zhù zài Bālí, I live in Paris). Sentence structure: subject + 是 + job, subject + 住 + 在 + place.",
      examples: [
        { target: "我是法国人。", roman: "Wǒ shì Fǎguó rén.", fr: "Je suis français.", en: "I am French." },
        { target: "我住在上海。", roman: "Wǒ zhù zài Shànghǎi.", fr: "J'habite à Shanghai.", en: "I live in Shanghai." },
        { target: "你是医生吗？", roman: "Nǐ shì yīshēng ma?", fr: "Es-tu médecin ?", en: "Are you a doctor?" },
        { target: "她是工程师。", roman: "Tā shì gōngchéngshī.", fr: "Elle est ingénieure.", en: "She is an engineer." },
      ],
      vocab: [
        { target: "法国", roman: "Fǎguó", fr: "la France", en: "France" },
        { target: "中国", roman: "Zhōngguó", fr: "la Chine", en: "China" },
        { target: "法国人", roman: "Fǎguó rén", fr: "Français(e)", en: "French person" },
        { target: "住在", roman: "zhù zài", fr: "habiter à", en: "to live in" },
        { target: "医生", roman: "yīshēng", fr: "médecin", en: "doctor" },
        { target: "工程师", roman: "gōngchéngshī", fr: "ingénieur", en: "engineer" },
        { target: "学生", roman: "xuésheng", fr: "étudiant(e)", en: "student" },
        { target: "哪儿", roman: "nǎr", fr: "où", en: "where" },
      ],
      exercises: [
        {
          prompt: "Complète : « 我___ 法国人。 » (verbe être)",
          promptEn: "Complete: \"我___ 法国人。\" (verb to be)",
          accept: ["是"],
          explain: "Le verbe être se dit 是 (shì) : 我是法国人.",
          explainEn: "The verb to be is 是 (shì): 我是法国人.",
        },
        {
          prompt: "Comment dit-on « j'habite à Paris » ?",
          promptEn: "How do you say \"I live in Paris\"?",
          options: ["我住在巴黎", "我巴黎住", "我是巴黎"],
          accept: ["我住在巴黎"],
          explain: "On utilise 住 (zhù) + 在 (zài) + lieu : 我住在巴黎.",
          explainEn: "We use 住 (zhù) + 在 (zài) + place: 我住在巴黎.",
        },
        {
          prompt: "Quel caractère signifie « où » ?",
          promptEn: "Which character means \"where\"?",
          options: ["哪儿", "医生", "法国"],
          accept: ["哪儿"],
          explain: "哪儿 (nǎr) signifie « où » : 你是哪儿人？ (d'où es-tu ?).",
          explainEn: "哪儿 (nǎr) means \"where\": 你是哪儿人？ (where are you from?).",
        },
      ],
    },
    {
      number: 3,
      slug: "cn-03",
      title: "Le verbe 是 et 有 (être et avoir)",
      titleEn: "The verbs 是 and 有 (to be and to have)",
      summary:
        "Les deux verbes essentiels : 是 (être) pour les attributs et 有 (avoir) pour la possession.",
      summaryEn:
        "The two essential verbs: 是 (to be) for attributes and 有 (to have) for possession.",
      grammar: ["Sujet + 是 + nom", "Sujet + 有 + objet", "Négation avec 不/没"],
      explanation:
        "Le verbe 是 (shì, être) ne change jamais de forme : 我是 (wǒ shì, je suis), 你是 (nǐ shì, tu es), 他是 (tā shì, il est). Le verbe 有 (yǒu, avoir) exprime la possession : 我有一个弟弟 (wǒ yǒu yī gè dìdi, j'ai un petit frère). La négation de 是 se fait avec 不是 (bù shì, ne pas être) : 我不是老师 (je ne suis pas professeur). La négation de 有 se fait avec 没有 (méi yǒu) : 我没有时间 (wǒ méi yǒu shíjiān, je n'ai pas le temps). Le classificateur 个 (gè) s'insère entre le nombre et le nom : 一个 (un), 两个 (deux).",
      explanationEn:
        "The verb 是 (shì, to be) never changes its form: 我是 (wǒ shì, I am), 你是 (nǐ shì, you are), 他是 (tā shì, he is). The verb 有 (yǒu, to have) expresses possession: 我有一个弟弟 (wǒ yǒu yī gè dìdi, I have a little brother). The negative of 是 is formed with 不是 (bù shì, not to be): 我不是老师 (I am not a teacher). The negative of 有 is 没有 (méi yǒu): 我没有时间 (wǒ méi yǒu shíjiān, I do not have time). The measure word 个 (gè) is inserted between the number and the noun: 一个 (one), 两个 (two).",
      examples: [
        { target: "我有一个哥哥。", roman: "Wǒ yǒu yī gè gēge.", fr: "J'ai un grand frère.", en: "I have an older brother." },
        { target: "你是老师吗？不是。", roman: "Nǐ shì lǎoshī ma? Bù shì.", fr: "Es-tu professeur ? Non.", en: "Are you a teacher? No." },
        { target: "她有两个孩子。", roman: "Tā yǒu liǎng gè háizi.", fr: "Elle a deux enfants.", en: "She has two children." },
        { target: "我没有时间。", roman: "Wǒ méi yǒu shíjiān.", fr: "Je n'ai pas le temps.", en: "I do not have time." },
      ],
      vocab: [
        { target: "有", roman: "yǒu", fr: "avoir", en: "to have" },
        { target: "是", roman: "shì", fr: "être", en: "to be" },
        { target: "不是", roman: "bù shì", fr: "ne pas être", en: "not to be" },
        { target: "没有", roman: "méi yǒu", fr: "ne pas avoir", en: "not to have" },
        { target: "个", roman: "gè", fr: "classificateur (général)", en: "measure word (general)" },
        { target: "时间", roman: "shíjiān", fr: "le temps", en: "time" },
        { target: "孩子", roman: "háizi", fr: "enfant", en: "child" },
        { target: "哥哥", roman: "gēge", fr: "grand frère", en: "older brother" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « je n'ai pas le temps » ?",
          promptEn: "How do you say \"I do not have time\"?",
          options: ["我没有时间", "我不是时间", "我有时间"],
          accept: ["我没有时间"],
          explain: "La négation de 有 (avoir) est 没有 (méi yǒu) : 我没有时间.",
          explainEn: "The negative of 有 (to have) is 没有 (méi yǒu): 我没有时间.",
        },
        {
          prompt: "Complète : « 我___ 老师。 » (verbe être)",
          promptEn: "Complete: \"我___ 老师。\" (verb to be)",
          accept: ["是"],
          explain: "Le verbe être est 是 (shì) : 我是老师.",
          explainEn: "The verb to be is 是 (shì): 我是老师.",
        },
        {
          prompt: "Quel nom se met entre le nombre et le nom en chinois ?",
          promptEn: "Which word goes between the number and the noun in Chinese?",
          options: ["个", "是", "有"],
          accept: ["个"],
          explain: "Le classificateur 个 (gè) s'emploie entre le nombre et le nom : 一个孩子.",
          explainEn: "The measure word 个 (gè) is used between the number and the noun: 一个孩子.",
        },
      ],
    },
    {
      number: 4,
      slug: "cn-04",
      title: "La routine quotidienne",
      titleEn: "The daily routine",
      summary:
        "Décrire sa journée typique : se lever, travailler, dormir avec les verbes d'action.",
      summaryEn:
        "Describing a typical day: getting up, working, sleeping with action verbs.",
      grammar: ["Verbes d'action (起床, 上班)", "早上/中午/晚上 (moments)", "Adverbe 每天 (chaque jour)"],
      explanation:
        "Les verbes d'action se placent après le sujet : 我起床 (wǒ qǐchuáng, je me lève), 我去上班 (wǒ qù shàngbān, je vais travailler). Les moments de la journée s'expriment avec 早上 (zǎoshang, le matin), 中午 (zhōngwǔ, midi), 晚上 (wǎnshang, le soir). L'adverbe 每天 (měitiān, chaque jour) exprime la routine : 我每天七点起床 (wǒ měitiān qī diǎn qǐchuáng, je me lève chaque jour à sept heures). Pour les heures on dit 点 (diǎn, heure) : 七点 (qī diǎn, sept heures).",
      explanationEn:
        "Action verbs come after the subject: 我起床 (wǒ qǐchuáng, I get up), 我去上班 (wǒ qù shàngbān, I go to work). Times of day are expressed with 早上 (zǎoshang, morning), 中午 (zhōngwǔ, noon), 晚上 (wǎnshang, evening). The adverb 每天 (měitiān, every day) expresses routine: 我每天七点起床 (wǒ měitiān qī diǎn qǐchuáng, I get up at seven o'clock every day). For hours we say 点 (diǎn, o'clock): 七点 (qī diǎn, seven o'clock).",
      examples: [
        { target: "我每天七点起床。", roman: "Wǒ měitiān qī diǎn qǐchuáng.", fr: "Je me lève à sept heures chaque jour.", en: "I get up at seven o'clock every day." },
        { target: "早上我去上班。", roman: "Zǎoshang wǒ qù shàngbān.", fr: "Le matin, je vais travailler.", en: "In the morning I go to work." },
        { target: "中午我吃午饭。", roman: "Zhōngwǔ wǒ chī wǔfàn.", fr: "À midi, je déjeune.", en: "At noon I have lunch." },
        { target: "晚上我睡觉。", roman: "Wǎnshang wǒ shuìjiào.", fr: "Le soir, je dors.", en: "In the evening I sleep." },
      ],
      vocab: [
        { target: "起床", roman: "qǐchuáng", fr: "se lever", en: "to get up" },
        { target: "上班", roman: "shàngbān", fr: "aller travailler", en: "to go to work" },
        { target: "吃午饭", roman: "chī wǔfàn", fr: "déjeuner", en: "to have lunch" },
        { target: "睡觉", roman: "shuìjiào", fr: "dormir", en: "to sleep" },
        { target: "每天", roman: "měitiān", fr: "chaque jour", en: "every day" },
        { target: "早上", roman: "zǎoshang", fr: "le matin", en: "morning" },
        { target: "中午", roman: "zhōngwǔ", fr: "le midi", en: "noon" },
        { target: "晚上", roman: "wǎnshang", fr: "le soir", en: "evening" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « je vais travailler » ?",
          promptEn: "How do you say \"I go to work\"?",
          options: ["我去上班", "我睡觉", "我起床"],
          accept: ["我去上班"],
          explain: "去上班 (qù shàngbān) signifie « aller au travail » : 我去上班.",
          explainEn: "去上班 (qù shàngbān) means \"to go to work\": 我去上班.",
        },
        {
          prompt: "Complète : « 我每天七点___ 。 » (se lever)",
          promptEn: "Complete: \"我每天七点___ 。\" (to get up)",
          accept: ["起床"],
          explain: "Le verbe 起床 (qǐchuáng) signifie « se lever » : 我每天七点起床.",
          explainEn: "The verb 起床 (qǐchuáng) means \"to get up\": 我每天七点起床.",
        },
        {
          prompt: "Quel mot signifie « midi » ?",
          promptEn: "Which word means \"noon\"?",
          options: ["中午", "早上", "晚上"],
          accept: ["中午"],
          explain: "中午 (zhōngwǔ) = midi ; 早上 (zǎoshang) = matin ; 晚上 (wǎnshang) = soir.",
          explainEn: "中午 (zhōngwǔ) = noon; 早上 (zǎoshang) = morning; 晚上 (wǎnshang) = evening.",
        },
      ],
    },
    {
      number: 5,
      slug: "cn-05",
      title: "Les goûts et loisirs",
      titleEn: "Tastes and leisure activities",
      summary:
        "Parler de ce qu'on aime ou n'aime pas faire : 我喜欢... (j'aime) et 我不喜欢... (je n'aime pas).",
      summaryEn:
        "Talking about what you like or dislike doing: 我喜欢... (I like) and 我不喜欢... (I do not like).",
      grammar: ["动词 喜欢 (aimer)", "不喜欢 (ne pas aimer)", "动词 + 吗 ? (question)"],
      explanation:
        "Pour exprimer ses goûts, on utilise le verbe 喜欢 (xǐhuan, aimer) suivi d'un nom ou d'un verbe : 我喜欢音乐 (wǒ xǐhuan yīnyuè, j'aime la musique), 我喜欢看书 (wǒ xǐhuan kànshū, j'aime lire). La négation se forme avec 不 : 我不喜欢 (wǒ bù xǐhuan, je n'aime pas). Pour poser une question, on ajoute la particule 吗 (ma) en fin de phrase : 你喜欢看书吗？ (nǐ xǐhuan kànshū ma?, aimes-tu lire ?). Le verbe reste invariable quelle que soit la personne.",
      explanationEn:
        "To express tastes, use the verb 喜欢 (xǐhuan, to like) followed by a noun or a verb: 我喜欢音乐 (wǒ xǐhuan yīnyuè, I like music), 我喜欢看书 (wǒ xǐhuan kànshū, I like reading). The negative is formed with 不: 我不喜欢 (wǒ bù xǐhuan, I do not like). To ask a question, add the particle 吗 (ma) at the end: 你喜欢看书吗？ (nǐ xǐhuan kànshū ma?, do you like reading?). The verb stays the same for every person.",
      examples: [
        { target: "我喜欢看书。", roman: "Wǒ xǐhuan kànshū.", fr: "J'aime lire.", en: "I like reading." },
        { target: "我不喜欢看电视。", roman: "Wǒ bù xǐhuan kàn diànshì.", fr: "Je n'aime pas regarder la télévision.", en: "I do not like watching television." },
        { target: "你喜欢音乐吗？", roman: "Nǐ xǐhuan yīnyuè ma?", fr: "Aimes-tu la musique ?", en: "Do you like music?" },
        { target: "我平时喜欢运动。", roman: "Wǒ píngshí xǐhuan yùndòng.", fr: "D'habitude, j'aime faire du sport.", en: "I usually like doing sports." },
      ],
      vocab: [
        { target: "喜欢", roman: "xǐhuan", fr: "aimer", en: "to like" },
        { target: "不喜欢", roman: "bù xǐhuan", fr: "ne pas aimer", en: "to dislike" },
        { target: "看书", roman: "kànshū", fr: "lire", en: "to read" },
        { target: "音乐", roman: "yīnyuè", fr: "la musique", en: "music" },
        { target: "运动", roman: "yùndòng", fr: "le sport", en: "sports" },
        { target: "电影", roman: "diànyǐng", fr: "le film", en: "movie" },
        { target: "吗", roman: "ma", fr: "particule interrogative", en: "interrogative particle" },
        { target: "平时", roman: "píngshí", fr: "d'habitude", en: "usually" },
      ],
      exercises: [
        {
          prompt: "Comment dis-tu « j'aime la musique » ?",
          promptEn: "How do you say \"I like music\"?",
          options: ["我喜欢音乐", "我不喜欢音乐", "我喜欢运动"],
          accept: ["我喜欢音乐"],
          explain: "喜欢 (xǐhuan) signifie « aimer » : 我喜欢音乐.",
          explainEn: "喜欢 (xǐhuan) means \"to like\": 我喜欢音乐.",
        },
        {
          prompt: "Complète pour poser une question : « 你喜欢电影___ ？ »",
          promptEn: "Complete to ask a question: \"你喜欢电影___ ？\"",
          accept: ["吗"],
          explain: "La particule 吗 (ma) en fin de phrase transforme une affirmation en question.",
          explainEn: "The particle 吗 (ma) at the end of a sentence turns a statement into a question.",
        },
        {
          prompt: "Quelle est la négation de 喜欢 ?",
          promptEn: "What is the negative of 喜欢?",
          options: ["不喜欢", "没喜欢", "一喜欢"],
          accept: ["不喜欢"],
          explain: "La négation se forme avec 不 : 不喜欢 (bù xǐhuan).",
          explainEn: "The negative is formed with 不: 不喜欢 (bù xǐhuan).",
        },
      ],
    },
    {
      number: 6,
      slug: "cn-06",
      title: "La famille et les personnes",
      titleEn: "Family and people",
      summary:
        "Présenter sa famille et les personnes : parents, frères, sœurs et les termes d'adresse.",
      summaryEn:
        "Presenting your family and people: parents, brothers, sisters and terms of address.",
      grammar: ["父亲/母亲/父母 (parents)", "哥哥/弟弟/姐姐/妹妹 (frères et sœurs)", "Quantificateur 个 avec les personnes"],
      explanation:
        "Le vocabulaire familial distingue l'âge et le sexe : 哥哥 (gēge, grand frère), 弟弟 (dìdi, petit frère), 姐姐 (jiějie, grande sœur), 妹妹 (mèimei, petite sœur). Pour dire plus généralement : 爸爸 (bàba, papa), 妈妈 (māma, maman), 父母 (fùmǔ, les parents). Pour compter les personnes, on utilise le classificateur 个 (gè) : 两个人 (liǎng gè rén, deux personnes). On emploie 我 (wǒ) pour exprimer la possession : 我的妈妈 (wǒ de māma, ma maman).",
      explanationEn:
        "Family vocabulary distinguishes age and sex: 哥哥 (gēge, older brother), 弟弟 (dìdi, younger brother), 姐姐 (jiějie, older sister), 妹妹 (mèimei, younger sister). More generally: 爸爸 (bàba, dad), 妈妈 (māma, mum), 父母 (fùmǔ, parents). To count people we use the measure word 个 (gè): 两个人 (liǎng gè rén, two people). We use 我 (wǒ) with the possessive 的 (de): 我的妈妈 (wǒ de māma, my mother).",
      examples: [
        { target: "我的爸爸是医生。", roman: "Wǒ de bàba shì yīshēng.", fr: "Mon papa est médecin.", en: "My father is a doctor." },
        { target: "我有一个弟弟。", roman: "Wǒ yǒu yī gè dìdi.", fr: "J'ai un petit frère.", en: "I have a younger brother." },
        { target: "我妈妈是老师。", roman: "Wǒ māma shì lǎoshī.", fr: "Ma maman est professeure.", en: "My mother is a teacher." },
        { target: "我们家有四口人。", roman: "Wǒmen jiā yǒu sì kǒu rén.", fr: "Nous sommes quatre dans ma famille.", en: "There are four people in my family." },
      ],
      vocab: [
        { target: "爸爸", roman: "bàba", fr: "papa", en: "dad" },
        { target: "妈妈", roman: "māma", fr: "maman", en: "mum" },
        { target: "哥哥", roman: "gēge", fr: "grand frère", en: "older brother" },
        { target: "弟弟", roman: "dìdi", fr: "petit frère", en: "younger brother" },
        { target: "姐姐", roman: "jiějie", fr: "grande sœur", en: "older sister" },
        { target: "妹妹", roman: "mèimei", fr: "petite sœur", en: "younger sister" },
        { target: "人", roman: "rén", fr: "personne", en: "person" },
        { target: "的", roman: "de", fr: "particule de possession", en: "possessive particle" },
      ],
      exercises: [
        {
          prompt: "Quel mot désigne le « grand frère » ?",
          promptEn: "Which word refers to the \"older brother\"?",
          options: ["哥哥", "弟弟", "妹妹"],
          accept: ["哥哥"],
          explain: "哥哥 (gēge) = grand frère ; 弟弟 (dìdi) = petit frère ; 妹妹 (mèimei) = petite sœur.",
          explainEn: "哥哥 (gēge) = older brother; 弟弟 (dìdi) = younger brother; 妹妹 (mèimei) = younger sister.",
        },
        {
          prompt: "Complète : « 我___ 一个哥哥。 » (avoir)",
          promptEn: "Complete: \"我___ 一个哥哥。\" (to have)",
          accept: ["有"],
          explain: "Le verbe avoir est 有 (yǒu) : 我有一个哥哥 (j'ai un grand frère).",
          explainEn: "The verb to have is 有 (yǒu): 我有一个哥哥 (I have an older brother).",
        },
        {
          prompt: "Comment dit-on « ma maman » ?",
          promptEn: "How do you say \"my mother\"?",
          options: ["我的妈妈", "妈妈的我", "我妈妈吗"],
          accept: ["我的妈妈"],
          explain: "La possession se marque avec 的 (de) : 我的妈妈 = ma maman.",
          explainEn: "Possession is marked with 的 (de): 我的妈妈 = my mother.",
        },
      ],
    },
    {
      number: 7,
      slug: "cn-07",
      title: "Le travail et le bureau",
      titleEn: "Work and the office",
      summary:
        "Parler de son travail, des collègues et de l'entreprise : 工作, 办公室, 同事.",
      summaryEn:
        "Talking about your job, colleagues and the company: 工作, 办公室, 同事.",
      grammar: ["动词 工作 (travailler)", "名词 公司 (l'entreprise)", "名词 同事 (les collègues)"],
      explanation:
        "Le mot 工作 (gōngzuò) signifie à la fois « travailler » et « le travail » : 我在一家公司工作 (wǒ zài yī jiā gōngsī gōngzuò, je travaille dans une entreprise). L'entreprise se dit 公司 (gōngsī), le bureau 办公室 (bàngōngshì), le collègue 同事 (tóngshì). Pour dire où l'on travaille, on utilise la préposition 在 (zài, à/dans) : 我在这家公司工作 (wǒ zài zhè jiā gōngsī gōngzuò, je travaille dans cette entreprise). Le classificateur 家 (jiā) s'emploie pour les entreprises : 一家公司.",
      explanationEn:
        "The word 工作 (gōngzuò) means both \"to work\" and \"work\": 我在一家公司工作 (wǒ zài yī jiā gōngsī gōngzuò, I work in a company). The company is 公司 (gōngsī), the office 办公室 (bàngōngshì), the colleague 同事 (tóngshì). To say where you work, use the preposition 在 (zài, at/in): 我在这家公司工作 (wǒ zài zhè jiā gōngsī gōngzuò, I work in this company). The measure word 家 (jiā) is used for companies: 一家公司.",
      examples: [
        { target: "我在这家公司工作。", roman: "Wǒ zài zhè jiā gōngsī gōngzuò.", fr: "Je travaille dans cette entreprise.", en: "I work in this company." },
        { target: "我的办公室在二楼。", roman: "Wǒ de bàngōngshì zài èr lóu.", fr: "Mon bureau est au deuxième étage.", en: "My office is on the second floor." },
        { target: "我的同事很友好。", roman: "Wǒ de tóngshì hěn yǒuhǎo.", fr: "Mes collègues sont très sympathiques.", en: "My colleagues are very friendly." },
        { target: "我喜欢我的工作。", roman: "Wǒ xǐhuan wǒ de gōngzuò.", fr: "J'aime mon travail.", en: "I like my job." },
      ],
      vocab: [
        { target: "工作", roman: "gōngzuò", fr: "travailler, le travail", en: "to work, work" },
        { target: "公司", roman: "gōngsī", fr: "l'entreprise", en: "company" },
        { target: "办公室", roman: "bàngōngshì", fr: "le bureau", en: "office" },
        { target: "同事", roman: "tóngshì", fr: "le collègue", en: "colleague" },
        { target: "在", roman: "zài", fr: "à, dans (préposition)", en: "at, in (preposition)" },
        { target: "家", roman: "jiā", fr: "classificateur des entreprises", en: "measure word for companies" },
        { target: "友好", roman: "yǒuhǎo", fr: "sympathique, amical", en: "friendly" },
        { target: "二楼", roman: "èr lóu", fr: "le deuxième étage", en: "the second floor" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « je travaille dans cette entreprise » ?",
          promptEn: "How do you say \"I work in this company\"?",
          options: ["我在这家公司工作", "我工作公司在这", "我办公室工作"],
          accept: ["我在这家公司工作"],
          explain: "On utilise 在 (zài) + 公司 (gōngsī) + 工作 (gōngzuò) : 我在这家公司工作.",
          explainEn: "We use 在 (zài) + 公司 (gōngsī) + 工作 (gōngzuò): 我在这家公司工作.",
        },
        {
          prompt: "Quel mot signifie « collègue » ?",
          promptEn: "Which word means \"colleague\"?",
          options: ["同事", "公司", "办公室"],
          accept: ["同事"],
          explain: "同事 (tóngshì) signifie « collègue » ; 公司 (gōngsī) = entreprise ; 办公室 (bàngōngshì) = bureau.",
          explainEn: "同事 (tóngshì) means \"colleague\"; 公司 (gōngsī) = company; 办公室 (bàngōngshì) = office.",
        },
        {
          prompt: "Complète : « 我___ 一家公司工作。 »",
          promptEn: "Complete: \"我___ 一家公司工作。\"",
          accept: ["在"],
          explain: "La préposition 在 (zài) indique le lieu : 我在一家公司工作.",
          explainEn: "The preposition 在 (zài) indicates the place: 我在一家公司工作.",
        },
      ],
    },
    {
      number: 8,
      slug: "cn-08",
      title: "Faire des achats et commander",
      titleEn: "Shopping and ordering",
      summary:
        "Acheter au marché et commander au restaurant : demander un prix et commander.",
      summaryEn:
        "Shopping at the market and ordering at a restaurant: asking a price and ordering.",
      grammar: ["动词 买 (acheter)", "多少钱 ? (combien ça coûte ?)", "我要... (je voudrais...)"],
      explanation:
        "Pour acheter, on utilise le verbe 买 (mǎi, acheter) : 我要买苹果 (wǒ yào mǎi píngguǒ, je veux acheter des pommes). Pour demander le prix, on dit 多少钱？ (duōshao qián?, combien ça coûte ?). Pour commander au restaurant, on dit 我要... (wǒ yào..., je voudrais...) : 我要一杯咖啡 (wǒ yào yī bēi kāfēi, je voudrais un café). Le classificateur 杯 (bēi) s'emploie pour les boissons en tasse, 个 (gè) pour les objets généraux.",
      explanationEn:
        "To shop, use the verb 买 (mǎi, to buy): 我要买苹果 (wǒ yào mǎi píngguǒ, I want to buy apples). To ask the price, say 多少钱？ (duōshao qián?, how much is it?). To order at a restaurant, say 我要... (wǒ yào..., I would like...): 我要一杯咖啡 (wǒ yào yī bēi kāfēi, I would like a coffee). The measure word 杯 (bēi) is used for drinks in a cup, 个 (gè) for general objects.",
      examples: [
        { target: "这个苹果多少钱？", roman: "Zhège píngguǒ duōshao qián?", fr: "Combien coûtent ces pommes ?", en: "How much are these apples?" },
        { target: "我要买水果。", roman: "Wǒ yào mǎi shuǐguǒ.", fr: "Je veux acheter des fruits.", en: "I want to buy some fruit." },
        { target: "请给我一杯咖啡。", roman: "Qǐng gěi wǒ yī bēi kāfēi.", fr: "S'il vous plaît, donnez-moi un café.", en: "Please give me a coffee." },
        { target: "太贵了！", roman: "Tài guì le!", fr: "C'est trop cher !", en: "It is too expensive!" },
      ],
      vocab: [
        { target: "买", roman: "mǎi", fr: "acheter", en: "to buy" },
        { target: "多少钱", roman: "duōshao qián", fr: "combien ça coûte", en: "how much is it" },
        { target: "苹果", roman: "píngguǒ", fr: "la pomme", en: "apple" },
        { target: "水果", roman: "shuǐguǒ", fr: "les fruits", en: "fruit" },
        { target: "咖啡", roman: "kāfēi", fr: "le café", en: "coffee" },
        { target: "杯", roman: "bēi", fr: "tasse (classificateur)", en: "cup (measure word)" },
        { target: "贵", roman: "guì", fr: "cher", en: "expensive" },
        { target: "请", roman: "qǐng", fr: "s'il vous plaît", en: "please" },
      ],
      exercises: [
        {
          prompt: "Comment demandes-tu un prix ?",
          promptEn: "How do you ask for a price?",
          options: ["多少钱", "早上好", "谢谢"],
          accept: ["多少钱"],
          explain: "多少钱？ (duōshao qián?) signifie « combien ça coûte ? ».",
          explainEn: "多少钱？ (duōshao qián?) means \"how much is it?\".",
        },
        {
          prompt: "Complète : « 请给我一___ 咖啡。 » (classificateur)",
          promptEn: "Complete: \"请给我一___ 咖啡。\" (measure word)",
          accept: ["杯"],
          explain: "On utilise 杯 (bēi) pour les boissons en tasse : 一杯咖啡.",
          explainEn: "We use 杯 (bēi) for drinks in a cup: 一杯咖啡.",
        },
        {
          prompt: "Comment dit-on « je veux acheter des fruits » ?",
          promptEn: "How do you say \"I want to buy some fruit\"?",
          options: ["我要买水果", "我要喝咖啡", "我不要水果"],
          accept: ["我要买水果"],
          explain: "买 (mǎi) signifie « acheter » : 我要买水果.",
          explainEn: "买 (mǎi) means \"to buy\": 我要买水果.",
        },
      ],
    },
    {
      number: 9,
      slug: "cn-09",
      title: "Le temps, les saisons et l'heure",
      titleEn: "Weather, seasons and time",
      summary:
        "Parler du temps qu'il fait, des saisons et de l'heure en mandarin.",
      summaryEn:
        "Talking about the weather, the seasons and the time in Mandarin.",
      grammar: ["今天... (temps qu'il fait)", "春/夏/秋/冬 (saisons)", "X点 (l'heure)"],
      explanation:
        "Pour parler du temps qu'il fait, on dit 今天很热 (jīntiān hěn rè, aujourd'hui il fait chaud), 今天下雨 (jīntiān xiàyǔ, il pleut aujourd'hui). Les quatre saisons sont 春天 (chūntiān, printemps), 夏天 (xiàtiān, été), 秋天 (qiūtiān, automne), 冬天 (dōngtiān, hiver). Pour dire l'heure, on utilise 点 (diǎn, heure) ; les minutes se disent 分钟 (fēnzhōng) ou simplement 分 (fēn) : 现在三点了 (xiànzài sān diǎn le, il est trois heures). L'adverbe 现在 (xiànzài) signifie « maintenant ».",
      explanationEn:
        "To talk about the weather, say 今天很热 (jīntiān hěn rè, it is hot today), 今天下雨 (jīntiān xiàyǔ, it is raining today). The four seasons are 春天 (chūntiān, spring), 夏天 (xiàtiān, summer), 秋天 (qiūtiān, autumn), 冬天 (dōngtiān, winter). To tell the time, use 点 (diǎn, o'clock); minutes are 分钟 (fēnzhōng) or simply 分 (fēn): 现在三点了 (xiànzài sān diǎn le, it is three o'clock). The adverb 现在 (xiànzài) means \"now\".",
      examples: [
        { target: "今天很热。", roman: "Jīntiān hěn rè.", fr: "Aujourd'hui, il fait très chaud.", en: "It is very hot today." },
        { target: "春天暖和。", roman: "Chūntiān nuǎnhuo.", fr: "Au printemps, il fait doux.", en: "It is mild in spring." },
        { target: "现在几点了？", roman: "Xiànzài jǐ diǎn le?", fr: "Quelle heure est-il maintenant ?", en: "What time is it now?" },
        { target: "现在是早上八点。", roman: "Xiànzài shì zǎoshang bā diǎn.", fr: "Il est huit heures du matin.", en: "It is eight o'clock in the morning." },
      ],
      vocab: [
        { target: "热", roman: "rè", fr: "chaud", en: "hot" },
        { target: "冷", roman: "lěng", fr: "froid", en: "cold" },
        { target: "下雨", roman: "xiàyǔ", fr: "pleuvoir", en: "to rain" },
        { target: "春天", roman: "chūntiān", fr: "le printemps", en: "spring" },
        { target: "夏天", roman: "xiàtiān", fr: "l'été", en: "summer" },
        { target: "秋天", roman: "qiūtiān", fr: "l'automne", en: "autumn" },
        { target: "冬天", roman: "dōngtiān", fr: "l'hiver", en: "winter" },
        { target: "现在", roman: "xiànzài", fr: "maintenant", en: "now" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « aujourd'hui il pleut » ?",
          promptEn: "How do you say \"it is raining today\"?",
          options: ["今天下雨", "今天很热", "今天很冷"],
          accept: ["今天下雨"],
          explain: "下雨 (xiàyǔ) signifie « pleuvoir » : 今天下雨.",
          explainEn: "下雨 (xiàyǔ) means \"to rain\": 今天下雨.",
        },
        {
          prompt: "Quel mot désigne l'« été » ?",
          promptEn: "Which word refers to \"summer\"?",
          options: ["夏天", "冬天", "秋天"],
          accept: ["夏天"],
          explain: "夏天 (xiàtiān) = été ; 冬天 (dōngtiān) = hiver ; 秋天 (qiūtiān) = automne.",
          explainEn: "夏天 (xiàtiān) = summer; 冬天 (dōngtiān) = winter; 秋天 (qiūtiān) = autumn.",
        },
        {
          prompt: "Complète : « 现在三点___ 。 » (heure)",
          promptEn: "Complete: \"现在三点___ 。\" (o'clock)",
          accept: ["点"],
          explain: "L'heure se dit avec 点 (diǎn) : 现在三点了.",
          explainEn: "Time is told with 点 (diǎn): 现在三点了.",
        },
      ],
    },
    {
      number: 10,
      slug: "cn-10",
      title: "Entretien : présente-toi et ton parcours",
      titleEn: "Interview: introducing yourself and your background",
      summary:
        "Se présenter et raconter son parcours professionnel avec les verbes d'expérience.",
      summaryEn:
        "Introducing yourself and telling your professional background with experience verbs.",
      grammar: ["我做过 / 我学了 (expérience)", "我的经历 (mon parcours)", "毕业 (être diplômé)"],
      explanation:
        "En entretien, la question classique d'ouverture est 请介绍一下你自己 (qǐng jièshào yīxià nǐ zìjǐ, présentez-vous). Pour évoquer son parcours, on utilise 我... (wǒ...) avec les verbes d'expérience : 我在大学学了经济 (wǒ zài dàxué xué le jīngjì, j'ai étudié l'économie à l'université), 我做过工程师 (wǒ zuòguo gōngchéngshī, j'ai travaillé comme ingénieur). 毕业 (bìyè) signifie « être diplômé » : 我毕业于... (wǒ bìyè yú..., je suis diplômé de...). Une bonne structure : identité, formation, expérience, puis projet.",
      explanationEn:
        "In an interview the classic opening question is 请介绍一下你自己 (qǐng jièshào yīxià nǐ zìjǐ, introduce yourself). To talk about your background, use 我... (wǒ...) with experience verbs: 我在大学学了经济 (wǒ zài dàxué xué le jīngjì, I studied economics at university), 我做过工程师 (wǒ zuòguo gōngchéngshī, I worked as an engineer). 毕业 (bìyè) means \"to graduate\": 我毕业于... (wǒ bìyè yú..., I graduated from...). A good structure: identity, education, experience, then your project.",
      examples: [
        { target: "请介绍一下你自己。", roman: "Qǐng jièshào yīxià nǐ zìjǐ.", fr: "Présentez-vous.", en: "Introduce yourself." },
        { target: "我在大学学了经济。", roman: "Wǒ zài dàxué xué le jīngjì.", fr: "J'ai étudié l'économie à l'université.", en: "I studied economics at university." },
        { target: "我做过三年工程师。", roman: "Wǒ zuòguo sān nián gōngchéngshī.", fr: "J'ai travaillé trois ans comme ingénieur.", en: "I worked as an engineer for three years." },
        { target: "我毕业于北京大学。", roman: "Wǒ bìyè yú Běijīng Dàxué.", fr: "Je suis diplômé de l'Université de Pékin.", en: "I graduated from Peking University." },
      ],
      vocab: [
        { target: "介绍", roman: "jièshào", fr: "présenter", en: "to introduce" },
        { target: "经历", roman: "jīnglì", fr: "le parcours, l'expérience", en: "background, experience" },
        { target: "大学", roman: "dàxué", fr: "l'université", en: "university" },
        { target: "学习", roman: "xuéxí", fr: "étudier, apprendre", en: "to study, to learn" },
        { target: "毕业", roman: "bìyè", fr: "être diplômé", en: "to graduate" },
        { target: "年", roman: "nián", fr: "l'année", en: "year" },
        { target: "做过", roman: "zuòguo", fr: "avoir fait (expérience)", en: "have done (experience)" },
        { target: "我的经历", roman: "wǒ de jīnglì", fr: "mon parcours", en: "my background" },
      ],
      exercises: [
        {
          prompt: "Quelle question ouvre l'entretien pour se présenter ?",
          promptEn: "Which question opens the interview to introduce yourself?",
          options: ["请介绍一下你自己", "多少钱", "你好"],
          accept: ["请介绍一下你自己"],
          explain: "请介绍一下你自己 (qǐng jièshào yīxià nǐ zìjǐ) signifie « présentez-vous ».",
          explainEn: "请介绍一下你自己 (qǐng jièshào yīxià nǐ zìjǐ) means \"introduce yourself\".",
        },
        {
          prompt: "Complète : « 我___ 过工程师。 » (avoir fait)",
          promptEn: "Complete: \"我___ 过工程师。\" (have done)",
          accept: ["做"],
          explain: "做过 (zuòguo) exprime une expérience passée : 我做过工程师.",
          explainEn: "做过 (zuòguo) expresses a past experience: 我做过工程师.",
        },
        {
          prompt: "Que signifie 毕业 ?",
          promptEn: "What does 毕业 mean?",
          options: ["être diplômé", "acheter", "dormir"],
          accept: ["être diplômé"],
          explain: "毕业 (bìyè) signifie « obtenir son diplôme ».",
          explainEn: "毕业 (bìyè) means \"to graduate\".",
        },
      ],
      interview: [
        {
          question: "请说说你的学习和工作经历。",
          roman: "Qǐng shuōshuo nǐ de xuéxí hé gōngzuò jīnglì.",
          fr: "Parlez-moi de vos études et de votre expérience professionnelle.",
          en: "Tell me about your studies and professional experience.",
          modelFr: "J'ai étudié l'informatique, puis j'ai travaillé cinq ans comme développeur dans une entreprise.",
          modelEn: "I studied computer science, then I worked for five years as a developer in a company.",
          accept: ["我学了计算机", "我做过开发", "我毕业于"],
        },
        {
          question: "你为什么离开上一家公司？",
          roman: "Nǐ wèishénme líkāi shàng yī jiā gōngsī?",
          fr: "Pourquoi avez-vous quitté votre précédente entreprise ?",
          en: "Why did you leave your previous company?",
          modelFr: "J'ai quitté mon ancienne entreprise pour chercher de nouvelles compétences et un poste plus stimulant.",
          modelEn: "I left my previous company to seek new skills and a more challenging position.",
          accept: ["因为我想学习", "我想有新的挑战", "我离开"],
        },
      ],
    },
    {
      number: 11,
      slug: "cn-11",
      title: "Entretien : atouts, faiblesses et motivation",
      titleEn: "Interview: strengths, weaknesses and motivation",
      summary:
        "Présenter ses atouts, admettre une faiblesse avec tact et expliquer sa motivation.",
      summaryEn:
        "Presenting your strengths, admitting a weakness tactfully, and explaining your motivation.",
      grammar: ["我的优点是... (mes atouts)", "我的缺点是... (ma faiblesse)", "因为... (parce que)"],
      explanation:
        "Pour présenter ses atouts, on dit 我的优点是... (wǒ de yōudiǎn shì..., mes atouts sont...) : 我的优点是负责和认真 (wǒ de yōudiǎn shì fùzé hé rènzhēn, mes atouts sont d'être responsable et consciencieux). Pour la faiblesse, on utilise 我的缺点是 (wǒ de quēdiǎn shì...) puis on montre qu'on y travaille : 我的缺点是有时候太追求完美 (wǒ de quēdiǎn shì yǒushíhou tài zhuīqiú wánměi, ma faiblesse est d'être parfois trop perfectionniste). La motivation se justifie avec 因为 (yīnwèi, parce que) : 我想在这里工作因为公司重视创新 (wǒ xiǎng zài zhèlǐ gōngzuò yīnwèi gōngsī zhòngshì chuàngxīn, je veux travailler ici parce que l'entreprise valorise l'innovation).",
      explanationEn:
        "To present your strengths, say 我的优点是... (wǒ de yōudiǎn shì..., my strengths are...): 我的优点是负责和认真 (wǒ de yōudiǎn shì fùzé hé rènzhēn, my strengths are being responsible and conscientious). For the weakness, use 我的缺点是 (wǒ de quēdiǎn shì...) then show you are working on it: 我的缺点是有时候太追求完美 (wǒ de quēdiǎn shì yǒushíhou tài zhuīqiú wánměi, my weakness is being sometimes too perfectionist). Motivation is justified with 因为 (yīnwèi, because): 我想在这里工作因为公司重视创新 (wǒ xiǎng zài zhèlǐ gōngzuò yīnwèi gōngsī zhòngshì chuàngxīn, I want to work here because the company values innovation).",
      examples: [
        { target: "我的优点是认真负责。", roman: "Wǒ de yōudiǎn shì rènzhēn fùzé.", fr: "Mes atouts sont d'être consciencieux et responsable.", en: "My strengths are being careful and responsible." },
        { target: "我的缺点是有时候太完美。", roman: "Wǒ de quēdiǎn shì yǒushíhou tài wánměi.", fr: "Ma faiblesse est d'être parfois trop perfectionniste.", en: "My weakness is being sometimes too perfectionist." },
        { target: "我喜欢团队合作。", roman: "Wǒ xǐhuan tuánduì hézuò.", fr: "J'aime le travail en équipe.", en: "I like teamwork." },
        { target: "我想在这里工作因为公司重视创新。", roman: "Wǒ xiǎng zài zhèlǐ gōngzuò yīnwèi gōngsī zhòngshì chuàngxīn.", fr: "Je veux travailler ici parce que l'entreprise valorise l'innovation.", en: "I want to work here because the company values innovation." },
      ],
      vocab: [
        { target: "优点", roman: "yōudiǎn", fr: "les atouts", en: "strengths" },
        { target: "缺点", roman: "quēdiǎn", fr: "les faiblesses", en: "weaknesses" },
        { target: "负责", roman: "fùzé", fr: "responsable", en: "responsible" },
        { target: "认真", roman: "rènzhēn", fr: "consciencieux, sérieux", en: "serious, careful" },
        { target: "完美", roman: "wánměi", fr: "parfait, perfectionniste", en: "perfect, perfectionist" },
        { target: "团队合作", roman: "tuánduì hézuò", fr: "le travail en équipe", en: "teamwork" },
        { target: "因为", roman: "yīnwèi", fr: "parce que", en: "because" },
        { target: "创新", roman: "chuàngxīn", fr: "l'innovation", en: "innovation" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « mon atout » ?",
          promptEn: "How do you say \"my strength\"?",
          options: ["我的优点", "我的缺点", "我的公司"],
          accept: ["我的优点"],
          explain: "优点 (yōudiǎn) = atout, force ; 缺点 (quēdiǎn) = faiblesse.",
          explainEn: "优点 (yōudiǎn) = strength; 缺点 (quēdiǎn) = weakness.",
        },
        {
          prompt: "Complète : « 我___ 在这里工作因为... » (vouloir)",
          promptEn: "Complete: \"我___ 在这里工作因为...\" (to want)",
          accept: ["想"],
          explain: "想 (xiǎng) signifie « vouloir » : 我想在这里工作 (je veux travailler ici).",
          explainEn: "想 (xiǎng) means \"to want\": 我想在这里工作 (I want to work here).",
        },
        {
          prompt: "Que signifie 因为 ?",
          promptEn: "What does 因为 mean?",
          options: ["parce que", "mais", "donc"],
          accept: ["parce que"],
          explain: "因为 (yīnwèi) signifie « parce que » et introduit une raison.",
          explainEn: "因为 (yīnwèi) means \"because\" and introduces a reason.",
        },
      ],
      interview: [
        {
          question: "你最大的优点是什么？",
          roman: "Nǐ zuì dà de yōudiǎn shì shénme?",
          fr: "Quel est votre plus grand atout ?",
          en: "What is your greatest strength?",
          modelFr: "Mon plus grand atout est d'être très responsable et de bien gérer mon temps.",
          modelEn: "My greatest strength is being very responsible and managing my time well.",
          accept: ["我的优点是负责", "我会管理时间", "我最大的优点是"],
        },
        {
          question: "你为什么选择我们公司？",
          roman: "Nǐ wèishénme xuǎnzé wǒmen gōngsī?",
          fr: "Pourquoi avez-vous choisi notre entreprise ?",
          en: "Why did you choose our company?",
          modelFr: "Je choisis votre entreprise car elle valorise l'innovation et offre de grandes opportunités de carrière.",
          modelEn: "I choose your company because it values innovation and offers great career opportunities.",
          accept: ["因为贵公司重视创新", "我想在这里发展", "我选择这家公司"],
        },
      ],
    },
    {
      number: 12,
      slug: "cn-12",
      title: "Entretien : projets, travail d'équipe et gestion du stress",
      titleEn: "Interview: plans, teamwork and stress management",
      summary:
        "Exprimer ses projets futurs, parler du travail en équipe et de la gestion du stress.",
      summaryEn:
        "Expressing future plans, talking about teamwork and stress management.",
      grammar: ["将来/未来 (le futur)", "和...一起工作 (travail d'équipe)", "压力 (le stress)"],
      explanation:
        "Pour parler de ses projets d'avenir, on utilise 将来 (jiānglái, l'avenir) ou 未来 (wèilái, le futur) et le verbe 打算 (dǎsuàn, avoir l'intention de) : 我打算在五年后成为经理 (wǒ dǎsuàn zài wǔ nián hòu chéngwéi jīnglǐ, j'ai l'intention de devenir manager dans cinq ans). Pour le travail d'équipe, on dit 我和同事一起工作 (wǒ hé tóngshì yīqǐ gōngzuò, je travaille avec mes collègues). La pression se dit 压力 (yā lì) : 我能处理压力 (wǒ néng chǔlǐ yālì, je peux gérer le stress). L'adverbe 能 (néng) exprime la capacité.",
      explanationEn:
        "To talk about your future plans, use 将来 (jiānglái, the future) or 未来 (wèilái, the future) and the verb 打算 (dǎsuàn, to intend to): 我打算在五年后成为经理 (wǒ dǎsuàn zài wǔ nián hòu chéngwéi jīnglǐ, I intend to become a manager in five years). For teamwork, say 我和同事一起工作 (wǒ hé tóngshì yīqǐ gōngzuò, I work with my colleagues). Pressure is 压力 (yālì): 我能处理压力 (wǒ néng chǔlǐ yālì, I can handle stress). The adverb 能 (néng) expresses ability.",
      examples: [
        { target: "我打算在五年后成为经理。", roman: "Wǒ dǎsuàn zài wǔ nián hòu chéngwéi jīnglǐ.", fr: "J'ai l'intention de devenir manager dans cinq ans.", en: "I intend to become a manager in five years." },
        { target: "我很会跟同事一起工作。", roman: "Wǒ hěn huì gēn tóngshì yīqǐ gōngzuò.", fr: "Je sais très bien travailler avec mes collègues.", en: "I am very good at working with my colleagues." },
        { target: "我能处理压力。", roman: "Wǒ néng chǔlǐ yālì.", fr: "Je sais gérer le stress.", en: "I can handle stress." },
        { target: "未来我想学习新技能。", roman: "Wèilái wǒ xiǎng xuéxí xīn jìnéng.", fr: "À l'avenir, je veux apprendre de nouvelles compétences.", en: "In the future, I want to learn new skills." },
      ],
      vocab: [
        { target: "将来", roman: "jiānglái", fr: "l'avenir", en: "the future" },
        { target: "未来", roman: "wèilái", fr: "le futur", en: "the future" },
        { target: "打算", roman: "dǎsuàn", fr: "avoir l'intention de", en: "to intend to" },
        { target: "压力", roman: "yālì", fr: "le stress, la pression", en: "stress, pressure" },
        { target: "能", roman: "néng", fr: "pouvoir, savoir faire", en: "can, to be able to" },
        { target: "团队", roman: "tuánduì", fr: "l'équipe", en: "team" },
        { target: "一起", roman: "yīqǐ", fr: "ensemble", en: "together" },
        { target: "新技能", roman: "xīn jìnéng", fr: "nouvelles compétences", en: "new skills" },
      ],
      exercises: [
        {
          prompt: "Comment dis-tu « je peux gérer le stress » ?",
          promptEn: "How do you say \"I can handle stress\"?",
          options: ["我能处理压力", "我有压力", "我很大压力"],
          accept: ["我能处理压力"],
          explain: "能 (néng) + 处理压力 (chǔlǐ yālì) = pouvoir gérer le stress : 我能处理压力.",
          explainEn: "能 (néng) + 处理压力 (chǔlǐ yālì) = to be able to handle stress: 我能处理压力.",
        },
        {
          prompt: "Complète : « 我和同事___ 工作。 » (ensemble)",
          promptEn: "Complete: \"我和同事___ 工作。\" (together)",
          accept: ["一起"],
          explain: "一起 (yīqǐ) signifie « ensemble » : 我和同事一起工作.",
          explainEn: "一起 (yīqǐ) means \"together\": 我和同事一起工作.",
        },
        {
          prompt: "Que signifie 打算 ?",
          promptEn: "What does 打算 mean?",
          options: ["avoir l'intention de", "acheter", "aimer"],
          accept: ["avoir l'intention de"],
          explain: "打算 (dǎsuàn) exprime l'intention, le projet : 我打算... (j'ai l'intention de...).",
          explainEn: "打算 (dǎsuàn) expresses intention, a plan: 我打算... (I intend to...).",
        },
      ],
      interview: [
        {
          question: "你未来五年的计划是什么？",
          roman: "Nǐ wèilái wǔ nián de jìhuà shì shénme?",
          fr: "Quels sont vos projets pour les cinq prochaines années ?",
          en: "What are your plans for the next five years?",
          modelFr: "D'ici cinq ans, j'espère assumer davantage de responsabilités et devenir manager de mon équipe.",
          modelEn: "Within five years, I hope to take on more responsibility and become the manager of my team.",
          accept: ["我打算成为经理", "我希望承担更多责任", "未来五年"],
        },
        {
          question: "你怎样处理工作压力？",
          roman: "Nǐ zěnyàng chǔlǐ gōngzuò yālì?",
          fr: "Comment gérez-vous le stress au travail ?",
          en: "How do you handle stress at work?",
          modelFr: "Je reste organisé, je priorise mes tâches et je fais du sport pour me détendre.",
          modelEn: "I stay organized, I prioritize my tasks and I do sports to relax.",
          accept: ["我合理安排时间", "我通过运动放松", "我能处理压力"],
        },
        {
          question: "请说说你的团队合作经验。",
          roman: "Qǐng shuōshuo nǐ de tuánduì hézuò jīngyàn.",
          fr: "Parlez-moi de votre expérience du travail en équipe.",
          en: "Tell me about your teamwork experience.",
          modelFr: "Dans mon dernier projet, j'ai travaillé avec une équipe de cinq personnes et nous avons bien collaboré.",
          modelEn: "In my last project, I worked with a team of five people and we collaborated well together.",
          accept: ["我和团队", "我们合作", "团队合作"],
        },
      ],
    },
  ],
};
