import type { LanguageCourse } from "./genericLessons";

export const ES_COURSE: LanguageCourse = {
  code: "es",
  name: "Espagnol",
  native: "Español",
  heroTitle1: { fr: "Apprenez", en: "Learn" },
  heroTitle2: { fr: "l'espagnol", en: "Spanish" },
  heroSubtitle: {
    fr: "Un parcours débutant en douze leçons : salutations, vie quotidienne, travail et entretien d'embauche.",
    en: "A beginner path in twelve lessons: greetings, daily life, work and the job interview.",
  },
  lessons: [
    {
      number: 1,
      slug: "es-01",
      title: "Se présenter et saluer",
      titleEn: "Introducing yourself and greeting",
      summary:
        "Les salutations de base et les présentations : dire bonjour, donner son nom et dire d'où l'on vient.",
      summaryEn:
        "Basic greetings and introductions: saying hello, giving your name and saying where you come from.",
      grammar: ["Presente de indicativo de ser", "Pronombres personales", "Hola / Buenos días / ¿Cómo estás?"],
      explanation:
        "Le verbe ser (être) est essentiel pour se présenter : yo soy (je suis), tú eres (tu es), él/ella es (il/elle est), nosotros somos (nous sommes), ellos son (ils/elles sont). On l'utilise pour donner son nom : « Me llamo... » (littéralement « je m'appelle »), sa nationalité et sa profession. Les salutations varient selon le moment de la journée : hola (salut), buenos días (bonjour le matin), buenas tardes (bonjour l'après-midi), buenas noches (bonsoir/bonne nuit). Pour demander comment quelqu'un va, on dit « ¿Cómo estás? » et on répond « Muy bien, gracias ». En espagnol, le sujet est souvent omis car la terminaison du verbe suffit : « Soy Daniel » (je suis Daniel).",
      explanationEn:
        "The verb ser (to be) is essential for introducing yourself: yo soy (I am), tú eres (you are), él/ella es (he/she is), nosotros somos (we are), ellos son (they are). We use it to give your name: \"Me llamo...\" (literally \"I call myself\"), your nationality and your job. Greetings vary depending on the time of day: hola (hi), buenos días (good morning), buenas tardes (good afternoon), buenas noches (good evening/good night). To ask how someone is, say \"¿Cómo estás?\" and answer \"Muy bien, gracias.\" In Spanish the subject is often omitted because the verb ending is enough: \"Soy Daniel\" (I am Daniel).",
      examples: [
        { target: "Hola, me llamo Daniel. Mucho gusto.", fr: "Salut, je m'appelle Daniel. Enchanté.", en: "Hi, my name is Daniel. Nice to meet you." },
        { target: "¿Cómo estás? Muy bien, gracias.", fr: "Comment vas-tu ? Très bien, merci.", en: "How are you? Very well, thank you." },
        { target: "Buenos días, soy de España.", fr: "Bonjour, je suis d'Espagne.", en: "Good morning, I am from Spain." },
        { target: "Soy estudiante y vivo en México.", fr: "Je suis étudiant et je vis au Mexique.", en: "I am a student and I live in Mexico." },
      ],
      vocab: [
        { target: "hola", fr: "bonjour, salut", en: "hello, hi" },
        { target: "buenos días", fr: "bonjour (le matin)", en: "good morning" },
        { target: "me llamo", fr: "je m'appelle", en: "my name is" },
        { target: "mucho gusto", fr: "enchanté", en: "nice to meet you" },
        { target: "¿cómo estás?", fr: "comment vas-tu ?", en: "how are you?" },
        { target: "muy bien", fr: "très bien", en: "very well" },
        { target: "gracias", fr: "merci", en: "thank you" },
        { target: "adiós", fr: "au revoir", en: "goodbye" },
      ],
      exercises: [
        {
          prompt: "Complète la phrase de présentation : « ___ llamo Ana. »",
          promptEn: "Complete the introduction sentence: \"___ llamo Ana.\"",
          accept: ["me"],
          explain: "On utilise toujours « me llamo » pour donner son nom : c'est le verbe llamar avec le pronom me.",
          explainEn: "We always use \"me llamo\" to give your name: it is the verb llamar with the pronoun me.",
        },
        {
          prompt: "Quelle salutation utilise-t-on le matin ?",
          promptEn: "Which greeting do you use in the morning?",
          options: ["buenos días", "buenas noches", "adiós"],
          accept: ["buenos días"],
          explain: "« Buenos días » se dit le matin ; « buenas noches » le soir et « adiós » pour dire au revoir.",
          explainEn: "\"Buenos días\" is said in the morning; \"buenas noches\" in the evening and \"adiós\" to say goodbye.",
        },
        {
          prompt: "Comment répond-on à « ¿Cómo estás? » ?",
          promptEn: "How do you answer \"¿Cómo estás?\"?",
          options: ["muy bien, gracias", "buenas tardes", "hasta luego"],
          accept: ["muy bien, gracias"],
          explain: "On répond naturellement « muy bien, gracias » (très bien, merci).",
          explainEn: "You naturally reply \"muy bien, gracias\" (very well, thank you).",
        },
      ],
    },
    {
      number: 2,
      slug: "es-02",
      title: "Nationalité, origine et profession",
      titleEn: "Nationality, origin and job",
      summary:
        "Dire d'où l'on vient, sa nationalité et sa profession avec les verbes ser et vivir.",
      summaryEn:
        "Saying where you come from, your nationality and your job with the verbs ser and vivir.",
      grammar: ["Ser + nacionalidad", "Vivir en + lugar", "Género de las profesiones"],
      explanation:
        "Pour dire sa nationalité et sa profession, on utilise le verbe ser : « Yo soy francés » (je suis français), « Ella es médica » (elle est médecin). Les nationalités et professions s'accordent en genre : frances/francesa, ingeniero/ingeniera. Pour dire où l'on vit, on utilise vivir (habiter) avec la préposition en : « Vivo en París » (j'habite à Paris). Avant une profession, on n'utilise pas d'article : on dit « Soy ingeniero » (je suis ingénieur) et jamais « Soy un ingeniero ». En entretien ou dans une conversation formelle, on emploie usted : « ¿De dónde es usted? » (d'où êtes-vous ?).",
      explanationEn:
        "To say your nationality and your job, use the verb ser: \"Yo soy francés\" (I am French), \"Ella es médica\" (she is a doctor). Nationalities and professions agree in gender: frances/francesa, ingeniero/ingeniera. To say where you live, use vivir (to live) with the preposition en: \"Vivo en París\" (I live in Paris). Before a profession there is no article: say \"Soy ingeniero\" (I am an engineer), never \"Soy un ingeniero.\" In an interview or formal conversation, use usted: \"¿De dónde es usted?\" (where are you from?).",
      examples: [
        { target: "Soy de Colombia, de Bogotá.", fr: "Je suis de Colombie, de Bogotá.", en: "I am from Colombia, from Bogotá." },
        { target: "¿De dónde eres? Soy francés.", fr: "D'où es-tu ? Je suis français.", en: "Where are you from? I am French." },
        { target: "Vivo en Madrid con mi familia.", fr: "J'habite à Madrid avec ma famille.", en: "I live in Madrid with my family." },
        { target: "Ella es enfermera en un hospital.", fr: "Elle est infirmière dans un hôpital.", en: "She is a nurse in a hospital." },
      ],
      vocab: [
        { target: "de dónde eres", fr: "d'où es-tu", en: "where are you from" },
        { target: "soy de", fr: "je suis de", en: "I am from" },
        { target: "francés, francesa", fr: "français(e)", en: "French" },
        { target: "vivo en", fr: "j'habite à", en: "I live in" },
        { target: "ingeniero, ingeniera", fr: "ingénieur(e)", en: "engineer" },
        { target: "médico, médica", fr: "médecin", en: "doctor" },
        { target: "estudiante", fr: "étudiant(e)", en: "student" },
        { target: "profesión", fr: "profession, métier", en: "profession, job" },
      ],
      exercises: [
        {
          prompt: "Complète : « Soy ___ Bogotá. »",
          promptEn: "Complete: \"Soy ___ Bogotá.\"",
          accept: ["de"],
          explain: "La préposition de exprime l'origine : « Soy de Bogotá » (je suis de Bogotá).",
          explainEn: "The preposition de expresses origin: \"Soy de Bogotá\" (I am from Bogotá).",
        },
        {
          prompt: "Comment dit-on « je suis ingénieur » ?",
          promptEn: "How do you say \"I am an engineer\"?",
          options: ["soy ingeniero", "estoy ingeniero", "tengo ingeniero"],
          accept: ["soy ingeniero"],
          explain: "On utilise ser + profession sans article : « Soy ingeniero ».",
          explainEn: "Use ser + profession without an article: \"Soy ingeniero.\"",
        },
        {
          prompt: "Complète : « ¿De dónde ___ ? » (verbe ser, tu)",
          promptEn: "Complete: \"¿De dónde ___ ?\" (verb ser, you)",
          accept: ["eres"],
          explain: "La forme correspondante est « eres » pour tú : « ¿De dónde eres? ».",
          explainEn: "The correct form is \"eres\" for tú: \"¿De dónde eres?\"",
        },
      ],
    },
    {
      number: 3,
      slug: "es-03",
      title: "Tener, ser et estar : possession et description",
      titleEn: "Tener, ser and estar: possession and description",
      summary:
        "Distinguer les trois verbes fondamentaux : tener pour la possession, ser pour l'essentiel, estar pour l'état.",
      summaryEn:
        "Distinguishing the three fundamental verbs: tener for possession, ser for essence, estar for state.",
      grammar: ["Tener: yo tengo, tú tienes", "Ser: identidad y descripción", "Estar: estado y localización"],
      explanation:
        "L'espagnol distingue trois verbes que le français rend souvent par « être » ou « avoir ». Tener signifie avoir : « Tengo un coche » (j'ai une voiture), « Tengo treinta años » (j'ai trente ans). Ser décrit l'identité permanente : « Soy alto » (je suis grand), « Soy paciente » (je suis patient). Estar décrit un état temporaire ou une localisation : « Estoy cansado » (je suis fatigué), « Estoy en la oficina » (je suis au bureau). L'âge se dit avec tener : « ¿Cuántos años tienes? Tengo veinticinco años. » On dit Pero cuidado : pour la santé on utilise estar (« Estoy enfermo »), pour la couleur ou la taille d'une personne on utilise ser (« Soy moreno »).",
      explanationEn:
        "Spanish distinguishes three verbs that French often renders as \"to be\" or \"to have\". Tener means to have: \"Tengo un coche\" (I have a car), \"Tengo treinta años\" (I am thirty years old). Ser describes permanent identity: \"Soy alto\" (I am tall), \"Soy paciente\" (I am patient). Estar describes a temporary state or a location: \"Estoy cansado\" (I am tired), \"Estoy en la oficina\" (I am at the office). Age is expressed with tener: \"¿Cuántos años tienes? Tengo veinticinco años.\" For health you use estar (\"Estoy enfermo\"), while for someone's hair colour or height you use ser (\"Soy moreno\").",
      examples: [
        { target: "Tengo un perro y dos gatos.", fr: "J'ai un chien et deux chats.", en: "I have a dog and two cats." },
        { target: "¿Cuántos años tienes? Tengo treinta años.", fr: "Quel âge as-tu ? J'ai trente ans.", en: "How old are you? I am thirty years old." },
        { target: "Soy una persona organizada.", fr: "Je suis une personne organisée.", en: "I am an organized person." },
        { target: "Estoy cansado hoy, pero estoy feliz.", fr: "Je suis fatigué aujourd'hui, mais je suis heureux.", en: "I am tired today, but I am happy." },
      ],
      vocab: [
        { target: "tener", fr: "avoir", en: "to have" },
        { target: "tengo", fr: "j'ai", en: "I have" },
        { target: "años", fr: "ans", en: "years" },
        { target: "alto, alta", fr: "grand(e)", en: "tall" },
        { target: "cansado, cansada", fr: "fatigué(e)", en: "tired" },
        { target: "feliz", fr: "heureux, heureuse", en: "happy" },
        { target: "en la oficina", fr: "au bureau", en: "in the office" },
        { target: "mascota", fr: "animal de compagnie", en: "pet" },
      ],
      exercises: [
        {
          prompt: "Complète : « Yo ___ veinticinco años. »",
          promptEn: "Complete: \"Yo ___ veinticinco años.\"",
          accept: ["tengo"],
          explain: "L'âge se dit avec tener : « Tengo veinticinco años ».",
          explainEn: "Age is expressed with tener: \"Tengo veinticinco años.\"",
        },
        {
          prompt: "« Je suis au bureau » se dit...",
          promptEn: "\"I am at the office\" is said...",
          options: ["estoy en la oficina", "soy en la oficina", "tengo la oficina"],
          accept: ["estoy en la oficina"],
          explain: "Estar exprime la localisation : « Estoy en la oficina ».",
          explainEn: "Estar expresses location: \"Estoy en la oficina.\"",
        },
        {
          prompt: "Conjugue ser à la première personne : « Yo ___ paciente. »",
          promptEn: "Conjugate ser in the first person: \"Yo ___ paciente.\"",
          accept: ["soy"],
          explain: "La première personne de ser est « soy ».",
          explainEn: "The first person of ser is \"soy\".",
        },
      ],
    },
    {
      number: 4,
      slug: "es-04",
      title: "La vie quotidienne et les routines",
      titleEn: "Daily life and routines",
      summary:
        "Raconter sa journée avec les verbes réguliers au présent et les verbes pronominaux.",
      summaryEn:
        "Telling your day with regular present-tense verbs and reflexive verbs.",
      grammar: ["Verbos regulares: -ar, -er, -ir", "Verbos reflexivos: levantarse, despertarse", "Partículas de frecuencia"],
      explanation:
        "Les verbes réguliers au présent : les verbes en -ar (hablar → hablo, hablas, habla), en -er (comer → como, comes, come) et en -ir (vivir → vivo, vives, vive, souvent confondu avec -er). Les verbes pronominaux s'emploient avec un pronom : me levanto (je me lève), te levantas, se levanta. On raconte sa routine avec des adverbes de fréquence : siempre (toujours), normalmente (normalement), a veces (parfois), nunca (jamais). Exemple : « Me levanto a las siete, desayuno y voy al trabajo. » Le présent sert aussi pour les habitudes : « Trabajo de lunes a viernes. »",
      explanationEn:
        "Regular verbs in the present: -ar verbs (hablar → hablo, hablas, habla), -er verbs (comer → como, comes, come) and -ir verbs (vivir → vivo, vives, vive, often confused with -er). Reflexive verbs take a pronoun: me levanto (I get up), te levantas, se levanta. You tell your routine using frequency adverbs: siempre (always), normalmente (usually), a veces (sometimes), nunca (never). Example: \"Me levanto a las siete, desayuno y voy al trabajo.\" The present tense is also used for habits: \"Trabajo de lunes a viernes.\"",
      examples: [
        { target: "Me despierto a las seis y media.", fr: "Je me réveille à six heures et demie.", en: "I wake up at half past six." },
        { target: "Trabajo de lunes a viernes en una oficina.", fr: "Je travaille du lundi au vendredi dans un bureau.", en: "I work from Monday to Friday in an office." },
        { target: "Normalmente desayuno pan y café.", fr: "Normalement, je prends du pain et du café au petit-déjeuner.", en: "Usually I have bread and coffee for breakfast." },
        { target: "A veces ceno tarde con mi familia.", fr: "Parfois je dîne tard avec ma famille.", en: "Sometimes I have dinner late with my family." },
      ],
      vocab: [
        { target: "levantarse", fr: "se lever", en: "to get up" },
        { target: "desayunar", fr: "prendre le petit-déjeuner", en: "to have breakfast" },
        { target: "trabajar", fr: "travailler", en: "to work" },
        { target: "cenar", fr: "dîner", en: "to have dinner" },
        { target: "siempre", fr: "toujours", en: "always" },
        { target: "a veces", fr: "parfois", en: "sometimes" },
        { target: "nunca", fr: "jamais", en: "never" },
        { target: "la rutina", fr: "la routine", en: "the routine" },
      ],
      exercises: [
        {
          prompt: "Complète : « Yo ___ a las siete. » (levantarse)",
          promptEn: "Complete: \"Yo ___ a las siete.\" (levantarse)",
          accept: ["me levanto"],
          explain: "Verbe pronominal : « me levanto » = je me lève.",
          explainEn: "Reflexive verb: \"me levanto\" = I get up.",
        },
        {
          prompt: "« A veces » signifie...",
          promptEn: "\"A veces\" means...",
          options: ["parfois", "toujours", "jamais"],
          accept: ["parfois"],
          explain: "« A veces » veut dire « parfois ». L'option française n'est pas espagnole ici : c'est la traduction demandée.",
          explainEn: "\"A veces\" means \"sometimes\". The French option is not Spanish here: it is the requested translation.",
        },
        {
          prompt: "Complète : « Yo ___ en una empresa. » (trabajar)",
          promptEn: "Complete: \"Yo ___ en una empresa.\" (trabajar)",
          accept: ["trabajo"],
          explain: "Verbe en -ar : « trabajo » est la première personne du présent.",
          explainEn: "-ar verb: \"trabajo\" is the first person present.",
        },
      ],
    },
    {
      number: 5,
      slug: "es-05",
      title: "Aimer et exprimer ses goûts",
      titleEn: "Liking and expressing tastes",
      summary:
        "Exprimer ses goûts avec gustar, encantar et les adverbes d'intensité.",
      summaryEn:
        "Expressing tastes with gustar, encantar and adverbs of intensity.",
      grammar: ["Gustar + infinitivo", "Gustar + sustantivo (me gusta / me gustan)", "Me encanta, me interesa"],
      explanation:
        "Le verbe gustar fonctionne à l'envers du français : le sujet est la chose aimée, et la personne est un complément indirect. On dit « Me gusta el café » (le café me plaît = j'aime le café) et « Me gustan los libros » (les livres me plaisent) : gusta au singulier, gustan au pluriel. Avec un verbe, on garde le singulier : « Me gusta viajar » (j'aime voyager). Pour renforcer, on utilise encantar : « Me encanta el chocolate » (j'adore le chocolat). Pour demander les goûts : « ¿Qué te gusta hacer? » (qu'est-ce que tu aimes faire ?). On peut aussi ajouter mucho : « Me gusta mucho bailar. »",
      explanationEn:
        "The verb gustar works in the opposite way to French: the subject is the thing that is liked, and the person is an indirect object. You say \"Me gusta el café\" (coffee pleases me = I like coffee) and \"Me gustan los libros\" (books please me): gusta in the singular, gustan in the plural. With a verb, keep the singular: \"Me gusta viajar\" (I like to travel). To strengthen the feeling, use encantar: \"Me encanta el chocolate\" (I love chocolate). To ask about tastes: \"¿Qué te gusta hacer?\" (what do you like to do?). You can also add mucho: \"Me gusta mucho bailar.\"",
      examples: [
        { target: "Me gusta leer libros en mi tiempo libre.", fr: "J'aime lire des livres pendant mon temps libre.", en: "I like reading books in my free time." },
        { target: "Me gustan las películas de aventuras.", fr: "J'aime les films d'aventure.", en: "I like adventure movies." },
        { target: "Me encanta viajar por el mundo.", fr: "J'adore voyager à travers le monde.", en: "I love travelling around the world." },
        { target: "¿Qué te gusta hacer los fines de semana?", fr: "Qu'est-ce que tu aimes faire le week-end ?", en: "What do you like to do on the weekends?" },
      ],
      vocab: [
        { target: "gustar", fr: "aimer (plaire)", en: "to like" },
        { target: "me gusta", fr: "j'aime", en: "I like" },
        { target: "me gustan", fr: "j'aime (pluriel)", en: "I like (plural)" },
        { target: "me encanta", fr: "j'adore", en: "I love" },
        { target: "leer", fr: "lire", en: "to read" },
        { target: "viajar", fr: "voyager", en: "to travel" },
        { target: "el tiempo libre", fr: "le temps libre", en: "free time" },
        { target: "los fines de semana", fr: "les week-ends", en: "weekends" },
      ],
      exercises: [
        {
          prompt: "Complète : « Me ___ el chocolate. »",
          promptEn: "Complete: \"Me ___ el chocolate.\"",
          accept: ["gusta"],
          explain: "Avec un nom singulier (el chocolate), on utilise « gusta ».",
          explainEn: "With a singular noun (el chocolate), use \"gusta\".",
        },
        {
          prompt: "Complète : « Me ___ los libros. »",
          promptEn: "Complete: \"Me ___ los libros.\"",
          accept: ["gustan"],
          explain: "Avec un nom pluriel (los libros), on utilise « gustan ».",
          explainEn: "With a plural noun (los libros), use \"gustan\".",
        },
        {
          prompt: "Comment dit-on « j'adore voyager » ?",
          promptEn: "How do you say \"I love to travel\"?",
          options: ["me encanta viajar", "me gusta viajar", "gusto viajar"],
          accept: ["me encanta viajar"],
          explain: "« Me encanta + infinitivo » exprime une passion. Réponse correcte : me encanta viajar.",
          explainEn: "\"Me encanta + infinitive\" expresses a passion. Correct answer: me encanta viajar.",
        },
      ],
    },
    {
      number: 6,
      slug: "es-06",
      title: "La famille et les personnes",
      titleEn: "Family and people",
      summary:
        "Le vocabulaire de la famille, les possessifs et les adjectifs pour décrire les personnes.",
      summaryEn:
        "Family vocabulary, possessives and adjectives to describe people.",
      grammar: ["Los posesivos: mi, tu, su", "Descripción física con ser", "Tiene + rasgos físicos"],
      explanation:
        "Le vocabulaire de la famille : padre (père), madre (mère), hermano/hermana (frère/sœur), hijo/hija (fils/fille), abuelo/abuela (grand-père/grand-mère). Les possessifs espagnols s'accordent avec la chose possédée et non avec le possesseur : mi hermano (mon frère), mis hermanos (mes frères), tu madre, su familia. Pour décrire une personne on utilise ser pour les traits permanents (« Ella es alta y delgada ») et tener pour les traits physiques (« Tiene los ojos azules », il a les yeux bleus). Les adjectifs s'accordent en genre et en nombre : alto/alta, inteligente (sans changement de genre).",
      explanationEn:
        "Family vocabulary: padre (father), madre (mother), hermano/hermana (brother/sister), hijo/hija (son/daughter), abuelo/abuela (grandfather/grandmother). Spanish possessives agree with the thing possessed, not with the possessor: mi hermano (my brother), mis hermanos (my brothers), tu madre, su familia. To describe a person, use ser for permanent traits (\"Ella es alta y delgada\") and tener for physical features (\"Tiene los ojos azules\", he has blue eyes). Adjectives agree in gender and number: alto/alta, inteligente (no gender change).",
      examples: [
        { target: "Mi hermana mayor es muy inteligente.", fr: "Ma sœur aînée est très intelligente.", en: "My older sister is very intelligent." },
        { target: "Mis padres viven en Sevilla.", fr: "Mes parents habitent à Séville.", en: "My parents live in Seville." },
        { target: "Tiene los ojos verdes y el pelo castaño.", fr: "Il a les yeux verts et les cheveux bruns.", en: "He has green eyes and brown hair." },
        { target: "Su abuela cocina muy bien.", fr: "Sa grand-mère cuisine très bien.", en: "His grandmother cooks very well." },
      ],
      vocab: [
        { target: "la familia", fr: "la famille", en: "the family" },
        { target: "el padre", fr: "le père", en: "the father" },
        { target: "la madre", fr: "la mère", en: "the mother" },
        { target: "el hermano, la hermana", fr: "le frère, la sœur", en: "the brother, the sister" },
        { target: "el hijo, la hija", fr: "le fils, la fille", en: "the son, the daughter" },
        { target: "los abuelos", fr: "les grands-parents", en: "the grandparents" },
        { target: "mi, mis", fr: "mon, mes", en: "my" },
        { target: "el pelo castaño", fr: "les cheveux bruns", en: "brown hair" },
      ],
      exercises: [
        {
          prompt: "Complète : « ___ hermanos son muy simpáticos. » (mes)",
          promptEn: "Complete: \"___ hermanos son muy simpáticos.\" (my)",
          accept: ["mis"],
          explain: "Au pluriel, « mon/mes » se dit « mis » : mis hermanos.",
          explainEn: "In the plural, \"my\" is \"mis\": mis hermanos.",
        },
        {
          prompt: "« Tiene los ojos azules » signifie...",
          promptEn: "\"Tiene los ojos azules\" means...",
          options: ["il a les yeux bleus", "il a les yeux verts", "il a les yeux noirs"],
          accept: ["il a les yeux bleus"],
          explain: "« azules » = bleus. La phrase complète : il a les yeux bleus.",
          explainEn: "\"azules\" = blue. The full sentence: he has blue eyes.",
        },
        {
          prompt: "Complète : « Mi madre ___ muy cariñosa. » (ser)",
          promptEn: "Complete: \"Mi madre ___ muy cariñosa.\" (ser)",
          accept: ["es"],
          explain: "Troisième personne du singulier de ser : « es ».",
          explainEn: "Third person singular of ser: \"es\".",
        },
      ],
    },
    {
      number: 7,
      slug: "es-07",
      title: "Le travail et le bureau",
      titleEn: "Work and the office",
      summary:
        "Parler de son travail, des tâches au bureau et de la hiérarchie.",
      summaryEn:
        "Talking about your job, office tasks and hierarchy.",
      grammar: ["Verbos del trabajo: trabajar, dirigir", "Ir a + lugar", "Los días de la semana"],
      explanation:
        "Pour parler de son travail : « Trabajo en una empresa » (je travaille dans une entreprise), « Trabajo como comercial » (je travaille comme commercial). On utilise ir a pour exprimer une destination : « Voy a la oficina » (je vais au bureau), « Voy al trabajo » (je vais au travail, contraction a + el = al). Les jours de la semaine : lunes, martes, miércoles, jueves, viernes, sábado, domingo, précédés de la préposition en ou utilisés directement : « Trabajo los lunes » (je travaille les lundis). Le vocabulaire du bureau : la reunión (la réunion), el jefe/la jefa (le chef/la cheffe), la tarea (la tâche), la empresa (l'entreprise).",
      explanationEn:
        "To talk about your job: \"Trabajo en una empresa\" (I work in a company), \"Trabajo como comercial\" (I work as a sales representative). Use ir a to express a destination: \"Voy a la oficina\" (I go to the office), \"Voy al trabajo\" (contraction of a + el). The days of the week: lunes, martes, miércoles, jueves, viernes, sábado, domingo: \"Trabajo los lunes\" (I work on Mondays). Office vocabulary: la reunión (the meeting), el jefe/la jefa (the boss), la tarea (the task), la empresa (the company).",
      examples: [
        { target: "Trabajo como contador en una empresa internacional.", fr: "Je travaille comme comptable dans une entreprise internationale.", en: "I work as an accountant in an international company." },
        { target: "Voy al trabajo en metro todos los días.", fr: "Je vais au travail en métro tous les jours.", en: "I go to work by metro every day." },
        { target: "Tenemos una reunión el martes por la mañana.", fr: "Nous avons une réunion mardi matin.", en: "We have a meeting on Tuesday morning." },
        { target: "Mi jefe es muy exigente pero justo.", fr: "Mon chef est très exigeant mais juste.", en: "My boss is very demanding but fair." },
      ],
      vocab: [
        { target: "el trabajo", fr: "le travail", en: "the work, the job" },
        { target: "la oficina", fr: "le bureau", en: "the office" },
        { target: "la empresa", fr: "l'entreprise", en: "the company" },
        { target: "la reunión", fr: "la réunion", en: "the meeting" },
        { target: "el jefe, la jefa", fr: "le chef, la cheffe", en: "the boss" },
        { target: "trabajar como", fr: "travailler comme", en: "to work as" },
        { target: "ir al trabajo", fr: "aller au travail", en: "to go to work" },
        { target: "el contador", fr: "le comptable", en: "the accountant" },
      ],
      exercises: [
        {
          prompt: "Complète : « Voy ___ oficina. »",
          promptEn: "Complete: \"Voy ___ oficina.\"",
          accept: ["a la"],
          explain: "Avec un nom féminin (la oficina), on dit « a la oficina ». La contraction al ne vaut que pour el.",
          explainEn: "With a feminine noun (la oficina), say \"a la oficina\". The contraction al only applies to el.",
        },
        {
          prompt: "« Trabajo como » signifie...",
          promptEn: "\"Trabajo como\" means...",
          options: ["je travaille comme", "je travaille à", "je travaille avec"],
          accept: ["je travaille comme"],
          explain: "« trabajar como » + profession = travailler comme (dans la fonction de).",
          explainEn: "\"trabajar como\" + profession = to work as.",
        },
        {
          prompt: "Complète : « ___ martes tenemos una reunión. » (le/el)",
          promptEn: "Complete: \"___ martes tenemos una reunión.\" (on/el)",
          accept: ["el"],
          explain: "Le jour précis se dit avec l'article défini : « el martes » = mardi.",
          explainEn: "A specific day uses the definite article: \"el martes\" = on Tuesday.",
        },
      ],
    },
    {
      number: 8,
      slug: "es-08",
      title: "Faire des achats et commander",
      titleEn: "Shopping and ordering",
      summary:
        "Commander au restaurant et faire des achats : formules de politesse et verbes utiles.",
      summaryEn:
        "Ordering at a restaurant and shopping: polite phrases and useful verbs.",
      grammar: ["Quisiera / Me gustaría", "El presente de querer y poder", "Las letras para pedir"],
      explanation:
        "Au restaurant, on commande poliment avec quisiera ou me gustaría (je voudrais) : « Quisiera un café, por favor » (je voudrais un café, s'il vous plaît). Le verbe querer (vouloir) est irrégulier : yo quiero, tú quieres, él quiere. Pour demander le prix : « ¿Cuánto cuesta? » (combien ça coûte ?), « ¿Cuánto vale? ». Le verbe poder : « ¿Puedo pagar con tarjeta? » (je peux payer par carte ?). Vocabulaire : el camarero (le serveur), la cuenta (l'addition), el plato (le plat), el precio (le prix). Exemple de commande complète : « Para mí, la ensalada y luego un flan. »",
      explanationEn:
        "At a restaurant, order politely with quisiera or me gustaría (I would like): \"Quisiera un café, por favor\" (I would like a coffee, please). The verb querer (to want) is irregular: yo quiero, tú quieres, él quiere. To ask the price: \"¿Cuánto cuesta?\" (how much does it cost?). The verb poder (to be able to): \"¿Puedo pagar con tarjeta?\" (can I pay by card?). Vocabulary: el camarero (the waiter), la cuenta (the bill), el plato (the dish), el precio (the price). A full order: \"Para mí, la ensalada y luego un flan.\"",
      examples: [
        { target: "Quisiera un menú del día, por favor.", fr: "Je voudrais un menu du jour, s'il vous plaît.", en: "I would like the daily special menu, please." },
        { target: "¿Cuánto cuesta esta camisa?", fr: "Combien coûte cette chemise ?", en: "How much does this shirt cost?" },
        { target: "¿Puedo pagar con tarjeta?", fr: "Je peux payer par carte ?", en: "Can I pay by card?" },
        { target: "La cuenta, por favor. Gracias.", fr: "L'addition, s'il vous plaît. Merci.", en: "The bill, please. Thank you." },
      ],
      vocab: [
        { target: "quisiera", fr: "je voudrais", en: "I would like" },
        { target: "el menú del día", fr: "le menu du jour", en: "the daily special" },
        { target: "la cuenta", fr: "l'addition", en: "the bill, the check" },
        { target: "el camarero", fr: "le serveur", en: "the waiter" },
        { target: "¿cuánto cuesta?", fr: "combien ça coûte ?", en: "how much does it cost?" },
        { target: "pagar con tarjeta", fr: "payer par carte", en: "to pay by card" },
        { target: "quiere", fr: "il/elle veut", en: "he/she wants" },
        { target: "el precio", fr: "le prix", en: "the price" },
      ],
      exercises: [
        {
          prompt: "Complète : « ___ un café, por favor. » (je voudrais)",
          promptEn: "Complete: \"___ un café, por favor.\" (I would like)",
          accept: ["quisiera", "me gustaría"],
          explain: "Les deux formules polies « quisiera » et « me gustaría » sont correctes.",
          explainEn: "Both polite forms \"quisiera\" and \"me gustaría\" are correct.",
        },
        {
          prompt: "« ¿Cuánto cuesta? » signifie...",
          promptEn: "\"¿Cuánto cuesta?\" means...",
          options: ["combien ça coûte ?", "où est-ce ?", "qui est-ce ?"],
          accept: ["combien ça coûte ?"],
          explain: "« cuánto » = combien, « cuesta » = ça coûte (coster).",
          explainEn: "\"cuánto\" = how much, \"cuesta\" = it costs.",
        },
        {
          prompt: "Complète : « Ella ___ la ensalada. » (querer)",
          promptEn: "Complete: \"Ella ___ la ensalada.\" (querer)",
          accept: ["quiere"],
          explain: "Troisième personne du présent irrégulier de querer : « quiere ».",
          explainEn: "Third person of the irregular present of querer: \"quiere\".",
        },
      ],
    },
    {
      number: 9,
      slug: "es-09",
      title: "L'heure, le temps et la météo",
      titleEn: "Time and weather",
      summary:
        "Demander et dire l'heure, parler de la météo et des saisons.",
      summaryEn:
        "Asking and telling the time, talking about the weather and the seasons.",
      grammar: ["¿Qué hora es? Son las...", "El clima con hacer: hace frío", "Las estaciones del año"],
      explanation:
        "Pour demander l'heure : « ¿Qué hora es? » (quelle heure est-il ?). On répond « Es la una » (il est une heure) au singulier et « Son las dos / las tres y media » au pluriel. Les minutes : y cinco, y cuarto (et quart), menos cuarto (moins le quart), en punto (pile). Pour la météo, on utilise le verbe hacer : hace frío (il fait froid), hace calor (il fait chaud), hace sol (il fait soleil), hace viento (il fait du vent). Le temps qu'il fait peut aussi se dire avec llover (pleuvoir) et nevar (neiger). Les saisons : la primavera (le printemps), el verano (l'été), el otoño (l'automne), el invierno (l'hiver).",
      explanationEn:
        "To ask the time: \"¿Qué hora es?\" (what time is it?). You answer \"Es la una\" (it is one o'clock) in the singular and \"Son las dos / las tres y media\" in the plural. Minutes: y cinco, y cuarto (quarter past), menos cuarto (quarter to), en punto (o'clock sharp). For the weather, use the verb hacer: hace frío (it is cold), hace calor (it is hot), hace sol (it is sunny), hace viento (it is windy). It can also rain and snow with llover and nevar. The seasons: la primavera (spring), el verano (summer), el otoño (autumn), el invierno (winter).",
      examples: [
        { target: "¿Qué hora es? Son las dos y media.", fr: "Quelle heure est-il ? Il est deux heures et demie.", en: "What time is it? It is half past two." },
        { target: "Es la una y cuarto.", fr: "Il est une heure et quart.", en: "It is a quarter past one." },
        { target: "Hoy hace mucho frío en Madrid.", fr: "Aujourd'hui il fait très froid à Madrid.", en: "Today it is very cold in Madrid." },
        { target: "En verano hace calor y hay sol.", fr: "En été il fait chaud et il y a du soleil.", en: "In summer it is hot and sunny." },
      ],
      vocab: [
        { target: "¿qué hora es?", fr: "quelle heure est-il ?", en: "what time is it?" },
        { target: "es la una", fr: "il est une heure", en: "it is one o'clock" },
        { target: "y media", fr: "et demie", en: "half past" },
        { target: "hace frío", fr: "il fait froid", en: "it is cold" },
        { target: "hace calor", fr: "il fait chaud", en: "it is hot" },
        { target: "llueve", fr: "il pleut", en: "it rains, it is raining" },
        { target: "el verano", fr: "l'été", en: "the summer" },
        { target: "el invierno", fr: "l'hiver", en: "the winter" },
      ],
      exercises: [
        {
          prompt: "Complète : « Son las dos y ___ » (15 minutes)",
          promptEn: "Complete: \"Son las dos y ___\" (15 minutes)",
          accept: ["cuarto"],
          explain: "« y cuarto » = et quart, soit 15 minutes.",
          explainEn: "\"y cuarto\" = quarter past, i.e. 15 minutes.",
        },
        {
          prompt: "« Hace frío » signifie...",
          promptEn: "\"Hace frío\" means...",
          options: ["il fait froid", "il fait chaud", "il pleut"],
          accept: ["il fait froid"],
          explain: "« frío » = froid. La réponse correcte est « il fait froid ».",
          explainEn: "\"frío\" = cold. The correct answer is \"il is cold\".",
        },
        {
          prompt: "Complète : « ¿Qué hora ___ ? »",
          promptEn: "Complete: \"¿Qué hora ___ ?\"",
          accept: ["es"],
          explain: "On demande l'heure avec « es » : « ¿Qué hora es? » (il est une heure, singulier).",
          explainEn: "Ask the time with \"es\": \"¿Qué hora es?\"",
        },
      ],
    },
    {
      number: 10,
      slug: "es-10",
      title: "Entretien : présente-toi et ton parcours",
      titleEn: "Interview: introduce yourself and your career",
      summary:
        "Répondre aux questions classiques de début d'entretien : présentation, expérience et formation.",
      summaryEn:
        "Answering the classic opening interview questions: presentation, experience and training.",
      grammar: ["Pretérito perfecto: he trabajado", "Los marcadores de tiempo: desde hace", "El vocabulario del currículum"],
      explanation:
        "Lors d'un entretien, pour parler de votre expérience passée, on utilise souvent le pretérito perfecto : « He trabajado en dos empresas » (j'ai travaillé dans deux entreprises), « He estudiado en la universidad » (j'ai étudié à l'université). Pour exprimer une durée depuis le passé jusqu'à maintenant : « desde hace » : « Llevo cinco años trabajando aquí » ou « Trabajo aquí desde hace cinco años » (je travaille ici depuis cinq ans). Le parcours se raconte avec le vocabulaire du CV : la experiencia (l'expérience), la formación (la formation), la titulación (le diplôme), el puesto (le poste). Une bonne structure de réponse : d'abord l'identité, puis la formation, puis l'expérience et enfin le projet.",
      explanationEn:
        "In an interview, to talk about past experience you often use the preterite perfect: \"He trabajado en dos empresas\" (I have worked in two companies), \"He estudiado en la universidad\" (I have studied at university). To express a duration from the past until now, use \"desde hace\": \"Trabajo aquí desde hace cinco años\" (I have worked here for five years). Your career is told with CV vocabulary: la experiencia (experience), la formación (training), la titulación (degree), el puesto (position). A good answer structure: first identity, then training, then experience, and finally your project.",
      examples: [
        { target: "He trabajado en dos empresas diferentes.", fr: "J'ai travaillé dans deux entreprises différentes.", en: "I have worked in two different companies." },
        { target: "Estudié economía en la universidad de Madrid.", fr: "J'ai étudié l'économie à l'université de Madrid.", en: "I studied economics at the University of Madrid." },
        { target: "Trabajo aquí desde hace tres años.", fr: "Je travaille ici depuis trois ans.", en: "I have been working here for three years." },
        { target: "Mi formación es en administración de empresas.", fr: "Ma formation est en gestion d'entreprise.", en: "My training is in business administration." },
      ],
      vocab: [
        { target: "la experiencia", fr: "l'expérience", en: "the experience" },
        { target: "la formación", fr: "la formation", en: "the training" },
        { target: "el currículum", fr: "le CV", en: "the resume" },
        { target: "el puesto", fr: "le poste", en: "the position" },
        { target: "la titulación", fr: "le diplôme", en: "the degree" },
        { target: "desde hace", fr: "depuis (durée)", en: "for (duration)" },
        { target: "he trabajado", fr: "j'ai travaillé", en: "I have worked" },
        { target: "la universidad", fr: "l'université", en: "the university" },
      ],
      exercises: [
        {
          prompt: "Complète : « ___ trabajado en una empresa. » (auxiliaire)",
          promptEn: "Complete: \"___ trabajado en una empresa.\" (auxiliary)",
          accept: ["he"],
          explain: "Le pretérito perfecto se forme avec l'auxiliaire haber : « he trabajado ».",
          explainEn: "The preterite perfect uses the auxiliary haber: \"he trabajado\".",
        },
        {
          prompt: "« Trabajo aquí desde hace tres años » signifie...",
          promptEn: "\"Trabajo aquí desde hace tres años\" means...",
          options: ["je travaille ici depuis trois ans", "je travaillais ici trois ans", "je travaille ici dans trois ans"],
          accept: ["je travaille ici depuis trois ans"],
          explain: "« desde hace » = depuis : la phrase exprime une durée qui continue.",
          explainEn: "\"desde hace\" = for (duration): the sentence expresses a duration that continues.",
        },
        {
          prompt: "Complète : « He ___ en la universidad. » (estudiar)",
          promptEn: "Complete: \"He ___ en la universidad.\" (estudiar)",
          accept: ["estudiado"],
          explain: "Le participe passé de estudiar est « estudiado ».",
          explainEn: "The past participle of estudiar is \"estudiado\".",
        },
      ],
      interview: [
        {
          question: "Cuéntame sobre tu formación y tu experiencia.",
          fr: "Parle-moi de ta formation et de ton expérience.",
          en: "Tell me about your education and your experience.",
          modelFr: "J'ai étudié l'économie, puis j'ai travaillé trois ans comme analyste dans une banque.",
          modelEn: "I studied economics and then I worked for three years as an analyst in a bank.",
          accept: ["he estudiado", "he trabajado", "mi formación"],
        },
        {
          question: "¿Por qué quieres este trabajo?",
          fr: "Pourquoi veux-tu ce travail ?",
          en: "Why do you want this job?",
          modelFr: "Ce poste correspond à mon parcours et il me permettra de développer de nouvelles compétences.",
          modelEn: "This position matches my background and will allow me to develop new skills.",
          accept: ["este puesto", "mis habilidades", "quiero aprender"],
        },
        {
          question: "Háblame de tu último trabajo.",
          fr: "Parle-moi de ton dernier travail.",
          en: "Tell me about your last job.",
          modelFr: "Dans mon dernier poste, je gérais les comptes clients et je reportais directement au directeur.",
          modelEn: "In my last position, I managed client accounts and reported directly to the director.",
          accept: ["mi último puesto", "yo gestionaba"],
        },
      ],
    },
    {
      number: 11,
      slug: "es-11",
      title: "Entretien : atouts, faiblesses et motivation",
      titleEn: "Interview: strengths, weaknesses and motivation",
      summary:
        "Présenter ses atouts, admettre une faiblesse avec tact et expliquer sa motivation.",
      summaryEn:
        "Presenting your strengths, admitting a weakness tactfully, and explaining your motivation.",
      grammar: ["Mis fortalezas son...", "Mi debilidad es...", "Porque + motivo"],
      explanation:
        "Pour présenter ses atouts : « Mis fortalezas son mi capacidad de organización y mi constancia » (mes atouts sont ma capacité d'organisation et ma constance). On peut dire aussi : « Soy bueno trabajando en equipo » pour un homme, « Soy buena trabajando en equipo » pour une femme (attention à l'accord). Pour la faiblesse, on l'annonce puis on montre qu'on travaille dessus : « Mi debilidad es ser muy perfeccionista, pero estoy aprendiendo a delegar » (ma faiblesse est d'être très perfectionniste, mais j'apprends à déléguer). La motivation se justifie avec porque : « Quiero trabajar aquí porque la empresa valora la innovación » (je veux travailler ici parce que l'entreprise valorise l'innovation).",
      explanationEn:
        "To present your strengths: \"Mis fortalezas son mi capacidad de organización y mi constancia\" (my strengths are my organizational ability and my perseverance). You can also say: \"Soy bueno trabajando en equipo\" for a man and \"Soy buena trabajando en equipo\" for a woman (watch the agreement). For the weakness, announce it then show you are working on it: \"Mi debilidad es ser muy perfeccionista, pero estoy aprendiendo a delegar\" (my weakness is being very perfectionist, but I am learning to delegate). Motivation is justified with porque: \"Quiero trabajar aquí porque la empresa valora la innovación\" (I want to work here because the company values innovation).",
      examples: [
        { target: "Mis fortalezas son la constancia y la responsabilidad.", fr: "Mes atouts sont la constance et la responsabilité.", en: "My strengths are perseverance and responsibility." },
        { target: "Soy buena trabajando en equipo.", fr: "Je suis bonne pour travailler en équipe.", en: "I am good at working in a team." },
        { target: "Mi debilidad es impacientarme con las tareas lentas.", fr: "Ma faiblesse est de m'impatienter avec les tâches lentes.", en: "My weakness is getting impatient with slow tasks." },
        { target: "Quiero trabajar aquí porque esta empresa valora la innovación.", fr: "Je veux travailler ici parce que cette entreprise valorise l'innovation.", en: "I want to work here because this company values innovation." },
      ],
      vocab: [
        { target: "las fortalezas", fr: "les atouts", en: "the strengths" },
        { target: "las debilidades", fr: "les faiblesses", en: "the weaknesses" },
        { target: "la constancia", fr: "la constance", en: "constancy, perseverance" },
        { target: "la responsabilidad", fr: "la responsabilité", en: "responsibility" },
        { target: "la innovación", fr: "l'innovation", en: "the innovation" },
        { target: "trabajar en equipo", fr: "travailler en équipe", en: "to work in a team" },
        { target: "aprender a delegar", fr: "apprendre à déléguer", en: "to learn to delegate" },
        { target: "porque", fr: "parce que", en: "because" },
      ],
      exercises: [
        {
          prompt: "Complète : « Quiero trabajar ___ porque me interesa el proyecto. »",
          promptEn: "Complete: \"Quiero trabajar ___ porque me interesa el proyecto.\"",
          accept: ["aquí"],
          explain: "« aquí » = ici : « Quiero trabajar aquí ».",
          explainEn: "\"aquí\" = here: \"Quiero trabajar aquí\".",
        },
        {
          prompt: "« Las fortalezas » signifie...",
          promptEn: "\"Las fortalezas\" means...",
          options: ["les atouts", "les faiblesses", "les habitudes"],
          accept: ["les atouts"],
          explain: "« la fortaleza » = l'atout, la force.",
          explainEn: "\"la fortaleza\" = the strength.",
        },
        {
          prompt: "Complète : « Mi debilidad es ser muy ___ » (perfectionniste)",
          promptEn: "Complete: \"Mi debilidad es ser muy ___\" (perfectionist)",
          accept: ["perfeccionista"],
          explain: "« perfeccionista » signifie perfectionniste en espagnol.",
          explainEn: "\"perfeccionista\" means perfectionist in Spanish.",
        },
      ],
      interview: [
        {
          question: "¿Cuáles son tus fortalezas?",
          fr: "Quelles sont tes forces ?",
          en: "What are your strengths?",
          modelFr: "Je suis organisé, ponctuel et je m'adapte facilement aux nouveaux outils.",
          modelEn: "I am organized, punctual and I adapt easily to new tools.",
          accept: ["soy organizado", "soy puntual", "me adapto"],
        },
        {
          question: "¿Cuál es tu mayor debilidad?",
          fr: "Quelle est ta plus grande faiblesse ?",
          en: "What is your greatest weakness?",
          modelFr: "Je tends à être perfectionniste, mais j'ai appris à déléguer et à prioriser.",
          modelEn: "I tend to be a perfectionist, but I have learned to delegate and to prioritize.",
          accept: ["soy perfeccionista", "perfeccionista", "estoy aprendiendo a delegar"],
        },
        {
          question: "¿Por qué quieres trabajar en esta empresa?",
          fr: "Pourquoi veux-tu travailler dans cette entreprise ?",
          en: "Why do you want to work in this company?",
          modelFr: "J'admire vos projets et je veux appliquer mon expérience à des défis ambitieux.",
          modelEn: "I admire your projects and I want to apply my experience to ambitious challenges.",
          accept: ["me interesa", "valoro", "aplicar mi experiencia"],
        },
      ],
    },
    {
      number: 12,
      slug: "es-12",
      title: "Entretien : projets, travail d'équipe et gestion du stress",
      titleEn: "Interview: projects, teamwork and stress management",
      summary:
        "Parler de ses projets, de son travail en équipe et de sa gestion du stress.",
      summaryEn:
        "Talking about your projects, your teamwork and your stress management.",
      grammar: ["El futuro: quiero + infinitivo", "Metáforas del trabajo en equipo", "El subjuntivo: es importante que..."],
      explanation:
        "Pour parler de ses projets : « Quiero seguir creciendo en esta empresa » (je veux continuer à grandir dans cette entreprise) ; le futur proche se forme avec ir a : « Voy a asumir más responsabilidades » (je vais assumer plus de responsabilités). Pour le travail en équipe : « Me gusta colaborar y escuchar las ideas de los demás » (j'aime collaborer et écouter les idées des autres). Pour le stress : « Mantengo la calma bajo presión » (je garde mon calme sous pression), « Planifico mis tareas para evitar el estrés » (je planifie mes tâches pour éviter le stress). On peut aussi introduire un conseil ou une opinion avec le subjonctif : « Es importante que yo me organice » (il est important que je m'organise).",
      explanationEn:
        "To talk about your projects: \"Quiero seguir creciendo en esta empresa\" (I want to keep growing in this company); the near future is formed with ir a: \"Voy a asumir más responsabilidades\" (I am going to take on more responsibilities). For teamwork: \"Me gusta colaborar y escuchar las ideas de los demás\" (I like collaborating and listening to others' ideas). For stress: \"Mantengo la calma bajo presión\" (I keep calm under pressure), \"Planifico mis tareas para evitar el estrés\" (I plan my tasks to avoid stress). You can also introduce a piece of advice or an opinion with the subjunctive: \"Es importante que yo me organice\" (it is important that I organize myself).",
      examples: [
        { target: "Quiero seguir creciendo profesionalmente en esta empresa.", fr: "Je veux continuer à grandir professionnellement dans cette entreprise.", en: "I want to keep growing professionally in this company." },
        { target: "Voy a asumir más responsabilidades en mi nuevo puesto.", fr: "Je vais assumer plus de responsabilités dans mon nouveau poste.", en: "I am going to take on more responsibilities in my new position." },
        { target: "Me gusta colaborar y escuchar las ideas de los demás.", fr: "J'aime collaborer et écouter les idées des autres.", en: "I like collaborating and listening to other people's ideas." },
        { target: "Mantengo la calma bajo presión y planifico mis tareas.", fr: "Je garde mon calme sous pression et je planifie mes tâches.", en: "I keep calm under pressure and I plan my tasks." },
      ],
      vocab: [
        { target: "crecer", fr: "grandir, évoluer", en: "to grow" },
        { target: "asumir responsabilidades", fr: "assumer des responsabilités", en: "to take on responsibilities" },
        { target: "colaborar", fr: "collaborer", en: "to collaborate" },
        { target: "la presión", fr: "la pression", en: "the pressure" },
        { target: "mantener la calma", fr: "garder son calme", en: "to keep calm" },
        { target: "planificar", fr: "planifier", en: "to plan" },
        { target: "el estrés", fr: "le stress", en: "the stress" },
        { target: "los proyectos", fr: "les projets", en: "the projects" },
      ],
      exercises: [
        {
          prompt: "Complète : « Voy a ___ más responsabilidades. » (assumer)",
          promptEn: "Complete: \"Voy a ___ más responsabilidades.\" (take on)",
          accept: ["asumir"],
          explain: "Après « voy a », on met l'infinitif : « asumir ».",
          explainEn: "After \"voy a\", use the infinitive: \"asumir\".",
        },
        {
          prompt: "« Mantener la calma » signifie...",
          promptEn: "\"Mantener la calma\" means...",
          options: ["garder son calme", "perdre patience", "aller vite"],
          accept: ["garder son calme"],
          explain: "« mantener » = maintenir, « la calma » = le calme : garder son calme.",
          explainEn: "\"mantener\" = to keep, \"la calma\" = calm: to keep calm.",
        },
        {
          prompt: "Complète : « Es importante que ___ planifique. » (yo)",
          promptEn: "Complete: \"Es importante que ___ planifique.\" (yo)",
          accept: ["yo", "me"],
          explain: "« Es importante que yo me planifique » : le subjonctif s'emploie après « es importante que ».",
          explainEn: "\"Es importante que yo me planifique\": the subjunctive is used after \"es importante que\".",
        },
      ],
      interview: [
        {
          question: "¿Cuáles son tus metas profesionales?",
          fr: "Quelles sont tes objectifs professionnels ?",
          en: "What are your professional goals?",
          modelFr: "Mon objectif est d'occuper à terme un poste à responsabilités et de continuer à apprendre.",
          modelEn: "My goal is to eventually hold a position of responsibility and keep learning.",
          accept: ["mis metas son", "un puesto con responsabilidad", "seguir aprendiendo"],
        },
        {
          question: "¿Prefieres trabajar en equipo o solo?",
          fr: "Tu préfères travailler en équipe ou seul ?",
          en: "Do you prefer working in a team or alone?",
          modelFr: "Je préfère travailler en équipe parce que les échanges améliorent les résultats.",
          modelEn: "I prefer working in a team because sharing ideas improves results.",
          accept: ["trabajo bien en equipo", "prefiero el equipo"],
        },
        {
          question: "¿Cómo manejas el estrés?",
          fr: "Comment gères-tu le stress ?",
          en: "How do you handle stress?",
          modelFr: "Je garde mon calme, je divise le travail en petites tâches et je respecte les délais.",
          modelEn: "I keep calm, I break the work into small tasks and I respect deadlines.",
          accept: ["mantengo la calma", "planifico mis tareas", "organizo el trabajo"],
        },
        {
          question: "¿Dónde te ves en cinco años?",
          fr: "Où te vois-tu dans cinq ans ?",
          en: "Where do you see yourself in five years?",
          modelFr: "Je me vois dans un poste de coordination, en train de diriger une petite équipe.",
          modelEn: "I see myself in a coordination position, leading a small team.",
          accept: ["me veo", "un puesto de coordinación", "liderando un equipo"],
        },
        {
          question: "¿Por qué debemos elegirte?",
          fr: "Pourquoi devons-nous te choisir ?",
          en: "Why should we choose you?",
          modelFr: "J'apporte une expérience concrète, de l'enthousiasme et une grande capacité d'adaptation.",
          modelEn: "I bring concrete experience, enthusiasm and a great ability to adapt.",
          accept: ["mi experiencia", "mi entusiasmo", "capacidad de adaptación"],
        },
      ],
    },
  ],
};