import type { LanguageCourse } from "./genericLessons";

export const HI_COURSE: LanguageCourse = {
  code: "hi",
  name: "Hindi",
  native: "हिन्दी",
  heroTitle1: { fr: "Apprenez", en: "Learn" },
  heroTitle2: { fr: "le hindi", en: "Hindi" },
  heroSubtitle: {
    fr: "Un parcours débutant en douze leçons : salutations, vie quotidienne, travail et entretien d'embauche, en dévanâgarî.",
    en: "A beginner path in twelve lessons: greetings, daily life, work and job interviews, in Devanagari.",
  },
  lessons: [
    {
      number: 1,
      slug: "hi-01",
      title: "Se présenter et saluer",
      titleEn: "Introducing yourself and greeting",
      summary: "Les salutations de base et les premières présentations : dire son nom, son origine et faire connaissance.",
      summaryEn: "Basic greetings and first introductions: giving your name, your origin and getting to know someone.",
      grammar: [
        "नमस्ते (namaste) et नमस्कार (namaskār)",
        "मेरा नाम ... है (merā nām ... hai : mon nom est)",
        "मैं ... से हूँ (maiṁ ... se hūṁ : je suis de ...)",
      ],
      explanation:
        "En hindi, on salue avec « नमस्ते » (namaste) ou « नमस्कार » (namaskār), utilisés aussi bien à l'arrivée qu'au départ. Pour se présenter on dit « मेरा नाम ... है » (littéralement « mon nom ... est »). Pour donner son origine, on emploie la postposition « से » (se = de) suivie du verbe « होना » (être) : « मैं फ्रांस से हूँ » (je suis de France). Le verbe « है » (hai = est) se place toujours en fin de phrase, et « हूँ » (hūṁ = suis) s'accorde avec le sujet « मैं ».",
      explanationEn:
        "In Hindi, you greet with \"नमस्ते\" (namaste) or \"नमस्कार\" (namaskār), used both on arrival and departure. To introduce yourself you say \"मेरा नाम ... है\" (literally \"my name ... is\"). To give your origin, you use the postposition \"से\" (se = from) followed by the verb \"होना\" (to be): \"मैं फ्रांस से हूँ\" (I am from France). The verb \"है\" (hai = is) always comes at the end of the sentence, and \"हूँ\" (hūṁ = am) agrees with the subject \"मैं\".",
      examples: [
        { target: "नमस्ते, मेरा नाम डैनियल है।", roman: "Namaste, merā nām Ḍainiyal hai.", fr: "Bonjour, je m'appelle Daniel.", en: "Hello, my name is Daniel." },
        { target: "मैं फ्रांस से हूँ।", roman: "Maiṁ Frāṁs se hūṁ.", fr: "Je suis de France.", en: "I am from France." },
        { target: "आप कैसे हैं?", roman: "Āp kaise haiṁ?", fr: "Comment allez-vous ?", en: "How are you?" },
        { target: "आपसे मिलकर खुशी हुई।", roman: "Āpse milkar khuśī huī.", fr: "Enchanté de vous rencontrer.", en: "Nice to meet you." },
      ],
      vocab: [
        { target: "नमस्ते", roman: "namaste", fr: "bonjour / salut", en: "hello" },
        { target: "नमस्कार", roman: "namaskār", fr: "bonjour (respectueux)", en: "good day (respectful)" },
        { target: "मेरा नाम", roman: "merā nām", fr: "mon nom / je m'appelle", en: "my name" },
        { target: "मैं", roman: "maiṁ", fr: "je", en: "I" },
        { target: "से", roman: "se", fr: "de (provenance)", en: "from" },
        { target: "हूँ / है", roman: "hūṁ / hai", fr: "suis / est (être)", en: "am / is (to be)" },
        { target: "आप", roman: "āp", fr: "vous", en: "you" },
        { target: "खुशी हुई", roman: "khuśī huī", fr: "enchanté (plaisir eu)", en: "nice to meet (pleasure had)" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Bonjour, je m'appelle Zeynep » → « ___ नाम ज़ैनब है ».",
          promptEn: "Complete: \"Hello, my name is Zeynep\" → \"___ nām Zainab hai\".",
          options: ["मेरा", "तेरा", "उसका", "हमारा"],
          accept: ["मेरा"],
          explain: "« मेरा नाम » signifie « mon nom ». La forme possessive मेरा (mon) précède नाम (nom).",
          explainEn: "\"मेरा नाम\" means \"my name\". The possessive form मेरा (my) precedes नाम (name).",
        },
        {
          prompt: "Que dit-on en hindi pour dire « bonjour » en toute occasion ?",
          promptEn: "What do you say in Hindi to greet someone on any occasion?",
          options: ["नमस्ते", "शुक्रिया", "अलविदा", "धन्यवाद"],
          accept: ["नमस्ते"],
          explain: "« नमस्ते » est le salut universel, utilisé à l'arrivée comme au départ. « शुक्रिया » signifie « merci ».",
          explainEn: "\"नमस्ते\" is the universal greeting, used on arrival and departure. \"शुक्रिया\" means \"thank you\".",
        },
        {
          prompt: "Complétez : « Je suis de France » → « मैं फ्रांस ___ हूँ ».",
          promptEn: "Complete: \"I am from France\" → \"Maiṁ Frāṁs ___ hūṁ\".",
          accept: ["से"],
          explain: "La postposition « से » (se) exprime la provenance : « मैं फ्रांस से हूँ » = « je suis de France ».",
          explainEn: "The postposition \"से\" (se) expresses origin: \"maiṁ Frāṁs se hūṁ\" = \"I am from France\".",
        },
      ],
      interview: [
        {
          question: "अपना परिचय दीजिए।",
          roman: "Apanā paricay dījie.",
          fr: "Présentez-vous.",
          en: "Introduce yourself.",
          modelFr: "Je m'appelle Daniel, je viens de France et je travaille comme développeur.",
          modelEn: "My name is Daniel, I come from France and I work as a developer.",
          accept: ["मेरा नाम डैनियल है", "मैं डैनियल हूँ", "मैं फ्रांस से हूँ", "मैं फ्रांस से आता हूँ"],
        },
      ],
    },
    {
      number: 2,
      slug: "hi-02",
      title: "Origine, nationalité et profession",
      titleEn: "Origin, nationality and profession",
      summary: "Exprimer sa nationalité, son origine et sa profession avec « हूँ » (être) et le suffixe des professions.",
      summaryEn: "Expressing your nationality, origin and profession with \"हूँ\" (to be) and professional suffixes.",
      grammar: [
        "कहाँ से (kahām se : d'où) et कहाँ (kahām : où)",
        "मैं ... हूँ (je suis ...)",
        "Suffixes de profession : -कार, -क, -ी",
      ],
      explanation:
        "Pour demander l'origine on dit « आप कहाँ से हैं? » (d'où êtes-vous ?). La réponse utilise « मैं ... से हूँ » (je suis de ...) ou « मैं ... से आता हूँ » (je viens de ...). Pour la nationalité, on emploie simplement le verbe être : « मैं फ्रांसीसी हूँ » (je suis français). Les métiers se forment souvent par suffixe : « काम » (travail) donne « कर्मचारी » (employé), ou par le terme spécifique comme « शिक्षक » (enseignant), « डॉक्टर » (médecin).",
      explanationEn:
        "To ask about origin you say \"आप कहाँ से हैं?\" (where are you from?). The answer uses \"मैं ... से हूँ\" (I am from ...) or \"मैं ... से आता हूँ\" (I come from ...). For nationality, you simply use the verb to be: \"मैं फ्रांसीसी हूँ\" (I am French). Professions are often formed with a suffix: \"काम\" (work) gives \"कर्मचारी\" (employee), or by a specific term such as \"शिक्षक\" (teacher), \"डॉक्टर\" (doctor).",
      examples: [
        { target: "आप कहाँ से हैं?", roman: "Āp kahām se haiṁ?", fr: "D'où êtes-vous ?", en: "Where are you from?" },
        { target: "मैं भारत से हूँ।", roman: "Maiṁ Bhārat se hūṁ.", fr: "Je suis de l'Inde.", en: "I am from India." },
        { target: "मैं फ्रांसीसी हूँ।", roman: "Maiṁ Frāṁsīsī hūṁ.", fr: "Je suis français.", en: "I am French." },
        { target: "मैं एक शिक्षक हूँ।", roman: "Maiṁ ek śikṣak hūṁ.", fr: "Je suis enseignant.", en: "I am a teacher." },
      ],
      vocab: [
        { target: "कहाँ से", roman: "kahām se", fr: "d'où", en: "from where" },
        { target: "भारत", roman: "Bhārat", fr: "l'Inde", en: "India" },
        { target: "फ्रांसीसी", roman: "Frāṁsīsī", fr: "français (nationalité)", en: "French (nationality)" },
        { target: "शिक्षक", roman: "śikṣak", fr: "enseignant", en: "teacher" },
        { target: "डॉक्टर", roman: "ḍākṭar", fr: "médecin", en: "doctor" },
        { target: "काम", roman: "kām", fr: "travail", en: "work" },
        { target: "कर्मचारी", roman: "karmacārī", fr: "employé", en: "employee" },
        { target: "आता हूँ", roman: "ātā hūṁ", fr: "je viens", en: "I come" },
      ],
      exercises: [
        {
          prompt: "Comment demander « d'où êtes-vous ? » en hindi ?",
          promptEn: "How do you ask \"where are you from?\" in Hindi?",
          options: ["आप कहाँ से हैं?", "आप क्या करते हैं?", "आप कैसे हैं?", "आपका क्या नाम है?"],
          accept: ["आप कहाँ से हैं?"],
          explain: "« आप कहाँ से हैं? » signifie littéralement « vous d'où êtes ? ». C'est la formule standard pour demander l'origine.",
          explainEn: "\"आप कहाँ से हैं?\" literally means \"you from where are?\". It is the standard way to ask about origin.",
        },
        {
          prompt: "Complétez : « Je suis de l'Inde » → « मैं भारत ___ हूँ ».",
          promptEn: "Complete: \"I am from India\" → \"Maiṁ Bhārat ___ hūṁ\".",
          accept: ["से"],
          explain: "« भारत से » (Bhārat se) = « de l'Inde ». La postposition से exprime toujours la provenance.",
          explainEn: "\"भारत से\" (Bhārat se) = \"from India\". The postposition से always expresses origin.",
        },
        {
          prompt: "Complétez : « Je suis enseignant » → « मैं एक ___ हूँ ».",
          promptEn: "Complete: \"I am a teacher\" → \"Maiṁ ek ___ hūṁ\".",
          options: ["शिक्षक", "डॉक्टर", "काम", "कर्मचारी"],
          accept: ["शिक्षक"],
          explain: "« शिक्षक » signifie « enseignant ». « डॉक्टर » = médecin, « कर्मचारी » = employé, « काम » = travail.",
          explainEn: "\"शिक्षक\" means \"teacher\". \"डॉक्टर\" = doctor, \"कर्मचारी\" = employee, \"काम\" = work.",
        },
      ],
    },
    {
      number: 3,
      slug: "hi-03",
      title: "Être et avoir",
      titleEn: "To be and to have",
      summary: "Le verbe « होना » (être) et l'expression de la possession avec « के पास » (avoir).",
      summaryEn: "The verb \"होना\" (to be) and expressing possession with \"के पास\" (to have).",
      grammar: [
        "होना (honā : être) au présent",
        "मैं हूँ, तुम हो, वह है, हम हैं",
        "के पास (ke pās : avoir) et मेरे पास (mere pās : j'ai)",
      ],
      explanation:
        "Le verbe « होना » (être) se conjugue : « मैं हूँ » (je suis), « तुम हो » (tu es), « वह है » (il/elle est), « हम हैं » (nous sommes), « आप हैं » (vous êtes). Pour exprimer la possession, le hindi utilise « के पास » (littéralement « auprès de, chez ») : « मेरे पास एक कार है » (j'ai une voiture, littéralement « chez moi une voiture est »). Le possesseur prend souvent la forme oblique (« मेरे » pour मैं).",
      explanationEn:
        "The verb \"होना\" (to be) conjugates: \"मैं हूँ\" (I am), \"तुम हो\" (you are), \"वह है\" (he/she is), \"हम हैं\" (we are), \"आप हैं\" (you are). To express possession, Hindi uses \"के पास\" (literally \"near, at\"): \"मेरे पास एक कार है\" (I have a car, literally \"at me a car is\"). The possessor often takes the oblique form (\"मेरे\" from मैं).",
      examples: [
        { target: "मैं सीईओ हूँ।", roman: "Maiṁ sī'ī'ō hūṁ.", fr: "Je suis directeur général.", en: "I am the CEO." },
        { target: "मेरे पास एक कार है।", roman: "Mere pās ek kār hai.", fr: "J'ai une voiture.", en: "I have a car." },
        { target: "क्या आपके पास समय है?", roman: "Kyā āpke pās samay hai?", fr: "Avez-vous du temps ?", en: "Do you have time?" },
        { target: "हम तैयार हैं।", roman: "Ham taiyār haiṁ.", fr: "Nous sommes prêts.", en: "We are ready." },
      ],
      vocab: [
        { target: "हूँ", roman: "hūṁ", fr: "je suis", en: "I am" },
        { target: "है", roman: "hai", fr: "est / il y a", en: "is / there is" },
        { target: "हैं", roman: "haiṁ", fr: "sont / êtes", en: "are" },
        { target: "के पास", roman: "ke pās", fr: "avoir (chez, auprès de)", en: "to have (at, near)" },
        { target: "मेरे पास", roman: "mere pās", fr: "j'ai (chez moi)", en: "I have (at me)" },
        { target: "कार", roman: "kār", fr: "voiture", en: "car" },
        { target: "समय", roman: "samay", fr: "temps", en: "time" },
        { target: "तैयार", roman: "taiyār", fr: "prêt", en: "ready" },
      ],
      exercises: [
        {
          prompt: "Complétez : « J'ai une voiture » → « ___ पास एक कार है ».",
          promptEn: "Complete: \"I have a car\" → \"___ pās ek kār hai\".",
          options: ["मेरे", "तुम्हारे", "उसके", "मेरा"],
          accept: ["मेरे"],
          explain: "« मेरे पास » = « chez moi », la forme oblique du possessif. On ne dit pas « मैं एक कार है » mais « मेरे पास एक कार है ».",
          explainEn: "\"मेरे पास\" = \"at me\", the oblique form of the possessive. You don't say \"मैं एक कार है\" but \"मेरे पास एक कार है\".",
        },
        {
          prompt: "Quelle forme du verbe être convient avec « मैं » (je) ?",
          promptEn: "Which form of the verb to be fits \"मैं\" (I)?",
          options: ["हूँ", "है", "हैं", "हो"],
          accept: ["हूँ"],
          explain: "« मैं हूँ » (je suis). « है » s'emploie avec « वह » (il/elle), « हैं » avec « वे/हम/आप ».",
          explainEn: "\"मैं हूँ\" (I am). \"है\" is used with \"वह\" (he/she), \"हैं\" with \"वे/हम/आप\".",
        },
        {
          prompt: "Complétez : « Nous sommes prêts » → « हम ___ हैं ».",
          promptEn: "Complete: \"We are ready\" → \"Ham ___ haiṁ\".",
          accept: ["तैयार"],
          explain: "« तैयार » signifie « prêt ». La phrase « हम तैयार हैं » = « nous sommes prêts ».",
          explainEn: "\"तैयार\" means \"ready\". The sentence \"हम तैयार हैं\" = \"we are ready\".",
        },
      ],
    },
    {
      number: 4,
      slug: "hi-04",
      title: "La routine quotidienne",
      titleEn: "Daily routine",
      summary: "Décrire sa journée : le matin, le déjeuner, le travail et le soir, avec les verbes réfléchis.",
      summaryEn: "Describing your day: morning, lunch, work and evening, with reflexively formed verbs.",
      grammar: [
        "उठना, नहाना, खाना (se lever, se doucher, manger)",
        "L'expression du temps : सुबह, दोपहर, शाम, रात",
        "करता हूँ (je fais) : habitude au présent",
      ],
      explanation:
        "La routine se décrit au présent avec les verbes du type « मैं ... करता हूँ » (je fais ...), la forme habituelle. On dit « मैं सुबह उठता हूँ » (je me lève le matin), « मैं नाश्ता करता हूँ » (je prends le petit-déjeuner), « मैं काम पर जाता हूँ » (je vais au travail). Les moments de la journée : « सुबह » (matin), « दोपहर » (midi/après-midi), « शाम » (soir), « रात » (nuit).",
      explanationEn:
        "Routine is described in the present with habitual forms like \"मैं ... करता हूँ\" (I do ...). You say \"मैं सुबह उठता हूँ\" (I get up in the morning), \"मैं नाश्ता करता हूँ\" (I have breakfast), \"मैं काम पर जाता हूँ\" (I go to work). Times of day: \"सुबह\" (morning), \"दोपहर\" (midday/afternoon), \"शाम\" (evening), \"रात\" (night).",
      examples: [
        { target: "मैं सुबह सात बजे उठता हूँ।", roman: "Maiṁ subah sāt baje uṭhtā hūṁ.", fr: "Je me lève à sept heures du matin.", en: "I get up at seven in the morning." },
        { target: "मैं नाश्ता करता हूँ।", roman: "Maiṁ nāśtā kartā hūṁ.", fr: "Je prends le petit-déjeuner.", en: "I have breakfast." },
        { target: "मैं काम पर जाता हूँ।", roman: "Maiṁ kām par jātā hūṁ.", fr: "Je vais au travail.", en: "I go to work." },
        { target: "शाम को मैं किताब पढ़ता हूँ।", roman: "Śām ko maiṁ kitāb paṛhtā hūṁ.", fr: "Le soir, je lis un livre.", en: "In the evening, I read a book." },
      ],
      vocab: [
        { target: "सुबह", roman: "subah", fr: "le matin", en: "morning" },
        { target: "दोपहर", roman: "dopahar", fr: "midi / après-midi", en: "midday / afternoon" },
        { target: "शाम", roman: "śām", fr: "le soir", en: "evening" },
        { target: "रात", roman: "rāt", fr: "la nuit", en: "night" },
        { target: "नाश्ता", roman: "nāśtā", fr: "petit-déjeuner", en: "breakfast" },
        { target: "उठता हूँ", roman: "uṭhtā hūṁ", fr: "je me lève", en: "I get up" },
        { target: "जाता हूँ", roman: "jātā hūṁ", fr: "je vais", en: "I go" },
        { target: "पढ़ता हूँ", roman: "paṛhtā hūṁ", fr: "je lis", en: "I read" },
      ],
      exercises: [
        {
          prompt: "Que signifie « सुबह » ?",
          promptEn: "What does \"सुबह\" mean?",
          options: ["le matin", "midi", "le soir", "la nuit"],
          accept: ["le matin"],
          explain: "« सुबह » = matin, « दोपहर » = midi, « शाम » = soir, « रात » = nuit.",
          explainEn: "\"सुबह\" = morning, \"दोपहर\" = midday, \"शाम\" = evening, \"रात\" = night.",
        },
        {
          prompt: "Complétez : « Je vais au travail » → « मैं काम ___ जाता हूँ ».",
          promptEn: "Complete: \"I go to work\" → \"Maiṁ kām ___ jātā hūṁ\".",
          accept: ["पर"],
          explain: "La postposition « पर » signifie « à, sur » : « काम पर » = « au travail ».",
          explainEn: "The postposition \"पर\" means \"at, on\": \"काम पर\" = \"to work\".",
        },
        {
          prompt: "Comment dit-on « le soir, je lis un livre » ?",
          promptEn: "How do you say \"in the evening, I read a book\"?",
          options: ["शाम को मैं किताब पढ़ता हूँ।", "सुबह मैं उठता हूँ।", "मैं नाश्ता करता हूँ।", "रात को मैं सोता हूँ।"],
          accept: ["शाम को मैं किताब पढ़ता हूँ।"],
          explain: "« शाम को » = « le soir », « किताब पढ़ता हूँ » = « je lis un livre ». C'est la phrase correcte.",
          explainEn: "\"शाम को\" = \"in the evening\", \"किताब पढ़ता हूँ\" = \"I read a book\". This is the correct sentence.",
        },
      ],
    },
    {
      number: 5,
      slug: "hi-05",
      title: "Les goûts et loisirs",
      titleEn: "Likes and hobbies",
      summary: "Exprimer ses goûts avec « मुझे पसंद है » (j'aime) et parler des loisirs et activités.",
      summaryEn: "Expressing likes with \"मुझे पसंद है\" (I like) and talking about hobbies and activities.",
      grammar: [
        "मुझे पसंद है (mujhe pasand hai : j'aime)",
        "मुझे ... करना पसंद है (j'aime faire ...)",
        "Négation : नहीं (nahīṁ : pas)",
      ],
      explanation:
        "Pour dire qu'on aime quelque chose, le hindi utilise le datif : « मुझे पसंद है » (littéralement « à moi est agréable »). « मुझे संगीत पसंद है » = j'aime la musique. Avec un verbe à l'infinitif : « मुझे पढ़ना पसंद है » (j'aime lire). La négation se forme avec « नहीं » : « मुझे यह पसंद नहीं है » (je n'aime pas ça). Pour demander on dit « क्या आपको ... पसंद है? » (aimez-vous ... ?).",
      explanationEn:
        "To say you like something, Hindi uses the dative: \"मुझे पसंद है\" (literally \"to me it is pleasing\"). \"मुझे संगीत पसंद है\" = I like music. With an infinitive verb: \"मुझे पढ़ना पसंद है\" (I like reading). The negation is formed with \"नहीं\": \"मुझे यह पसंद नहीं है\" (I don't like that). To ask, you say \"क्या आपको ... पसंद है?\" (do you like ... ?).",
      examples: [
        { target: "मुझे संगीत पसंद है।", roman: "Mujhe saṁgīt pasand hai.", fr: "J'aime la musique.", en: "I like music." },
        { target: "मुझे पढ़ना पसंद है।", roman: "Mujhe paṛhnā pasand hai.", fr: "J'aime lire.", en: "I like reading." },
        { target: "क्या आपको क्रिकेट पसंद है?", roman: "Kyā āpko kriket pasand hai?", fr: "Aimez-vous le cricket ?", en: "Do you like cricket?" },
        { target: "मुझे यह पसंद नहीं है।", roman: "Mujhe yah pasand nahīṁ hai.", fr: "Je n'aime pas ça.", en: "I don't like that." },
      ],
      vocab: [
        { target: "मुझे", roman: "mujhe", fr: "à moi / moi", en: "to me / me" },
        { target: "पसंद है", roman: "pasand hai", fr: "j'aime (est agréable)", en: "I like (is pleasing)" },
        { target: "संगीत", roman: "saṁgīt", fr: "la musique", en: "music" },
        { target: "पढ़ना", roman: "paṛhnā", fr: "lire", en: "to read" },
        { target: "क्रिकेट", roman: "kriket", fr: "le cricket", en: "cricket" },
        { target: "नहीं", roman: "nahīṁ", fr: "non, pas", en: "no, not" },
        { target: "खेलना", roman: "khelnā", fr: "jouer", en: "to play" },
        { target: "यह", roman: "yah", fr: "ceci, ça", en: "this, that" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « j'aime la musique » en hindi ?",
          promptEn: "How do you say \"I like music\" in Hindi?",
          options: ["मुझे संगीत पसंद है।", "मैं संगीत हूँ।", "संगीत मुझे है।", "मुझे संगीत नहीं है।"],
          accept: ["मुझे संगीत पसंद है।"],
          explain: "La structure est « मुझे ... पसंद है » = « à moi ... est agréable ». « मैं संगीत हूँ » (je suis musique) est faux.",
          explainEn: "The structure is \"मुझे ... पसंद है\" = \"to me ... is pleasing\". \"मैं संगीत हूँ\" (I am music) is wrong.",
        },
        {
          prompt: "Complétez : « Je n'aime pas ça » → « मुझे यह पसंद ___ है ».",
          promptEn: "Complete: \"I don't like that\" → \"Mujhe yah pasand ___ hai\".",
          accept: ["नहीं"],
          explain: "La négation se place avant « है » : « पसंद नहीं है » = « ne ... pas aimé ».",
          explainEn: "The negation comes before \"है\": \"पसंद नहीं है\" = \"not liked\". The negation नहीं negates the verb.",
        },
        {
          prompt: "Complétez : « Aimez-vous le cricket ? » → « क्या ___ क्रिकेट पसंद है? ».",
          promptEn: "Complete: \"Do you like cricket?\" → \"Kyā ___ kriket pasand hai?\".",
          options: ["आपको", "मुझे", "आप", "तुम"],
          accept: ["आपको"],
          explain: "Le datif de « आप » (vous) est « आपको ». « क्या आपको...पसंद है? » = « aimez-vous... ? ».",
          explainEn: "The dative of \"आप\" (you) is \"आपको\". \"क्या आपको...पसंद है?\" = \"do you like...?\".",
        },
      ],
    },
    {
      number: 6,
      slug: "hi-06",
      title: "La famille et les personnes",
      titleEn: "Family and people",
      summary: "Le vocabulaire de la famille (परिवार) : père, mère, frère, sœur, et les liens de parenté.",
      summaryEn: "Family vocabulary (परिवार): father, mother, brother, sister, and kinship relations.",
      grammar: [
        "परिवार (parivār : famille)",
        "मेरा / मेरी (mon/ma selon le genre)",
        "वह ... है, वे ... हैं (il/elle est, ils sont)",
      ],
      explanation:
        "Le possessif « मेरा » s'accorde en genre avec le nom : « मेरा पिता » (mon père, masculin) mais « मेरी माँ » (ma mère, féminin). Les membres de la famille : « पिता » (père), « माता/माँ » (mère), « भाई » (frère), « बहन » (sœur), « बेटा » (fils), « बेटी » (fille). Pour présenter sa famille : « यह मेरा भाई है » (c'est mon frère).",
      explanationEn:
        "The possessive \"मेरा\" agrees in gender with the noun: \"मेरा पिता\" (my father, masculine) but \"मेरी माँ\" (my mother, feminine). Family members: \"पिता\" (father), \"माता/माँ\" (mother), \"भाई\" (brother), \"बहन\" (sister), \"बेटा\" (son), \"बेटी\" (daughter). To introduce your family: \"यह मेरा भाई है\" (this is my brother).",
      examples: [
        { target: "यह मेरी माँ है।", roman: "Yah merī māṁ hai.", fr: "C'est ma mère.", en: "This is my mother." },
        { target: "मेरे दो भाई हैं।", roman: "Mere do bhāī haiṁ.", fr: "J'ai deux frères.", en: "I have two brothers." },
        { target: "मेरा पिता डॉक्टर है।", roman: "Merā pitā ḍākṭar hai.", fr: "Mon père est médecin.", en: "My father is a doctor." },
        { target: "यह मेरी बहन है।", roman: "Yah merī bahan hai.", fr: "C'est ma sœur.", en: "This is my sister." },
      ],
      vocab: [
        { target: "परिवार", roman: "parivār", fr: "la famille", en: "family" },
        { target: "पिता", roman: "pitā", fr: "père", en: "father" },
        { target: "माँ", roman: "māṁ", fr: "mère", en: "mother" },
        { target: "भाई", roman: "bhāī", fr: "frère", en: "brother" },
        { target: "बहन", roman: "bahan", fr: "sœur", en: "sister" },
        { target: "बेटा", roman: "beṭā", fr: "fils", en: "son" },
        { target: "बेटी", roman: "beṭī", fr: "fille", en: "daughter" },
        { target: "मेरा / मेरी", roman: "merā / merī", fr: "mon / ma", en: "my (masc. / fem.)" },
      ],
      exercises: [
        {
          prompt: "Complétez : « C'est ma mère » → « यह ___ माँ है ».",
          promptEn: "Complete: \"This is my mother\" → \"Yah ___ māṁ hai\".",
          options: ["मेरी", "मेरा", "मेरे", "हमारा"],
          accept: ["मेरी"],
          explain: "« माँ » est féminin, donc le possessif est « मेरी » (ma), pas « मेरा » (masculin).",
          explainEn: "\"माँ\" is feminine, so the possessive is \"मेरी\" (my), not \"मेरा\" (masculine).",
        },
        {
          prompt: "Comment dit-on « frère » et « sœur » en hindi ?",
          promptEn: "How do you say \"brother\" and \"sister\" in Hindi?",
          options: ["भाई et बहन", "पिता et माँ", "बेटा et बेटी", "दादा et दादी"],
          accept: ["भाई et बहन"],
          explain: "« भाई » = frère, « बहन » = sœur. « पिता/माँ » = père/mère, « बेटा/बेटी » = fils/fille.",
          explainEn: "\"भाई\" = brother, \"बहन\" = sister. \"पिता/माँ\" = father/mother, \"बेटा/बेटी\" = son/daughter.",
        },
        {
          prompt: "Complétez : « Mon père est médecin » → « ___ पिता डॉक्टर है ».",
          promptEn: "Complete: \"My father is a doctor\" → \"___ pitā ḍākṭar hai\".",
          accept: ["मेरा"],
          explain: "« पिता » (père) est masculin, donc le possessif « मेरा » (mon) s'emploie au masculin.",
          explainEn: "\"पिता\" (father) is masculine, so the masculine possessive \"मेरा\" (my) is used.",
        },
      ],
    },
    {
      number: 7,
      slug: "hi-07",
      title: "Le travail et le bureau",
      titleEn: "Work and the office",
      summary: "Parler de son poste, de son entreprise et de ses activités au bureau (काम, कार्यालय).",
      summaryEn: "Talking about your job, your company and your office activities (काम, कार्यालय).",
      grammar: [
        "मैं ... में काम करता हूँ (je travaille dans ...)",
        "मेरी कंपनी, मेरा कार्यालय (mon entreprise, mon bureau)",
        "संगठन et विभाग (organisation, département)",
      ],
      explanation:
        "Pour dire où l'on travaille : « मैं एक कंपनी में काम करता हूँ » (je travaille dans une entreprise). « कार्यालय » signifie « bureau » (le lieu), « काम » le « travail ». On dit « मैं विपणन विभाग में हूँ » (je suis dans le département marketing). Pour le poste : « मैं प्रबंधक हूँ » (je suis manager) ou « मैं डेवलपर के रूप में काम करता हूँ » (je travaille comme développeur).",
      explanationEn:
        "To say where you work: \"मैं एक कंपनी में काम करता हूँ\" (I work in a company). \"कार्यालय\" means \"office\" (the place), \"काम\" the \"work\". You say \"मैं विपणन विभाग में हूँ\" (I am in the marketing department). For your position: \"मैं प्रबंधक हूँ\" (I am a manager) or \"मैं डेवलपर के रूप में काम करता हूँ\" (I work as a developer).",
      examples: [
        { target: "मैं एक कंपनी में काम करता हूँ।", roman: "Maiṁ ek kampanī meṁ kām kartā hūṁ.", fr: "Je travaille dans une entreprise.", en: "I work in a company." },
        { target: "मेरा कार्यालय दिल्ली में है।", roman: "Merā kāryālay Dillī meṁ hai.", fr: "Mon bureau est à Delhi.", en: "My office is in Delhi." },
        { target: "मैं डेवलपर के रूप में काम करता हूँ।", roman: "Maiṁ ḍevalpar ke rūp meṁ kām kartā hūṁ.", fr: "Je travaille comme développeur.", en: "I work as a developer." },
        { target: "मैं विपणन विभाग में हूँ।", roman: "Maiṁ vipaṇan vibhāg meṁ hūṁ.", fr: "Je suis dans le département marketing.", en: "I am in the marketing department." },
      ],
      vocab: [
        { target: "काम", roman: "kām", fr: "le travail", en: "work" },
        { target: "कार्यालय", roman: "kāryālay", fr: "le bureau (lieu)", en: "office" },
        { target: "कंपनी", roman: "kampanī", fr: "l'entreprise", en: "company" },
        { target: "में काम करता हूँ", roman: "meṁ kām kartā hūṁ", fr: "je travaille dans", en: "I work in" },
        { target: "विभाग", roman: "vibhāg", fr: "département", en: "department" },
        { target: "प्रबंधक", roman: "prabandhak", fr: "manager, gestionnaire", en: "manager" },
        { target: "डेवलपर", roman: "ḍevalpar", fr: "développeur", en: "developer" },
        { target: "मीटिंग", roman: "mīṭiṁg", fr: "réunion", en: "meeting" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Je travaille dans une entreprise » → « मैं एक कंपनी ___ काम करता हूँ ».",
          promptEn: "Complete: \"I work in a company\" → \"Maiṁ ek kampanī ___ kām kartā hūṁ\".",
          accept: ["में"],
          explain: "La postposition « में » signifie « dans, à l'intérieur de » : « कंपनी में » = « dans l'entreprise ».",
          explainEn: "The postposition \"में\" means \"in, inside\": \"कंपनी में\" = \"in the company\".",
        },
        {
          prompt: "Que signifie « कार्यालय » ?",
          promptEn: "What does \"कार्यालय\" mean?",
          options: ["le bureau (lieu)", "le travail", "l'entreprise", "la réunion"],
          accept: ["le bureau (lieu)"],
          explain: "« कार्यालय » = le bureau en tant que lieu de travail. « काम » = le travail, « कंपनी » = l'entreprise.",
          explainEn: "\"कार्यालय\" = the office as a workplace. \"काम\" = work, \"कंपनी\" = company.",
        },
        {
          prompt: "Comment dites-vous « je suis dans le département marketing » ?",
          promptEn: "How do you say \"I am in the marketing department\"?",
          options: ["मैं विपणन विभाग में हूँ।", "मैं कंपनी में हूँ।", "मैं कार्यालय में हूँ।", "मैं मीटिंग में हूँ।"],
          accept: ["मैं विपणन विभाग में हूँ।"],
          explain: "« विपणन » = marketing, « विभाग » = département. « मैं विपणन विभाग में हूँ » = « je suis dans le département marketing ».",
          explainEn: "\"विपणन\" = marketing, \"विभाग\" = department. \"मैं विपणन विभाग में हूँ\" = \"I am in the marketing department\".",
        },
      ],
    },
    {
      number: 8,
      slug: "hi-08",
      title: "Faire des achats et commander",
      titleEn: "Shopping and ordering",
      summary: "Acheter au marché (बाज़ार) et commander au restaurant : prix, quantités et phrases polies.",
      summaryEn: "Shopping at the market (बाज़ार) and ordering at the restaurant: prices, quantities and polite phrases.",
      grammar: [
        "कितने का है? (combien ça coûte ?)",
        "मुझे ... चाहिए (je voudrais ...)",
        "Politese : कृपया (kṛpayā : s'il vous plaît), धन्यवाद (merci)",
      ],
      explanation:
        "Au marché, on demande le prix avec « यह कितने का है? » (combien ça coûte ?). Pour commander, on emploie « मुझे ... चाहिए » (je voudrais ... , littéralement « il me faut ») : « मुझे एक चाय चाहिए » (je voudrais un thé). Les formules de politesse : « कृपया » (s'il vous plaît) et « धन्यवाद » (merci). Les nombres s'emploient avec les objets : « एक » (un), « दो » (deux), « तीन » (trois).",
      explanationEn:
        "At the market you ask the price with \"यह कितने का है?\" (how much is this?). To order, you use \"मुझे ... चाहिए\" (I would like ..., literally \"it is needed for me\"): \"मुझे एक चाय चाहिए\" (I would like a tea). Polite phrases: \"कृपया\" (please) and \"धन्यवाद\" (thank you). Numbers are used with objects: \"एक\" (one), \"दो\" (two), \"तीन\" (three).",
      examples: [
        { target: "यह कितने का है?", roman: "Yah kitne kā hai?", fr: "Combien ça coûte ?", en: "How much is this?" },
        { target: "मुझे एक चाय चाहिए।", roman: "Mujhe ek cāy cāhie.", fr: "Je voudrais un thé.", en: "I would like a tea." },
        { target: "कृपया, एक किलो सेब दीजिए।", roman: "Kṛpayā, ek kilo seb dījie.", fr: "S'il vous plaît, donnez-moi un kilo de pommes.", en: "Please, give me a kilo of apples." },
        { target: "धन्यवाद, बहुत अच्छा है।", roman: "Dhanyavād, bahut acchā hai.", fr: "Merci, c'est très bon.", en: "Thank you, it's very good." },
      ],
      vocab: [
        { target: "बाज़ार", roman: "bāzār", fr: "le marché", en: "market" },
        { target: "कितने का", roman: "kitne kā", fr: "combien (prix)", en: "how much (price)" },
        { target: "चाहिए", roman: "cāhie", fr: "il faut / je voudrais", en: "is needed / I would like" },
        { target: "कृपया", roman: "kṛpayā", fr: "s'il vous plaît", en: "please" },
        { target: "धन्यवाद", roman: "dhanyavād", fr: "merci", en: "thank you" },
        { target: "चाय", roman: "cāy", fr: "le thé", en: "tea" },
        { target: "सेब", roman: "seb", fr: "la pomme", en: "apple" },
        { target: "किलो", roman: "kilo", fr: "le kilo", en: "kilo" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Je voudrais un thé » → « मुझे एक ___ चाहिए ».",
          promptEn: "Complete: \"I would like a tea\" → \"Mujhe ek ___ cāhie\".",
          options: ["चाय", "सेब", "बाज़ार", "पैसा"],
          accept: ["चाय"],
          explain: "« चाय » = thé. « मुझे एक चाय चाहिए » = « je voudrais un thé ». Le verbe चाहिए exprime le besoin/le souhait.",
          explainEn: "\"चाय\" = tea. \"मुझे एक चाय चाहिए\" = \"I would like a tea\". The verb चाहिए expresses need/wish.",
        },
        {
          prompt: "Comment demander « combien ça coûte ? » en hindi ?",
          promptEn: "How do you ask \"how much is this?\" in Hindi?",
          options: ["यह कितने का है?", "यह कौन है?", "यह कहाँ है?", "यह कब है?"],
          accept: ["यह कितने का है?"],
          explain: "« कितने का » se réfère au prix. « कौन » = qui, « कहाँ » = où, « कब » = quand, « कितना » = combien.",
          explainEn: "\"कितने का\" refers to price. \"कौन\" = who, \"कहाँ\" = where, \"कब\" = when, \"कितना\" = how much.",
        },
        {
          prompt: "Complétez : « Merci, c'est très bon » → « ___, बहुत अच्छा है ».",
          promptEn: "Complete: \"Thank you, it's very good\" → \"___, bahut acchā hai\".",
          accept: ["धन्यवाद"],
          explain: "« धन्यवाद » = merci. « बहुत अच्छा » = « très bon, très bien ». C'est une formule de remerciement courante.",
          explainEn: "\"धन्यवाद\" = thank you. \"बहुत अच्छा\" = \"very good\". This is a common thanks formula.",
        },
      ],
    },
    {
      number: 9,
      slug: "hi-09",
      title: "Le temps, les saisons et l'heure",
      titleEn: "Weather, seasons and time",
      summary: "Parler de la météo, des quatre saisons et de l'heure, avec « बजे » (heures) et « कितने बजे » (à quelle heure).",
      summaryEn: "Talking about the weather, the four seasons and the time, with \"बजे\" (hours) and \"कितने बजे\" (at what time).",
      grammar: [
        "आज मौसम कैसा है? (quel temps fait-il ?)",
        "मौसम et ऋतु (temps / saison)",
        "बजे (heures) et कितने बजे? (à quelle heure ?)",
      ],
      explanation:
        "Pour parler de la météo : « आज मौसम कैसा है? » (quel temps fait-il aujourd'hui ?) et « आज गर्मी है » (il fait chaud aujourd'hui). Les quatre saisons : « ग्रीष्म » (été), « वर्षा » (mousson/pluies), « शरद » (automne), « शीत » (hiver). Pour l'heure, « बजे » marque l'heure pleine : « तीन बजे » (trois heures), et on demande « कितने बजे हैं? » (quelle heure est-il ?).",
      explanationEn:
        "To talk about the weather: \"आज मौसम कैसा है?\" (how is the weather today?) and \"आज गर्मी है\" (it is hot today). The four seasons: \"ग्रीष्म\" (summer), \"वर्षा\" (monsoon/rains), \"शरद\" (autumn), \"शीत\" (winter). For time, \"बजे\" marks the full hour: \"तीन बजे\" (three o'clock), and you ask \"कितने बजे हैं?\" (what time is it?).",
      examples: [
        { target: "आज मौसम कैसा है?", roman: "Āj mausam kaisā hai?", fr: "Quel temps fait-il aujourd'hui ?", en: "How is the weather today?" },
        { target: "आज बहुत गर्मी है।", roman: "Āj bahut garmī hai.", fr: "Il fait très chaud aujourd'hui.", en: "It is very hot today." },
        { target: "अभी तीन बजे हैं।", roman: "Abhī tīn baje haiṁ.", fr: "Il est trois heures.", en: "It is three o'clock now." },
        { target: "सर्दियों में बर्फ पड़ती है।", roman: "Sardiyoṁ meṁ barph paṛtī hai.", fr: "En hiver, il neige.", en: "In winter, it snows." },
      ],
      vocab: [
        { target: "मौसम", roman: "mausam", fr: "le temps, le climat", en: "weather" },
        { target: "गर्मी", roman: "garmī", fr: "la chaleur", en: "heat" },
        { target: "सर्दी", roman: "sardī", fr: "le froid / l'hiver", en: "cold / winter" },
        { target: "बारिश", roman: "bāriś", fr: "la pluie", en: "rain" },
        { target: "सर्दी (ऋतु)", roman: "sardī (ṛtu)", fr: "l'hiver (saison)", en: "winter (season)" },
        { target: "ग्रीष्म", roman: "grīṣma", fr: "l'été", en: "summer" },
        { target: "बजे", roman: "baje", fr: "heures (pleines)", en: "o'clock" },
        { target: "कितने बजे", roman: "kitne baje", fr: "à quelle heure", en: "at what time" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Il est trois heures » → « अभी ___ बजे हैं ».",
          promptEn: "Complete: \"It is three o'clock\" → \"Abhī ___ baje haiṁ\".",
          options: ["तीन", "दो", "पाँच", "एक"],
          accept: ["तीन"],
          explain: "« तीन बजे » = trois heures. La question indique « अभी » (maintenant) et la réponse correcte est « तीन » (trois).",
          explainEn: "\"तीन बजे\" = three o'clock. The question says \"अभी\" (now) and the correct answer is \"तीन\" (three).",
        },
        {
          prompt: "Comment dit-on « l'été » (saison) en hindi ?",
          promptEn: "How do you say \"summer\" (season) in Hindi?",
          options: ["ग्रीष्म", "शीत", "वर्षा", "शरद"],
          accept: ["ग्रीष्म"],
          explain: "« ग्रीष्म » = été, « शीत » = hiver, « वर्षा » = mousson, « शरद » = automne.",
          explainEn: "\"ग्रीष्म\" = summer, \"शीत\" = winter, \"वर्षा\" = monsoon, \"शरद\" = autumn.",
        },
        {
          prompt: "Complétez : « Quel temps fait-il aujourd'hui ? » → « आज मौसम ___ है? ».",
          promptEn: "Complete: \"How is the weather today?\" → \"Āj mausam ___ hai?\".",
          accept: ["कैसा"],
          explain: "« कैसा » signifie « comment, quel genre ». « आज मौसम कैसा है? » = « quel temps fait-il aujourd'hui ? ».",
          explainEn: "\"कैसा\" means \"how, what kind\". \"आज मौसम कैसा है?\" = \"how is the weather today?\".",
        },
      ],
    },
    {
      number: 10,
      slug: "hi-10",
      title: "Entretien : présente-toi et ton parcours",
      titleEn: "Interview: introduce yourself and your background",
      summary: "Préparer un entretien : se présenter, raconter son parcours d'études et d'expérience professionnelle.",
      summaryEn: "Preparing for an interview: introducing yourself, recounting your studies and professional experience.",
      grammar: [
        "मेरा नाम ... है (je m'appelle ...)",
        "मैंने ... किया है (j'ai fait ..., passé)",
        "मुझे ... का अनुभव है (j'ai de l'expérience en ...)",
      ],
      explanation:
        "Lors d'un entretien, on se présente clairement : « मेरा नाम डैनियल है » (je m'appelle Daniel), « मैं एक डेवलपर हूँ » (je suis développeur). Pour le parcours on emploie « मैंने ... किया है » (j'ai fait ...) : « मैंने कंप्यूटर विज्ञान में पढ़ाई की है » (j'ai étudié l'informatique). Pour l'expérience : « मुझे तीन साल का अनुभव है » (j'ai trois ans d'expérience).",
      explanationEn:
        "During an interview you introduce yourself clearly: \"मेरा नाम डैनियल है\" (my name is Daniel), \"मैं एक डेवलपर हूँ\" (I am a developer). For your background you use \"मैंने ... किया है\" (I have done ...): \"मैंने कंप्यूटर विज्ञान में पढ़ाई की है\" (I studied computer science). For experience: \"मुझे तीन साल का अनुभव है\" (I have three years of experience).",
      examples: [
        { target: "मेरा नाम डैनियल है।", roman: "Merā nām Ḍainiyal hai.", fr: "Je m'appelle Daniel.", en: "My name is Daniel." },
        { target: "मैंने कंप्यूटर विज्ञान में पढ़ाई की है।", roman: "Maiṁne kampyūṭar vijñān meṁ paṛhāī kī hai.", fr: "J'ai étudié l'informatique.", en: "I studied computer science." },
        { target: "मुझे तीन साल का अनुभव है।", roman: "Mujhe tīn sāl kā anubhav hai.", fr: "J'ai trois ans d'expérience.", en: "I have three years of experience." },
        { target: "मैंने पाँच साल काम किया है।", roman: "Maiṁne pāṁc sāl kām kiyā hai.", fr: "J'ai travaillé cinq ans.", en: "I have worked for five years." },
      ],
      vocab: [
        { target: "अपना परिचय", roman: "apanā paricay", fr: "se présenter", en: "introduce yourself" },
        { target: "पढ़ाई", roman: "paṛhāī", fr: "les études", en: "studies" },
        { target: "अनुभव", roman: "anubhav", fr: "l'expérience", en: "experience" },
        { target: "साल", roman: "sāl", fr: "l'année", en: "year" },
        { target: "कंप्यूटर विज्ञान", roman: "kampyūṭar vijñān", fr: "l'informatique", en: "computer science" },
        { target: "मैंने", roman: "maiṁne", fr: "j'ai (ergatif)", en: "I (agent)" },
        { target: "किया है", roman: "kiyā hai", fr: "j'ai fait", en: "I have done" },
        { target: "पर", roman: "par", fr: "sur, à", en: "on, at" },
      ],
      exercises: [
        {
          prompt: "Complétez : « J'ai trois ans d'expérience » → « मुझे तीन साल ___ अनुभव है ».",
          promptEn: "Complete: \"I have three years of experience\" → \"Mujhe tīn sāl ___ anubhav hai\".",
          accept: ["का"],
          explain: "« का » marque ici le génitif : « तीन साल का अनुभव » = « l'expérience de trois ans ». Le possesseur précède l'objet.",
          explainEn: "\"का\" here marks the genitive: \"तीन साल का अनुभव\" = \"three years of experience\". The possessor precedes the object.",
        },
        {
          prompt: "Comment dit-on « j'ai étudié l'informatique » ?",
          promptEn: "How do you say \"I studied computer science\"?",
          options: ["मैंने कंप्यूटर विज्ञान में पढ़ाई की है।", "मैं कंप्यूटर हूँ।", "मैंने काम किया है।", "मुझे अनुभव है।"],
          accept: ["मैंने कंप्यूटर विज्ञान में पढ़ाई की है।"],
          explain: "« मैंने ... पढ़ाई की है » = « j'ai fait des études de ... ». « कंप्यूटर विज्ञान » = informatique. C'est la phrase correcte.",
          explainEn: "\"मैंने ... पढ़ाई की है\" = \"I did studies in ...\". \"कंप्यूटर विज्ञान\" = computer science. This is the correct sentence.",
        },
        {
          prompt: "Complétez : « Je m'appelle Daniel » → « ___ नाम डैनियल है ».",
          promptEn: "Complete: \"My name is Daniel\" → \"___ nām Ḍainiyal hai\".",
          options: ["मेरा", "तेरा", "उसका", "हमारा"],
          accept: ["मेरा"],
          explain: "« मेरा नाम » = « mon nom ». C'est la formule standard de présentation avec le possessif मेरा.",
          explainEn: "\"मेरा नाम\" = \"my name\". This is the standard introduction formula with the possessive मेरा.",
        },
      ],
      interview: [
        {
          question: "अपना परिचय और शैक्षिक पृष्ठभूमि दीजिए।",
          roman: "Apanā paricay aur śaikṣik pṛṣṭhabhūmi dījie.",
          fr: "Présentez-vous et parlez de votre parcours scolaire.",
          en: "Introduce yourself and talk about your educational background.",
          modelFr: "Je m'appelle Daniel, j'ai étudié l'informatique et j'ai trois ans d'expérience en développement.",
          modelEn: "My name is Daniel, I studied computer science and I have three years of experience in development.",
          accept: ["मेरा नाम डैनियल है", "मैंने कंप्यूटर विज्ञान में पढ़ाई की है", "मुझे तीन साल का अनुभव है", "मैं एक डेवलपर हूँ"],
        },
      ],
    },
    {
      number: 11,
      slug: "hi-11",
      title: "Entretien : atouts, faiblesses, motivation",
      titleEn: "Interview: strengths, weaknesses, motivation",
      summary: "Répondre avec confiance aux questions sur vos atouts, vos points faibles et votre motivation pour l'entreprise.",
      summaryEn: "Answering confidently the questions about your strengths, weaknesses and motivation for the company.",
      grammar: [
        "मेरी ताकत (ma force / mon atout)",
        "मेरी कमज़ोरी (ma faiblesse)",
        "मुझे ... पसंद है क्योंकि ... (j'aime ... parce que ...)",
      ],
      explanation:
        "Pour les atouts : « मेरी सबसे बड़ी ताकत यह है कि मैं कड़ी मेहनत करता हूँ » (ma plus grande force est que je travaille dur). Pour les faiblesses : « मेरी एक कमज़ोरी यह है कि ... » (un de mes points faibles est que ...). Pour la motivation : « मैं आपकी कंपनी को चुनता हूँ क्योंकि ... » (je choisis votre entreprise parce que ...). On relie les idées avec « क्योंकि » (parce que).",
      explanationEn:
        "For strengths: \"मेरी सबसे बड़ी ताकत यह है कि मैं कड़ी मेहनत करता हूँ\" (my greatest strength is that I work hard). For weaknesses: \"मेरी एक कमज़ोरी यह है कि ...\" (one of my weaknesses is that ...). For motivation: \"मैं आपकी कंपनी को चुनता हूँ क्योंकि ...\" (I choose your company because ...). You link ideas with \"क्योंकि\" (because).",
      examples: [
        { target: "मेरी सबसे बड़ी ताकत है कड़ी मेहनत।", roman: "Merī sabase baṛī tākat hai kaṛī mehanat.", fr: "Ma plus grande force est le travail acharné.", en: "My greatest strength is hard work." },
        { target: "मेरी एक कमज़ोरी यह है कि मैं बहुत बोलता हूँ।", roman: "Merī ek kamzorī yah hai ki maiṁ bahut boltā hūṁ.", fr: "Un de mes points faibles est que je parle trop.", en: "One of my weaknesses is that I talk too much." },
        { target: "मैं आपकी कंपनी को चुनता हूँ क्योंकि यह बहुत अच्छी है।", roman: "Maiṁ āpkī kampanī ko cuntā hūṁ kyōṁki yah bahut acchī hai.", fr: "Je choisis votre entreprise parce qu'elle est très bonne.", en: "I choose your company because it is very good." },
        { target: "मुझे चुनौतियाँ पसंद हैं।", roman: "Mujhe cautātiyāṁ pasand haiṁ.", fr: "J'aime les défis.", en: "I like challenges." },
      ],
      vocab: [
        { target: "ताकत", roman: "tākat", fr: "la force, l'atout", en: "strength" },
        { target: "कमज़ोरी", roman: "kamzorī", fr: "la faiblesse", en: "weakness" },
        { target: "कड़ी मेहनत", roman: "kaṛī mehanat", fr: "le travail acharné", en: "hard work" },
        { target: "क्योंकि", roman: "kyōṁki", fr: "parce que", en: "because" },
        { target: "चुनता हूँ", roman: "cuntā hūṁ", fr: "je choisis", en: "I choose" },
        { target: "आपकी कंपनी", roman: "āpkī kampanī", fr: "votre entreprise", en: "your company" },
        { target: "चुनौती", roman: "cautātī", fr: "le défi", en: "challenge" },
        { target: "बड़ा / सबसे बड़ा", roman: "baṛā / sabase baṛā", fr: "grand / le plus grand", en: "big / biggest" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Parce que » en hindi se dit ___.",
          promptEn: "Complete: \"Because\" in Hindi is ___.",
          options: ["क्योंकि", "क्यों", "कब", "कौन"],
          accept: ["क्योंकि"],
          explain: "« क्योंकि » = parce que. « क्यों » = pourquoi, « कब » = quand, « कौन » = qui.",
          explainEn: "\"क्योंकि\" = because. \"क्यों\" = why, \"कब\" = when, \"कौन\" = who.",
        },
        {
          prompt: "Complétez : « Ma plus grande force » → « मेरी सबसे ___ ताकत ».",
          promptEn: "Complete: \"My greatest strength\" → \"Merī sabase ___ tākat\".",
          accept: ["बड़ी"],
          explain: "« सबसे बड़ी » = « la plus grande ». « ताकत » (force) est féminin, d'où la forme féminine « बड़ी ».",
          explainEn: "\"सबसे बड़ी\" = \"the greatest\". \"ताकत\" (strength) is feminine, hence the feminine form \"बड़ी\".",
        },
        {
          prompt: "Comment dites-vous « j'aime les défis » ?",
          promptEn: "How do you say \"I like challenges\"?",
          options: ["मुझे चुनौतियाँ पसंद हैं।", "मैं पसंद हूँ।", "मुझे पसंद नहीं है।", "मैं चुनौती हूँ।"],
          accept: ["मुझे चुनौतियाँ पसंद हैं।"],
          explain: "« चुनौतियाँ » = défis (pluriel). « मुझे ... पसंद हैं » = « j'aime ... ». C'est la formulation correcte.",
          explainEn: "\"चुनौतियाँ\" = challenges (plural). \"मुझे ... पसंद हैं\" = \"I like ...\". This is the correct phrasing.",
        },
      ],
      interview: [
        {
          question: "आपकी ताकतें और कमज़ोरियाँ क्या हैं?",
          roman: "Āpkī tākateṁ aur kamzoriyāṁ kyā haiṁ?",
          fr: "Quelles sont vos forces et vos faiblesses ?",
          en: "What are your strengths and weaknesses?",
          modelFr: "Ma plus grande force est le travail acharné ; un de mes points faibles est que je suis parfois perfectionniste.",
          modelEn: "My greatest strength is hard work; one of my weaknesses is that I am sometimes a perfectionist.",
          accept: ["मेरी ताकत कड़ी मेहनत है", "मेरी कमज़ोरी यह है", "मैं कड़ी मेहनत करता हूँ", "मैं बहुत बोलता हूँ"],
        },
        {
          question: "आप इस कंपनी को क्यों चुनते हैं?",
          roman: "Āp is kampanī ko kyōṁ cunte haiṁ?",
          fr: "Pourquoi choisissez-vous cette entreprise ?",
          en: "Why do you choose this company?",
          modelFr: "Je choisis cette entreprise parce qu'elle est innovante et que sa culture m'attire.",
          modelEn: "I choose this company because it is innovative and its culture attracts me.",
          accept: ["मैं इस कंपनी को चुनता हूँ", "यह कंपनी बहुत अच्छी है", "मुझे यह कंपनी पसंद है", "यह कंपनी नवीन है"],
        },
      ],
    },
    {
      number: 12,
      slug: "hi-12",
      title: "Entretien : projets, travail d'équipe, gestion du stress",
      titleEn: "Interview: plans, teamwork, stress management",
      summary: "Exprimer vos projets d'avenir, votre capacité à travailler en équipe (टीम) et à gérer le stress.",
      summaryEn: "Expressing your future plans, your ability to work in a team (टीम) and to manage stress.",
      grammar: [
        "मैं चाहता हूँ कि ... (je souhaite que ...)",
        "टीम में काम करना (travailler en équipe)",
        "तनाव का प्रबंधन (la gestion du stress)",
      ],
      explanation:
        "Pour les projets : « मैं चाहता हूँ कि पाँच साल में मैं एक प्रबंधक बनूँ » (je souhaite devenir manager en cinq ans). Le futur s'exprime avec « बनूँगा/बनूँगी » (je deviendrai). Pour le travail d'équipe : « मुझे टीम में काम करना पसंद है » (j'aime travailler en équipe). Pour le stress : « मैं तनाव को संभालता हूँ » (je gère le stress). On pose souvent les questions « पाँच साल बाद आप कहाँ देखते हैं? » (où vous voyez-vous dans cinq ans ?).",
      explanationEn:
        "For plans: \"मैं चाहता हूँ कि पाँच साल में मैं एक प्रबंधक बनूँ\" (I wish to become a manager in five years). The future is expressed with \"बनूँगा/बनूँगी\" (I will become). For teamwork: \"मुझे टीम में काम करना पसंद है\" (I like working in a team). For stress: \"मैं तनाव को संभालता हूँ\" (I handle stress). A common question is \"पाँच साल बाद आप कहाँ देखते हैं?\" (where do you see yourself in five years?).",
      examples: [
        { target: "पाँच साल बाद आप कहाँ देखते हैं?", roman: "Pāṁc sāl bād āp kahām dekhte haiṁ?", fr: "Où vous voyez-vous dans cinq ans ?", en: "Where do you see yourself in five years?" },
        { target: "मैं चाहता हूँ कि मैं एक प्रबंधक बनूँ।", roman: "Maiṁ cāhtā hūṁ ki maiṁ ek prabandhak banūṁ.", fr: "Je souhaite devenir manager.", en: "I wish to become a manager." },
        { target: "मुझे टीम में काम करना पसंद है।", roman: "Mujhe ṭīm meṁ kām karnā pasand hai.", fr: "J'aime travailler en équipe.", en: "I like working in a team." },
        { target: "मैं तनाव को संभालता हूँ।", roman: "Maiṁ tanāv ko saṁbhāltā hūṁ.", fr: "Je gère le stress.", en: "I handle stress." },
      ],
      vocab: [
        { target: "पाँच साल बाद", roman: "pāṁc sāl bād", fr: "dans cinq ans", en: "in five years" },
        { target: "देखते हैं", roman: "dekhte haiṁ", fr: "vous voyez", en: "you see" },
        { target: "बनूँगा", roman: "banūṁgā", fr: "je deviendrai", en: "I will become" },
        { target: "टीम", roman: "ṭīm", fr: "l'équipe", en: "team" },
        { target: "तनाव", roman: "tanāv", fr: "le stress", en: "stress" },
        { target: "संभालता हूँ", roman: "saṁbhāltā hūṁ", fr: "je gère, je m'occupe de", en: "I handle" },
        { target: "चाहता हूँ", roman: "cāhtā hūṁ", fr: "je souhaite, je veux", en: "I wish, I want" },
        { target: "सहयोग", roman: "sahayog", fr: "la coopération", en: "cooperation" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Où vous voyez-vous dans cinq ans ? » → « पाँच साल ___ आप कहाँ देखते हैं? ».",
          promptEn: "Complete: \"Where do you see yourself in five years?\" → \"Pāṁc sāl ___ āp kahām dekhte haiṁ?\".",
          accept: ["बाद"],
          explain: "« बाद » signifie « après » : « पाँच साल बाद » = « dans cinq ans, cinq ans plus tard ». Sans बाद le sens change.",
          explainEn: "\"बाद\" means \"after\": \"पाँच साल बाद\" = \"in five years, five years later\". Without बाद the meaning changes.",
        },
        {
          prompt: "Comment dit-on « travailler en équipe » ?",
          promptEn: "How do you say \"working in a team\"?",
          options: ["टीम में काम करना", "अकेले काम करना", "तनाव में काम करना", "घर पर काम करना"],
          accept: ["टीम में काम करना"],
          explain: "« टीम में काम करना » = « travailler en équipe ». « टीम » = équipe, « काम करना » = travailler.",
          explainEn: "\"टीम में काम करना\" = \"working in a team\". \"टीम\" = team, \"काम करना\" = to work.",
        },
        {
          prompt: "Complétez : « Je gère le stress » → « मैं ___ को संभालता हूँ ».",
          promptEn: "Complete: \"I handle stress\" → \"Maiṁ ___ ko saṁbhāltā hūṁ\".",
          options: ["तनाव", "टीम", "काम", "सहयोग"],
          accept: ["तनाव"],
          explain: "« तनाव » = stress. « मैं तनाव को संभालता हूँ » = « je gère le stress ». La particule « को » marque l'objet direct.",
          explainEn: "\"तनाव\" = stress. \"मैं तनाव को संभालता हूँ\" = \"I handle stress\". The particle \"को\" marks the direct object.",
        },
      ],
      interview: [
        {
          question: "पाँच साल बाद आप खुद को कहाँ देखते हैं?",
          roman: "Pāṁc sāl bād āp khud ko kahām dekhte haiṁ?",
          fr: "Où vous voyez-vous dans cinq ans ?",
          en: "Where do you see yourself in five years?",
          modelFr: "Dans cinq ans, je souhaite devenir manager et diriger une équipe dans cette entreprise.",
          modelEn: "In five years, I wish to become a manager and lead a team in this company.",
          accept: ["मैं एक प्रबंधक बनूँगा", "मैं एक टीम का नेतृत्व करूँगा", "मैं इस कंपनी में रहूँगा", "मुझे आगे बढ़ना है"],
        },
        {
          question: "आप टीम में कैसे काम करते हैं और तनाव को कैसे संभालते हैं?",
          roman: "Āp ṭīm meṁ kaise kām karte haiṁ aur tanāv ko kaise saṁbhālte haiṁ?",
          fr: "Comment travaillez-vous en équipe et comment gérez-vous le stress ?",
          en: "How do you work in a team and how do you manage stress?",
          modelFr: "J'aime la coopération, j'écoute les autres, et je gère le stress en restant organisé et calme.",
          modelEn: "I enjoy cooperation, I listen to others, and I manage stress by staying organized and calm.",
          accept: ["मुझे टीम में काम करना पसंद है", "मैं सहयोग करता हूँ", "मैं तनाव को संभालता हूँ", "मैं शांत रहता हूँ"],
        },
      ],
    },
  ],
};
