import type { LanguageCourse } from "./genericLessons";

export const IT_COURSE: LanguageCourse = {
  code: "it",
  name: "Italien",
  native: "Italiano",
  heroTitle1: { fr: "Apprenez", en: "Learn" },
  heroTitle2: { fr: "l'italien", en: "Italian" },
  heroSubtitle: {
    fr: "Un parcours débutant en douze leçons : salutations, vie quotidienne, travail et préparation à l'entretien d'embauche.",
    en: "A beginner path in twelve lessons: greetings, daily life, work and job interview preparation.",
  },
  lessons: [
    {
      number: 1,
      slug: "it-01",
      title: "Salutare e presentarsi",
      titleEn: "Greetings and introducing yourself",
      summary: "Les salutations et les présentations : dire bonjour, son nom et d'où l'on vient.",
      summaryEn: "Greetings and introductions: saying hello, your name and where you are from.",
      grammar: ["I saluti (ciao, buongiorno)", "Mi chiamo… / Vengo da…", "Il verbo parlare"],
      explanation:
        "En italien, on salue à toute heure avec « Ciao » (salut, familier), et plus formellement avec « Buongiorno » (bonjour) et « Buonasera » (bonsoir). Pour se présenter, on dit « Mi chiamo… » (je m'appelle…), et pour indiquer sa provenance « Vengo da… » (je viens de…). Le verbe parler (parlare) se conjugue : io parlo, tu parli, lui/lei parla. À l'oral, on est très souvent tutoyé, mais dans un entretien on utilise le vouvoiement de politesse avec la forme « Lei ».",
      explanationEn:
        "In Italian you can greet at any time with \"Ciao\" (informal hi), and more formally with \"Buongiorno\" (good morning) and \"Buonasera\" (good evening). To introduce yourself you say \"Mi chiamo…\" (my name is…), and to say where you are from \"Vengo da…\" (I come from…). The verb to speak (parlare) is conjugated: io parlo, tu parli, lui/lei parla. Italians use the informal \"tu\" a lot in speech, but in a job interview you should use the polite form \"Lei\".",
      examples: [
        { target: "Ciao, mi chiamo Marco. Piacere di conoscerti!", fr: "Salut, je m'appelle Marco. Enchanté de te rencontrer !", en: "Hi, my name is Marco. Nice to meet you!" },
        { target: "Buongiorno, vengo da Torino.", fr: "Bonjour, je viens de Turin.", en: "Good morning, I come from Turin." },
        { target: "Buonasera, lei come si chiama?", fr: "Bonsoir, comment vous appelez-vous ?", en: "Good evening, what is your name?" },
        { target: "Io parlo italiano e un po' di inglese.", fr: "Je parle italien et un peu d'anglais.", en: "I speak Italian and a little English." },
      ],
      vocab: [
        { target: "ciao", fr: "salut, bonjour, au revoir", en: "hi, hello, bye" },
        { target: "buongiorno", fr: "bonjour (le matin)", en: "good morning" },
        { target: "buonasera", fr: "bonsoir", en: "good evening" },
        { target: "Mi chiamo…", fr: "je m'appelle…", en: "my name is…" },
        { target: "Vengo da…", fr: "je viens de…", en: "I come from…" },
        { target: "piacere di conoscerti", fr: "enchanté de te rencontrer", en: "nice to meet you" },
        { target: "parlare", fr: "parler", en: "to speak" },
      ],
      exercises: [
        {
          prompt: "Complète : « … , mi chiamo Sara. » pour dire bonjour le matin.",
          promptEn: "Complete: \"…, mi chiamo Sara.\" to say good morning.",
          options: ["Buongiorno", "Bene", "Arrivederci"],
          accept: ["Buongiorno"],
          explain: "« Buongiorno » est le salut du matin ; « Bene » signifie « bien » et « Arrivederci » signifie « au revoir ».",
          explainEn: "\"Buongiorno\" is the morning greeting; \"Bene\" means \"well\" and \"Arrivederci\" means \"goodbye\".",
        },
        {
          prompt: "Traduis en italien : « Je viens de Paris. »",
          promptEn: "Translate into Italian: \"I come from Paris.\"",
          accept: ["Vengo da Parigi"],
          explain: "« Vengo da » = « je viens de », suivi du nom de la ville.",
          explainEn: "\"Vengo da\" means \"I come from\", followed by the city name.",
        },
        {
          prompt: "Choisis la formule de politesse pour un entretien : comment dit-on « vous appelez-vous » ?",
          promptEn: "Choose the polite form for an interview: how do you say \"what is your name\"?",
          options: ["Come si chiama?", "Come ti chiami?", "Come mai?"],
          accept: ["Come si chiama?"],
          explain: "Dans un contexte formel, on emploie « Lei » avec la 3e personne : « Come si chiama? » ; « Come ti chiami? » est le tutoiement familier.",
          explainEn: "In a formal context, use \"Lei\" with the third person: \"Come si chiama?\"; \"Come ti chiami?\" is the informal form.",
        },
      ],
      interview: [
        {
          question: "Buongiorno, può presentarsi brevemente?",
          fr: "Bonjour, pouvez-vous vous présenter brièvement ?",
          en: "Good morning, can you briefly introduce yourself?",
          modelFr: "Je m'appelle Daniel, je suis français et je viens de Lyon. Je parle français, anglais et un peu d'italien.",
          modelEn: "My name is Daniel, I am French and I come from Lyon. I speak French, English and a little Italian.",
          accept: ["Mi chiamo Daniel", "Mi chiamo Daniel e vengo da Lione", "Mi chiamo Daniel e parlo francese e inglese"],
        },
      ],
    },
    {
      number: 2,
      slug: "it-02",
      title: "Origine, nazionalità e professione",
      titleEn: "Origin, nationality and profession",
      summary: "Dire d'où l'on vient, sa nationalité et son métier avec les verbes essere et abitare.",
      summaryEn: "Saying where you are from, your nationality and your job with the verbs essere and abitare.",
      grammar: ["Il verbo essere (sono, è)", "Le nazionalità", "Il verbo abitare"],
      explanation:
        "Le verbe essere (être) est indispensable : « sono italiano » (je suis italien), « lei è francese » (elle est française). Les nationalités s'accordent en genre : italiano/italiana, francese (invariable). Pour dire où l'on vit, on utilise abitare (habiter) : « abito a Milano » (j'habite à Milan). Pour le métier, en italien on n'utilise pas d'article : « sono ingegnere » (je suis ingénieur), jamais « sono un ingegnere » pour présenter sa profession.",
      explanationEn:
        "The verb essere (to be) is essential: \"sono italiano\" (I am Italian), \"lei è francese\" (she is French). Nationalities agree in gender: italiano/italiana, francese (invariable). To say where you live, use abitare (to live): \"abito a Milano\" (I live in Milan). For professions, Italian uses no article: \"sono ingegnere\" (I am an engineer), never \"sono un ingegnere\" when stating your job.",
      examples: [
        { target: "Sono francese, ma vivo in Italia.", fr: "Je suis français, mais je vis en Italie.", en: "I am French, but I live in Italy." },
        { target: "Mio fratello è italiano.", fr: "Mon frère est italien.", en: "My brother is Italian." },
        { target: "Abito a Roma da due anni.", fr: "J'habite à Rome depuis deux ans.", en: "I have been living in Rome for two years." },
        { target: "Sono ingegnere e lavoro a Milano.", fr: "Je suis ingénieur et je travaille à Milan.", en: "I am an engineer and I work in Milan." },
      ],
      vocab: [
        { target: "essere", fr: "être", en: "to be" },
        { target: "italiano / italiana", fr: "italien / italienne", en: "Italian (m/f)" },
        { target: "francese", fr: "français(e)", en: "French" },
        { target: "abitare", fr: "habiter", en: "to live" },
        { target: "ingegnere", fr: "ingénieur", en: "engineer" },
        { target: "medico", fr: "médecin", en: "doctor" },
        { target: "lavorare", fr: "travailler", en: "to work" },
        { target: "a / in", fr: "à (ville) / en, à (pays)", en: "in (city) / in (country)" },
      ],
      exercises: [
        {
          prompt: "Complète : « Io … italiano. » (verbe être)",
          promptEn: "Complete: \"Io … italiano.\" (verb to be)",
          accept: ["sono"],
          explain: "« Sono » est la 1re personne du verbe essere : « je suis ».",
          explainEn: "\"Sono\" is the first person of the verb essere: \"I am\".",
        },
        {
          prompt: "Choisis la bonne forme : comment dit-on « j'habite à Florence » ?",
          promptEn: "Choose the correct form: how do you say \"I live in Florence\"?",
          options: ["Abito a Firenze", "Abito in Firenze", "Abito Firenze"],
          accept: ["Abito a Firenze"],
          explain: "Pour une ville, on utilise la préposition « a » : « abito a Firenze ».",
          explainEn: "For a city, use the preposition \"a\": \"abito a Firenze\".",
        },
        {
          prompt: "Complète la phrase pour dire ta profession : « … architetto. »",
          promptEn: "Complete the sentence to state your profession: \"… architetto.\"",
          accept: ["Sono"],
          explain: "On dit « sono architetto » sans article pour la profession.",
          explainEn: "Say \"sono architetto\" without an article to state a profession.",
        },
      ],
    },
    {
      number: 3,
      slug: "it-03",
      title: "Essere e avere: possesso e descrizione",
      titleEn: "Essere and avere: possession and description",
      summary: "Conjuguer essere et avere pour décrire, posséder et exprimer l'âge.",
      summaryEn: "Conjugating essere and avere to describe, possess and express age.",
      grammar: ["Presente di essere e avere", "Gli aggettivi (grande, piccolo)", "L'età: avere + anni"],
      explanation:
        "Les deux piliers de l'italien sont essere (être) et avere (avoir). Leur présent : essere → io sono, tu sei, lui/lei è ; avere → io ho, tu hai, lui/lei ha. Attention : avoir - hanno (ils ont) et être - sono (ils sont) s'écrivent avec « h » prononcé comme un simple « a ». En italien, l'âge s'exprime avec avere : « ho 30 anni » (j'ai 30 ans), et non avec essere. La possession se dit « ho una macchina » (j'ai une voiture), la description « la casa è grande » (la maison est grande).",
      explanationEn:
        "The two pillars of Italian are essere (to be) and avere (to have). Their present tense: essere → io sono, tu sei, lui/lei è; avere → io ho, tu hai, lui/lei ha. Note that avere - hanno (they have) and essere - sono (they are) are written with an \"h\" that is pronounced like a plain \"a\". Age is expressed with avere: \"ho 30 anni\" (I am 30). Possession is \"ho una macchina\" (I have a car), description is \"la casa è grande\" (the house is big).",
      examples: [
        { target: "Ho un fratello e una sorella.", fr: "J'ai un frère et une sœur.", en: "I have one brother and one sister." },
        { target: "Lei è alta e ha i capelli biondi.", fr: "Elle est grande et a les cheveux blonds.", en: "She is tall and has blond hair." },
        { target: "Quanti anni hai? Ho ventotto anni.", fr: "Quel âge as-tu ? J'ai vingt-huit ans.", en: "How old are you? I am twenty-eight." },
        { target: "Abbiamo un cane molto piccolo.", fr: "Nous avons un très petit chien.", en: "We have a very small dog." },
      ],
      vocab: [
        { target: "ho / hai / ha", fr: "j'ai / tu as / il·elle a", en: "I have / you have / he·she has" },
        { target: "sono / sei / è", fr: "je suis / tu es / il·elle est", en: "I am / you are / he·she is" },
        { target: "gli anni", fr: "l'âge (les années)", en: "age (years)" },
        { target: "grande", fr: "grand, gros", en: "big" },
        { target: "piccolo", fr: "petit", en: "small" },
        { target: "la macchina", fr: "la voiture", en: "the car" },
        { target: "i capelli", fr: "les cheveux", en: "hair" },
      ],
      exercises: [
        {
          prompt: "Complète : « Io … venticinque anni. » (verbe avere)",
          promptEn: "Complete: \"Io … venticinque anni.\" (verb avere)",
          accept: ["ho"],
          explain: "« Ho » est la 1re personne de avere. L'âge se dit « io ho … anni ».",
          explainEn: "\"Ho\" is the first person of avere. Age is \"io ho … anni\".",
        },
        {
          prompt: "Choisis la conjugaison correcte de essere avec « lui » :",
          promptEn: "Choose the correct conjugation of essere with \"lui\":",
          options: ["è", "sei", "siamo"],
          accept: ["è"],
          explain: "À la 3e personne du singulier : « lui è » (il est).",
          explainEn: "Third person singular: \"lui è\" (he is).",
        },
        {
          prompt: "Complète : « Quanti anni … ? Ho trenta anni. »",
          promptEn: "Complete: \"Quanti anni …? Ho trenta anni.\"",
          accept: ["hai"],
          explain: "On demande l'âge avec « Quanti anni hai? » (quel âge as-tu ?).",
          explainEn: "Ask age with \"Quanti anni hai?\" (how old are you?).",
        },
      ],
    },
    {
      number: 4,
      slug: "it-04",
      title: "La routine quotidiana",
      titleEn: "Daily routine",
      summary: "Raconter sa journée : se lever, travailler, manger, se coucher au présent.",
      summaryEn: "Telling your day: getting up, working, eating, going to bed in the present tense.",
      grammar: ["I verbi riflessivi (mi alzo)", "Il presente dei verbi in -are/-ere/-ire", "Le espressioni di tempo"],
      explanation:
        "Pour décrire sa routine, on utilise le présent et les verbes pronominaux : « mi alzo » (je me lève), « mi sveglio » (je me réveille), « mi addormento » (je m'endors). Le présent régulier : lavorare → lavoro, lavori, lavora ; prendere → prendo ; partire → parto. Le pronom réflexif se place avant le verbe : mi, ti, si. Pour lier la journée : « la mattina » (le matin), « il pomeriggio » (l'après-midi), « la sera » (le soir), « di solito » (d'habitude), « poi » (ensuite).",
      explanationEn:
        "To describe your routine, use the present tense and reflexive verbs: \"mi alzo\" (I get up), \"mi sveglio\" (I wake up), \"mi addormento\" (I fall asleep). The regular present: lavorare → lavoro, lavori, lavora; prendere → prendo; partire → parto. The reflexive pronoun goes before the verb: mi, ti, si. To link the day: \"la mattina\" (in the morning), \"il pomeriggio\" (in the afternoon), \"la sera\" (in the evening), \"di solito\" (usually), \"poi\" (then).",
      examples: [
        { target: "Mi alzo alle sette e faccio colazione.", fr: "Je me lève à sept heures et je prends le petit-déjeuner.", en: "I get up at seven and have breakfast." },
        { target: "Di solito lavoro dalle nove alle cinque.", fr: "D'habitude, je travaille de neuf heures à cinq heures.", en: "I usually work from nine to five." },
        { target: "La sera guardo la televisione o leggo.", fr: "Le soir, je regarde la télévision ou je lis.", en: "In the evening I watch TV or read." },
        { target: "Mi addormento verso mezzanotte.", fr: "Je m'endors vers minuit.", en: "I fall asleep around midnight." },
      ],
      vocab: [
        { target: "mi alzo", fr: "je me lève", en: "I get up" },
        { target: "faccio colazione", fr: "je prends le petit-déjeuner", en: "I have breakfast" },
        { target: "lavoro", fr: "je travaille", en: "I work" },
        { target: "la mattina", fr: "le matin", en: "the morning" },
        { target: "il pomeriggio", fr: "l'après-midi", en: "the afternoon" },
        { target: "la sera", fr: "le soir", en: "the evening" },
        { target: "di solito", fr: "d'habitude", en: "usually" },
        { target: "leggere", fr: "lire", en: "to read" },
      ],
      exercises: [
        {
          prompt: "Complète le verbe pronominal : « Io … alle sette. »",
          promptEn: "Complete the reflexive verb: \"Io … alle sette.\"",
          accept: ["mi alzo"],
          explain: "« Alzarsi » se conjugue avec le pronom réflexif : « io mi alzo ».",
          explainEn: "\"Alzarsi\" is conjugated with the reflexive pronoun: \"io mi alzo\".",
        },
        {
          prompt: "Quel verbe signifie « prendre le petit-déjeuner » ?",
          promptEn: "Which phrase means \"to have breakfast\"?",
          options: ["fare colazione", "fare la spesa", "andare a letto"],
          accept: ["fare colazione"],
          explain: "« Fare colazione » = prendre le petit-déjeuner ; « fare la spesa » = faire les courses.",
          explainEn: "\"Fare colazione\" means to have breakfast; \"fare la spesa\" means to do the shopping.",
        },
        {
          prompt: "Complète : « La mattina mi sveglio e … » (je me lève ensuite)",
          promptEn: "Complete: \"La mattina mi sveglio e …\" (then I get up)",
          accept: ["mi alzo"],
          explain: "On dit « mi sveglio e mi alzo » : je me réveille et je me lève.",
          explainEn: "Say \"mi sveglio e mi alzo\": I wake up and I get up.",
        },
      ],
    },
    {
      number: 5,
      slug: "it-05",
      title: "I gusti e i passatempi",
      titleEn: "Tastes and hobbies",
      summary: "Exprimer ses goûts avec mi piace, mi piacciono et le vocabulaire des loisirs.",
      summaryEn: "Expressing tastes with mi piace, mi piacciono and hobby vocabulary.",
      grammar: ["Mi piace + singolare", "Mi piacciono + plurale", "Anche, invece, molto, tanto"],
      explanation:
        "Pour exprimer un goût : « mi piace » (ça me plaît / j'aime) suivi d'un singulier ou d'un infinitif, et « mi piacciono » suivi d'un pluriel : « mi piace la musica », « mi piacciono i film ». « molto » et « tanto » renforcent : « mi piace molto leggere » (j'aime beaucoup lire). Pour comparer : « anche » (aussi), « invece » (par contre), « non mi piace » (je n'aime pas). L'imparfait de description « mi piaceva » apparaît en entretien pour parler de ses anciens goûts.",
      explanationEn:
        "To express a taste: \"mi piace\" (I like) followed by a singular noun or an infinitive, and \"mi piacciono\" followed by a plural noun: \"mi piace la musica\", \"mi piacciono i film\". \"molto\" and \"tanto\" reinforce: \"mi piace molto leggere\" (I really like reading). To compare: \"anche\" (also), \"invece\" (on the other hand), \"non mi piace\" (I don't like). The imperfect \"mi piaceva\" appears in interviews to talk about past tastes.",
      examples: [
        { target: "Mi piace molto la cucina italiana.", fr: "J'aime beaucoup la cuisine italienne.", en: "I really like Italian food." },
        { target: "Mi piacciono i viaggi e la fotografia.", fr: "J'aime les voyages et la photographie.", en: "I like travelling and photography." },
        { target: "Non mi piace alzarmi presto.", fr: "Je n'aime pas me lever tôt.", en: "I don't like getting up early." },
        { target: "Mi piace correre al parco la domenica.", fr: "J'aime courir au parc le dimanche.", en: "I like running in the park on Sundays." },
      ],
      vocab: [
        { target: "mi piace", fr: "j'aime (une chose, une action)", en: "I like (one thing, an action)" },
        { target: "mi piacciono", fr: "j'aime (plusieurs choses)", en: "I like (several things)" },
        { target: "molto / tanto", fr: "beaucoup", en: "very much" },
        { target: "il passatempo", fr: "le passe-temps, le loisir", en: "hobby" },
        { target: "la musica", fr: "la musique", en: "music" },
        { target: "il viaggio", fr: "le voyage", en: "trip, travel" },
        { target: "invece", fr: "par contre, en revanche", en: "on the other hand" },
        { target: "lo sport", fr: "le sport", en: "sport" },
      ],
      exercises: [
        {
          prompt: "Complète avec la bonne forme : « Mi … i libri di storia. » (pluriel)",
          promptEn: "Complete with the correct form: \"Mi … i libri di storia.\" (plural)",
          accept: ["piacciono"],
          explain: "Avec un pluriel (« i libri ») on utilise « mi piacciono ».",
          explainEn: "With a plural noun (\"i libri\") use \"mi piacciono\".",
        },
        {
          prompt: "Comment dit-on « j'aime beaucoup le cinéma » ?",
          promptEn: "How do you say \"I really like cinema\"?",
          options: ["Mi piace molto il cinema", "Mi piacciono molto il cinema", "Mi piace il cinema molto"],
          accept: ["Mi piace molto il cinema"],
          explain: "« Mi piace molto » + singulier : « mi piace molto il cinema ».",
          explainEn: "\"Mi piace molto\" + singular: \"mi piace molto il cinema\".",
        },
        {
          prompt: "Complète : « … mi piace il calcio. » pour dire « moi aussi, oui »... choisis l'adverbe qui veut dire « aussi ».",
          promptEn: "Complete with the adverb meaning \"too\": \"… mi piace il calcio.\"",
          accept: ["Anche"],
          explain: "« Anche » signifie « aussi » : « anche a me piace il calcio ».",
          explainEn: "\"Anche\" means \"too\": \"anche a me piace il calcio\".",
        },
      ],
    },
    {
      number: 6,
      slug: "it-06",
      title: "La famiglia e le persone",
      titleEn: "Family and people",
      summary: "Le vocabulaire de la famille et les adjectifs possessifs (mio, tua, loro).",
      summaryEn: "Family vocabulary and possessive adjectives (mio, tua, loro).",
      grammar: ["I membri della famiglia", "Gli aggettivi possessivi (mio, tua, nostro)", "Descrivere le persone"],
      explanation:
        "Le vocabulaire familial : il padre (le père), la madre (la mère), il figlio/la figlia (le fils/la fille), i fratelli (les frères et sœurs), la nonna (la grand-mère). Les possessifs s'accordent : mio/mia, tuo/tua, suo/sua, nostro/nostra, loro (invariable) : « mio padre » (mon père), « la sua famiglia » (sa famille). Sauf pour les noms de famille et certains titres, l'article défini accompagne le possessif : « la mia famiglia », mais « mia madre » se dit sans article. Pour décrire : « alto/basso » (grand/petit), « giovane/anziano » (jeune/âgé).",
      explanationEn:
        "Family vocabulary: il padre (father), la madre (mother), il figlio/la figlia (son/daughter), i fratelli (siblings), la nonna (grandmother). Possessives agree: mio/mia, tuo/tua, suo/sua, nostro/nostra, loro (invariable): \"mio padre\" (my father), \"la sua famiglia\" (his/her family). Except for family terms and some titles, the definite article accompanies the possessive: \"la mia famiglia\", but \"mia madre\" is said without the article. To describe people: \"alto/basso\" (tall/short), \"giovane/anziano\" (young/elderly).",
      examples: [
        { target: "Mio padre è medico e mia madre è insegnante.", fr: "Mon père est médecin et ma mère est enseignante.", en: "My father is a doctor and my mother is a teacher." },
        { target: "Ho due sorelle e un fratello più piccolo.", fr: "J'ai deux sœurs et un frère plus jeune.", en: "I have two sisters and a younger brother." },
        { target: "La mia nonna abita vicino a noi.", fr: "Ma grand-mère habite près de chez nous.", en: "My grandmother lives near us." },
        { target: "I miei genitori sono italiani.", fr: "Mes parents sont italiens.", en: "My parents are Italian." },
      ],
      vocab: [
        { target: "il padre", fr: "le père", en: "father" },
        { target: "la madre", fr: "la mère", en: "mother" },
        { target: "il figlio / la figlia", fr: "le fils / la fille", en: "son / daughter" },
        { target: "il fratello / la sorella", fr: "le frère / la sœur", en: "brother / sister" },
        { target: "i genitori", fr: "les parents", en: "parents" },
        { target: "la nonna / il nonno", fr: "la grand-mère / le grand-père", en: "grandmother / grandfather" },
        { target: "mio / mia", fr: "mon / ma", en: "my (m/f)" },
        { target: "la moglie / il marito", fr: "la femme / le mari (conjoint)", en: "wife / husband" },
      ],
      exercises: [
        {
          prompt: "Choisis le possessif correct : « … madre è insegnante. »",
          promptEn: "Choose the correct possessive: \"… madre è insegnante.\"",
          options: ["Mia", "Mio", "Miei"],
          accept: ["Mia"],
          explain: "« Madre » est féminin singulier : on dit « mia madre » (sans article).",
          explainEn: "\"Madre\" is feminine singular: say \"mia madre\" (without article).",
        },
        {
          prompt: "Quel mot désigne les « frères et sœurs » ensemble ?",
          promptEn: "Which word means \"siblings\"?",
          options: ["i fratelli", "i genitori", "i cugini"],
          accept: ["i fratelli"],
          explain: "« I fratelli » désigne les frères et sœurs ; « i genitori » = les parents.",
          explainEn: "\"I fratelli\" means siblings; \"i genitori\" means parents.",
        },
        {
          prompt: "Complète : « La … famiglia è molto grande. » (possession de « lui/elle »)",
          promptEn: "Complete: \"La … famiglia è molto grande.\" (his/her possession)",
          accept: ["sua"],
          explain: "« Sua » = sa (féminin singulier, 3e personne) : « la sua famiglia ».",
          explainEn: "\"Sua\" = his/her (feminine singular, 3rd person): \"la sua famiglia\".",
        },
      ],
    },
    {
      number: 7,
      slug: "it-07",
      title: "Il lavoro e l'ufficio",
      titleEn: "Work and the office",
      summary: "Parler de son travail, de son équipe et des tâches de bureau.",
      summaryEn: "Talking about your job, your team and office tasks.",
      grammar: ["I nomi delle professioni", "Il condizionale di cortesia (vorrei)", "Le particelle c'è / ci sono"],
      explanation:
        "Au bureau : « la riunione » (la réunion), « il progetto » (le projet), « il collega/le colleghe » (le·la collègue), « il capo » (le chef). Pour exprimer une volonté polie, on emploie le conditionnel : « vorrei » (je voudrais), « potrei » (je pourrais) : « vorrei lavorare in un team » (je voudrais travailler en équipe). On présente l'existence avec « c'è » (il y a, singulier) et « ci sono » (il y a, pluriel) : « c'è un progetto urgente », « ci sono molte riunioni ». Les professions : amministratore, contabile, sviluppatore, responsabile commerciale.",
      explanationEn:
        "At the office: \"la riunione\" (meeting), \"il progetto\" (project), \"il collega/le colleghe\" (colleague), \"il capo\" (boss). To express a polite wish, use the conditional: \"vorrei\" (I would like), \"potrei\" (I could): \"vorrei lavorare in un team\" (I would like to work in a team). We state existence with \"c'è\" (there is, singular) and \"ci sono\" (there are, plural): \"c'è un progetto urgente\", \"ci sono molte riunioni\". Professions: amministratore (administrator), contabile (accountant), sviluppatore (developer), responsabile commerciale (sales manager).",
      examples: [
        { target: "Lavoro come sviluppatore web a Milano.", fr: "Je travaille comme développeur web à Milan.", en: "I work as a web developer in Milan." },
        { target: "Ci sono molte riunioni questa settimana.", fr: "Il y a beaucoup de réunions cette semaine.", en: "There are many meetings this week." },
        { target: "Vorrei lavorare in un team internazionale.", fr: "Je voudrais travailler dans une équipe internationale.", en: "I would like to work in an international team." },
        { target: "I miei colleghi sono molto disponibili.", fr: "Mes collègues sont très serviables.", en: "My colleagues are very helpful." },
      ],
      vocab: [
        { target: "il lavoro", fr: "le travail", en: "work, job" },
        { target: "l'ufficio", fr: "le bureau", en: "the office" },
        { target: "la riunione", fr: "la réunion", en: "the meeting" },
        { target: "il progetto", fr: "le projet", en: "the project" },
        { target: "il collega", fr: "le collègue", en: "the colleague" },
        { target: "il capo", fr: "le chef, le responsable", en: "the boss" },
        { target: "vorrei", fr: "je voudrais", en: "I would like" },
        { target: "disponibile", fr: "disponible, serviable", en: "available, helpful" },
      ],
      exercises: [
        {
          prompt: "Complète pour être poli : « … un caffè, per favore. » (je voudrais)",
          promptEn: "Complete to be polite: \"… un caffè, per favore.\" (I would like)",
          accept: ["Vorrei"],
          explain: "« Vorrei » est le conditionnel de souhait : « je voudrais ».",
          explainEn: "\"Vorrei\" is the conditional of wish: \"I would like\".",
        },
        {
          prompt: "Comment dit-on « il y a » avec un pluriel ?",
          promptEn: "How do you say \"there are\" with a plural?",
          options: ["ci sono", "c'è", "ce ne è"],
          accept: ["ci sono"],
          explain: "« Ci sono » (il y a) s'emploie avec un pluriel : « ci sono due uffici ».",
          explainEn: "\"Ci sono\" (there are) is used with a plural: \"ci sono due uffici\".",
        },
        {
          prompt: "Complète : « Io … come contabile. » (verbe lavorare, 1re personne)",
          promptEn: "Complete: \"Io … come contabile.\" (verb lavorare, 1st person)",
          accept: ["lavoro"],
          explain: "« Lavoro » est la 1re personne du présent de lavorare.",
          explainEn: "\"Lavoro\" is the first-person present of lavorare.",
        },
      ],
    },
    {
      number: 8,
      slug: "it-08",
      title: "Fare acquisti e ordinare",
      titleEn: "Shopping and ordering",
      summary: "Au marché et au restaurant : demander le prix, commander, payer.",
      summaryEn: "At the market and the restaurant: asking prices, ordering, paying.",
      grammar: ["Quantità e prezzi", "Il verbo prendere per ordinare", "La forma di cortesia posso"],
      explanation:
        "Au marché, on demande le prix avec « Quanto costa? » (combien ça coûte ?, singulier) et « Quanti costano? » (pluriel). Les aliments : il pane (le pain), la frutta (les fruits), la verdura (les légumes), il formaggio (le fromage). Au restaurant, on commande avec « prendere » : « prendo un espresso » ou avec le potentiel poli : « posso avere…? » (puis-je avoir… ?). Pour payer : « il conto, per favore » (l'addition, s'il vous plaît). La quantité : « un chilo di pomodori » (un kilo de tomates), « mezzo litro d'acqua » (un demi-litre d'eau).",
      explanationEn:
        "At the market, ask the price with \"Quanto costa?\" (how much does it cost?, singular) and \"Quanti costano?\" (plural). Foods: il pane (bread), la frutta (fruit), la verdura (vegetables), il formaggio (cheese). At the restaurant, order with \"prendere\": \"prendo un espresso\", or with the polite potential: \"posso avere…?\" (can I have…?). To pay: \"il conto, per favore\" (the bill, please). Quantity: \"un chilo di pomodori\" (a kilo of tomatoes), \"mezzo litro d'acqua\" (half a litre of water).",
      examples: [
        { target: "Quanto costa un chilo di pomodori?", fr: "Combien coûte un kilo de tomates ?", en: "How much does a kilo of tomatoes cost?" },
        { target: "Prendo una pizza margherita e un'acqua minerale.", fr: "Je prends une pizza margherita et une eau minérale.", en: "I'll have a margherita pizza and a mineral water." },
        { target: "Posso avere il conto, per favore?", fr: "Puis-je avoir l'addition, s'il vous plaît ?", en: "Can I have the bill, please?" },
        { target: "Vorrei due etti di prosciutto, per favore.", fr: "Je voudrais deux cents grammes de jambon, s'il vous plaît.", en: "I would like two hundred grams of ham, please." },
      ],
      vocab: [
        { target: "quanto costa?", fr: "combien ça coûte ?", en: "how much is it?" },
        { target: "il conto", fr: "l'addition", en: "the bill" },
        { target: "il pane", fr: "le pain", en: "the bread" },
        { target: "la frutta", fr: "les fruits", en: "the fruit" },
        { target: "il formaggio", fr: "le fromage", en: "the cheese" },
        { target: "prendere", fr: "prendre", en: "to take" },
        { target: "posso avere…?", fr: "puis-je avoir… ?", en: "can I have…?" },
        { target: "per favore", fr: "s'il vous plaît", en: "please" },
      ],
      exercises: [
        {
          prompt: "Choisis la question pour demander un prix (singulier) :",
          promptEn: "Choose the question to ask a price (singular):",
          options: ["Quanto costa?", "Quanti costi?", "Come si paga?"],
          accept: ["Quanto costa?"],
          explain: "« Quanto costa? » = combien ça coûte (une seule chose).",
          explainEn: "\"Quanto costa?\" = how much does it cost (one thing).",
        },
        {
          prompt: "Complète : « Il … , per favore! » (l'addition)",
          promptEn: "Complete: \"Il … , per favore!\" (the bill)",
          accept: ["conto"],
          explain: "Pour payer au restaurant : « il conto, per favore ».",
          explainEn: "To pay at the restaurant: \"il conto, per favore\".",
        },
        {
          prompt: "Complète : « … un cappuccino. » pour commander (verbe prendere, 1re personne)",
          promptEn: "Complete: \"… un cappuccino.\" to order (verb prendere, 1st person)",
          accept: ["Prendo"],
          explain: "« Prendo » = je prends : « prendo un cappuccino ».",
          explainEn: "\"Prendo\" = I take: \"prendo un cappuccino\".",
        },
      ],
    },
    {
      number: 9,
      slug: "it-09",
      title: "Il tempo, le stagioni e l'ora",
      titleEn: "Weather, seasons and the time",
      summary: "Parler de la météo, des saisons et de l'heure avec fare, essere et a che ora.",
      summaryEn: "Talking about weather, seasons and the time with fare, essere and a che ora.",
      grammar: ["Fare + meteo (fa caldo, fa freddo)", "Le stagioni e i mesi", "Che ora è? / A che ora…?"],
      explanation:
        "Pour la météo, on utilise le verbe fare : « fa bel tempo » (il fait beau), « fa caldo » (il fait chaud), « fa freddo » (il fait froid). Le mot « il tempo » signifie à la fois « le temps » (météo) et « le temps » (durée). Les saisons : la primavera, l'estate, l'autunno, l'inverno. Pour l'heure : « Che ora è? » ou « Che ore sono? » (quelle heure est-il ?) ; pour demander un horaire : « A che ora…? » (à quelle heure… ?). Réponses : « è l'una » (il est une heure), « sono le tre » (il est trois heures).",
      explanationEn:
        "For the weather, use the verb fare: \"fa bel tempo\" (the weather is nice), \"fa caldo\" (it is hot), \"fa freddo\" (it is cold). The word \"il tempo\" means both \"weather\" and \"time\". Seasons: la primavera (spring), l'estate (summer), l'autunno (autumn), l'inverno (winter). For the time: \"Che ora è?\" or \"Che ore sono?\" (what time is it?); to ask a schedule: \"A che ora…?\" (at what time…?). Answers: \"è l'una\" (it is one o'clock), \"sono le tre\" (it is three o'clock).",
      examples: [
        { target: "Oggi fa bel tempo, che bella giornata!", fr: "Aujourd'hui il fait beau, quelle belle journée !", en: "The weather is nice today, what a beautiful day!" },
        { target: "In inverno fa freddo e spesso nevica.", fr: "En hiver il fait froid et il neige souvent.", en: "In winter it is cold and it often snows." },
        { target: "Che ore sono? Sono le tre meno un quarto.", fr: "Quelle heure est-il ? Il est trois heures moins le quart.", en: "What time is it? It is a quarter to three." },
        { target: "A che ora inizia la riunione? Alle dieci.", fr: "À quelle heure commence la réunion ? À dix heures.", en: "What time does the meeting start? At ten." },
      ],
      vocab: [
        { target: "fa caldo", fr: "il fait chaud", en: "it is hot" },
        { target: "fa freddo", fr: "il fait froid", en: "it is cold" },
        { target: "la primavera", fr: "le printemps", en: "spring" },
        { target: "l'estate", fr: "l'été", en: "summer" },
        { target: "l'autunno", fr: "l'automne", en: "autumn" },
        { target: "l'inverno", fr: "l'hiver", en: "winter" },
        { target: "che ore sono?", fr: "quelle heure est-il ?", en: "what time is it?" },
        { target: "a che ora?", fr: "à quelle heure ?", en: "at what time?" },
      ],
      exercises: [
        {
          prompt: "Complète pour dire « j'aime l'été » avec la préposition juste : « Mi piace … estate. »",
          promptEn: "Complete to say \"I like summer\" with the right preposition: \"Mi piace … estate.\"",
          accept: ["l'"],
          explain: "Les saisons prennent l'article : « l'estate ».",
          explainEn: "Seasons take the article: \"l'estate\".",
        },
        {
          prompt: "Comment dit-on « il fait chaud » ?",
          promptEn: "How do you say \"it is hot\"?",
          options: ["fa caldo", "fa freddo", "ha caldo"],
          accept: ["fa caldo"],
          explain: "« Fa caldo » = il fait chaud (météo) ; « fa freddo » = il fait froid.",
          explainEn: "\"Fa caldo\" = it is hot (weather); \"fa freddo\" = it is cold.",
        },
        {
          prompt: "Complète la question de l'heure : « Che … sono? »",
          promptEn: "Complete the time question: \"Che … sono?\"",
          accept: ["ore"],
          explain: "« Che ore sono? » est la question usuelle pour l'heure.",
          explainEn: "\"Che ore sono?\" is the usual question for the time.",
        },
      ],
    },
    {
      number: 10,
      slug: "it-10",
      title: "Colloquio: presentati e il tuo percorso",
      titleEn: "Interview: introduce yourself and your background",
      summary: "Structurer sa présentation et raconter son parcours professionnel et scolaire.",
      summaryEn: "Structuring your presentation and telling your professional and academic background.",
      grammar: ["Il passato prossimo (ho studiato, ho lavorato)", "Espressioni di tempo (prima, poi, da… a…)", "Lessico del percorso"],
      explanation:
        "Pour raconter son parcours, on utilise souvent le passé composé (passato prossimo) : « ho studiato » (j'ai étudié), « ho lavorato » (j'ai travaillé), « mi sono laureato/a » (j'ai obtenu mon diplôme). Les marqueurs de temps : « prima » (avant), « poi » (puis), « dopo » (après), « da… a… » (de… à…). On structure la réponse en trois temps : la formation (la laurea), l'expérience (l'esperienza), les compétences (le competenze). Terminer par ce qu'on cherche aujourd'hui : « adesso cerco una nuova opportunità » (maintenant je cherche une nouvelle opportunité).",
      explanationEn:
        "To tell your background, use the present perfect (passato prossimo): \"ho studiato\" (I studied), \"ho lavorato\" (I worked), \"mi sono laureato/a\" (I graduated). Time markers: \"prima\" (before), \"poi\" (then), \"dopo\" (after), \"da… a…\" (from… to…). Structure the answer in three parts: education (la laurea), experience (l'esperienza), skills (le competenze). End with what you are looking for today: \"adesso cerco una nuova opportunità\" (now I am looking for a new opportunity).",
      examples: [
        { target: "Mi sono laureato in economia e poi ho lavorato a Torino.", fr: "J'ai obtenu un diplôme en économie puis j'ai travaillé à Turin.", en: "I graduated in economics and then I worked in Turin." },
        { target: "Ho iniziato come stagista, poi sono diventato contabile.", fr: "J'ai commencé comme stagiaire, puis je suis devenu comptable.", en: "I started as an intern, then I became an accountant." },
        { target: "Ho lavorato in questo settore per cinque anni.", fr: "J'ai travaillé dans ce secteur pendant cinq ans.", en: "I have worked in this field for five years." },
        { target: "Ora cerco una nuova sfida in un'azienda internazionale.", fr: "Maintenant je cherche un nouveau défi dans une entreprise internationale.", en: "Now I am looking for a new challenge in an international company." },
      ],
      vocab: [
        { target: "il percorso", fr: "le parcours", en: "the background, path" },
        { target: "la laurea", fr: "le diplôme universitaire", en: "the degree" },
        { target: "l'esperienza", fr: "l'expérience", en: "the experience" },
        { target: "le competenze", fr: "les compétences", en: "the skills" },
        { target: "lo stagista", fr: "le·la stagiaire", en: "the intern" },
        { target: "ho studiato", fr: "j'ai étudié", en: "I studied" },
        { target: "poi / dopo", fr: "puis / ensuite, après", en: "then / after" },
        { target: "la sfida", fr: "le défi", en: "the challenge" },
      ],
      exercises: [
        {
          prompt: "Complète au passé composé : « Per tre anni … in banca. » (verbe lavorare)",
          promptEn: "Complete in the past: \"Per tre anni … in banca.\" (verb lavorare)",
          accept: ["ho lavorato"],
          explain: "Passato prossimo de lavorare avec avere : « ho lavorato ».",
          explainEn: "Passato prossimo of lavorare with avere: \"ho lavorato\".",
        },
        {
          prompt: "Quel mot désigne le « diplôme universitaire » en italien ?",
          promptEn: "Which word means \"university degree\" in Italian?",
          options: ["la laurea", "la lezione", "lo stipendio"],
          accept: ["la laurea"],
          explain: "« La laurea » = le diplôme universitaire ; « la lezione » = le cours ; « lo stipendio » = le salaire.",
          explainEn: "\"La laurea\" = university degree; \"la lezione\" = lesson; \"lo stipendio\" = salary.",
        },
        {
          prompt: "Complète : « … mi sono trasferito a Napoli. » (ensuite)",
          promptEn: "Complete: \"… mi sono trasferito a Napoli.\" (then)",
          accept: ["Poi"],
          explain: "« Poi » (puis) sert à ordonner son parcours.",
          explainEn: "\"Poi\" (then) is used to order your background.",
        },
      ],
      interview: [
        {
          question: "Mi parli del suo percorso di studi e professionale.",
          fr: "Parlez-moi de votre parcours d'études et professionnel.",
          en: "Tell me about your education and career path.",
          modelFr: "J'ai étudié l'économie à Lyon. J'ai ensuite travaillé trois ans comme comptable à Turin, puis j'ai rejoint une équipe commerciale, où j'ai développé des compétences en gestion de projet.",
          modelEn: "I studied economics in Lyon. I then worked for three years as an accountant in Turin, then I joined a sales team, where I developed project management skills.",
          accept: ["Mi sono laureato in economia", "Ho iniziato come stagista", "Ho lavorato tre anni a Torino", "Mi occupavo di gestione di progetti"],
        },
        {
          question: "Perché ha scelto questo settore?",
          fr: "Pourquoi avez-vous choisi ce secteur ?",
          en: "Why did you choose this field?",
          modelFr: "J'ai toujours aimé les chiffres et la relation client. Lors de mon stage, j'ai découvert ce secteur et j'ai décidé d'y construire ma carrière.",
          modelEn: "I have always liked numbers and client relationships. During my internship I discovered this field and decided to build my career in it.",
          accept: ["Mi piace lavorare con le persone", "Ho sempre amato i numeri", "Volevo crescere in questo settore"],
        },
      ],
    },
    {
      number: 11,
      slug: "it-11",
      title: "Colloquio: punti di forza, debolezze e motivazione",
      titleEn: "Interview: strengths, weaknesses and motivation",
      summary: "Exprimer ses atouts, reconnaître ses faiblesses et justifier sa motivation.",
      summaryEn: "Expressing your strengths, acknowledging weaknesses and justifying motivation.",
      grammar: ["Frasi con mi ritengo / sono bravo a…", "Il congiuntivo nelle risposte (penso che)", "Il lessico della motivazione"],
      explanation:
        "Pour parler de ses atouts : « sono molto organizzato » (je suis très organisé), « sono bravo a lavorare in team » (je suis bon pour travailler en équipe), « sono affidabile » (je suis fiable). Pour une faiblesse, on choisit un vrai défaut lié au travail et on montre qu'on le gère : « a volte sono troppo perfezionista » (parfois je suis trop perfectionniste). Pour la motivation : « sono molto motivato/a » (je suis très motivé), « questo ruolo mi interessa perché… » (ce poste m'intéresse parce que…). Le subjonctif apparaît après « penso che » : « penso che sia importante » (je pense qu'il est important).",
      explanationEn:
        "For your strengths: \"sono molto organizzato\" (I am very organized), \"sono bravo a lavorare in team\" (I am good at teamwork), \"sono affidabile\" (I am reliable). For a weakness, pick a real work-related flaw and show you manage it: \"a volte sono troppo perfezionista\" (sometimes I am too much of a perfectionist). For motivation: \"sono molto motivato/a\" (I am very motivated), \"questo ruolo mi interessa perché…\" (this role interests me because…). The subjunctive appears after \"penso che\": \"penso che sia importante\" (I think it is important).",
      examples: [
        { target: "Sono molto organizzato e rispetto le scadenze.", fr: "Je suis très organisé et je respecte les délais.", en: "I am very organized and I meet deadlines." },
        { target: "Sono bravo a lavorare in team e a comunicare.", fr: "Je suis bon pour travailler en équipe et communiquer.", en: "I am good at teamwork and communication." },
        { target: "La mia debolezza è che a volte sono troppo perfezionista.", fr: "Ma faiblesse, c'est que parfois je suis trop perfectionniste.", en: "My weakness is that sometimes I am too much of a perfectionist." },
        { target: "Questo ruolo mi interessa perché voglio crescere in questa azienda.", fr: "Ce poste m'intéresse parce que je veux évoluer dans cette entreprise.", en: "This role interests me because I want to grow in this company." },
      ],
      vocab: [
        { target: "i punti di forza", fr: "les points forts", en: "the strengths" },
        { target: "le debolezze", fr: "les faiblesses", en: "the weaknesses" },
        { target: "affidabile", fr: "fiable", en: "reliable" },
        { target: "organizzato", fr: "organisé", en: "organized" },
        { target: "essere bravo a…", fr: "être doué pour…", en: "to be good at…" },
        { target: "la motivazione", fr: "la motivation", en: "the motivation" },
        { target: "perfezionista", fr: "perfectionniste", en: "perfectionist" },
        { target: "la scadenza", fr: "le délai, l'échéance", en: "the deadline" },
      ],
      exercises: [
        {
          prompt: "Choisis ce qui est un point fort :",
          promptEn: "Choose which one is a strength:",
          options: ["Sono molto affidabile", "Arrivo sempre in ritardo", "Non mi piace il lavoro"],
          accept: ["Sono molto affidabile"],
          explain: "« Sono affidabile » (je suis fiable) est un atout, contrairement au retard et à l'aversion pour le travail.",
          explainEn: "\"Sono affidabile\" (I am reliable) is a strength, unlike arriving late or disliking work.",
        },
        {
          prompt: "Complète pour introduire une faiblesse : « La mia … è che… »",
          promptEn: "Complete to introduce a weakness: \"La mia … è che…\"",
          accept: ["debolezza"],
          explain: "« La debolezza » = la faiblesse : « la mia debolezza è che… ».",
          explainEn: "\"La debolezza\" = weakness: \"la mia debolezza è che…\".",
        },
        {
          prompt: "Complète : « Questo lavoro mi interessa … voglio sviluppare le mie competenze. » (parce que)",
          promptEn: "Complete: \"Questo lavoro mi interessa … voglio sviluppare le mie competenze.\" (because)",
          accept: ["perché"],
          explain: "« Perché » introduit la raison : « mi interessa perché… ».",
          explainEn: "\"Perché\" introduces the reason: \"mi interessa perché…\".",
        },
      ],
      interview: [
        {
          question: "Quali sono i suoi punti di forza?",
          fr: "Quels sont vos points forts ?",
          en: "What are your strengths?",
          modelFr: "Je suis très organisé et fiable. Je suis également bon pour travailler en équipe et je communique avec clarté, ce qui m'aide à coordonner les projets.",
          modelEn: "I am very organized and reliable. I am also good at teamwork and I communicate clearly, which helps me coordinate projects.",
          accept: ["Sono molto organizzato", "Sono affidabile e attento ai dettagli", "Sono bravo a lavorare in team"],
        },
        {
          question: "Qual è la sua più grande debolezza?",
          fr: "Quelle est votre plus grande faiblesse ?",
          en: "What is your biggest weakness?",
          modelFr: "Parfois je suis trop perfectionniste et je peux passer trop de temps sur les détails. J'ai appris à me fixer des priorités et à être plus efficace.",
          modelEn: "Sometimes I am too much of a perfectionist and I can spend too much time on details. I have learned to set priorities and be more efficient.",
          accept: ["Sono troppo perfezionista", "A volte mi concentro troppo sui dettagli", "Cerco di essere più efficiente"],
        },
        {
          question: "Perché vuole lavorare nella nostra azienda?",
          fr: "Pourquoi voulez-vous travailler dans notre entreprise ?",
          en: "Why do you want to work in our company?",
          modelFr: "J'admire vos projets innovants et votre environnement international. Ce poste correspond à mes compétences et m'offre la possibilité de grandir professionnellement.",
          modelEn: "I admire your innovative projects and your international environment. This role matches my skills and gives me the chance to grow professionally.",
          accept: ["Perché ammiro i vostri progetti", "Questo ruolo corrisponde alle mie competenze", "Voglio crescere in questa azienda"],
        },
      ],
    },
    {
      number: 12,
      slug: "it-12",
      title: "Colloquio: progetti futuri, lavoro di squadra e stress",
      titleEn: "Interview: future goals, teamwork and stress",
      summary: "Parler de ses projets, de sa vision dans 5 ans, du travail d'équipe et de la gestion du stress.",
      summaryEn: "Talking about your goals, your 5-year vision, teamwork and stress management.",
      grammar: ["Il futuro semplice (lavorerò, sarò)", "Il periodo ipotetico (se potessi…)", "Gestire lo stress (di solito, riesco a…)"],
      explanation:
        "Pour les projets futurs, on utilise le futur simple : « lavorerò » (je travaillerai), « sarò » (je serai), « vorrei sviluppare » (je voudrais développer). La vision à 5 ans : « tra cinque anni mi vedo… » (dans cinq ans je me vois…). L'hypothèse : « se potessi scegliere, sceglierei… » (si je pouvais choisir, je choisirais…). Pour le travail d'équipe : « mi piace collaborare », « ascolto i colleghi », « condivido le informazioni ». Pour le stress : « di solito riesco a gestire la pressione » (d'habitude j'arrive à gérer la pression), « faccio una pausa e riorganizzo le priorità » (je fais une pause et je réorganise les priorités).",
      explanationEn:
        "For future goals, use the simple future: \"lavorerò\" (I will work), \"sarò\" (I will be), \"vorrei sviluppare\" (I would like to develop). The 5-year vision: \"tra cinque anni mi vedo…\" (in five years I see myself…). The hypothesis: \"se potessi scegliere, sceglierei…\" (if I could choose, I would choose…). For teamwork: \"mi piace collaborare\", \"ascolto i colleghi\", \"condivido le informazioni\". For stress: \"di solito riesco a gestire la pressione\" (I usually manage to handle pressure), \"faccio una pausa e riorganizzo le priorità\" (I take a break and rearrange priorities).",
      examples: [
        { target: "Tra cinque anni mi vedo responsabile di un piccolo team.", fr: "Dans cinq ans, je me vois responsable d'une petite équipe.", en: "In five years I see myself as the head of a small team." },
        { target: "Lavorerò con entusiasmo per crescere insieme all'azienda.", fr: "Je travaillerai avec enthousiasme pour grandir avec l'entreprise.", en: "I will work enthusiastically to grow together with the company." },
        { target: "Mi piace collaborare perché il confronto migliora i risultati.", fr: "J'aime collaborer car la confrontation des idées améliore les résultats.", en: "I like collaborating because exchanging ideas improves results." },
        { target: "Di solito gestisco lo stress facendo una pausa e riorganizzando le priorità.", fr: "D'habitude, je gère le stress en faisant une pause et en réorganisant les priorités.", en: "I usually manage stress by taking a break and rearranging priorities." },
      ],
      vocab: [
        { target: "il futuro", fr: "le futur, l'avenir", en: "the future" },
        { target: "tra cinque anni", fr: "dans cinq ans", en: "in five years" },
        { target: "lavorerò", fr: "je travaillerai", en: "I will work" },
        { target: "il lavoro di squadra", fr: "le travail d'équipe", en: "teamwork" },
        { target: "collaborare", fr: "collaborer", en: "to collaborate" },
        { target: "lo stress / la pressione", fr: "le stress / la pression", en: "stress / pressure" },
        { target: "gestire", fr: "gérer", en: "to manage" },
        { target: "le priorità", fr: "les priorités", en: "the priorities" },
      ],
      exercises: [
        {
          prompt: "Complète au futur : « Tra un anno … in questa azienda. » (verbo lavorare)",
          promptEn: "Complete in the future: \"Tra un anno … in questa azienda.\" (verb lavorare)",
          accept: ["lavorerò"],
          explain: "Futur simple de lavorare à la 1re personne : « lavorerò ».",
          explainEn: "Simple future of lavorare, 1st person: \"lavorerò\".",
        },
        {
          prompt: "Comment dit-on « le travail d'équipe » en italien ?",
          promptEn: "How do you say \"teamwork\" in Italian?",
          options: ["il lavoro di squadra", "il lavoro di casa", "il lavoro pesante"],
          accept: ["il lavoro di squadra"],
          explain: "« Il lavoro di squadra » = le travail d'équipe ; « il lavoro di casa » = le ménage.",
          explainEn: "\"Il lavoro di squadra\" means teamwork; \"il lavoro di casa\" means housework.",
        },
        {
          prompt: "Complète : « Di solito … a gestire la pressione. » (j'arrive à)",
          promptEn: "Complete: \"Di solito … a gestire la pressione.\" (I manage to)",
          accept: ["riesco"],
          explain: "« Riuscire a » = réussir à/arriver à : « riesco a gestire la pressione ».",
          explainEn: "\"Riuscire a\" means to manage to: \"riesco a gestire la pressione\".",
        },
      ],
      interview: [
        {
          question: "Dove si vede tra cinque anni?",
          fr: "Où vous voyez-vous dans cinq ans ?",
          en: "Where do you see yourself in five years?",
          modelFr: "Dans cinq ans, je me vois dans une position de responsable, avec la maîtrise complète de ce métier et une équipe que j'aide à grandir.",
          modelEn: "In five years, I see myself in a leadership position, with full mastery of this job and a team I help to grow.",
          accept: ["Mi vedo responsabile di un team", "Vorrei crescere in questa azienda", "Tra cinque anni voglio essere esperto del mio mestiere"],
        },
        {
          question: "Come lavora in team?",
          fr: "Comment travaillez-vous en équipe ?",
          en: "How do you work in a team?",
          modelFr: "J'écoute mes collègues, je partage les informations et je respecte les rôles de chacun. Je crois que le dialogue améliore les résultats de tout le groupe.",
          modelEn: "I listen to my colleagues, I share information and I respect everyone's role. I believe that dialogue improves the results of the whole group.",
          accept: ["Ascolto i colleghi e condivido le informazioni", "Mi piace collaborare", "Il confronto migliora i risultati"],
        },
        {
          question: "Come gestisce lo stress sul lavoro?",
          fr: "Comment gérez-vous le stress au travail ?",
          en: "How do you manage stress at work?",
          modelFr: "Je reste calme, je fais une pause si nécessaire et je réorganise mes priorités. Une liste claire de tâches m'aide à avancer même sous pression.",
          modelEn: "I stay calm, I take a break if needed and I rearrange my priorities. A clear task list helps me move forward even under pressure.",
          accept: ["Faccio una pausa e riorganizzo le priorità", "Riesco a gestire la pressione", "Organizzo le attività in una lista"],
        },
      ],
    },
  ],
};