import type { LanguageCourse } from "./genericLessons";

export const KO_COURSE: LanguageCourse = {
  code: "ko",
  name: "Coréen",
  native: "한국어",
  heroTitle1: { fr: "Apprenez", en: "Learn" },
  heroTitle2: { fr: "le coréen", en: "Korean" },
  heroSubtitle: {
    fr: "Un parcours débutant en douze leçons : salutations, vie quotidienne, travail et entretien d'embauche.",
    en: "A beginner path in twelve lessons: greetings, daily life, work and a job interview.",
  },
  lessons: [
    {
      number: 1,
      slug: "ko-01",
      title: "Se présenter et saluer",
      titleEn: "Introducing yourself and greeting",
      summary:
        "Apprenez à saluer et à vous présenter simplement : dire bonjour, donner son nom et son origine.",
      summaryEn:
        "Learn to greet and introduce yourself simply: say hello, give your name and where you come from.",
      grammar: ["안녕하세요 (bonjour)", "제 이름은...입니다", "저는...에서 왔어요"],
      explanation:
        "La forme polie en -요 est la base de la conversation courante en coréen. « 제 이름은... » signifie « mon nom est... » et « 저는...에서 왔어요 » exprime votre origine. Le verbe se place toujours en fin de phrase.",
      explanationEn:
        "The polite -요 form is the basis of everyday conversation in Korean. '제 이름은...' means 'My name is...' and '저는...에서 왔어요' expresses your origin. The verb always comes at the end of the sentence.",
      examples: [
        { target: "안녕하세요, 저는 다니엘이에요.", roman: "annyeonghaseyo, jeoneun danieorieyo.", fr: "Bonjour, je suis Daniel.", en: "Hello, I am Daniel." },
        { target: "제 이름은 김민수예요.", roman: "je ireumeun gimminusuyeyo.", fr: "Mon nom est Kim Minsu.", en: "My name is Kim Minsu." },
        { target: "저는 프랑스에서 왔어요.", roman: "jeoneun peurangseueseo wasseoyo.", fr: "Je viens de France.", en: "I come from France." },
        { target: "만나서 반가워요.", roman: "mannaseo bangawoyo.", fr: "Enchanté de vous rencontrer.", en: "Nice to meet you." },
      ],
      vocab: [
        { target: "안녕하세요", roman: "annyeonghaseyo", fr: "bonjour (poli)", en: "hello (polite)" },
        { target: "제 이름은", roman: "je ireumeun", fr: "mon nom est", en: "my name is" },
        { target: "저는", roman: "jeoneun", fr: "je / moi", en: "I / me" },
        { target: "에서 왔어요", roman: "eseo wasseoyo", fr: "venir de", en: "to come from" },
        { target: "만나서 반가워요", roman: "mannaseo bangawoyo", fr: "enchanté(e)", en: "nice to meet you" },
        { target: "네", roman: "ne", fr: "oui", en: "yes" },
        { target: "아니요", roman: "aniyo", fr: "non", en: "no" },
        { target: "미안해요", roman: "mianhaeyo", fr: "pardon / je suis désolé", en: "sorry", },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Bonjour » en coréen ?",
          promptEn: "How do you say 'Hello' in Korean?",
          options: ["안녕하세요", "감사합니다", "주세요", "안녕히 가세요"],
          accept: ["안녕하세요"],
          explain: "« 안녕하세요 » est la salutation polie standard en coréen.",
          explainEn: "'안녕하세요' is the standard polite greeting in Korean.",
        },
        {
          prompt: "Complétez : « Mon nom est... ».",
          promptEn: "Complete: 'My name is...'.",
          accept: ["제 이름은"],
          explain: "« 제 이름은 » signifie littéralement « mon nom [est] ».",
          explainEn: "'제 이름은' literally means 'my name [is]'.",
        },
        {
          prompt: "Comment dit-on « Je viens de France » ?",
          promptEn: "How do you say 'I come from France'?",
          options: ["저는 프랑스에서 왔어요.", "저는 학교에 가요.", "프랑스는 좋아요.", "커피를 마셔요."],
          accept: ["저는 프랑스에서 왔어요."],
          explain: "« 저는 프랑스에서 왔어요 » associe l'origine à la forme polie.",
          explainEn: "'저는 프랑스에서 왔어요' links your origin with the polite form.",
        },
      ],
      interview: [
        {
          question: "자기소개 해 주세요.",
          roman: "jagisogae hae juseyo.",
          fr: "Présentez-vous, s'il vous plaît.",
          en: "Please introduce yourself.",
          modelFr: "Bonjour, je m'appelle Daniel, j'ai 30 ans et je viens de France.",
          modelEn: "Hello, my name is Daniel, I am 30 years old and I come from France.",
          accept: ["안녕하세요, 저는 다니엘이에요."],
        },
      ],
    },
    {
      number: 2,
      slug: "ko-02",
      title: "Origine, nationalité et profession",
      titleEn: "Origin, nationality and profession",
      summary:
        "Parlez de votre pays, de votre nationalité et de votre métier.",
      summaryEn:
        "Talk about your country, your nationality and your job.",
      grammar: ["~사람 (personne)", "저는...이에요 / 예요", "직업 (profession)"],
      explanation:
        "Pour dire sa nationalité, on ajoute « 사람 » (personne) au nom du pays, par exemple « 프랑스 사람 » (Français). La copule « 이에요/예요 » signifie « être ». Pour demander le métier, on emploie « 무슨 일을 하세요? ».",
      explanationEn:
        "To state your nationality, you add '사람' (person) to the country name, e.g. '프랑스 사람' (French). The copula '이에요/예요' means 'to be'. To ask the job you use '무슨 일을 하세요?'.",
      examples: [
        { target: "저는 프랑스 사람이에요.", roman: "jeoneun peurangseu saramiyeyo.", fr: "Je suis français.", en: "I am French." },
        { target: "무슨 일을 하세요?", roman: "museun ireul haseyo?", fr: "Quel métier faites-vous ?", en: "What do you do for a living?" },
        { target: "저는 개발자예요.", roman: "jeoneun gaebaljayeyo.", fr: "Je suis développeur.", en: "I am a developer." },
        { target: "한국 사람이에요.", roman: "hanguk saramiyeyo.", fr: "C'est un Coréen.", en: "He is Korean." },
      ],
      vocab: [
        { target: "프랑스", roman: "peurangseu", fr: "France", en: "France" },
        { target: "한국", roman: "hanguk", fr: "Corée", en: "Korea" },
        { target: "사람", roman: "saram", fr: "personne", en: "person" },
        { target: "국적", roman: "gukjeok", fr: "nationalité", en: "nationality" },
        { target: "직업", roman: "jigeop", fr: "profession", en: "profession" },
        { target: "개발자", roman: "gaebalja", fr: "développeur", en: "developer" },
        { target: "선생님", roman: "seonsaengnim", fr: "professeur", en: "teacher" },
        { target: "의사", roman: "uisa", fr: "médecin", en: "doctor" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Je suis français » ?",
          promptEn: "How do you say 'I am French'?",
          options: ["저는 프랑스 사람이에요.", "저는 한국에 가요.", "저는 학생이에요.", "감사합니다."],
          accept: ["저는 프랑스 사람이에요."],
          explain: "On associe « 프랑스 사람 » (Français) à la copule « 이에요 ».",
          explainEn: "You combine '프랑스 사람' (French person) with the copula '이에요'.",
        },
        {
          prompt: "Complétez : « Quel métier faites-vous ? ».",
          promptEn: "Complete: 'What do you do for a living?'.",
          accept: ["무슨 일을 하세요?"],
          explain: "« 무슨 일을 하세요? » est la façon polie de demander le métier.",
          explainEn: "'무슨 일을 하세요?' is the polite way to ask one's job.",
        },
        {
          prompt: "Quel mot signifie « médecin » ?",
          promptEn: "Which word means 'doctor'?",
          options: ["의사", "학생", "선생님", "사람"],
          accept: ["의사"],
          explain: "« 의사 » signifie « médecin » en coréen.",
          explainEn: "'의사' means 'doctor' in Korean.",
        },
      ],
    },
    {
      number: 3,
      slug: "ko-03",
      title: "Être et avoir",
      titleEn: "To be and to have",
      summary:
        "Utilisez la copule 이에요/예요 et exprimez la possession avec 있어요/없어요.",
      summaryEn:
        "Use the copula 이에요/예요 and express possession with 있어요/없어요.",
      grammar: ["이에요 / 예요 (être)", "있어요 (avoir)", "없어요 (ne pas avoir)"],
      explanation:
        "« 이에요 » suit les consonnes et « 예요 » les voyelles pour « être ». « 있어요 » signifie « avoir / il y a », et « 없어요 » son contraire. Pour la possession on dit « 제 것은... » ou plus simplement « 저는...이 있어요 ».",
      explanationEn:
        "'이에요' follows consonants and '예요' vowels for 'to be'. '있어요' means 'to have / there is', and '없어요' is its negative. For possession you say '저는...이 있어요'.",
      examples: [
        { target: "저는 한국어를 공부해요.", roman: "jeoneun hangugeoreul gongbuhaeyo.", fr: "J'étudie le coréen.", en: "I study Korean." },
        { target: "사과가 있어요.", roman: "sagwaga isseoyo.", fr: "Il y a une pomme.", en: "There is an apple." },
        { target: "시간이 없어요.", roman: "sigani eopseoyo.", fr: "Je n'ai pas le temps.", en: "I don't have time." },
        { target: "동생이 두 명 있어요.", roman: "dongsaengi du myeong isseoyo.", fr: "J'ai deux frères (ou sœurs) plus jeunes.", en: "I have two younger siblings." },
      ],
      vocab: [
        { target: "있다", roman: "itda", fr: "avoir / être là", en: "to have / to exist" },
        { target: "없다", roman: "eopda", fr: "ne pas avoir", en: "to not have" },
        { target: "사과", roman: "sagwa", fr: "pomme", en: "apple" },
        { target: "시간", roman: "sigan", fr: "temps", en: "time" },
        { target: "동생", roman: "dongsaeng", fr: "frère/sœur plus jeune", en: "younger sibling" },
        { target: "가방", roman: "gabang", fr: "sac", en: "bag" },
        { target: "책", roman: "chaek", fr: "livre", en: "book" },
        { target: "물", roman: "mul", fr: "eau", en: "water" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Il y a une pomme » ?",
          promptEn: "How do you say 'There is an apple'?",
          options: ["사과가 있어요.", "사과가 없어요.", "사과예요.", "사과를 먹어요."],
          accept: ["사과가 있어요."],
          explain: "« 사과가 있어요 » signifie « il y a une pomme ».",
          explainEn: "'사과가 있어요' means 'there is an apple'.",
        },
        {
          prompt: "Complétez : « Je n'ai pas le temps ».",
          promptEn: "Complete: 'I don't have time'.",
          accept: ["시간이 없어요."],
          explain: "« 없어요 » est la forme négative de « avoir ».",
          explainEn: "'없어요' is the negative form of 'to have'.",
        },
        {
          prompt: "Que signifie « 책 » ?",
          promptEn: "What does '책' mean?",
          options: ["livre", "sac", "eau", "pomme"],
          accept: ["책"],
          explain: "« 책 » signifie « livre ».",
          explainEn: "'책' means 'book'.",
        },
      ],
    },
    {
      number: 4,
      slug: "ko-04",
      title: "La routine quotidienne",
      titleEn: "The daily routine",
      summary:
        "Décrivez votre journée : se lever, travailler, manger et rentrer chez soi.",
      summaryEn:
        "Describe your day: waking up, working, eating and going home.",
      grammar: ["~아요 / 어요 (présent poli)", "일어나요 (se lever)", "~에서 (dans, à)"],
      explanation:
        "Les verbes se conjuguent au présent poli avec les terminaisons « 아요/어요 », par exemple « 일어나다 » → « 일어나요 » (se lever). « ~에서 » indique le lieu de l'action : « 회사에서 일해요 » (je travaille au bureau).",
      explanationEn:
        "Verbs conjugate in the polite present with the endings '아요/어요', e.g. '일어나다' → '일어나요' (to wake up). '~에서' marks the place of the action: '회사에서 일해요' (I work at the office).",
      examples: [
        { target: "아침에 일곱 시에 일어나요.", roman: "achime ilgop sie ireonayo.", fr: "Je me lève à sept heures du matin.", en: "I wake up at seven in the morning." },
        { target: "회사에서 일해요.", roman: "hoesaeseo ilhaeyo.", fr: "Je travaille au bureau.", en: "I work at the office." },
        { target: "밥을 먹어요.", roman: "babeul meogeoyo.", fr: "Je mange (du riz).", en: "I eat (a meal)." },
        { target: "집에 돌아가요.", roman: "jibe doragayo.", fr: "Je rentre à la maison.", en: "I go back home." },
      ],
      vocab: [
        { target: "아침", roman: "achim", fr: "matin / petit-déjeuner", en: "morning / breakfast" },
        { target: "일어나다", roman: "ireonada", fr: "se lever", en: "to wake up" },
        { target: "일하다", roman: "ilhada", fr: "travailler", en: "to work" },
        { target: "밥", roman: "bap", fr: "riz / repas", en: "rice / meal" },
        { target: "먹다", roman: "meokda", fr: "manger", en: "to eat" },
        { target: "집", roman: "jip", fr: "maison", en: "home" },
        { target: "돌아가다", roman: "doragada", fr: "rentrer", en: "to go back" },
        { target: "시", roman: "si", fr: "heure", en: "o'clock" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Je me lève à sept heures » ?",
          promptEn: "How do you say 'I wake up at seven o'clock'?",
          options: ["일곱 시에 일어나요.", "일곱 시에 자요.", "여덟 시에 일해요.", "밥을 먹어요."],
          accept: ["일곱 시에 일어나요."],
          explain: "« 일곱 시에 » = à sept heures, « 일어나요 » = je me lève.",
          explainEn: "'일곱 시에' = at seven o'clock, '일어나요' = I wake up.",
        },
        {
          prompt: "Complétez : « Je travaille au bureau ».",
          promptEn: "Complete: 'I work at the office'.",
          accept: ["회사에서 일해요."],
          explain: "« 회사에서 » signifie « au bureau » et « 일해요 » « je travaille ».",
          explainEn: "'회사에서' means 'at the office' and '일해요' means 'I work'.",
        },
        {
          prompt: "Que signifie « 밥 » ?",
          promptEn: "What does '밥' mean?",
          options: ["riz / repas", "thé", "maison", "dormir"],
          accept: ["밥"],
          explain: "« 밥 » désigne le riz, par extension le repas.",
          explainEn: "'밥' means rice, by extension a meal.",
        },
      ],
    },
    {
      number: 5,
      slug: "ko-05",
      title: "Les goûts et les loisirs",
      titleEn: "Likes and hobbies",
      summary:
        "Exprimez vos préférences avec 좋아해요 et parlez de vos loisirs.",
      summaryEn:
        "Express your preferences with 좋아해요 and talk about your hobbies.",
      grammar: ["좋아해요 (aimer)", "~을/를 좋아해요", "취미 (loisir)"],
      explanation:
        "« 좋아하다 » signifie « aimer ». On marque l'objet avec la particule « 을/를 » : « 음악을 좋아해요 » (j'aime la musique). La particule « 을 » suit une consonne, « 를 » une voyelle.",
      explanationEn:
        "'좋아하다' means 'to like'. The object is marked with the particle '을/를': '음악을 좋아해요' (I like music). '을' follows a consonant, '를' a vowel.",
      examples: [
        { target: "저는 음악을 좋아해요.", roman: "jeoneun eumageul johahaeyo.", fr: "J'aime la musique.", en: "I like music." },
        { target: "축구를 좋아해요.", roman: "chukgureul johahaeyo.", fr: "J'aime le football.", en: "I like football." },
        { target: "무슨 취미가 있어요?", roman: "museun chwimiga isseoyo?", fr: "Quels sont vos loisirs ?", en: "What hobbies do you have?" },
        { target: "저는 책 읽는 것을 좋아해요.", roman: "jeoneun chaek ingneun geoseul johahaeyo.", fr: "J'aime lire des livres.", en: "I like reading books." },
      ],
      vocab: [
        { target: "좋아하다", roman: "johahada", fr: "aimer", en: "to like" },
        { target: "음악", roman: "eumak", fr: "musique", en: "music" },
        { target: "축구", roman: "chukgu", fr: "football", en: "football" },
        { target: "취미", roman: "chwimi", fr: "loisir / hobby", en: "hobby" },
        { target: "책", roman: "chaek", fr: "livre", en: "book" },
        { target: "을/를", roman: "eul/reul", fr: "particule objet", en: "object particle" },
        { target: "하다", roman: "hada", fr: "faire", en: "to do" },
        { target: "좋아요", roman: "joayo", fr: "c'est bien", en: "it's good" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « J'aime la musique » ?",
          promptEn: "How do you say 'I like music'?",
          options: ["음악을 좋아해요.", "음악이 좋아요.", "음악을 해요.", "음악을 봐요."],
          accept: ["음악을 좋아해요."],
          explain: "« 음악을 좋아해요 » associe l'objet et le verbe « aimer ».",
          explainEn: "'음악을 좋아해요' combines the object and the verb 'to like'.",
        },
        {
          prompt: "Complétez : « Quels sont vos loisirs ? ».",
          promptEn: "Complete: 'What hobbies do you have?'.",
          accept: ["무슨 취미가 있어요?"],
          explain: "« 무슨 취미가 있어요? » demande quels sont vos loisirs.",
          explainEn: "'무슨 취미가 있어요?' asks what your hobbies are.",
        },
        {
          prompt: "Que signifie « 취미 » ?",
          promptEn: "What does '취미' mean?",
          options: ["loisir", "travail", "école", "voyage"],
          accept: ["취미"],
          explain: "« 취미 » signifie « loisir / hobby ».",
          explainEn: "'취미' means 'hobby'.",
        },
      ],
    },
    {
      number: 6,
      slug: "ko-06",
      title: "La famille et les personnes",
      titleEn: "Family and people",
      summary:
        "Présentez votre famille : père, mère, frère, sœur et leurs âges.",
      summaryEn:
        "Present your family: father, mother, brother, sister and their ages.",
      grammar: ["가족 (famille)", "~명 (compteur de personnes)", "몇 살 (quel âge)"],
      explanation:
        "Les termes de famille distinguent l'âge : « 오빠 » (frère aîné d'une fille), « 형 » (frère aîné d'un garçon), « 누나 » (sœur aînée d'un garçon). On compte les personnes avec « 명 » et l'âge avec « 몇 살 ».",
      explanationEn:
        "Family terms distinguish age: '오빠' (older brother of a girl), '형' (older brother of a boy), '누나' (older sister of a boy). People are counted with '명' and age is asked with '몇 살'.",
      examples: [
        { target: "우리 가족은 네 명이에요.", roman: "uri gajogeun ne myeongiyeyo.", fr: "Nous sommes quatre dans la famille.", en: "We are four in the family." },
        { target: "아버지는 의사예요.", roman: "abeojineun uisayeyo.", fr: "Mon père est médecin.", en: "My father is a doctor." },
        { target: "어머니는 선생님이세요.", roman: "eomeonineun seonsaengnimuseyo.", fr: "Ma mère est professeur.", en: "My mother is a teacher." },
        { target: "몇 살이에요?", roman: "myeoch sariyeyo?", fr: "Quel âge avez-vous ?", en: "How old are you?" },
      ],
      vocab: [
        { target: "가족", roman: "gajok", fr: "famille", en: "family" },
        { target: "아버지", roman: "abeoji", fr: "père", en: "father" },
        { target: "어머니", roman: "eomeoni", fr: "mère", en: "mother" },
        { target: "형", roman: "hyeong", fr: "frère aîné (garçon)", en: "older brother (male speaker)" },
        { target: "누나", roman: "nuna", fr: "sœur aînée (garçon)", en: "older sister (male speaker)" },
        { target: "명", roman: "myeong", fr: "compteur de personnes", en: "person counter" },
        { target: "살", roman: "sal", fr: "âge (compteur)", en: "age (counter)" },
        { target: "몇", roman: "myeot", fr: "combien", en: "how many" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Nous sommes quatre dans la famille » ?",
          promptEn: "How do you say 'We are four in the family'?",
          options: ["가족은 네 명이에요.", "가족은 네 살이에요.", "가족을 좋아해요.", "가족에 가요."],
          accept: ["우리 가족은 네 명이에요."],
          explain: "« 네 » = quatre, « 명 » = compteur de personnes.",
          explainEn: "'네' = four, '명' = the person counter.",
        },
        {
          prompt: "Complétez : « Mon père est médecin ».",
          promptEn: "Complete: 'My father is a doctor'.",
          accept: ["아버지는 의사예요."],
          explain: "« 아버지 » = père, « 의사 » = médecin.",
          explainEn: "'아버지' = father, '의사' = doctor.",
        },
        {
          prompt: "Que signifie « 형 » ?",
          promptEn: "What does '형' mean?",
          options: ["frère aîné (garçon)", "sœur aînée", "mère", "grand-père"],
          accept: ["형"],
          explain: "« 형 » est le frère aîné vu par un homme.",
          explainEn: "'형' is the older brother as seen by a male speaker.",
        },
      ],
    },
    {
      number: 7,
      slug: "ko-07",
      title: "Le travail et le bureau",
      titleEn: "Work and the office",
      summary:
        "Parlez de votre travail, de votre société et de vos collègues.",
      summaryEn:
        "Talk about your job, your company and your colleagues.",
      grammar: ["회사 (entreprise)", "~에서 일해요", "동료 (collègue)"],
      explanation:
        "« 회사 » signifie « entreprise » et « 직장 » « lieu de travail ». On dit « 저는 ○○회사에서 일해요 » (je travaille dans l'entreprise ○○). « 동료 » désigne un collègue, « 상사 » un supérieur.",
      explanationEn:
        "'회사' means 'company' and '직장' means 'workplace'. You say '저는 ○○회사에서 일해요' (I work at ○○ company). '동료' is a colleague, '상사' a superior.",
      examples: [
        { target: "저는 IT 회사에서 일해요.", roman: "jeoneun IT hoesaeseo ilhaeyo.", fr: "Je travaille dans une entreprise IT.", en: "I work at an IT company." },
        { target: "제 상사는 친절해요.", roman: "je sangsaneun chinjeolhaeyo.", fr: "Mon supérieur est gentil.", en: "My boss is kind." },
        { target: "동료들과 점심을 먹어요.", roman: "dongnyodeulgwa jeomsimeul meogeoyo.", fr: "Je déjeune avec mes collègues.", en: "I have lunch with my colleagues." },
        { target: "회사에 가요.", roman: "hoesae gayo.", fr: "Je vais à l'entreprise.", en: "I go to the company." },
      ],
      vocab: [
        { target: "회사", roman: "hoesa", fr: "entreprise", en: "company" },
        { target: "직장", roman: "jikjang", fr: "lieu de travail", en: "workplace" },
        { target: "동료", roman: "dongnyo", fr: "collègue", en: "colleague" },
        { target: "상사", roman: "sangsa", fr: "supérieur", en: "superior / boss" },
        { target: "사무실", roman: "samusil", fr: "bureau (pièce)", en: "office (room)" },
        { target: "일", roman: "il", fr: "travail / affaire", en: "work" },
        { target: "회의", roman: "hoeui", fr: "réunion", en: "meeting" },
        { target: "출근하다", roman: "chulgeunhada", fr: "aller au travail", en: "to go to work" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Je travaille dans une entreprise IT » ?",
          promptEn: "How do you say 'I work at an IT company'?",
          options: ["IT 회사에서 일해요.", "IT 회사에 가요.", "IT 회사를 좋아해요.", "IT에서 먹어요."],
          accept: ["저는 IT 회사에서 일해요."],
          explain: "« 회사에서 일해요 » = travailler à l'entreprise.",
          explainEn: "'회사에서 일해요' = to work at the company.",
        },
        {
          prompt: "Complétez : « Je déjeune avec mes collègues ».",
          promptEn: "Complete: 'I have lunch with my colleagues'.",
          accept: ["동료들과 점심을 먹어요."],
          explain: "« 동료들 » = collègues, « 점심 » = déjeuner.",
          explainEn: "'동료들' = colleagues, '점심' = lunch.",
        },
        {
          prompt: "Que signifie « 상사 » ?",
          promptEn: "What does '상사' mean?",
          options: ["supérieur", "collègue", "réunion", "bureau"],
          accept: ["상사"],
          explain: "« 상사 » désigne le supérieur hiérarchique.",
          explainEn: "'상사' refers to one's superior.",
        },
      ],
    },
    {
      number: 8,
      slug: "ko-08",
      title: "Faire des achats et commander",
      titleEn: "Shopping and ordering",
      summary:
        "Faites des achats au marché et commandez au restaurant.",
      summaryEn:
        "Go shopping at the market and order food at a restaurant.",
      grammar: ["~주세요 (donnez-moi)", "얼마예요? (combien)", "이것 / 저것 (ceci / cela)"],
      explanation:
        "« 주세요 » est la forme polie de « donner » : « 커피 주세요 » (un café, s'il vous plaît). Pour demander le prix on dit « 얼마예요? ». « 이것 » désigne une chose proche (ceci), « 저것 » une chose éloignée (cela).",
      explanationEn:
        "'주세요' is the polite form of 'to give': '커피 주세요' (a coffee, please). To ask the price you say '얼마예요?'. '이것' refers to a nearby thing (this), '저것' to a distant one (that).",
      examples: [
        { target: "이거 얼마예요?", roman: "igeo eolmayeyo?", fr: "Combien ça coûte ?", en: "How much is this?" },
        { target: "커피 한 잔 주세요.", roman: "keopi han jan juseyo.", fr: "Un café, s'il vous plaît.", en: "One coffee, please." },
        { target: "김치찌개 하나 주세요.", roman: "gimchijjigae hana juseyo.", fr: "Un ragoût de kimchi, s'il vous plaît.", en: "One kimchi stew, please." },
        { target: "계산서 주세요.", roman: "gyesanseo juseyo.", fr: "L'addition, s'il vous plaît.", en: "The bill, please." },
      ],
      vocab: [
        { target: "주세요", roman: "juseyo", fr: "donnez-moi, s'il vous plaît", en: "please give me" },
        { target: "얼마예요?", roman: "eolmayeyo?", fr: "combien ça coûte ?", en: "how much is it?" },
        { target: "커피", roman: "keopi", fr: "café", en: "coffee" },
        { target: "한 잔", roman: "han jan", fr: "un verre / une tasse", en: "a cup / glass" },
        { target: "음식", roman: "eumsik", fr: "plats / nourriture", en: "food" },
        { target: "값", roman: "gap", fr: "prix", en: "price" },
        { target: "시장", roman: "sijang", fr: "marché", en: "market" },
        { target: "계산서", roman: "gyesanseo", fr: "addition / facture", en: "bill" },
      ],
      exercises: [
        {
          prompt: "Comment demande-t-on « Combien ça coûte ? » ?",
          promptEn: "How do you ask 'How much is this?'?",
          options: ["이거 얼마예요?", "이거 주세요.", "이거 좋아요.", "이거 뭐예요?"],
          accept: ["이거 얼마예요?"],
          explain: "« 얼마 », associé à « 이거 », demande le prix.",
          explainEn: "'얼마', combined with '이거', asks the price.",
        },
        {
          prompt: "Complétez : « Un café, s'il vous plaît ».",
          promptEn: "Complete: 'One coffee, please'.",
          accept: ["커피 한 잔 주세요."],
          explain: "On commande avec « 주세요 » : « 한 잔 » = une tasse.",
          explainEn: "You order with '주세요': '한 잔' = one cup.",
        },
        {
          prompt: "Que signifie « 계산서 » ?",
          promptEn: "What does '계산서' mean?",
          options: ["l'addition", "le menu", "le marché", "le prix"],
          accept: ["계산서"],
          explain: "« 계산서 » est l'addition que l'on demande en fin de repas.",
          explainEn: "'계산서' is the bill you ask for at the end of a meal.",
        },
      ],
    },
    {
      number: 9,
      slug: "ko-09",
      title: "Le temps, les saisons et l'heure",
      titleEn: "Weather, seasons and time",
      summary:
        "Parlez du temps qu'il fait, des saisons et de l'heure qu'il est.",
      summaryEn:
        "Talk about the weather, the seasons and the time of day.",
      grammar: ["날씨 (temps qu'il fait)", "계절 (saison)", "지금 몇 시예요? (quelle heure)"],
      explanation:
        "« 날씨 » désigne le temps qu'il fait : « 날씨가 좋아요 » (il fait beau). Les quatre saisons sont « 봄 » (printemps), « 여름 » (été), « 가을 » (automne) et « 겨울 » (hiver). Pour l'heure on demande « 지금 몇 시예요? ».",
      explanationEn:
        "'날씨' refers to the weather: '날씨가 좋아요' (the weather is nice). The four seasons are '봄' (spring), '여름' (summer), '가을' (autumn) and '겨울' (winter). For the time you ask '지금 몇 시예요?'.",
      examples: [
        { target: "오늘 날씨가 좋아요.", roman: "oneul nalssiga joayo.", fr: "Il fait beau aujourd'hui.", en: "The weather is nice today." },
        { target: "여름에는 더워요.", roman: "yeoreumeneun deoweoyo.", fr: "Il fait chaud en été.", en: "It is hot in summer." },
        { target: "지금 몇 시예요?", roman: "jigeum myeot siyeyo?", fr: "Quelle heure est-il ?", en: "What time is it?" },
        { target: "저는 봄을 좋아해요.", roman: "jeoneun bomeul johahaeyo.", fr: "J'aime le printemps.", en: "I like spring." },
      ],
      vocab: [
        { target: "날씨", roman: "nalssi", fr: "temps (météo)", en: "weather" },
        { target: "봄", roman: "bom", fr: "printemps", en: "spring" },
        { target: "여름", roman: "yeoreum", fr: "été", en: "summer" },
        { target: "가을", roman: "gaeul", fr: "automne", en: "autumn" },
        { target: "겨울", roman: "gyeoul", fr: "hiver", en: "winter" },
        { target: "비", roman: "bi", fr: "pluie", en: "rain" },
        { target: "눈", roman: "nun", fr: "neige", en: "snow" },
        { target: "지금", roman: "jigeum", fr: "maintenant", en: "now" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Il fait beau aujourd'hui » ?",
          promptEn: "How do you say 'The weather is nice today'?",
          options: ["오늘 날씨가 좋아요.", "오늘 비가 와요.", "오늘 추워요.", "오늘 몇 시예요?"],
          accept: ["오늘 날씨가 좋아요."],
          explain: "« 날씨가 좋아요 » = il fait beau.",
          explainEn: "'날씨가 좋아요' = the weather is nice.",
        },
        {
          prompt: "Complétez : « Quelle heure est-il ? ».",
          promptEn: "Complete: 'What time is it?'.",
          accept: ["지금 몇 시예요?"],
          explain: "« 몇 시 » = quelle heure, « 예요 » = est.",
          explainEn: "'몇 시' = what time, '예요' = is.",
        },
        {
          prompt: "Quel mot signifie « hiver » ?",
          promptEn: "Which word means 'winter'?",
          options: ["겨울", "봄", "여름", "가을"],
          accept: ["겨울"],
          explain: "« 겨울 » est le mot pour « hiver ».",
          explainEn: "'겨울' is the word for 'winter'.",
        },
      ],
    },
    {
      number: 10,
      slug: "ko-10",
      title: "Entretien : présente-toi et ton parcours",
      titleEn: "Interview: introduce yourself and your background",
      summary:
        "Préparez votre présentation d'entretien et décrivez votre parcours professionnel.",
      summaryEn:
        "Prepare your interview introduction and describe your professional background.",
      grammar: ["경력 (expérience)", "프로젝트 (projet)", "~동안 (pendant)"],
      explanation:
        "En entretien, présentez votre expérience avec « 경력 » et vos réalisations avec « 프로젝트 ». La durée se dit avec « ~동안 » : « 5년 동안 일했어요 » (j'ai travaillé pendant 5 ans).",
      explanationEn:
        "In an interview, present your experience with '경력' and your achievements with '프로젝트'. Duration is expressed with '~동안': '5년 동안 일했어요' (I worked for 5 years).",
      examples: [
        { target: "저는 5년 동안 개발자로 일했어요.", roman: "jeoneun o nyeon dongan gaebaljaro ilhaesseoyo.", fr: "J'ai travaillé comme développeur pendant 5 ans.", en: "I worked as a developer for 5 years." },
        { target: "프로젝트를 맡았어요.", roman: "peurojekteureul matasseoyo.", fr: "J'ai pris en charge un projet.", en: "I took charge of a project." },
        { target: "대학에서 컴퓨터를 전공했어요.", roman: "daehageseo keompyuteoreul jeongonghaesseoyo.", fr: "J'ai étudié l'informatique à l'université.", en: "I majored in computer science at university." },
        { target: "팀에서 함께 일했어요.", roman: "timeseo hamkke ilhaesseoyo.", fr: "J'ai travaillé en équipe.", en: "I worked together in a team." },
      ],
      vocab: [
        { target: "경력", roman: "gyeongnyeok", fr: "expérience professionnelle", en: "work experience" },
        { target: "프로젝트", roman: "peurojekteu", fr: "projet", en: "project" },
        { target: "전공하다", roman: "jeongonghada", fr: "se spécialiser", en: "to major in" },
        { target: "대학", roman: "daehak", fr: "université", en: "university" },
        { target: "팀", roman: "tim", fr: "équipe", en: "team" },
        { target: "함께", roman: "hamkke", fr: "ensemble", en: "together" },
        { target: "배우다", roman: "baeuda", fr: "apprendre", en: "to learn" },
        { target: "성장하다", roman: "seongjanghada", fr: "grandir / se développer", en: "to grow" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « J'ai travaillé pendant 5 ans » ?",
          promptEn: "How do you say 'I worked for 5 years'?",
          options: ["5년 동안 일했어요.", "5년 동안 공부해요.", "여름 동안 일해요.", "5년 동안 자요."],
          accept: ["저는 5년 동안 개발자로 일했어요."],
          explain: "« 5년 동안 » = pendant 5 ans.",
          explainEn: "'5년 동안' = for 5 years.",
        },
        {
          prompt: "Complétez : « J'ai travaillé en équipe ».",
          promptEn: "Complete: 'I worked together in a team'.",
          accept: ["팀에서 함께 일했어요."],
          explain: "« 팀에서 » = en équipe, « 함께 » = ensemble.",
          explainEn: "'팀에서' = in a team, '함께' = together.",
        },
        {
          prompt: "Que signifie « 경력 » ?",
          promptEn: "What does '경력' mean?",
          options: ["expérience professionnelle", "université", "projet", "équipe"],
          accept: ["경력"],
          explain: "« 경력 » désigne l'expérience professionnelle.",
          explainEn: "'경력' refers to professional experience.",
        },
      ],
      interview: [
        {
          question: "자기소개와 경력에 대해 말씀해 주세요.",
          roman: "jagisogae wa gyeongnyeonge daehae malsseumhae juseyo.",
          fr: "Parlez-moi de vous et de votre parcours.",
          en: "Tell me about yourself and your background.",
          modelFr: "Je m'appelle Daniel, développeur avec cinq ans d'expérience, spécialisé dans les projets web.",
          modelEn: "My name is Daniel, a developer with five years of experience, specialised in web projects.",
          accept: ["저는 5년 동안 개발자로 일했어요."],
        },
      ],
    },
    {
      number: 11,
      slug: "ko-11",
      title: "Entretien : atouts, faiblesses et motivation",
      titleEn: "Interview: strengths, weaknesses and motivation",
      summary:
        "Présentez vos atouts, admettez vos faiblesses et expliquez pourquoi vous postulez.",
      summaryEn:
        "Present your strengths, admit your weaknesses and explain why you are applying.",
      grammar: ["장점 (atout)", "단점 (faiblesse)", "지원 동기 (motivation)"],
      explanation:
        "« 장점 » signifie « point fort » et « 단점 » « point faible ». Pour motiver votre candidature, dites « 지원 동기 » et employez « 이 회사에 지원한 이유 » (la raison pour laquelle j'ai postulé ici).",
      explanationEn:
        "'장점' means 'strength' and '단점' 'weakness'. To motivate your application, say '지원 동기' and use '이 회사에 지원한 이유' (the reason I applied here).",
      examples: [
        { target: "제 장점은 꼼꼼한 것이에요.", roman: "je jangjeomeun kkomkkomhan geosiyeyo.", fr: "Mon atout, c'est d'être minutieux.", en: "My strength is being thorough." },
        { target: "제 단점은 너무 완벽을 추구하는 거예요.", roman: "je danjeomeun neomu wanbyeogeul chuguhaneun geoyeyo.", fr: "Mon défaut est de trop rechercher la perfection.", en: "My weakness is pursuing perfection too much." },
        { target: "이 회사에 지원한 이유가 뭐예요?", roman: "i hoesae jiwonhan iyuga mwoyeyo?", fr: "Pourquoi avez-vous postulé dans cette entreprise ?", en: "Why did you apply to this company?" },
        { target: "저는 열심히 일해요.", roman: "jeoneun yeolsimhi ilhaeyo.", fr: "Je travaille avec ardeur.", en: "I work hard." },
      ],
      vocab: [
        { target: "장점", roman: "jangjeom", fr: "atout / point fort", en: "strength" },
        { target: "단점", roman: "danjeom", fr: "faiblesse / point faible", en: "weakness" },
        { target: "지원 동기", roman: "jiwon donggi", fr: "motivation de candidature", en: "motive for applying" },
        { target: "열심히", roman: "yeolsimhi", fr: "avec ardeur", en: "hard / diligently" },
        { target: "꼼꼼하다", roman: "kkomkkomhada", fr: "minutieux", en: "to be thorough" },
        { target: "성실하다", roman: "seongsilhada", fr: "fiable / consciencieux", en: "to be sincere/diligent" },
        { target: "회사", roman: "hoesa", fr: "entreprise", en: "company" },
        { target: "이유", roman: "iyu", fr: "raison", en: "reason" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Mon atout, c'est d'être minutieux » ?",
          promptEn: "How do you say 'My strength is being thorough'?",
          options: ["장점은 꼼꼼한 것이에요.", "단점은 꼼꼼한 것이에요.", "장점은 빨라요.", "이 회사를 좋아해요."],
          accept: ["제 장점은 꼼꼼한 것이에요."],
          explain: "« 장점 » = atout, « 꼼꼼하다 » = minutieux.",
          explainEn: "'장점' = strength, '꼼꼼하다' = to be thorough.",
        },
        {
          prompt: "Complétez : « Pourquoi avez-vous postulé ici ? ».",
          promptEn: "Complete: 'Why did you apply here?'.",
          accept: ["이 회사에 지원한 이유가 뭐예요?"],
          explain: "« 지원한 이유 » = la raison de la candidature.",
          explainEn: "'지원한 이유' = the reason for applying.",
        },
        {
          prompt: "Quel mot signifie « point faible » ?",
          promptEn: "Which word means 'weakness'?",
          options: ["단점", "장점", "이유", "회사"],
          accept: ["단점"],
          explain: "« 단점 » désigne le point faible.",
          explainEn: "'단점' refers to a weakness.",
        },
      ],
      interview: [
        {
          question: "당신의 장점과 단점은 무엇입니까?",
          roman: "dangsinui jangjeom gwa danjeomeun mueosimnikka?",
          fr: "Quels sont vos atouts et vos faiblesses ?",
          en: "What are your strengths and weaknesses?",
          modelFr: "Mon atout est la rigueur, et je travaille à améliorer ma prise de parole en public.",
          modelEn: "My strength is rigour, and I am working to improve my public speaking.",
          accept: ["제 장점은 꼼꼼한 것이에요."],
        },
        {
          question: "이 회사에 지원한 이유가 무엇입니까?",
          roman: "i hoesae jiwonhan iyuga mueosimnikka?",
          fr: "Pourquoi avez-vous postulé dans cette entreprise ?",
          en: "Why did you apply to this company?",
          modelFr: "Parce que votre entreprise est innovante et que je veux y grandir professionnellement.",
          modelEn: "Because your company is innovative and I want to grow professionally here.",
          accept: ["이 회사가 혁신적이어서 지원했어요."],
        },
      ],
    },
    {
      number: 12,
      slug: "ko-12",
      title: "Entretien : projets, équipe et gestion du stress",
      titleEn: "Interview: goals, teamwork and stress management",
      summary:
        "Parlez de vos projets futurs, du travail d'équipe et de la manière de gérer le stress.",
      summaryEn:
        "Talk about your future plans, teamwork and how you manage stress.",
      grammar: ["계획 (plan)", "협동 (coopération)", "스트레스 관리 (gestion du stress)"],
      explanation:
        "« 계획 » signifie « plan / projet » : on décrit ses ambitions avec « 5년 후에... » (dans cinq ans). « 협동 » désigne le travail d'équipe et « 스트레스 관리 » la gestion du stress, sujet fréquent en entretien.",
      explanationEn:
        "'계획' means 'plan / goal': you describe your ambitions with '5년 후에...' (in five years). '협동' refers to teamwork and '스트레스 관리' to stress management, a frequent interview topic.",
      examples: [
        { target: "5년 후에 팀장이 되고 싶어요.", roman: "o nyeon hue timjangi doego sipeoyo.", fr: "Dans cinq ans, je veux devenir chef d'équipe.", en: "In five years, I want to become a team leader." },
        { target: "협동이 중요해요.", roman: "hyeopdongi jungyohaeyo.", fr: "La coopération est importante.", en: "Cooperation is important." },
        { target: "스트레스는 운동으로 관리해요.", roman: "seuteureseuneun undongeuro gwallihaeyo.", fr: "Je gère le stress par le sport.", en: "I manage stress through exercise." },
        { target: "저는 함께 목표를 이루고 싶어요.", roman: "jeoneun hamkke mokpyoreul irugo sipeoyo.", fr: "Je veux atteindre l'objectif ensemble.", en: "I want to achieve the goal together." },
      ],
      vocab: [
        { target: "계획", roman: "gyehoek", fr: "plan / projet", en: "plan / goal" },
        { target: "협동", roman: "hyeopdong", fr: "coopération", en: "cooperation" },
        { target: "스트레스", roman: "seuteureseu", fr: "stress", en: "stress" },
        { target: "관리하다", roman: "gwallihada", fr: "gérer", en: "to manage" },
        { target: "목표", roman: "mokpyo", fr: "objectif", en: "goal" },
        { target: "이루다", roman: "iruda", fr: "réaliser / atteindre", en: "to achieve" },
        { target: "팀장", roman: "timjang", fr: "chef d'équipe", en: "team leader" },
        { target: "운동", roman: "undong", fr: "sport / exercice", en: "exercise" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « Je gère le stress par le sport » ?",
          promptEn: "How do you say 'I manage stress through exercise'?",
          options: ["운동으로 관리해요.", "운동을 좋아해요.", "팀에서 운동해요.", "목표가 있어요."],
          accept: ["스트레스는 운동으로 관리해요."],
          explain: "« 스트레스 » = stress, « 운동 » = sport.",
          explainEn: "'스트레스' = stress, '운동' = exercise.",
        },
        {
          prompt: "Complétez : « Dans cinq ans, je veux devenir chef d'équipe ».",
          promptEn: "Complete: 'In five years, I want to become a team leader'.",
          accept: ["5년 후에 팀장이 되고 싶어요."],
          explain: "« 5년 후에 » = dans cinq ans, « 되고 싶어요 » = je veux devenir.",
          explainEn: "'5년 후에' = in five years, '되고 싶어요' = I want to become.",
        },
        {
          prompt: "Que signifie « 협동 » ?",
          promptEn: "What does '협동' mean?",
          options: ["coopération", "stress", "objectif", "plan"],
          accept: ["협동"],
          explain: "« 협동 » signifie « coopération / travail d'équipe ».",
          explainEn: "'협동' means 'cooperation / teamwork'.",
        },
      ],
      interview: [
        {
          question: "5년 후의 자신은 어떤 사람이 되고 싶습니까?",
          roman: "o nyeon huui jasineun eotteon sarami doego sipeumnikka?",
          fr: "Que voulez-vous être dans cinq ans ?",
          en: "What do you want to become in five years?",
          modelFr: "Dans cinq ans, je veux diriger des projets et faire grandir mon équipe.",
          modelEn: "In five years, I want to lead projects and help my team grow.",
          accept: ["5년 후에 팀장이 되고 싶어요."],
        },
        {
          question: "팀에서 어떻게 협동합니까?",
          roman: "timeseo eotteoke hyeopdonghamnikka?",
          fr: "Comment coopérez-vous au sein d'une équipe ?",
          en: "How do you cooperate within a team?",
          modelFr: "J'écoute mes collègues, je partage les idées et j'atteins l'objectif ensemble.",
          modelEn: "I listen to my colleagues, share ideas and reach the goal together.",
          accept: ["동료들과 함께 목표를 이루려고 해요."],
        },
        {
          question: "스트레스를 어떻게 관리합니까?",
          roman: "seuteureseureul eotteoke gwallihamnikka?",
          fr: "Comment gérez-vous le stress ?",
          en: "How do you manage stress?",
          modelFr: "Je fais du sport et j'organise mes priorités pour rester efficace.",
          modelEn: "I exercise and organise my priorities to stay efficient.",
          accept: ["운동하고 우선순위를 정해요."],
        },
      ],
    },
  ],
};
