import type { LanguageCourse } from "./genericLessons";

export const RU_COURSE: LanguageCourse = {
  code: "ru",
  name: "Russe",
  native: "Русский",
  heroTitle1: { fr: "Apprenez", en: "Learn" },
  heroTitle2: { fr: "le russe", en: "Russian" },
  heroSubtitle: {
    fr: "Un parcours débutant en douze leçons : salutations, vie quotidienne, travail et entretien d'embauche.",
    en: "A beginner path in twelve lessons: greetings, daily life, work and job interviews.",
  },
  lessons: [
    {
      number: 1,
      slug: "ru-01",
      title: "Se présenter et saluer",
      titleEn: "Introducing yourself and greeting",
      summary: "Les salutations de base et les premières présentations : dire son nom et son origine.",
      summaryEn: "Basic greetings and first introductions: giving your name and your origin.",
      grammar: ["Здравствуйте и приветствия", "Меня зовут ... (je m'appelle)", "Я из ... (je suis de ...)"],
      explanation:
        "On commence une conversation en russe par « Здравствуйте » (bonjour, forme polie) ou « Привет » (salut, familier). Pour se présenter, on dit « Меня зовут ... » (littéralement « on m'appelle ... »). Pour indiquer son origine, on emploie la préposition « из » suivie du génitif : « Я из Франции » (je suis de France). Enfin, « Очень приятно » signifie « enchanté » et se dit à la fin des présentations.",
      explanationEn:
        "In Russian, a conversation starts with \"Здравствуйте\" (hello, polite form) or \"Привет\" (hi, informal). To introduce yourself, you say \"Меня зовут ...\" (literally \"they call me ...\"). To give your origin, you use the preposition \"из\" followed by the genitive: \"Я из Франции\" (I am from France). Finally, \"Очень приятно\" means \"nice to meet you\" and is said at the end of introductions.",
      examples: [
        { target: "Здравствуйте, меня зовут Даниэль.", roman: "Zdravstvuyte, menya zovut Daniyel.", fr: "Bonjour, je m'appelle Daniel.", en: "Hello, my name is Daniel." },
        { target: "Я из Франции.", roman: "Ya iz Frantsii.", fr: "Je viens de France.", en: "I am from France." },
        { target: "Как вас зовут?", roman: "Kak vas zovut?", fr: "Comment vous appelez-vous ?", en: "What is your name?" },
        { target: "Очень приятно, добро пожаловать!", roman: "Ochen priyatno, dobro pozhalovat!", fr: "Enchanté, bienvenue !", en: "Nice to meet you, welcome!" },
      ],
      vocab: [
        { target: "здравствуйте", roman: "zdravstvuyte", fr: "bonjour (poli)", en: "hello (formal)" },
        { target: "привет", roman: "privet", fr: "salut", en: "hi" },
        { target: "меня зовут", roman: "menya zovut", fr: "je m'appelle", en: "my name is" },
        { target: "имя", roman: "imya", fr: "nom, prénom", en: "name" },
        { target: "из", roman: "iz", fr: "de, depuis", en: "from" },
        { target: "очень приятно", roman: "ochen priyatno", fr: "enchanté", en: "nice to meet you" },
        { target: "как дела?", roman: "kak dela?", fr: "comment vas-tu ?", en: "how are you?" },
        { target: "добро пожаловать", roman: "dobro pozhalovat", fr: "bienvenue", en: "welcome" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Bonjour, je m'appelle Anna » → « Здравствуйте, ___ зовут Анна ».",
          promptEn: "Complete: \"Hello, my name is Anna\" → \"Здравствуйте, ___ зовут Анна\".",
          options: ["меня", "тебя", "его", "нас"],
          accept: ["меня"],
          explain: "« Меня зовут » signifie « je m'appelle » : le pronom меня (moi) précède зовут (ils appellent).",
          explainEn: "\"Меня зовут\" means \"my name is\": the pronoun меня (me) comes before зовут (they call).",
        },
        {
          prompt: "Comment salue-t-on de façon polie en russe ?",
          promptEn: "How do you greet someone politely in Russian?",
          options: ["здравствуйте", "пока", "спасибо", "извините"],
          accept: ["здравствуйте"],
          explain: "« Здравствуйте » est la salutation polie ; « пока » signifie « au revoir ».",
          explainEn: "\"Здравствуйте\" is the polite greeting; \"пока\" means \"goodbye\".",
        },
        {
          prompt: "Complétez : « Je suis de France » → « Я ___ Франции ».",
          promptEn: "Complete: \"I am from France\" → \"Я ___ Франции\".",
          accept: ["из"],
          explain: "La préposition « из » exprime la provenance et se construit avec le génitif : из Франции.",
          explainEn: "The preposition \"из\" expresses origin and takes the genitive: из Франции.",
        },
      ],
      interview: [
        {
          question: "Расскажите о себе.",
          roman: "Rasskazhite o sebe.",
          fr: "Pouvez-vous vous présenter ?",
          en: "Can you introduce yourself?",
          modelFr: "Je m'appelle Daniel, je viens de France et je suis développeur.",
          modelEn: "My name is Daniel, I come from France and I am a developer.",
          accept: ["Меня зовут Даниэль", "Я из Франции", "Я разработчик", "Мне 28 лет", "Очень приятно"],
        },
      ],
    },
    {
      number: 2,
      slug: "ru-02",
      title: "Origine, nationalité et profession",
      titleEn: "Origin, nationality and profession",
      summary: "Dire sa nationalité, son métier et le lieu où l'on vit.",
      summaryEn: "Saying your nationality, your job and where you live.",
      grammar: ["Я ... (je suis + nationalité/profession)", "Я живу в ... (prépositionnel)", "Я работаю ... (instrumental)"],
      explanation:
        "La nationalité et le métier se forment directement avec le verbe « быть » sous-entendu : « Я француз » (je suis français), « Я врач » (je suis médecin) à l'instrumental « Я работаю врачом ». Pour dire où l'on vit, on utilise le prépositionnel : « Я живу в Париже » (je vis à Paris), la préposition « в » indiquant le lieu.",
      explanationEn:
        "Nationality and profession are built with the verb \"to be\" implied: \"Я француз\" (I am French), \"Я врач\" (I am a doctor); with a job you use the instrumental \"Я работаю врачом\". To say where you live, you use the prepositional case: \"Я живу в Париже\" (I live in Paris); the preposition \"в\" indicates the place.",
      examples: [
        { target: "Я француз.", roman: "Ya frantsuz.", fr: "Je suis français.", en: "I am French." },
        { target: "Я работаю врачом.", roman: "Ya rabotayu vrachom.", fr: "Je travaille comme médecin.", en: "I work as a doctor." },
        { target: "Я живу в Париже.", roman: "Ya zhivu v Parizhe.", fr: "Je vis à Paris.", en: "I live in Paris." },
        { target: "Он инженер.", roman: "On inzhener.", fr: "C'est un ingénieur.", en: "He is an engineer." },
      ],
      vocab: [
        { target: "француз", roman: "frantsuz", fr: "français (homme)", en: "Frenchman" },
        { target: "русский", roman: "russkiy", fr: "russe", en: "Russian" },
        { target: "врач", roman: "vrach", fr: "médecin", en: "doctor" },
        { target: "учитель", roman: "uchitel", fr: "professeur", en: "teacher" },
        { target: "инженер", roman: "inzhener", fr: "ingénieur", en: "engineer" },
        { target: "студент", roman: "student", fr: "étudiant", en: "student" },
        { target: "я живу", roman: "ya zhivu", fr: "je vis", en: "I live" },
        { target: "где ты живёшь?", roman: "gde ty zhivyosh?", fr: "où habites-tu ?", en: "where do you live?" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Je suis russe » → « Я ___ ».",
          promptEn: "Complete: \"I am Russian\" → \"Я ___\".",
          options: ["русский", "немец", "китаец", "француз"],
          accept: ["русский"],
          explain: "« Русский » désigne l'homme russe, forme simple du verbe être : Я русский.",
          explainEn: "\"Русский\" means Russian (male), the simple form of the verb to be: Я русский.",
        },
        {
          prompt: "Comment dit-on « ingénieur » ?",
          promptEn: "How do you say \"engineer\"?",
          options: ["инженер", "врач", "учитель", "студент"],
          accept: ["инженер"],
          explain: "« Инженер » est l'ingénieur ; врач est le médecin, учитель le professeur, студент l'étudiant.",
          explainEn: "\"Инженер\" is the engineer; врач is the doctor, учитель the teacher, студент the student.",
        },
        {
          prompt: "Complétez : « Je vis à Moscou » → « Я ___ в Москве ».",
          promptEn: "Complete: \"I live in Moscow\" → \"Я ___ в Москве\".",
          accept: ["живу"],
          explain: "« Жить » (vivre) se conjugue « я живу » : Я живу в Москве.",
          explainEn: "\"Жить\" (to live) conjugates \"я живу\": Я живу в Москве.",
        },
      ],
    },
    {
      number: 3,
      slug: "ru-03",
      title: "Être et avoir",
      titleEn: "To be and to have",
      summary: "Le verbe être et l'expression de la possession avec « у меня есть ».",
      summaryEn: "The verb to be and expressing possession with \"у меня есть\".",
      grammar: ["Быть au présent (omis)", "У меня есть ... (j'ai)", "У меня нет ... (je n'ai pas)"],
      explanation:
        "Au présent, le verbe « быть » (être) s'omet généralement : « Я студент » (je suis étudiant). La possession se dit avec « у меня есть » (littéralement « auprès de moi il y a ») : « У меня есть машина » (j'ai une voiture). La négation utilise « нет » suivi du génitif : « У меня нет времени » (je n'ai pas de temps).",
      explanationEn:
        "In the present tense, the verb \"быть\" (to be) is generally omitted: \"Я студент\" (I am a student). Possession is expressed with \"у меня есть\" (literally \"by me there is\"): \"У меня есть машина\" (I have a car). Negation uses \"нет\" followed by the genitive: \"У меня нет времени\" (I have no time).",
      examples: [
        { target: "Я студент.", roman: "Ya student.", fr: "Je suis étudiant.", en: "I am a student." },
        { target: "У меня есть машина.", roman: "U menya yest mashina.", fr: "J'ai une voiture.", en: "I have a car." },
        { target: "У меня нет времени.", roman: "U menya net vremeni.", fr: "Je n'ai pas de temps.", en: "I have no time." },
        { target: "У нас есть большой офис.", roman: "U nas yest bolshoy ofis.", fr: "Nous avons un grand bureau.", en: "We have a big office." },
      ],
      vocab: [
        { target: "быть", roman: "byt", fr: "être", en: "to be" },
        { target: "у меня есть", roman: "u menya yest", fr: "j'ai", en: "I have" },
        { target: "нет", roman: "net", fr: "non, il n'y a pas", en: "no, there is not" },
        { target: "машина", roman: "mashina", fr: "voiture", en: "car" },
        { target: "время", roman: "vremya", fr: "temps", en: "time" },
        { target: "офис", roman: "ofis", fr: "bureau", en: "office" },
        { target: "дом", roman: "dom", fr: "maison", en: "house" },
        { target: "большой", roman: "bolshoy", fr: "grand", en: "big" },
      ],
      exercises: [
        {
          prompt: "Complétez : « J'ai une voiture » → « У меня ___ машина ».",
          promptEn: "Complete: \"I have a car\" → \"У меня ___ машина\".",
          options: ["есть", "нет", "быть", "живу"],
          accept: ["есть"],
          explain: "« У меня есть » exprime la possession : У меня есть машина.",
          explainEn: "\"У меня есть\" expresses possession: У меня есть машина.",
        },
        {
          prompt: "Que dit-on pour exprimer la possession (« j'ai ») ?",
          promptEn: "How do you express possession (\"I have\")?",
          options: ["у меня есть", "я есть", "мне есть", "у тебя"],
          accept: ["у меня есть"],
          explain: "La possession se dit « у меня есть » ; « я есть » n'est pas utilisé ainsi en russe.",
          explainEn: "Possession uses \"у меня есть\"; \"я есть\" is not used this way in Russian.",
        },
        {
          prompt: "Complétez : « Je n'ai pas de temps » → « У меня ___ времени ».",
          promptEn: "Complete: \"I have no time\" → \"У меня ___ времени\".",
          accept: ["нет"],
          explain: "La négation de possession se fait avec « нет » + génitif : У меня нет времени.",
          explainEn: "Negated possession uses \"нет\" + genitive: У меня нет времени.",
        },
      ],
    },
    {
      number: 4,
      slug: "ru-04",
      title: "La routine quotidienne",
      titleEn: "Daily routine",
      summary: "Décrire sa journée : se lever, travailler, se reposer.",
      summaryEn: "Describing your day: getting up, working, resting.",
      grammar: ["Настоящее время: я встаю", "Я работаю каждый день", "Сначала ... потом ..."],
      explanation:
        "Les verbes russes se conjuguent au présent. « Вставать » (se lever) → « я встаю » (je me lève) ; « работать » (travailler) → « я работаю » (je travaille). On enchaîne les actions avec des adverbes : « сначала » (d'abord), « потом » (ensuite). La fréquence se dit avec « каждый день » (chaque jour) et « обычно » (d'habitude).",
      explanationEn:
        "Russian verbs conjugate in the present. \"Вставать\" (to get up) → \"я встаю\" (I get up); \"работать\" (to work) → \"я работаю\" (I work). You link actions with adverbs: \"сначала\" (first), \"потом\" (then). Frequency is expressed with \"каждый день\" (every day) and \"обычно\" (usually).",
      examples: [
        { target: "Я встаю в семь часов.", roman: "Ya vstayu v sem chasov.", fr: "Je me lève à sept heures.", en: "I get up at seven o'clock." },
        { target: "Я работаю каждый день.", roman: "Ya rabotayu kazhdyy den.", fr: "Je travaille chaque jour.", en: "I work every day." },
        { target: "Сначала я пью кофе, потом работаю.", roman: "Snachala ya pyu kofe, potom rabotayu.", fr: "D'abord je bois un café, ensuite je travaille.", en: "First I drink coffee, then I work." },
        { target: "Вечером я отдыхаю.", roman: "Vecherom ya otdykhayu.", fr: "Le soir je me repose.", en: "In the evening I rest." },
      ],
      vocab: [
        { target: "вставать", roman: "vstavat", fr: "se lever", en: "to get up" },
        { target: "работать", roman: "rabotat", fr: "travailler", en: "to work" },
        { target: "отдыхать", roman: "otdykhat", fr: "se reposer", en: "to rest" },
        { target: "пить кофе", roman: "pit kofe", fr: "boire un café", en: "to drink coffee" },
        { target: "каждый день", roman: "kazhdyy den", fr: "chaque jour", en: "every day" },
        { target: "сначала", roman: "snachala", fr: "d'abord", en: "first" },
        { target: "потом", roman: "potom", fr: "ensuite", en: "then" },
        { target: "утром", roman: "utrom", fr: "le matin", en: "in the morning" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Je me lève à sept heures » → « Я ___ в семь часов ».",
          promptEn: "Complete: \"I get up at seven o'clock\" → \"Я ___ в семь часов\".",
          options: ["встаю", "работаю", "отдыхаю", "живу"],
          accept: ["встаю"],
          explain: "« Встаю » est la 1re personne du présent de вставать (se lever).",
          explainEn: "\"Встаю\" is the 1st person present of вставать (to get up).",
        },
        {
          prompt: "Comment dit-on « chaque jour » ?",
          promptEn: "How do you say \"every day\"?",
          options: ["каждый день", "вчера", "завтра", "вечером"],
          accept: ["каждый день"],
          explain: "« Каждый день » = chaque jour ; вчера = hier, завтра = demain.",
          explainEn: "\"Каждый день\" = every day; вчера = yesterday, завтра = tomorrow.",
        },
        {
          prompt: "Complétez : « D'abord je bois un café » → « ___ я пью кофе ».",
          promptEn: "Complete: \"First I drink coffee\" → \"___ я пью кофе\".",
          accept: ["сначала"],
          explain: "« Сначала » signifie « d'abord » et introduit la première action.",
          explainEn: "\"Сначала\" means \"first\" and introduces the first action.",
        },
      ],
    },
    {
      number: 5,
      slug: "ru-05",
      title: "Les goûts et loisirs",
      titleEn: "Likes and hobbies",
      summary: "Exprimer ses goûts avec « мне нравится » et parler de ses loisirs.",
      summaryEn: "Expressing likes with \"мне нравится\" and talking about hobbies.",
      grammar: ["Мне нравится + singulier", "Мне нравятся + pluriel", "Я люблю ..."],
      explanation:
        "Pour dire qu'on aime, on emploie « мне нравится » (littéralement « à moi plaît ») devant un verbe ou un nom singulier : « Мне нравится читать » (j'aime lire). Au pluriel on dit « мне нравятся » : « Мне нравятся книги » (j'aime les livres). Plus fort, « я люблю » exprime l'amour : « Я люблю музыку » (j'aime la musique).",
      explanationEn:
        "To say you like something, you use \"мне нравится\" (literally \"to me it pleases\") before a verb or a singular noun: \"Мне нравится читать\" (I like to read). In the plural you say \"мне нравятся\": \"Мне нравятся книги\" (I like books). Stronger, \"я люблю\" expresses love: \"Я люблю музыку\" (I love music).",
      examples: [
        { target: "Мне нравится читать.", roman: "Mne nravitsya chitat.", fr: "J'aime lire.", en: "I like to read." },
        { target: "Мне нравятся книги.", roman: "Mne nravyatsya knigi.", fr: "J'aime les livres.", en: "I like books." },
        { target: "Я люблю музыку.", roman: "Ya lyublyu muzyku.", fr: "J'aime la musique.", en: "I love music." },
        { target: "В свободное время я гуляю.", roman: "V svobodnoye vremya ya gulyayu.", fr: "Pendant mon temps libre, je me promène.", en: "In my free time I go for walks." },
      ],
      vocab: [
        { target: "мне нравится", roman: "mne nravitsya", fr: "j'aime (ça me plaît)", en: "I like (it pleases me)" },
        { target: "нравиться", roman: "nravitsya", fr: "plaire", en: "to please" },
        { target: "читать", roman: "chitat", fr: "lire", en: "to read" },
        { target: "книги", roman: "knigi", fr: "livres", en: "books" },
        { target: "музыка", roman: "muzyka", fr: "musique", en: "music" },
        { target: "спорт", roman: "sport", fr: "sport", en: "sport" },
        { target: "свободное время", roman: "svobodnoye vremya", fr: "temps libre", en: "free time" },
        { target: "любить", roman: "lyubit", fr: "aimer", en: "to love" },
      ],
      exercises: [
        {
          prompt: "Complétez : « J'aime lire » → « Мне ___ читать ».",
          promptEn: "Complete: \"I like to read\" → \"Мне ___ читать\".",
          options: ["нравится", "нравятся", "люблю", "есть"],
          accept: ["нравится"],
          explain: "Devant un verbe à l'infinitif, on utilise « мне нравится » (au singulier).",
          explainEn: "Before an infinitive verb, you use \"мне нравится\" (singular).",
        },
        {
          prompt: "Complétez : « J'aime les livres » → « Мне ___ книги ».",
          promptEn: "Complete: \"I like books\" → \"Мне ___ книги\".",
          options: ["нравятся", "нравится", "нравиться", "любят"],
          accept: ["нравятся"],
          explain: "Avec un sujet pluriel (книги), on emploie « мне нравятся ».",
          explainEn: "With a plural subject (книги), you use \"мне нравятся\".",
        },
        {
          prompt: "Comment dit-on « le temps libre » ?",
          promptEn: "How do you say \"free time\"?",
          options: ["свободное время", "каждый день", "книга", "утро"],
          accept: ["свободное время"],
          explain: "« Свободное время » = le temps libre ; книга = livre.",
          explainEn: "\"Свободное время\" = free time; книга = book.",
        },
      ],
    },
    {
      number: 6,
      slug: "ru-06",
      title: "La famille et les personnes",
      titleEn: "Family and people",
      summary: "Parler de sa famille, de ses proches et des personnes qui l'entourent.",
      summaryEn: "Talking about your family, relatives and people around you.",
      grammar: ["Моя семья", "У меня есть мать и отец", "Притяжательные: моя, мой, моё"],
      explanation:
        "Pour décrire sa famille : « У меня есть мать и отец » (j'ai une mère et un père). Les possessifs s'accordent en genre : « мой брат » (mon frère, masculin), « моя сестра » (ma sœur, féminin), « моё имя » (mon prénom, neutre). On dit l'âge avec « мне ... лет » : « Мне двадцать пять лет » (j'ai 25 ans).",
      explanationEn:
        "To describe your family: \"У меня есть мать и отец\" (I have a mother and a father). Possessives agree in gender: \"мой брат\" (my brother, masculine), \"моя сестра\" (my sister, feminine), \"моё имя\" (my name, neuter). You say age with \"мне ... лет\": \"Мне двадцать пять лет\" (I am 25 years old).",
      examples: [
        { target: "У меня есть мать и отец.", roman: "U menya yest mat i otets.", fr: "J'ai une mère et un père.", en: "I have a mother and a father." },
        { target: "Это мой брат.", roman: "Eto moy brat.", fr: "C'est mon frère.", en: "This is my brother." },
        { target: "Это моя сестра.", roman: "Eto moya sestra.", fr: "C'est ma sœur.", en: "This is my sister." },
        { target: "Мне двадцать пять лет.", roman: "Mne dvadtsat pyat let.", fr: "J'ai vingt-cinq ans.", en: "I am twenty-five years old." },
      ],
      vocab: [
        { target: "семья", roman: "semya", fr: "famille", en: "family" },
        { target: "мать", roman: "mat", fr: "mère", en: "mother" },
        { target: "отец", roman: "otets", fr: "père", en: "father" },
        { target: "брат", roman: "brat", fr: "frère", en: "brother" },
        { target: "сестра", roman: "sestra", fr: "sœur", en: "sister" },
        { target: "сын", roman: "syn", fr: "fils", en: "son" },
        { target: "дочь", roman: "doch", fr: "fille", en: "daughter" },
        { target: "жена", roman: "zhena", fr: "femme, épouse", en: "wife" },
      ],
      exercises: [
        {
          prompt: "Complétez : « C'est mon frère » → « Это ___ брат ».",
          promptEn: "Complete: \"This is my brother\" → \"Это ___ брат\".",
          options: ["мой", "моя", "моё", "мои"],
          accept: ["мой"],
          explain: "« Брат » est masculin, on emploie le possessif masculin « мой ».",
          explainEn: "\"Брат\" is masculine, so you use the masculine possessive \"мой\".",
        },
        {
          prompt: "Comment dit-on « ma sœur » ?",
          promptEn: "How do you say \"my sister\"?",
          options: ["моя сестра", "мой брат", "мой сын", "моя мать"],
          accept: ["моя сестра"],
          explain: "« Сестра » est féminin, d'où le possessif féminin « моя » : моя сестра.",
          explainEn: "\"Сестра\" is feminine, hence the feminine possessive \"моя\": моя сестра.",
        },
        {
          prompt: "Complétez : « J'ai 25 ans » → « Мне ___ лет ».",
          promptEn: "Complete: \"I am 25 years old\" → \"Мне ___ лет\".",
          accept: ["двадцать пять"],
          explain: "Après 5-20 et les dizaines on dit « лет » : мне двадцать пять лет.",
          explainEn: "After 5-20 and tens you say \"лет\": мне двадцать пять лет.",
        },
      ],
    },
    {
      number: 7,
      slug: "ru-07",
      title: "Le travail et le bureau",
      titleEn: "Work and the office",
      summary: "Vocabulaire professionnel, le bureau, les réunions et les collègues.",
      summaryEn: "Work vocabulary, the office, meetings and colleagues.",
      grammar: ["Я работаю в компании", "Коллеги и встречи", "Я занят / Я свободен"],
      explanation:
        "Pour parler de son travail : « Я работаю в компании » (je travaille dans une entreprise). La fonction se met à l'instrumental : « Я работаю менеджером » (je travaille comme manager). Le bureau se dit « офис », la réunion « встреча », les collègues « коллеги ». Pour dire qu'on est occupé : « я занят » ; libre : « я свободен ».",
      explanationEn:
        "To talk about your work: \"Я работаю в компании\" (I work at a company). The position goes into the instrumental: \"Я работаю менеджером\" (I work as a manager). The office is \"офис\", the meeting \"встреча\", colleagues \"коллеги\". To say you are busy: \"я занят\"; free: \"я свободен\".",
      examples: [
        { target: "Я работаю в компании.", roman: "Ya rabotayu v kompanii.", fr: "Je travaille dans une entreprise.", en: "I work at a company." },
        { target: "Я работаю менеджером.", roman: "Ya rabotayu menedzherom.", fr: "Je travaille comme manager.", en: "I work as a manager." },
        { target: "У нас сегодня встреча.", roman: "U nas segodnya vstrecha.", fr: "Nous avons une réunion aujourd'hui.", en: "We have a meeting today." },
        { target: "Мои коллеги очень добрые.", roman: "Moi kollegi ochen dobrye.", fr: "Mes collègues sont très gentils.", en: "My colleagues are very kind." },
      ],
      vocab: [
        { target: "работа", roman: "rabota", fr: "travail", en: "work" },
        { target: "офис", roman: "ofis", fr: "bureau", en: "office" },
        { target: "компания", roman: "kompaniya", fr: "entreprise", en: "company" },
        { target: "менеджер", roman: "menedzher", fr: "manager", en: "manager" },
        { target: "встреча", roman: "vstrecha", fr: "réunion, rencontre", en: "meeting" },
        { target: "коллеги", roman: "kollegi", fr: "collègues", en: "colleagues" },
        { target: "я занят", roman: "ya zanyat", fr: "je suis occupé", en: "I am busy" },
        { target: "я свободен", roman: "ya svoboden", fr: "je suis libre", en: "I am free" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Je travaille comme manager » → « Я работаю ___ ».",
          promptEn: "Complete: \"I work as a manager\" → \"Я работаю ___\".",
          options: ["менеджером", "менеджер", "менеджеры", "менеджеру"],
          accept: ["менеджером"],
          explain: "La fonction se met à l'instrumental : я работаю менеджером.",
          explainEn: "The position goes into the instrumental: я работаю менеджером.",
        },
        {
          prompt: "Comment dit-on « la réunion » ?",
          promptEn: "How do you say \"meeting\"?",
          options: ["встреча", "офис", "коллеги", "работа"],
          accept: ["встреча"],
          explain: "« Встреча » = réunion ; офис = bureau, коллеги = collègues.",
          explainEn: "\"Встреча\" = meeting; офис = office, коллеги = colleagues.",
        },
        {
          prompt: "Complétez : « Nous avons une réunion » → « У нас сегодня ___ ».",
          promptEn: "Complete: \"We have a meeting\" → \"У нас сегодня ___\".",
          accept: ["встреча"],
          explain: "« У нас сегодня встреча » : l'expression « у нас » signifie « nous avons ».",
          explainEn: "\"У нас сегодня встреча\": the expression \"у нас\" means \"we have\".",
        },
      ],
    },
    {
      number: 8,
      slug: "ru-08",
      title: "Faire des achats et commander",
      titleEn: "Shopping and ordering",
      summary: "Au marché et au restaurant : acheter, commander et demander le prix.",
      summaryEn: "At the market and restaurant: buying, ordering and asking the price.",
      grammar: ["Сколько стоит? (le prix)", "Я хочу ... (je veux)", "Дайте, пожалуйста ..."],
      explanation:
        "Au marché, on demande le prix avec « Сколько стоит? » (combien ça coûte ?). Pour commander on dit « Я хочу ... » (je veux ...) ou « Дайте, пожалуйста ... » (donnez-moi s'il vous plaît ...). La politesse passe par « пожалуйста » (s'il vous plaît) et « спасибо » (merci). Les noms de produits se déclinent à l'accusatif.",
      explanationEn:
        "At the market, you ask the price with \"Сколько стоит?\" (how much does it cost?). To order you say \"Я хочу ...\" (I want ...) or \"Дайте, пожалуйста ...\" (give me, please ...). Politeness comes through \"пожалуйста\" (please) and \"спасибо\" (thank you). Product nouns go into the accusative case.",
      examples: [
        { target: "Сколько стоит это яблоко?", roman: "Skolko stoit eto yabloko?", fr: "Combien coûte cette pomme ?", en: "How much does this apple cost?" },
        { target: "Я хочу чашку кофе.", roman: "Ya khochu chashku kofe.", fr: "Je veux une tasse de café.", en: "I want a cup of coffee." },
        { target: "Дайте, пожалуйста, два хлеба.", roman: "Dayte, pozhaluysta, dva khleba.", fr: "Donnez-moi deux pains, s'il vous plaît.", en: "Give me two loaves of bread, please." },
        { target: "Спасибо, это всё.", roman: "Spasibo, eto vsyo.", fr: "Merci, c'est tout.", en: "Thank you, that's all." },
      ],
      vocab: [
        { target: "рынок", roman: "rynok", fr: "marché", en: "market" },
        { target: "ресторан", roman: "restoran", fr: "restaurant", en: "restaurant" },
        { target: "сколько стоит?", roman: "skolko stoit?", fr: "combien ça coûte ?", en: "how much does it cost?" },
        { target: "я хочу", roman: "ya khochu", fr: "je veux", en: "I want" },
        { target: "пожалуйста", roman: "pozhaluysta", fr: "s'il vous plaît", en: "please" },
        { target: "спасибо", roman: "spasibo", fr: "merci", en: "thank you" },
        { target: "хлеб", roman: "khleb", fr: "pain", en: "bread" },
        { target: "яблоко", roman: "yabloko", fr: "pomme", en: "apple" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Combien coûte cette pomme ? » → « ___ стоит это яблоко? »",
          promptEn: "Complete: \"How much does this apple cost?\" → \"___ стоит это яблоко?\"",
          options: ["сколько", "почему", "когда", "где"],
          accept: ["сколько"],
          explain: "« Сколько стоит? » demande le prix ; почему = pourquoi, когда = quand.",
          explainEn: "\"Сколько стоит?\" asks the price; почему = why, когда = when.",
        },
        {
          prompt: "Comment dit-on « s'il vous plaît » ?",
          promptEn: "How do you say \"please\"?",
          options: ["пожалуйста", "спасибо", "извините", "да"],
          accept: ["пожалуйста"],
          explain: "« Пожалуйста » = s'il vous plaît ; спасибо = merci.",
          explainEn: "\"Пожалуйста\" = please; спасибо = thank you.",
        },
        {
          prompt: "Complétez : « Je veux un café » → « Я ___ кофе ».",
          promptEn: "Complete: \"I want a coffee\" → \"Я ___ кофе\".",
          accept: ["хочу"],
          explain: "« Хотеть » (vouloir) se conjugue « я хочу » : Я хочу кофе.",
          explainEn: "\"Хотеть\" (to want) conjugates \"я хочу\": Я хочу кофе.",
        },
      ],
    },
    {
      number: 9,
      slug: "ru-09",
      title: "Le temps, les saisons et l'heure",
      titleEn: "Weather, seasons and time",
      summary: "Parler de la météo, des saisons et donner l'heure.",
      summaryEn: "Talking about the weather, seasons and telling the time.",
      grammar: ["Сегодня холодно / жарко", "Четыре сезона", "Который час?"],
      explanation:
        "La météo se dit avec des adverbes impersonnels : « Сегодня холодно » (il fait froid aujourd'hui), « жарко » (il fait chaud), « дождь » (il pleut). Les saisons : « весна » (printemps), « лето » (été), « осень » (automne), « зима » (hiver). Pour l'heure : « Который час? » (quelle heure est-il ?) → « Сейчас два часа » (il est deux heures).",
      explanationEn:
        "Weather is expressed with impersonal adverbs: \"Сегодня холодно\" (it is cold today), \"жарко\" (it is hot), \"дождь\" (it rains). The seasons: \"весна\" (spring), \"лето\" (summer), \"осень\" (autumn), \"зима\" (winter). For the time: \"Который час?\" (what time is it?) → \"Сейчас два часа\" (it is two o'clock).",
      examples: [
        { target: "Сегодня холодно.", roman: "Segodnya kholodno.", fr: "Il fait froid aujourd'hui.", en: "It is cold today." },
        { target: "Летом жарко, зимой холодно.", roman: "Letom zharko, zimoy kholodno.", fr: "En été il fait chaud, en hiver il fait froid.", en: "In summer it is hot, in winter it is cold." },
        { target: "Который час?", roman: "Kotoryy chas?", fr: "Quelle heure est-il ?", en: "What time is it?" },
        { target: "Сейчас два часа.", roman: "Seichas dva chasa.", fr: "Il est deux heures.", en: "It is two o'clock." },
      ],
      vocab: [
        { target: "погода", roman: "pogoda", fr: "météo, temps", en: "weather" },
        { target: "холодно", roman: "kholodno", fr: "il fait froid", en: "it is cold" },
        { target: "жарко", roman: "zharko", fr: "il fait chaud", en: "it is hot" },
        { target: "дождь", roman: "dozhd", fr: "pluie", en: "rain" },
        { target: "зима", roman: "zima", fr: "hiver", en: "winter" },
        { target: "лето", roman: "leto", fr: "été", en: "summer" },
        { target: "час", roman: "chas", fr: "heure", en: "hour" },
        { target: "сейчас", roman: "seichas", fr: "maintenant", en: "now" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Il fait froid aujourd'hui » → « Сегодня ___ ».",
          promptEn: "Complete: \"It is cold today\" → \"Сегодня ___\".",
          options: ["холодно", "жарко", "дождь", "зима"],
          accept: ["холодно"],
          explain: "« Холодно » est l'adverbe impersonnel qui exprime le froid.",
          explainEn: "\"Холодно\" is the impersonal adverb expressing cold.",
        },
        {
          prompt: "Comment dit-on « l'hiver » ?",
          promptEn: "How do you say \"winter\"?",
          options: ["зима", "лето", "весна", "осень"],
          accept: ["зима"],
          explain: "« Зима » = hiver ; лето = été, весна = printemps, осень = automne.",
          explainEn: "\"Зима\" = winter; лето = summer, весна = spring, осень = autumn.",
        },
        {
          prompt: "Complétez : « Quelle heure est-il ? » → « Который ___? »",
          promptEn: "Complete: \"What time is it?\" → \"Который ___?\"",
          accept: ["час"],
          explain: "« Который час? » est la question pour demander l'heure.",
          explainEn: "\"Который час?\" is the question to ask the time.",
        },
      ],
    },
    {
      number: 10,
      slug: "ru-10",
      title: "Entretien : présente-toi et ton parcours",
      titleEn: "Interview: introducing yourself and your background",
      summary: "Parler de ses études, de son expérience et de sa carrière en entretien.",
      summaryEn: "Talking about your studies, experience and career in an interview.",
      grammar: ["Прошедшее время: я окончил", "Университет и опыт", "Я работал ... (passé)"],
      explanation:
        "En entretien, on décrit son parcours au passé : « Я окончил университет » (j'ai terminé l'université), « Я работал три года » (j'ai travaillé trois ans). Le passé se forme avec le suffixe -л : окончил (il a terminé), работал (il a travaillé). On enchaîne avec le présent pour situer la situation actuelle : « Сейчас я работаю ... ».",
      explanationEn:
        "In an interview, you describe your background in the past tense: \"Я окончил университет\" (I finished university), \"Я работал три года\" (I worked for three years). The past is formed with the suffix -л: окончил (he finished), работал (he worked). You then move to the present to describe your current situation: \"Сейчас я работаю ...\".",
      examples: [
        { target: "Я окончил университет в Москве.", roman: "Ya okonchil universitet v Moskve.", fr: "J'ai terminé l'université à Moscou.", en: "I finished university in Moscow." },
        { target: "Я работал три года в компании.", roman: "Ya rabotal tri goda v kompanii.", fr: "J'ai travaillé trois ans dans une entreprise.", en: "I worked for three years at a company." },
        { target: "Сейчас я работаю разработчиком.", roman: "Seichas ya rabotayu razrabotchikom.", fr: "Actuellement je travaille comme développeur.", en: "I currently work as a developer." },
        { target: "Я хочу получить новый опыт.", roman: "Ya khochu poluchit novyy opyt.", fr: "Je souhaite acquérir une nouvelle expérience.", en: "I want to gain new experience." },
      ],
      vocab: [
        { target: "университет", roman: "universitet", fr: "université", en: "university" },
        { target: "окончить", roman: "okonchit", fr: "terminer (études)", en: "to graduate" },
        { target: "опыт", roman: "opyt", fr: "expérience", en: "experience" },
        { target: "работа", roman: "rabota", fr: "travail", en: "work" },
        { target: "стажировка", roman: "stazhirovka", fr: "stage", en: "internship" },
        { target: "три года", roman: "tri goda", fr: "trois ans", en: "three years" },
        { target: "карьера", roman: "karyera", fr: "carrière", en: "career" },
        { target: "получить", roman: "poluchit", fr: "obtenir", en: "to get, to obtain" },
      ],
      exercises: [
        {
          prompt: "Complétez : « J'ai terminé l'université » → « Я ___ университет ».",
          promptEn: "Complete: \"I finished university\" → \"Я ___ университет\".",
          options: ["окончил", "работал", "живу", "хочу"],
          accept: ["окончил"],
          explain: "« Окончить » au passé masculin : окончил — Я окончил университет.",
          explainEn: "\"Окончить\" in the masculine past: окончил — Я окончил университет.",
        },
        {
          prompt: "Comment dit-on « l'expérience » (professionnelle) ?",
          promptEn: "How do you say \"experience\" (professional)?",
          options: ["опыт", "стажировка", "карьера", "работа"],
          accept: ["опыт"],
          explain: "« Опыт » = expérience ; стажировка = stage, карьера = carrière.",
          explainEn: "\"Опыт\" = experience; стажировка = internship, карьера = career.",
        },
        {
          prompt: "Complétez : « J'ai travaillé trois ans » → « Я ___ три года ».",
          promptEn: "Complete: \"I worked for three years\" → \"Я ___ три года\".",
          accept: ["работал"],
          explain: "Passé de работать à la 1re personne : я работал.",
          explainEn: "Past of работать in the 1st person: я работал.",
        },
      ],
      interview: [
        {
          question: "Расскажите о себе и вашем образовании.",
          roman: "Rasskazhite o sebe i vashem obrazovanii.",
          fr: "Pouvez-vous me parler de vous et de votre parcours académique ?",
          en: "Can you tell me about yourself and your educational background?",
          modelFr: "Je m'appelle Daniel, je suis diplômé en informatique et j'ai travaillé trois ans dans le développement web.",
          modelEn: "My name is Daniel, I have a degree in computer science and I worked in web development for three years.",
          accept: ["Я окончил университет", "Я изучал информатику", "Я работал три года", "Меня зовут Даниэль"],
        },
      ],
    },
    {
      number: 11,
      slug: "ru-11",
      title: "Entretien : atouts, faiblesses et motivation",
      titleEn: "Interview: strengths, weaknesses and motivation",
      summary: "Parler de ses forces, de ses axes de progrès et de sa motivation.",
      summaryEn: "Talking about your strengths, areas for improvement and motivation.",
      grammar: ["Прилагательные: сильный, слабый", "Почему ...? Потому что ...", "Одна из моих сильных сторон"],
      explanation:
        "Pour décrire ses atouts : « Одна из моих сильных сторон — работа в команде » (l'une de mes forces est le travail d'équipe). On exprime la cause avec « потому что » (parce que) : « Я хочу работать в этой компании, потому что ... ». Les adjectifs « сильный » (fort) et « слабый » (faible) décrivent les aspects : сильные стороны (points forts), слабые стороны (points faibles).",
      explanationEn:
        "To describe your strengths: \"Одна из моих сильных сторон — работа в команде\" (one of my strengths is teamwork). You express cause with \"потому что\" (because): \"Я хочу работать в этой компании, потому что ...\". The adjectives \"сильный\" (strong) and \"слабый\" (weak) describe aspects: сильные стороны (strengths), слабые стороны (weaknesses).",
      examples: [
        { target: "Одна из моих сильных сторон — работа в команде.", roman: "Odna iz moikh silnykh storon — rabota v komande.", fr: "L'une de mes forces est le travail d'équipe.", en: "One of my strengths is teamwork." },
        { target: "Я стараюсь улучшить свои слабые стороны.", roman: "Ya starayus uluchshit svoi slabye storony.", fr: "Je m'efforce d'améliorer mes points faibles.", en: "I am working on improving my weaknesses." },
        { target: "Я хочу работать в этой компании, потому что она инновационная.", roman: "Ya khochu rabotat v etoy kompanii, potomu chto ona innovatsionnaya.", fr: "Je veux travailler dans cette entreprise car elle est innovante.", en: "I want to work at this company because it is innovative." },
        { target: "Моя мотивация — работать над новыми проектами.", roman: "Moya motivatsiya — rabotat nad novymi proyektami.", fr: "Ma motivation est de travailler sur de nouveaux projets.", en: "My motivation is working on new projects." },
      ],
      vocab: [
        { target: "сильный", roman: "silnyy", fr: "fort", en: "strong" },
        { target: "слабый", roman: "slabyy", fr: "faible", en: "weak" },
        { target: "сторона", roman: "storona", fr: "côté, aspect", en: "side, aspect" },
        { target: "работа в команде", roman: "rabota v komande", fr: "travail d'équipe", en: "teamwork" },
        { target: "мотивация", roman: "motivatsiya", fr: "motivation", en: "motivation" },
        { target: "потому что", roman: "potomu chto", fr: "parce que", en: "because" },
        { target: "инновационный", roman: "innovatsionnyy", fr: "innovant", en: "innovative" },
        { target: "улучшить", roman: "uluchshit", fr: "améliorer", en: "to improve" },
      ],
      exercises: [
        {
          prompt: "Complétez : « L'une de mes forces est le travail d'équipe » → « Одна из моих ___ сторон — работа в команде ».",
          promptEn: "Complete: \"One of my strengths is teamwork\" → \"Одна из моих ___ сторон — работа в команде\".",
          options: ["сильных", "слабых", "больших", "новых"],
          accept: ["сильных"],
          explain: "« Сильные стороны » = points forts ; слабые стороны = points faibles.",
          explainEn: "\"Сильные стороны\" = strengths; слабые стороны = weaknesses.",
        },
        {
          prompt: "Complétez : « Je veux travailler dans cette entreprise » → « Я хочу ___ в этой компании ».",
          promptEn: "Complete: \"I want to work at this company\" → \"Я хочу ___ в этой компании\".",
          options: ["работать", "жить", "учить", "есть"],
          accept: ["работать"],
          explain: "« Хотеть работать » = vouloir travailler : я хочу работать.",
          explainEn: "\"Хотеть работать\" = to want to work: я хочу работать.",
        },
        {
          prompt: "Complétez : « Je veux ce poste parce que... » → « Я хочу эту должность, ___ ... ».",
          promptEn: "Complete: \"I want this position because...\" → \"Я хочу эту должность, ___ ...\".",
          accept: ["потому что"],
          explain: "« Потому что » introduit la cause : я хочу ..., потому что ...",
          explainEn: "\"Потому что\" introduces the reason: я хочу ..., потому что ...",
        },
      ],
      interview: [
        {
          question: "Какие ваши сильные и слабые стороны?",
          roman: "Kakiye vashi silnyye i slabyye storony?",
          fr: "Quelles sont vos forces et vos faiblesses ?",
          en: "What are your strengths and weaknesses?",
          modelFr: "Je suis organisé et j'aime le travail d'équipe ; je travaille encore sur ma prise de parole en public.",
          modelEn: "I am organized and I enjoy teamwork; I am still working on my public speaking.",
          accept: ["Работа в команде — моя сильная сторона", "Я организованный человек", "Мои сильные стороны — работа в команде", "Моя слабая сторона — публичные выступления"],
        },
        {
          question: "Почему вы хотите работать в этой компании?",
          roman: "Pochemu vy khotite rabotat v etoy kompanii?",
          fr: "Pourquoi voulez-vous travailler dans cette entreprise ?",
          en: "Why do you want to work at this company?",
          modelFr: "Parce que votre entreprise est innovante et que je pourrais y développer de réelles compétences.",
          modelEn: "Because your company is innovative and I could develop real skills here.",
          accept: ["Ваша компания инновационная", "Я хочу получить опыт", "Я хочу развиваться здесь", "Мне очень нравится ваша команда"],
        },
      ],
    },
    {
      number: 12,
      slug: "ru-12",
      title: "Entretien : projets, travail d'équipe et gestion du stress",
      titleEn: "Interview: plans, teamwork and stress management",
      summary: "Exprimer ses projets d'avenir, parler du travail d'équipe et du stress.",
      summaryEn: "Expressing future plans, talking about teamwork and handling stress.",
      grammar: ["Будущее: где вы видите себя", "Через пять лет (dans cinq ans)", "Управлять стрессом"],
      explanation:
        "Pour parler de l'avenir, on emploie « через пять лет » (dans cinq ans) : « Через пять лет я вижу себя в этой компании » (dans cinq ans, je me vois dans cette entreprise). Pour le travail d'équipe, on dit « я работаю с командой » (je travaille avec l'équipe). Pour le stress : « я управляю стрессом » (je gère le stress) ou « я делаю перерыв » (je fais une pause).",
      explanationEn:
        "To talk about the future, you use \"через пять лет\" (in five years): \"Через пять лет я вижу себя в этой компании\" (in five years, I see myself at this company). For teamwork you say \"я работаю с командой\" (I work with the team). For stress: \"я управляю стрессом\" (I manage stress) or \"я делаю перерыв\" (I take a break).",
      examples: [
        { target: "Через пять лет я вижу себя лидером в этой компании.", roman: "Cherez pyat let ya vizhu sebya liderom v etoy kompanii.", fr: "Dans cinq ans, je me vois comme leader dans cette entreprise.", en: "In five years, I see myself as a leader at this company." },
        { target: "Я работаю вместе со своей командой.", roman: "Ya rabotayu vmeste so svoey komandoy.", fr: "Je travaille avec mon équipe.", en: "I work together with my team." },
        { target: "Когда я в стрессе, я делаю перерыв.", roman: "Kogda ya v stresse, ya delayu pereryv.", fr: "Quand je suis stressé, je fais une pause.", en: "When I am stressed, I take a break." },
        { target: "В этом году я хочу продолжить карьеру.", roman: "V etom godu ya khochu prodolzhit karyeru.", fr: "Cette année, je veux poursuivre ma carrière.", en: "This year I want to continue my career." },
      ],
      vocab: [
        { target: "будущее", roman: "budushcheye", fr: "avenir, futur", en: "future" },
        { target: "через пять лет", roman: "cherez pyat let", fr: "dans cinq ans", en: "in five years" },
        { target: "цель", roman: "tsel", fr: "objectif", en: "goal" },
        { target: "стресс", roman: "stress", fr: "stress", en: "stress" },
        { target: "управлять стрессом", roman: "upravlyat stressom", fr: "gérer le stress", en: "to manage stress" },
        { target: "команда", roman: "komanda", fr: "équipe", en: "team" },
        { target: "перерыв", roman: "pereryv", fr: "pause", en: "break" },
        { target: "продолжить", roman: "prodolzhit", fr: "continuer, poursuivre", en: "to continue" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Dans cinq ans, je me vois... » → « ___ пять лет я вижу себя... ».",
          promptEn: "Complete: \"In five years, I see myself...\" → \"___ пять лет я вижу себя...\".",
          options: ["через", "после", "от", "для"],
          accept: ["через"],
          explain: "« Через » + durée exprime le délai : через пять лет (dans cinq ans).",
          explainEn: "\"Через\" + duration expresses a deadline: через пять лет (in five years).",
        },
        {
          prompt: "Comment dit-on « l'équipe » ?",
          promptEn: "How do you say \"team\"?",
          options: ["команда", "перерыв", "цель", "стресс"],
          accept: ["команда"],
          explain: "« Команда » = équipe ; перерыв = pause, цель = objectif.",
          explainEn: "\"Команда\" = team; перерыв = break, цель = goal.",
        },
        {
          prompt: "Complétez : « Je gère le stress » → « Я ___ стрессом ».",
          promptEn: "Complete: \"I manage stress\" → \"Я ___ стрессом\".",
          accept: ["управляю"],
          explain: "« Управлять » (gérer) se conjugue « я управляю » + instrumental.",
          explainEn: "\"Управлять\" (to manage) conjugates \"я управляю\" + instrumental.",
        },
      ],
      interview: [
        {
          question: "Где вы видите себя через пять лет?",
          roman: "Gde vy vidite sebya cherez pyat let?",
          fr: "Où vous voyez-vous dans cinq ans ?",
          en: "Where do you see yourself in five years?",
          modelFr: "Je me vois comme leader dans cette entreprise, en ayant développé mes compétences.",
          modelEn: "I see myself as a leader at this company, having developed my skills.",
          accept: ["Через пять лет я вижу себя лидером", "Я вижу себя в этой компании", "Я хочу развиваться в этой компании", "Через пять лет я хочу больше ответственности"],
        },
        {
          question: "Как вы работаете в команде?",
          roman: "Kak vy rabotayete v komande?",
          fr: "Comment travaillez-vous en équipe ?",
          en: "How do you work in a team?",
          modelFr: "J'aime coopérer, j'écoute mes collègues et je partage mes idées avec l'équipe.",
          modelEn: "I like to cooperate, I listen to my colleagues and I share my ideas with the team.",
          accept: ["Я люблю работать в команде", "Я слушаю своих коллег", "Я делюсь идеями с командой", "Я уважаю своих коллег"],
        },
        {
          question: "Как вы справляетесь со стрессом?",
          roman: "Kak vy spravlyayetes so stressom?",
          fr: "Comment gérez-vous le stress ?",
          en: "How do you deal with stress?",
          modelFr: "Je fais une pause, je respire et je m'organise pour rester calme.",
          modelEn: "I take a break, I breathe and I organize myself to stay calm.",
          accept: ["Я делаю перерыв", "Я глубоко дышу", "Я хорошо организую своё время", "Я остаюсь спокойным"],
        },
      ],
    },
  ],
};
