import type { LanguageCourse } from "./genericLessons";

export const TR_COURSE: LanguageCourse = {
  code: "tr",
  name: "Turc",
  native: "Türkçe",
  heroTitle1: { fr: "Apprenez", en: "Learn" },
  heroTitle2: { fr: "le turc", en: "Turkish" },
  heroSubtitle: {
    fr: "Un parcours débutant en douze leçons : salutations, vie quotidienne, travail et entretien d'embauche.",
    en: "A beginner path in twelve lessons: greetings, daily life, work and job interviews.",
  },
  lessons: [
    {
      number: 1,
      slug: "tr-01",
      title: "Se présenter et saluer",
      titleEn: "Introducing yourself and greeting",
      summary: "Les salutations de base et les premières présentations : dire son nom et son origine.",
      summaryEn: "Basic greetings and first introductions: giving your name and your origin.",
      grammar: ["Merhaba ve tanışma ifadeleri", "Benim adım ... (je m'appelle)", "Ben ...den geliyorum"],
      explanation:
        "En turc, on commence une conversation par « Merhaba ». Pour se présenter on dit « Benim adım ... » (littéralement « mon nom est ... ») ou plus simplement « Ben ... ». Pour indiquer son origine, on emploie le suffixe du cas ablatif : « Ben Fransa'dan geliyorum » (je viens de France). Enfin, « Memnun oldum » signifie « enchanté » et se dit à la fin des présentations.",
      explanationEn:
        "In Turkish, a conversation starts with \"Merhaba.\" To introduce yourself, you say \"Benim adım ...\" (literally \"my name is ...\") or more simply \"Ben ...\". To give your origin, you use the ablative case suffix: \"Ben Fransa'dan geliyorum\" (I come from France). Finally, \"Memnun oldum\" means \"nice to meet you\" and is said at the end of introductions.",
      examples: [
        { target: "Merhaba, benim adım Daniel.", fr: "Bonjour, je m'appelle Daniel.", en: "Hello, my name is Daniel." },
        { target: "Ben Fransa'dan geliyorum.", fr: "Je viens de France.", en: "I come from France." },
        { target: "Merhaba, nasılsın?", fr: "Bonjour, comment vas-tu ?", en: "Hello, how are you?" },
        { target: "Memnun oldum, hoş geldiniz!", fr: "Enchanté, bienvenue !", en: "Nice to meet you, welcome!" },
      ],
      vocab: [
        { target: "merhaba", fr: "bonjour", en: "hello" },
        { target: "günaydın", fr: "bonjour (le matin)", en: "good morning" },
        { target: "iyi akşamlar", fr: "bonsoir", en: "good evening" },
        { target: "ad", fr: "nom, prénom", en: "name" },
        { target: "benim adım", fr: "je m'appelle (mon nom est)", en: "my name is" },
        { target: "geliyorum", fr: "je viens", en: "I come" },
        { target: "memnun oldum", fr: "enchanté", en: "nice to meet you" },
        { target: "nasılsın?", fr: "comment vas-tu ?", en: "how are you?" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Bonjour, je m'appelle Zeynep » → « Merhaba, ___ adım Zeynep ».",
          promptEn: "Complete: \"Hello, my name is Zeynep\" → \"Merhaba, ___ adım Zeynep\".",
          options: ["benim", "senin", "onun", "bizim"],
          accept: ["benim"],
          explain: "« Benim adım » signifie « mon nom est » : le possessif benim (mon) précède ad (nom).",
          explainEn: "\"Benim adım\" means \"my name is\": the possessive benim (my) comes before ad (name).",
        },
        {
          prompt: "Que dit-on le matin pour dire « bonjour » ?",
          promptEn: "What do you say in the morning to greet someone?",
          options: ["günaydın", "iyi geceler", "hoşça kal", "teşekkürler"],
          accept: ["günaydın"],
          explain: "« Günaydın » signifie littéralement « que ta journée soit lumineuse », utilisé uniquement le matin.",
          explainEn: "\"Günaydın\" literally means \"may your day be bright\" and is used only in the morning.",
        },
        {
          prompt: "Complétez : « Je viens de France » → « Ben Fransa'___ geliyorum ».",
          promptEn: "Complete: \"I come from France\" → \"Ben Fransa'___ geliyorum\".",
          accept: ["dan"],
          explain: "Le suffixe -dan est le cas ablatif : il exprime la provenance (« de, depuis »).",
          explainEn: "The suffix -dan is the ablative case: it expresses origin (\"from\").",
        },
      ],
      interview: [
        {
          question: "Kendini tanıtabilir misin?",
          fr: "Peux-tu te présenter ?",
          en: "Can you introduce yourself?",
          modelFr: "Je m'appelle Daniel, je viens de France et je suis développeur.",
          modelEn: "My name is Daniel, I come from France and I am a developer.",
          accept: ["Benim adım Daniel", "Adım Daniel", "Ben Daniel", "Ben Daniel'im", "Ben Fransa'dan geliyorum"],
        },
      ],
    },
    {
      number: 2,
      slug: "tr-02",
      title: "Origine, nationalité et profession",
      titleEn: "Origin, nationality and profession",
      summary: "Dire sa nationalité, son métier et le lieu où l'on vit.",
      summaryEn: "Saying your nationality, your job and where you live.",
      grammar: ["Milliyet ekleri: Ben ...ım/-ım", "Ben ...da yaşıyorum (locatif)", "Meslek adları"],
      explanation:
        "La nationalité et le métier se forment sur le verbe être, ajouté au mot : « Ben Fransızım » (je suis français), « Ben doktorum » (je suis médecin). Pour dire où l'on vit, on utilise le cas locatif : « İstanbul'da yaşıyorum » (je vis à Istanbul), le suffixe -da/-de indiquant le lieu.",
      explanationEn:
        "Nationality and profession are built with the verb to be, added to the word: \"Ben Fransızım\" (I am French), \"Ben doktorum\" (I am a doctor). To say where you live, you use the locative case: \"İstanbul'da yaşıyorum\" (I live in Istanbul); the suffix -da/-de indicates the place.",
      examples: [
        { target: "Ben Fransızım.", fr: "Je suis français.", en: "I am French." },
        { target: "Ben doktorum.", fr: "Je suis médecin.", en: "I am a doctor." },
        { target: "İstanbul'da yaşıyorum.", fr: "Je vis à Istanbul.", en: "I live in Istanbul." },
        { target: "O bir öğretmen.", fr: "C'est un professeur.", en: "He is a teacher." },
      ],
      vocab: [
        { target: "Fransız", fr: "français", en: "French" },
        { target: "Türk", fr: "turc", en: "Turk" },
        { target: "doktor", fr: "médecin", en: "doctor" },
        { target: "öğretmen", fr: "professeur", en: "teacher" },
        { target: "mühendis", fr: "ingénieur", en: "engineer" },
        { target: "öğrenci", fr: "étudiant", en: "student" },
        { target: "yaşıyorum", fr: "je vis", en: "I live" },
        { target: "Nerelisin?", fr: "D'où es-tu ?", en: "Where are you from?" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Je suis turc » → « Ben Türk'___ ».",
          promptEn: "Complete: \"I am Turkish\" → \"Ben Türk'___\".",
          options: ["üm", "sin", "tür", "dür"],
          accept: ["üm"],
          explain: "Après Türk, on ajoute -üm : « Ben Türk'üm » (je suis turc), forme harmonisée du verbe être.",
          explainEn: "After Türk, you add -üm: \"Ben Türk'üm\" (I am Turkish), the vowel-harmonized form of the verb to be.",
        },
        {
          prompt: "Comment dit-on « ingénieur » ?",
          promptEn: "How do you say \"engineer\"?",
          options: ["mühendis", "doktor", "öğretmen", "öğrenci"],
          accept: ["mühendis"],
          explain: "« Mühendis » est l'ingénieur ; doktor est le médecin, öğretmen le professeur, öğrenci l'étudiant.",
          explainEn: "\"Mühendis\" is the engineer; doktor is the doctor, öğretmen the teacher, öğrenci the student.",
        },
        {
          prompt: "Complétez : « J'habite à Istanbul » → « İstanbul'da ___ ».",
          promptEn: "Complete: \"I live in Istanbul\" → \"İstanbul'da ___\".",
          accept: ["yaşıyorum"],
          explain: "« Yaşamak » (vivre) donne « yaşıyorum » (je vis). İstanbul'da signifie « à Istanbul ».",
          explainEn: "\"Yaşamak\" (to live) gives \"yaşıyorum\" (I live). İstanbul'da means \"in Istanbul\".",
        },
      ],
    },
    {
      number: 3,
      slug: "tr-03",
      title: "Le verbe être et avoir",
      titleEn: "The verbs to be and to have",
      summary: "Se conjuguer au présent et exprimer la possession avec var / yok.",
      summaryEn: "Conjugating in the present tense and expressing possession with var / yok.",
      grammar: ["Ek fiil: -im, -sin, -dir", "Sahip olmak: var / yok", "Benim ... var"],
      explanation:
        "Le verbe « être » se réduit à des suffixes : -im (je suis), -sin (tu es), -dir (il/elle est). Exemple : « Ben mutluyum » (je suis heureux). Le turc n'a pas de verbe « avoir » : on dit « Bir arabam var » (j'ai une voiture, littéralement « ma voiture existe ») et sa négation se fait avec yok : « Param yok » (je n'ai pas d'argent).",
      explanationEn:
        "The verb \"to be\" is reduced to suffixes: -im (I am), -sin (you are), -dir (he/she is). Example: \"Ben mutluyum\" (I am happy). Turkish has no verb \"to have\": you say \"Bir arabam var\" (I have a car, literally \"my car exists\"), and its negation uses yok: \"Param yok\" (I have no money).",
      examples: [
        { target: "Ben mutluyum.", fr: "Je suis heureux.", en: "I am happy." },
        { target: "Sen doktorsun.", fr: "Tu es médecin.", en: "You are a doctor." },
        { target: "Bir arabam var.", fr: "J'ai une voiture.", en: "I have a car." },
        { target: "Param yok.", fr: "Je n'ai pas d'argent.", en: "I have no money." },
      ],
      vocab: [
        { target: "mutlu", fr: "heureux", en: "happy" },
        { target: "ek fiil", fr: "verbe « être » (suffixes)", en: "verb \"to be\" (suffixes)" },
        { target: "var", fr: "il y a, avoir", en: "there is, have" },
        { target: "yok", fr: "il n'y a pas", en: "there is not, don't have" },
        { target: "para", fr: "argent", en: "money" },
        { target: "araba", fr: "voiture", en: "car" },
        { target: "ev", fr: "maison", en: "house" },
        { target: "kitap", fr: "livre", en: "book" },
      ],
      exercises: [
        {
          prompt: "Complétez : « Je suis heureux » → « Ben mutlu___ ».",
          promptEn: "Complete: \"I am happy\" → \"Ben mutlu___\".",
          options: ["yum", "sun", "dur", "yuz"],
          accept: ["yum"],
          explain: "Après mutlu, le suffixe du verbe être est -yum : « Ben mutluyum » (je suis heureux).",
          explainEn: "After mutlu, the verb-to-be suffix is -yum: \"Ben mutluyum\" (I am happy).",
        },
        {
          prompt: "Quel mot turc exprime l'idée d'« avoir » (possession) ?",
          promptEn: "Which Turkish word expresses the idea of \"having\" (possession)?",
          options: ["var", "yok", "mutlu", "ev"],
          accept: ["var"],
          explain: "« Var » signifie « il y a / j'ai » : Bir arabam var. « Yok » en est la négation.",
          explainEn: "\"Var\" means \"there is / I have\": Bir arabam var. \"Yok\" is its negation.",
        },
        {
          prompt: "Complétez : « J'ai une voiture » → « Bir arabam ___ ».",
          promptEn: "Complete: \"I have a car\" → \"Bir arabam ___\".",
          accept: ["var"],
          explain: "On dit littéralement « ma voiture existe » : araba + -m (ma) + var.",
          explainEn: "You literally say \"my car exists\": araba + -m (my) + var.",
        },
      ],
    },
    {
      number: 4,
      slug: "tr-04",
      title: "La routine quotidienne",
      titleEn: "Daily routine",
      summary: "Décrire sa journée : se lever, travailler, manger, dormir, avec le présent continu.",
      summaryEn: "Describing your day: getting up, working, eating, sleeping, with the present continuous.",
      grammar: ["Şimdiki zaman: -iyor", "Dönüşlü fiiller: kalkmak, kalkıyorum", "Sıklık: her gün, genellikle"],
      explanation:
        "Le présent continu turc se forme avec le suffixe -iyor : « kalkıyorum » (je me lève), « çalışıyorum » (je travaille). Pour indiquer la fréquence, on place des expressions comme « her gün » (chaque jour) ou « genellikle » (généralement) avant le verbe.",
      explanationEn:
        "The Turkish present continuous is formed with the suffix -iyor: \"kalkıyorum\" (I get up), \"çalışıyorum\" (I work). To indicate frequency, you place expressions like \"her gün\" (every day) or \"genellikle\" (usually) before the verb.",
      examples: [
        { target: "Her gün saat yedide kalkıyorum.", fr: "Chaque jour, je me lève à sept heures.", en: "Every day I get up at seven o'clock." },
        { target: "İşe gidiyorum.", fr: "Je vais au travail.", en: "I go to work." },
        { target: "Kahvaltıda çay içiyorum.", fr: "Au petit-déjeuner, je bois du thé.", en: "I drink tea at breakfast." },
        { target: "Saat sekizde çalışmaya başlıyorum.", fr: "À huit heures, je commence à travailler.", en: "At eight o'clock I start working." },
      ],
      vocab: [
        { target: "kalkmak", fr: "se lever", en: "to get up" },
        { target: "işe gitmek", fr: "aller au travail", en: "to go to work" },
        { target: "çalışmak", fr: "travailler", en: "to work" },
        { target: "başlamak", fr: "commencer", en: "to start" },
        { target: "çay", fr: "thé", en: "tea" },
        { target: "kahvaltı", fr: "petit-déjeuner", en: "breakfast" },
        { target: "her gün", fr: "chaque jour", en: "every day" },
        { target: "akşam", fr: "le soir", en: "evening" },
      ],
      exercises: [
        {
          prompt: "Quel verbe signifie « se lever » ?",
          promptEn: "Which verb means \"to get up\"?",
          options: ["kalkmak", "uyumak", "çalışmak", "gitmek"],
          accept: ["kalkmak"],
          explain: "« Kalkmak » = se lever : Her gün saat yedide kalkıyorum.",
          explainEn: "\"Kalkmak\" = to get up: Her gün saat yedide kalkıyorum.",
        },
        {
          prompt: "Complétez : « Je bois du thé » → « Çay ___ ».",
          promptEn: "Complete: \"I drink tea\" → \"Çay ___\".",
          options: ["içiyorum", "kalkıyorum", "çalışıyorum", "uyuyorum"],
          accept: ["içiyorum"],
          explain: "« İçmek » (boire) → « içiyorum » (je bois).",
          explainEn: "\"İçmek\" (to drink) → \"içiyorum\" (I drink).",
        },
        {
          prompt: "Complétez : « Je vais au travail » → « İşe ___ ».",
          promptEn: "Complete: \"I go to work\" → \"İşe ___\".",
          accept: ["gidiyorum"],
          explain: "« Gitmek » (aller) → « gidiyorum » : İşe gidiyorum.",
          explainEn: "\"Gitmek\" (to go) → \"gidiyorum\": İşe gidiyorum.",
        },
      ],
    },
    {
      number: 5,
      slug: "tr-05",
      title: "Les goûts et les loisirs",
      titleEn: "Tastes and hobbies",
      summary: "Exprimer ce que l'on aime : sevmek, hoşlanmak et le suffixe du gérondif.",
      summaryEn: "Expressing what you like: sevmek, hoşlanmak and the gerund suffix.",
      grammar: ["-meyi sevmek", "-maktan hoşlanmak", "Mi soru eki: ... misin?"],
      explanation:
        "Pour dire que l'on aime une activité, le verbe se transforme en gérondif suivi de sevmek ou hoşlanmak : « Kitap okumayı seviyorum » (j'aime lire des livres), « Futbol oynamaktan hoşlanıyorum » (j'aime jouer au football). Pour poser une question, on ajoute l'enclitique mi : « ... hoşlanıyor musun? ».",
      explanationEn:
        "To say you like an activity, the verb becomes a gerund followed by sevmek or hoşlanmak: \"Kitap okumayı seviyorum\" (I like reading books), \"Futbol oynamaktan hoşlanıyorum\" (I enjoy playing football). To ask a question, you add the enclitic mi: \"... hoşlanıyor musun?\".",
      examples: [
        { target: "Kitap okumayı seviyorum.", fr: "J'aime lire des livres.", en: "I like reading books." },
        { target: "Futbol oynamaktan hoşlanıyorum.", fr: "J'aime jouer au football.", en: "I enjoy playing football." },
        { target: "Müzik dinlemeyi seviyorum.", fr: "J'aime écouter de la musique.", en: "I like listening to music." },
        { target: "Sinemaya gitmekten hoşlanıyor musun?", fr: "Aimes-tu aller au cinéma ?", en: "Do you enjoy going to the cinema?" },
      ],
      vocab: [
        { target: "sevmek", fr: "aimer", en: "to like, to love" },
        { target: "hoşlanmak", fr: "aimer, apprécier", en: "to enjoy, to like" },
        { target: "okumak", fr: "lire", en: "to read" },
        { target: "oynamak", fr: "jouer", en: "to play" },
        { target: "dinlemek", fr: "écouter", en: "to listen" },
        { target: "müzik", fr: "musique", en: "music" },
        { target: "sinema", fr: "cinéma", en: "cinema" },
        { target: "boş zaman", fr: "temps libre", en: "free time" },
      ],
      exercises: [
        {
          prompt: "Quel verbe signifie « aimer » ?",
          promptEn: "Which verb means \"to like\"?",
          options: ["sevmek", "okumak", "dinlemek", "çalışmak"],
          accept: ["sevmek"],
          explain: "« Sevmek » = aimer ; hoşlanmak = apprécier, aimer (une activité).",
          explainEn: "\"Sevmek\" = to like/love; hoşlanmak = to enjoy, to like (an activity).",
        },
        {
          prompt: "Complétez : « J'aime écouter de la musique » → « Müzik ___ seviyorum ».",
          promptEn: "Complete: \"I like listening to music\" → \"Müzik ___ seviyorum\".",
          options: ["dinlemeyi", "okumayı", "oynamayı", "sevmeyi"],
          accept: ["dinlemeyi"],
          explain: "Dinlemek (écouter) → dinlemeyi : Müzik dinlemeyi seviyorum.",
          explainEn: "Dinlemek (to listen) → dinlemeyi: Müzik dinlemeyi seviyorum.",
        },
        {
          prompt: "Complétez : « Aimes-tu le cinéma ? » → « Sinemayı ___ misin? ».",
          promptEn: "Complete: \"Do you like the cinema?\" → \"Sinemayı ___ misin?\".",
          accept: ["seviyor"],
          explain: "On ajoute l'enclitique mi : Sinemayı seviyor musun?",
          explainEn: "You add the enclitic mi: Sinemayı seviyor musun?",
        },
      ],
    },
    {
      number: 6,
      slug: "tr-06",
      title: "La famille et les personnes",
      titleEn: "Family and people",
      summary: "Le vocabulaire de la famille et les suffixes possessifs.",
      summaryEn: "Family vocabulary and possessive suffixes.",
      grammar: ["İyelik ekleri: -ım, -ımız", "Benim ailem", "Akrabalık terimleri"],
      explanation:
        "Pour dire « ma famille », on ajoute le possessif : « benim ailem » (ma famille), « kardeşim » (mon frère). Les personnes de la famille se nomment annem (ma mère), babam (mon père). On utilise aussi var pour exprimer un nombre : « İki kardeşim var » (j'ai deux frères et sœurs).",
      explanationEn:
        "To say \"my family\", you add the possessive: \"benim ailem\" (my family), \"kardeşim\" (my sibling). Family members are named annem (my mother), babam (my father). You also use var to express a number: \"İki kardeşim var\" (I have two siblings).",
      examples: [
        { target: "Benim ailem geniştir.", fr: "Ma famille est nombreuse.", en: "My family is large." },
        { target: "İki kardeşim var.", fr: "J'ai deux frères et sœurs.", en: "I have two siblings." },
        { target: "Annem öğretmen, babam doktor.", fr: "Ma mère est professeure, mon père est médecin.", en: "My mother is a teacher, my father is a doctor." },
        { target: "Kardeşim İstanbul'da yaşıyor.", fr: "Mon frère vit à Istanbul.", en: "My sibling lives in Istanbul." },
      ],
      vocab: [
        { target: "aile", fr: "famille", en: "family" },
        { target: "anne", fr: "mère", en: "mother" },
        { target: "baba", fr: "père", en: "father" },
        { target: "kardeş", fr: "frère, sœur", en: "sibling" },
        { target: "kız kardeş", fr: "sœur", en: "sister" },
        { target: "erkek kardeş", fr: "frère", en: "brother" },
        { target: "büyükanne", fr: "grand-mère", en: "grandmother" },
        { target: "büyükbaba", fr: "grand-père", en: "grandfather" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « mère » ?",
          promptEn: "How do you say \"mother\"?",
          options: ["anne", "baba", "kardeş", "aile"],
          accept: ["anne"],
          explain: "« Anne » = mère, « baba » = père, « kardeş » = frère ou sœur.",
          explainEn: "\"Anne\" = mother, \"baba\" = father, \"kardeş\" = sibling.",
        },
        {
          prompt: "Complétez : « J'ai deux sœurs » → « İki ___ kardeşim var ».",
          promptEn: "Complete: \"I have two sisters\" → \"İki ___ kardeşim var\".",
          options: ["kız", "erkek", "anne", "baba"],
          accept: ["kız"],
          explain: "« Kız kardeş » est la sœur : İki kız kardeşim var.",
          explainEn: "\"Kız kardeş\" is the sister: İki kız kardeşim var.",
        },
        {
          prompt: "Complétez : « Ma famille » → « Benim ___ ».",
          promptEn: "Complete: \"My family\" → \"Benim ___\".",
          accept: ["ailem"],
          explain: "Le suffixe possessif -im devient -em après aile : ailem (ma famille).",
          explainEn: "The possessive suffix -im becomes -em after aile: ailem (my family).",
        },
      ],
    },
    {
      number: 7,
      slug: "tr-07",
      title: "Le travail et le bureau",
      titleEn: "Work and the office",
      summary: "Décrire son travail, son bureau et parler de projets et de réunions.",
      summaryEn: "Describing your job, your office, and talking about projects and meetings.",
      grammar: ["Locatif: ofiste", "Meslek ve ofis sözcükleri", "Şu anda + şimdiki zaman"],
      explanation:
        "Au bureau, on emploie le cas locatif : « ofiste » (dans le bureau), « şirkette » (dans l'entreprise). Le présent continu sert à décrire ce qui se passe maintenant : « Şu anda toplantıdayım » (en ce moment, je suis en réunion). On complète avec le vocabulaire des réunions et des projets.",
      explanationEn:
        "At the office, you use the locative case: \"ofiste\" (in the office), \"şirkette\" (in the company). The present continuous describes what is happening now: \"Şu anda toplantıdayım\" (right now I am in a meeting). You complete it with meeting and project vocabulary.",
      examples: [
        { target: "Bir şirkette çalışıyorum.", fr: "Je travaille dans une entreprise.", en: "I work in a company." },
        { target: "Ofise her gün gidiyorum.", fr: "Je vais au bureau tous les jours.", en: "I go to the office every day." },
        { target: "Şu anda toplantıdayım.", fr: "Je suis en réunion en ce moment.", en: "I am in a meeting right now." },
        { target: "Yeni bir proje üzerinde çalışıyoruz.", fr: "Nous travaillons sur un nouveau projet.", en: "We are working on a new project." },
      ],
      vocab: [
        { target: "iş", fr: "travail", en: "work, job" },
        { target: "şirket", fr: "entreprise", en: "company" },
        { target: "ofis", fr: "bureau", en: "office" },
        { target: "toplantı", fr: "réunion", en: "meeting" },
        { target: "proje", fr: "projet", en: "project" },
        { target: "meslektaş", fr: "collègue", en: "colleague" },
        { target: "müdür", fr: "directeur", en: "manager, director" },
        { target: "üzerinde çalışmak", fr: "travailler sur", en: "to work on" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « réunion » ?",
          promptEn: "How do you say \"meeting\"?",
          options: ["toplantı", "şirket", "ofis", "proje"],
          accept: ["toplantı"],
          explain: "« Toplantı » = réunion : Şu anda toplantıdayım.",
          explainEn: "\"Toplantı\" = meeting: Şu anda toplantıdayım.",
        },
        {
          prompt: "Complétez : « Je travaille dans une entreprise » → « Bir ___ çalışıyorum ».",
          promptEn: "Complete: \"I work in a company\" → \"Bir ___ çalışıyorum\".",
          options: ["şirkette", "okulda", "evde", "pazarda"],
          accept: ["şirkette"],
          explain: "Şirket + locatif -te → şirkette : Bir şirkette çalışıyorum.",
          explainEn: "Şirket + locative -te → şirkette: Bir şirkette çalışıyorum.",
        },
        {
          prompt: "Complétez : « Je vais au bureau demain » → « Yarın ___ gidiyorum ».",
          promptEn: "Complete: \"I go to the office tomorrow\" → \"Yarın ___ gidiyorum\".",
          accept: ["ofise"],
          explain: "Le suffixe -e est le cas directif : ofise (vers le bureau).",
          explainEn: "The suffix -e is the dative case: ofise (to the office).",
        },
      ],
    },
    {
      number: 8,
      slug: "tr-08",
      title: "Faire des achats et commander",
      titleEn: "Shopping and ordering",
      summary: "Demander un prix, commander au marché et au restaurant.",
      summaryEn: "Asking prices, ordering at the market and at the restaurant.",
      grammar: ["İstemek: ... istiyorum", "Fiyat sormak: Ne kadar?", "İzin istemek: ... alabilir miyim?"],
      explanation:
        "Pour commander, on emploie « istiyorum » (je veux, je voudrais) : « Bir çay istiyorum, lütfen » (un thé, s'il vous plaît). Pour demander un prix, on utilise « Ne kadar? » (combien ?). Enfin, « alabilir miyim? » (puis-je avoir ?) sert à demander poliment, comme l'addition.",
      explanationEn:
        "To order, you use \"istiyorum\" (I want, I would like): \"Bir çay istiyorum, lütfen\" (a tea, please). To ask the price, you use \"Ne kadar?\" (how much?). Finally, \"alabilir miyim?\" (may I have?) is used to ask politely, such as for the bill.",
      examples: [
        { target: "Bir kilo elma istiyorum, lütfen.", fr: "Je voudrais un kilo de pommes, s'il vous plaît.", en: "I would like a kilo of apples, please." },
        { target: "Bu kaç para?", fr: "Ça coûte combien ?", en: "How much is this?" },
        { target: "Bir çay istiyorum, lütfen.", fr: "Un thé, s'il vous plaît.", en: "A tea, please." },
        { target: "Faturayı alabilir miyim?", fr: "Puis-je avoir l'addition ?", en: "Can I have the bill, please?" },
      ],
      vocab: [
        { target: "pazar", fr: "marché", en: "market" },
        { target: "elma", fr: "pomme", en: "apple" },
        { target: "ekmek", fr: "pain", en: "bread" },
        { target: "para", fr: "argent", en: "money" },
        { target: "fiyat", fr: "prix", en: "price" },
        { target: "hesap", fr: "addition, compte", en: "bill, account" },
        { target: "sipariş vermek", fr: "commander", en: "to order" },
        { target: "almak", fr: "prendre, acheter", en: "to take, to buy" },
      ],
      exercises: [
        {
          prompt: "Comment demande-t-on un prix ?",
          promptEn: "How do you ask the price?",
          options: ["Ne kadar?", "Nasıl?", "Nerede?", "Kim?"],
          accept: ["Ne kadar?"],
          explain: "« Ne kadar? » signifie « combien ? », utilisé pour le prix.",
          explainEn: "\"Ne kadar?\" means \"how much?\", used for the price.",
        },
        {
          prompt: "Complétez : « Un thé, s'il vous plaît » → « Bir çay ___, lütfen ».",
          promptEn: "Complete: \"A tea, please\" → \"Bir çay ___, lütfen\".",
          options: ["istiyorum", "gidiyorum", "yapıyorum", "alıyorum"],
          accept: ["istiyorum"],
          explain: "On commande avec « istiyorum » (je voudrais) : Bir çay istiyorum, lütfen.",
          explainEn: "You order with \"istiyorum\" (I would like): Bir çay istiyorum, lütfen.",
        },
        {
          prompt: "Complétez : « Puis-je avoir l'addition ? » → « ___ alabilir miyim? ».",
          promptEn: "Complete: \"Can I have the bill?\" → \"___ alabilir miyim?\".",
          accept: ["Faturayı", "Hesabı"],
          explain: "« Fatura » ou « hesap » désignent l'addition ; le suffixe -yı/-ı est l'accusatif.",
          explainEn: "\"Fatura\" or \"hesap\" both mean the bill; the suffix -yı/-ı is the accusative case.",
        },
      ],
    },
    {
      number: 9,
      slug: "tr-09",
      title: "Le temps, les saisons et l'heure",
      titleEn: "Weather, seasons and time",
      summary: "Donner l'heure, parler de la météo et des saisons.",
      summaryEn: "Telling the time, talking about the weather and the seasons.",
      grammar: ["Saat kaç?", "Hava durumu: hava güzel", "Mevsimler: yaz, kış"],
      explanation:
        "Pour demander l'heure : « Saat kaç? » (quelle heure est-il ?), réponse « Saat üç » (il est trois heures). Pour la météo, on dit « Bugün hava güzel » (il fait beau aujourd'hui). Les saisons se nomment ilkbahar (printemps), yaz (été), sonbahar (automne) et kış (hiver), utilisées au locatif : « Kışın hava soğuk ».",
      explanationEn:
        "To ask the time: \"Saat kaç?\" (what time is it?), answer \"Saat üç\" (it is three o'clock). For the weather, you say \"Bugün hava güzel\" (the weather is nice today). The seasons are ilkbahar (spring), yaz (summer), sonbahar (autumn) and kış (winter), used in the locative: \"Kışın hava soğuk\".",
      examples: [
        { target: "Saat üç.", fr: "Il est trois heures.", en: "It is three o'clock." },
        { target: "Saat kaç?", fr: "Quelle heure est-il ?", en: "What time is it?" },
        { target: "Bugün hava güzel.", fr: "Il fait beau aujourd'hui.", en: "The weather is nice today." },
        { target: "Kışın hava soğuk olur.", fr: "En hiver, il fait froid.", en: "In winter, the weather is cold." },
      ],
      vocab: [
        { target: "saat", fr: "heure", en: "hour, time" },
        { target: "dakika", fr: "minute", en: "minute" },
        { target: "bugün", fr: "aujourd'hui", en: "today" },
        { target: "hava", fr: "temps (météo)", en: "weather" },
        { target: "güneş", fr: "soleil", en: "sun" },
        { target: "yağmur", fr: "pluie", en: "rain" },
        { target: "yaz", fr: "été", en: "summer" },
        { target: "kış", fr: "hiver", en: "winter" },
      ],
      exercises: [
        {
          prompt: "Comment demande-t-on l'heure en turc ?",
          promptEn: "How do you ask the time in Turkish?",
          options: ["Saat kaç?", "Nasılsın?", "Nerelisin?", "Adın ne?"],
          accept: ["Saat kaç?"],
          explain: "« Saat kaç? » signifie littéralement « l'heure est combien ? ».",
          explainEn: "\"Saat kaç?\" literally means \"what number is the hour?\".",
        },
        {
          prompt: "Quel mot désigne l'« hiver » ?",
          promptEn: "Which word means \"winter\"?",
          options: ["kış", "yaz", "ilkbahar", "sonbahar"],
          accept: ["kış"],
          explain: "Kış = hiver, yaz = été, ilkbahar = printemps, sonbahar = automne.",
          explainEn: "Kış = winter, yaz = summer, ilkbahar = spring, sonbahar = autumn.",
        },
        {
          prompt: "Complétez : « Quelle heure est-il ? — Il est trois heures » → « Saat kaç? — Saat ___ ».",
          promptEn: "Complete: \"What time is it? — It is three o'clock\" → \"Saat kaç? — Saat ___\".",
          accept: ["üç"],
          explain: "« Saat üç » = il est trois heures; üç signifie « trois ».",
          explainEn: "\"Saat üç\" = it is three o'clock; üç means \"three\".",
        },
      ],
    },
    {
      number: 10,
      slug: "tr-10",
      title: "Entretien : présente-toi et ton parcours",
      titleEn: "Interview: introducing yourself and your background",
      summary: "Parler de ses études, de son expérience et de sa carrière en entretien.",
      summaryEn: "Talking about your studies, experience and career in an interview.",
      grammar: ["Geçmiş zaman: -dım, -dim", "Okul ve deneyim sözcükleri", "Ben ...da çalıştım"],
      explanation:
        "En entretien, on décrit son parcours au passé simple : « Üniversitede ekonomi okudum » (j'ai étudié l'économie à l'université), « Üç yıl İstanbul'da çalıştım » (j'ai travaillé trois ans à Istanbul). On enchaîne avec le présent pour situer la situation actuelle et ses projets.",
      explanationEn:
        "In an interview, you describe your background in the past tense: \"Üniversitede ekonomi okudum\" (I studied economics at university), \"Üç yıl İstanbul'da çalıştım\" (I worked in Istanbul for three years). You then move to the present tense to describe your current situation and plans.",
      examples: [
        { target: "Üniversitede ekonomi okudum.", fr: "J'ai étudié l'économie à l'université.", en: "I studied economics at university." },
        { target: "Üç yıl İstanbul'da çalıştım.", fr: "J'ai travaillé trois ans à Istanbul.", en: "I worked in Istanbul for three years." },
        { target: "Şu anda bir yazılım şirketinde çalışıyorum.", fr: "Je travaille actuellement dans une société de logiciels.", en: "I currently work at a software company." },
        { target: "Yeni deneyimler kazanmak istiyorum.", fr: "Je souhaite acquérir de nouvelles expériences.", en: "I want to gain new experiences." },
      ],
      vocab: [
        { target: "üniversite", fr: "université", en: "university" },
        { target: "okumak", fr: "étudier", en: "to study" },
        { target: "deneyim", fr: "expérience", en: "experience" },
        { target: "mezun olmak", fr: "être diplômé", en: "to graduate" },
        { target: "staj", fr: "stage", en: "internship" },
        { target: "iş deneyimi", fr: "expérience professionnelle", en: "work experience" },
        { target: "kariyer", fr: "carrière", en: "career" },
        { target: "kazanmak", fr: "gagner, acquérir", en: "to gain, to earn" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « expérience professionnelle » ?",
          promptEn: "How do you say \"work experience\"?",
          options: ["iş deneyimi", "staj", "üniversite", "kariyer"],
          accept: ["iş deneyimi"],
          explain: "« İş deneyimi » = expérience professionnelle ; staj = stage.",
          explainEn: "\"İş deneyimi\" = work experience; staj = internship.",
        },
        {
          prompt: "Complétez : « J'ai étudié l'économie » → « Ekonomi ___ ».",
          promptEn: "Complete: \"I studied economics\" → \"Ekonomi ___\".",
          options: ["okudum", "çalıştım", "yaşadım", "bitirdim"],
          accept: ["okudum"],
          explain: "Passé simple de okumak (étudier) à la 1re personne : okudum.",
          explainEn: "Past tense of okumak (to study) in the 1st person: okudum.",
        },
        {
          prompt: "Complétez : « Je suis diplômé de l'université » → « Üniversiteden ___ oldum ».",
          promptEn: "Complete: \"I graduated from the university\" → \"Üniversiteden ___ oldum\".",
          accept: ["mezun"],
          explain: "« Mezun olmak » signifie « être diplômé » : Üniversiteden mezun oldum.",
          explainEn: "\"Mezun olmak\" means \"to graduate\": Üniversiteden mezun oldum.",
        },
      ],
      interview: [
        {
          question: "Bana kendinizden ve eğitim geçmişinizden bahseder misiniz?",
          fr: "Pouvez-vous me parler de vous et de votre parcours académique ?",
          en: "Can you tell me about yourself and your educational background?",
          modelFr: "Je m'appelle Daniel, je suis diplômé en informatique et j'ai travaillé trois ans dans le développement web.",
          modelEn: "My name is Daniel, I have a degree in computer science and I worked in web development for three years.",
          accept: ["Üniversiteden mezun oldum", "Bilgisayar mühendisliği okudum", "Üç yıl çalıştım", "Benim adım Daniel"],
        },
      ],
    },
    {
      number: 11,
      slug: "tr-11",
      title: "Entretien : atouts, faiblesses et motivation",
      titleEn: "Interview: strengths, weaknesses and motivation",
      summary: "Parler de ses forces, de ses axes de progrès et de sa motivation.",
      summaryEn: "Talking about your strengths, areas for improvement and motivation.",
      grammar: ["Sıfatlar: güçlü, zayıf", "Neden ...? Çünkü ...", "Yönlerimden biri"],
      explanation:
        "Pour décrire ses atouts : « Güçlü yönlerimden biri takım çalışmasıdır » (l'une de mes forces est le travail d'équipe). On exprime la cause avec « çünkü » (parce que) : « Bu şirkette çalışmak istiyorum çünkü ... ». Le mot « yön » (aspect) se décline : güçlü yönler (points forts), zayıf yönler (points faibles).",
      explanationEn:
        "To describe your strengths: \"Güçlü yönlerimden biri takım çalışmasıdır\" (one of my strengths is teamwork). You express cause with \"çünkü\" (because): \"Bu şirkette çalışmak istiyorum çünkü ...\". The word \"yön\" (aspect) declines: güçlü yönler (strengths), zayıf yönler (weaknesses).",
      examples: [
        { target: "Güçlü yönlerimden biri takım çalışmasıdır.", fr: "L'une de mes forces est le travail d'équipe.", en: "One of my strengths is teamwork." },
        { target: "Zayıf yönlerimi geliştirmeye çalışıyorum.", fr: "Je m'efforce d'améliorer mes points faibles.", en: "I am working on improving my weaknesses." },
        { target: "Bu şirkette çalışmak istiyorum çünkü büyük bir takımınız var.", fr: "Je veux travailler dans cette entreprise car vous avez une grande équipe.", en: "I want to work at this company because you have a great team." },
        { target: "Motivasyonum yenilikçi projelerde çalışmaktan geliyor.", fr: "Ma motivation vient du travail sur des projets innovants.", en: "My motivation comes from working on innovative projects." },
      ],
      vocab: [
        { target: "güçlü", fr: "fort", en: "strong" },
        { target: "zayıf", fr: "faible", en: "weak" },
        { target: "yön", fr: "aspect, point", en: "side, aspect" },
        { target: "takım çalışması", fr: "travail d'équipe", en: "teamwork" },
        { target: "motivasyon", fr: "motivation", en: "motivation" },
        { target: "çünkü", fr: "parce que", en: "because" },
        { target: "yenilikçi", fr: "innovant", en: "innovative" },
        { target: "iyileştirmek", fr: "améliorer", en: "to improve" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « points forts » ?",
          promptEn: "How do you say \"strengths\"?",
          options: ["güçlü yönler", "zayıf yönler", "takım", "iş"],
          accept: ["güçlü yönler"],
          explain: "« Güçlü yönler » = points forts ; « zayıf yönler » = points faibles.",
          explainEn: "\"Güçlü yönler\" = strengths; \"zayıf yönler\" = weaknesses.",
        },
        {
          prompt: "Complétez : « Je veux travailler dans cette entreprise » → « Bu şirkette çalışmak ___ ».",
          promptEn: "Complete: \"I want to work at this company\" → \"Bu şirkette çalışmak ___\".",
          options: ["istiyorum", "seviyorum", "biliyorum", "yapıyorum"],
          accept: ["istiyorum"],
          explain: "« İstemek » exprime la volonté : çalışmak istiyorum (je veux travailler).",
          explainEn: "\"İstemek\" expresses will: çalışmak istiyorum (I want to work).",
        },
        {
          prompt: "Complétez : « Je veux ce poste parce que... » → « Bu işi istiyorum ___ ».",
          promptEn: "Complete: \"I want this job because...\" → \"Bu işi istiyorum ___\".",
          accept: ["çünkü"],
          explain: "« Çünkü » introduit la cause : Bu işi istiyorum çünkü ...",
          explainEn: "\"Çünkü\" introduces the reason: Bu işi istiyorum çünkü ...",
        },
      ],
      interview: [
        {
          question: "Güçlü ve zayıf yönleriniz nelerdir?",
          fr: "Quelles sont vos forces et vos faiblesses ?",
          en: "What are your strengths and weaknesses?",
          modelFr: "Je suis organisé et j'aime le travail d'équipe ; je travaille encore sur ma prise de parole en public.",
          modelEn: "I am organized and I enjoy teamwork; I am still working on my public speaking.",
          accept: ["Takım çalışmasında iyiyim", "Organize biriyim", "Güçlü yönlerim takım çalışması", "Zayıf yönüm topluluk önünde konuşmak"],
        },
        {
          question: "Neden bu şirkette çalışmak istiyorsunuz?",
          fr: "Pourquoi voulez-vous travailler dans cette entreprise ?",
          en: "Why do you want to work at this company?",
          modelFr: "Parce que votre entreprise est innovante et que je pourrais y développer de réelles compétences.",
          modelEn: "Because your company is innovative and I could develop real skills here.",
          accept: ["Şirketiniz yenilikçi", "İş deneyimi kazanmak istiyorum", "Burada gelişmek istiyorum", "Takımınızı çok beğeniyorum"],
        },
      ],
    },
    {
      number: 12,
      slug: "tr-12",
      title: "Entretien : projets, travail d'équipe et gestion du stress",
      titleEn: "Interview: plans, teamwork and stress management",
      summary: "Exprimer ses projets d'avenir, parler du travail d'équipe et du stress.",
      summaryEn: "Expressing future plans, talking about teamwork and handling stress.",
      grammar: ["Gelecek: 5 yıl sonra", "Kendimi ... görüyorum", "Stresle başa çıkmak"],
      explanation:
        "Pour parler de l'avenir, on utilise « gelecek » (futur) et l'expression « beş yıl sonra » (dans cinq ans) : « Beş yıl sonra kendimi bu şirkette görüyorum » (dans cinq ans, je me vois dans cette entreprise). Pour le stress, on emploie « stresle başa çıkmak » (gérer le stress) : « Stresliyken kısa bir ara veriyorum » (quand je suis stressé, je fais une courte pause).",
      explanationEn:
        "To talk about the future, you use \"gelecek\" (future) and the expression \"beş yıl sonra\" (in five years): \"Beş yıl sonra kendimi bu şirkette görüyorum\" (in five years, I see myself at this company). For stress, you use \"stresle başa çıkmak\" (to deal with stress): \"Stresliyken kısa bir ara veriyorum\" (when I am stressed, I take a short break).",
      examples: [
        { target: "Beş yıl sonra kendimi bu şirkette lider olarak görüyorum.", fr: "Dans cinq ans, je me vois comme leader dans cette entreprise.", en: "In five years, I see myself as a leader at this company." },
        { target: "Takım arkadaşlarımla birlikte çalışıyorum.", fr: "Je travaille avec mes coéquipiers.", en: "I work together with my teammates." },
        { target: "Stresliyken kısa bir ara veriyorum.", fr: "Quand je suis stressé, je fais une courte pause.", en: "When I am stressed, I take a short break." },
        { target: "Bu yıl kariyerime devam etmek istiyorum.", fr: "Cette année, je veux poursuivre ma carrière.", en: "This year I want to continue my career." },
      ],
      vocab: [
        { target: "gelecek", fr: "avenir, futur", en: "future" },
        { target: "beş yıl sonra", fr: "dans cinq ans", en: "in five years" },
        { target: "hedef", fr: "objectif", en: "goal" },
        { target: "stres", fr: "stress", en: "stress" },
        { target: "stresle başa çıkmak", fr: "gérer le stress", en: "to cope with stress" },
        { target: "takım arkadaşı", fr: "coéquipier", en: "teammate" },
        { target: "ara vermek", fr: "faire une pause", en: "to take a break" },
        { target: "devam etmek", fr: "continuer, poursuivre", en: "to continue" },
      ],
      exercises: [
        {
          prompt: "Comment dit-on « objectif » ?",
          promptEn: "How do you say \"goal\"?",
          options: ["hedef", "stres", "takım", "ara"],
          accept: ["hedef"],
          explain: "« Hedef » = objectif : Kariyer hedefim ...",
          explainEn: "\"Hedef\" = goal: Kariyer hedefim ...",
        },
        {
          prompt: "Complétez : « Dans cinq ans » → « Beş yıl ___ ».",
          promptEn: "Complete: \"In five years\" → \"Beş yıl ___\".",
          options: ["sonra", "önce", "içinde", "boyunca"],
          accept: ["sonra"],
          explain: "« Sonra » = plus tard, après : beş yıl sonra (dans cinq ans).",
          explainEn: "\"Sonra\" = later, after: beş yıl sonra (in five years).",
        },
        {
          prompt: "Complétez : « Dans cinq ans, je me vois ici » → « Beş yıl sonra kendimi burada ___ ».",
          promptEn: "Complete: \"In five years, I see myself here\" → \"Beş yıl sonra kendimi burada ___\".",
          accept: ["görüyorum"],
          explain: "« Görmek » (voir) → « kendimi görüyorum » (je me vois).",
          explainEn: "\"Görmek\" (to see) → \"kendimi görüyorum\" (I see myself).",
        },
      ],
      interview: [
        {
          question: "Beş yıl sonra kendinizi nerede görüyorsunuz?",
          fr: "Où vous voyez-vous dans cinq ans ?",
          en: "Where do you see yourself in five years?",
          modelFr: "Je me vois évoluer au sein de votre entreprise et prendre davantage de responsabilités.",
          modelEn: "I see myself growing within your company and taking on more responsibilities.",
          accept: ["Beş yıl sonra kendimi bu şirkette görüyorum", "Kariyerimde ilerliyorum", "Daha fazla sorumluluk alıyorum", "Kendimi burada görüyorum"],
        },
        {
          question: "Stresli durumlarla nasıl başa çıkıyorsunuz?",
          fr: "Comment gérez-vous les situations stressantes ?",
          en: "How do you deal with stressful situations?",
          modelFr: "Je m'organise avec une liste de priorités et je fais de courtes pauses.",
          modelEn: "I organize myself with a priority list and take short breaks.",
          accept: ["Sakin kalıyorum", "Plan yapıyorum", "Öncelik listesi yapıyorum", "Kısa bir ara veriyorum"],
        },
      ],
    },
  ],
};